;; src/fortran-lexer.lisp — Tokenization for FORTRAN source
;; Following the pattern of basic-lexer.lisp
(in-package :eightbol)

(defparameter *fortran-keyword-alist*
  '(("PROGRAM" . :PROGRAM)
    ("SUBROUTINE" . :SUBROUTINE)
    ("FUNCTION" . :FUNCTION)
    ("END" . :END)
    ("RETURN" . :RETURN)
    ("STOP" . :STOP)
    ("CALL" . :CALL)
    ("GOTO" . :GOTO)
    ("IF" . :IF)
    ("THEN" . :THEN)
    ("ELSE" . :ELSE)
    ("DO" . :DO)
    ("READ" . :READ)
    ("WRITE" . :WRITE)
    ("PRINT" . :PRINT)
    ("OPEN" . :OPEN)
    ("CLOSE" . :CLOSE)
    ("REAL" . :REAL-TYPE)
    ("INTEGER" . :INTEGER-TYPE)
    ("LOGICAL" . :LOGICAL-TYPE)
    ("CHARACTER" . :CHARACTER-TYPE)
    ("COMPLEX" . :COMPLEX-TYPE)
    ("TYPE" . :TYPE)
    ("CLASS" . :CLASS)
    ("METHOD" . :METHOD)
    ("INSTANCE" . :INSTANCE)
    ("NEW" . :NEW)
    ("DELETE" . :DELETE)
    ("INVOKE" . :INVOKE)
    ("SUPER" . :SUPER)
    ("SELF" . :SELF)
    ("PROCEDURE" . :PROCEDURE)
    ("DATA" . :DATA)
    ("PARAMETER" . :PARAMETER)
    ("DIMENSION" . :DIMENSION)
    ("COMMON" . :COMMON)
    ("EQUIVALENCE" . :EQUIVALENCE)
    ("INCLUDE" . :INCLUDE)
    ("WHILE" . :WHILE)
    ("UNTIL" . :UNTIL)
    ("AND" . :AND)
    ("OR" . :OR)
    ("NOT" . :NOT)
    ("TRUE" . :TRUE)
    ("FALSE" . :FALSE))
  "Association list of FORTRAN keywords to token symbols.
   OOP keywords added for OOPS system integration.")

(defparameter *fortran-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("**" . :POWER)
    ("=" . :EQUAL)
    ("==" . :EQUAL-EQUAL)
    ("/=" . :NOT-EQUAL)
    ("<>" . :NOT-EQUAL)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE)
    ("(" . :LPAREN)
    (")" . :RPAREN)
    ("," . :COMMA)
    (":" . :COLON)
    ("." . :DOT))
  "Association list of FORTRAN operators to token symbols.")

(defun fortran-token-type (lexeme)
  "Return token type for LEXEME, a string."
  (cond
    ((and (stringp lexeme) (digit-char-p (char lexeme 0)))
     :NUMBER)
    ((and (stringp lexeme) (char= (char lexeme 0) #\"))
     :STRING)
    ((assoc lexeme *fortran-keyword-alist* :test #'string-equal)
     (cdr (assoc lexeme *fortran-keyword-alist* :test #'string-equal)))
    ((assoc lexeme *fortran-operators-alist* :test #'string-equal)
     (cdr (assoc lexeme *fortran-operators-alist* :test #'string-equal)))
    ((string= lexeme "(") :LPAREN)
    ((string= lexeme ")") :RPAREN)
    ((string= lexeme ",") :COMMA)
    ((string= lexeme ":") :COLON)
    ((fortran-valid-identifier-p lexeme) :IDENT)
    (t :UNKNOWN)))

(defun fortran-valid-identifier-p (s)
  "Check if S is a valid FORTRAN identifier."
  (and (stringp s)
       (plusp (length s))
       (every (lambda (c)
                (or (alphanumericp c)
                    (char= c #\_)))
              s)))

(defun fortran-lex-line (line)
  "Split LINE into token list of (type value) pairs.
  Handles quoted strings, operators, and identifiers."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (skip-whitespace ()
               (loop while (and (not (eof?))
                                (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (flush-token (start end type)
               (let ((text (coerce (subseq chars start end) 'string)))
                 (unless (zerop (length text))
                   (push (cons type text) tokens))))
             (scan-number (start)
               (loop while (and (not (eof?)) (digit-char-p (peek)))
                     do (next-char))
               (flush-token start (1- i) :NUMBER))
             (scan-string (start)
               (next-char) ; skip opening quote
               (loop while (and (not (eof?)) (char/= (peek) #\"))
                     do (next-char))
               (when (not (eof?)) (next-char)) ; skip closing quote
               (flush-token (1+ start) (1- i) :STRING))
             (scan-identifier (start)
               (loop while (and (not (eof?))
                                (or (alphanumericp (peek))
                                    (char= (peek) #\_)))
                     do (next-char))
               (let ((text (coerce (subseq chars start (1- i)) 'string)))
                 (let ((type (fortran-token-type text)))
                   (when (not (eq type :UNKNOWN))
                     (flush-token start (1- i) type))))))
    (loop until (eof?)
          do (skip-whitespace)
             (cond
               ((eof?) (return))
               ((char= (peek) #\") (scan-string i))
               ((digit-char-p (peek)) (scan-number i))
               ((or (alphanumericp (peek))
                    (char= (peek) #\_)) (scan-identifier i))
               (t
                (let* ((op1 (string (next-char)))
                       (op2 (when (not (eof?)) (string (peek)))))
                  (cond
                    ((and op2 (string= (concatenate 'string op1 op2) "=="))
                     (next-char)
                     (flush-token (1- i) i :EQUAL-EQUAL))
                    ((and op2 (string= (concatenate 'string op1 op2) "/="))
                     (next-char)
                     (flush-token (1- i) i :NOT-EQUAL))
                    ((and op2 (string= (concatenate 'string op1 op2) "<="))
                     (next-char)
                     (flush-token (1- i) i :LESS-OR-EQUAL))
                    ((and op2 (string= (concatenate 'string op1 op2) ">="))
                     (next-char)
                     (flush-token (1- i) i :GREATER-OR-EQUAL))
                    (t
                     (flush-token (1- i) i :OP)))))))
       (nreverse tokens))))

(defun fortran-lex-source (source)
  "Lex complete FORTRAN SOURCE string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (or (zerop (length trimmed))
                    (char= #\; (char trimmed 0))
                    (char= #\' (char trimmed 0)))
          (setf all-tokens (nconc all-tokens (fortran-lex-line trimmed))))))
    all-tokens))

(defun fortran-lex (source)
  "Lex FORTRAN SOURCE string into a token list for YACC."
  (fortran-lex-source source))

(defun fortran-parse-line-prefix (tokens)
  "Parse line number and optional quoted label from start of TOKENS.
  Returns (values line-number label remaining-tokens)."
  (declare (ignore tokens))
  (values nil nil))

(provide 'fortran-lexer)