;; src/backend-cp1610.lisp — cp1610 (Intellivision) code generation backend
;;
;; The GI cp1610 is a 16-bit RISC-like CPU used in the Mattel Intellivision.
;;   16-bit registers: R0–R7 (R5 = return addr for JSR, R6 = stack pointer)
;;   Instructions: MVII (move imm), MVI (load), MVO (store), ADDR, SUBR
;;   JSR R5, label — call subroutine (return addr in R5)
;;   JR R5 — return
;;
;; Output: as1600 assembler syntax (Intellivision).
;; Variables map to 16-bit memory; 8-bit EIGHTBOL values use low byte.
(in-package :eightbol)

(defvar *output-stream* nil)

;;; Shared helpers (symbol naming)

(defun cp1610-symbol (name)
  "Convert EIGHTBOL identifier to cp1610 assembly symbol (PascalCase). COBOL stabby-case supported."
  (pascal-case (format nil "~a" name)))

;;; def-cp1610-statement macro — compiles through the generic compile-statement

(defmacro def-cp1610-statement (statement-type &body body)
  `(defmethod compile-statement ((cpu (eql :cp1610)) (statement-type (eql ,statement-type)) ast-node-data)
     ,@body))

;;; Top-level entry point

(defmethod compile-to-assembly (ast (cpu (eql :cp1610)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/cp1610: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table
                          pic-size-table pic-width-table pic-frac-bits-table
                          pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (let ((*output-stream* output-stream)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*service-bank-table* service-bank-table)
            (*usage-table* usage-table)
            (*sign-table* sign-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table)
            (*pic-frac-bits-table* pic-frac-bits-table)
            (*pic-nybble-semantics-table* pic-nybble-semantics-table))
        (format *output-stream*
                ";;; ~a -- generated by EIGHTBOL for cp1610 (Intellivision)~%;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
                class-id class-id)
        (format *output-stream* "~&~10tROMW    16")
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-cp1610-method method)))))))

;;; Method compilation

(defun compile-cp1610-method (method)
  (let ((*method-id* (getf (rest method) :method-id)))
    (declare (special *method-id*))
    (let* ((dispatch-label (format nil "Method~a~a"
                                   (cp1610-symbol *class-id*)
                                   (cp1610-symbol (format nil "~a" *method-id*))))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                        (getf (rest method) :statements))))
           (block-label (if custom-entry
                            (cp1610-symbol custom-entry)
                            dispatch-label))
           (stmts (nth-value 1 (split-method-leading-assembly-entry
                                 (getf (rest method) :statements))))
           (last-stmt (car (last stmts))))
      (format *output-stream* "~&~%~a PROC" block-label)
      (dolist (stmt stmts)
        (compile-statement :cp1610 (first stmt) (rest stmt)))
      (unless (and (listp last-stmt)
                   (member (first last-stmt)
                           '(:goback :exit-method :exit-program :exit :stop-run)))
        (format *output-stream* "~&~10tJR      R5"))
      (format *output-stream* "~&~10tENDP")
      (when custom-entry
        (format *output-stream* "~&~a EQU ~a" dispatch-label block-label)))))

;;; Statement dispatch — :around method for source comments

(defmethod compile-statement :around ((cpu (eql :cp1610)) stmt-type ast-node-data)
  (emit-statement-source-comment *output-stream* (cons stmt-type ast-node-data))
  (call-next-method))

;;; Individual statement methods

(def-cp1610-statement :goback
  (format *output-stream* "~&~10tJR      R5"))

(def-cp1610-statement :exit-method
  (format *output-stream* "~&~10tJR      R5"))

(def-cp1610-statement :exit-program
  (format *output-stream* "~&~10tJR      R5"))

(def-cp1610-statement :stop-run
  (format *output-stream* "~&~10tJR      R5"))

(def-cp1610-statement :exit
  (format *output-stream* "~&~10tJR      R5"))

(def-cp1610-statement :move
  (let ((stmt (cons :move ast-node-data)))
    (compile-cp1610-move stmt)))

(def-cp1610-statement :invoke
  (let ((stmt (cons :invoke ast-node-data)))
    (compile-cp1610-invoke stmt)))

(def-cp1610-statement :call
  (let ((stmt (cons :call ast-node-data)))
    (compile-cp1610-call stmt)))

(def-cp1610-statement :if
  (let ((stmt (cons :if ast-node-data)))
    (compile-cp1610-if stmt)))

(def-cp1610-statement :add
  (let ((stmt (cons :add ast-node-data)))
    (compile-cp1610-add stmt)))

(def-cp1610-statement :subtract
  (let ((stmt (cons :subtract ast-node-data)))
    (compile-cp1610-subtract stmt)))

(def-cp1610-statement :compute
  (let ((stmt (cons :compute ast-node-data)))
    (compile-cp1610-compute stmt)))

(def-cp1610-statement :set
  (let ((stmt (cons :set ast-node-data)))
    (compile-cp1610-set stmt)))

(def-cp1610-statement :log-fault
  (format *output-stream* "~&~10t;; LOG FAULT ~s" (getf ast-node-data :code)))

(def-cp1610-statement :debug-break
  (format *output-stream* "~&~10t;; DEBUG BREAK ~s" (getf ast-node-data :code)))

(def-cp1610-statement :perform
  (let ((stmt (cons :perform ast-node-data)))
    (compile-cp1610-perform stmt)))

(def-cp1610-statement :string-blt
  (let ((stmt (cons :string-blt ast-node-data)))
    (compile-cp1610-string-blt stmt)))

(def-cp1610-statement :goto
  (let ((stmt (cons :goto ast-node-data)))
    (compile-cp1610-goto stmt)))

(def-cp1610-statement :paragraph
  (let ((stmt (cons :paragraph ast-node-data)))
    (compile-cp1610-paragraph stmt)))

(def-cp1610-statement :evaluate
  (let ((stmt (cons :evaluate ast-node-data)))
    (compile-cp1610-evaluate stmt)))

(def-cp1610-statement :inspect
  (let ((stmt (cons :inspect ast-node-data)))
    (compile-cp1610-inspect stmt)))

(def-cp1610-statement :comment
  (format *output-stream* "~%~10t;; ~a"
          (let ((text (first ast-node-data)))
            (if (listp text)
                (format nil "~{~a~%~10t;; ~}" (mapcar (lambda (s) (if (stringp s) s (princ-to-string s))) text))
                (princ-to-string text)))))

(def-cp1610-statement :copy
  (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
         (getf ast-node-data :name)))

(def-cp1610-statement :divide
  (let* ((divisor (getf ast-node-data :divisor))
         (into (getf ast-node-data :into))
         (by (getf ast-node-data :by))
         (source (or by into))
         (dest (or (getf ast-node-data :giving) into)))
    (if (and (expression-constant-p divisor)
             (power-of-two-p (expression-constant-value divisor)))
        (let ((shift (log2 (expression-constant-value divisor))))
          (when (or (operand-bcd-p source) (operand-bcd-p dest))
            (error 'source-error
                   :message "DIVIDE: cannot use with USAGE DECIMAL operands"
                   :detail (list :divisor divisor :source source :dest dest)))
          (unless (zerop shift)
            (compile-cp1610-load (or source dest) 1)
            (format *output-stream* "~&~10tSARC    R0, ~d" shift)
            (when (stringp dest)
              (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol dest)))))
        (error 'source-error
               :message "DIVIDE: divisor must be constant power-of-two (1, 2, 4, 8, ...)"
               :detail (format nil "DIVIDE by ~s" divisor)))))

(def-cp1610-statement :multiply
  (let* ((multiplier (getf ast-node-data :multiplier))
         (by (getf ast-node-data :by))
         (giving (getf ast-node-data :giving))
         (source (or giving by))
         (dest (or giving by)))
    (if (and (expression-constant-p multiplier)
             (power-of-two-p (expression-constant-value multiplier)))
        (let ((shift (log2 (expression-constant-value multiplier))))
          (when (or (operand-bcd-p source) (operand-bcd-p dest))
            (error 'source-error
                   :message "MULTIPLY: cannot use with USAGE DECIMAL operands"
                   :detail (list :multiplier multiplier :source source :dest dest)))
          (unless (zerop shift)
            (compile-cp1610-load (or source dest) 1)
            (format *output-stream* "~&~10tSLL     R0, ~d" shift)
            (when (stringp dest)
              (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol dest)))))
        (error 'source-error
               :message "MULTIPLY: multiplier must be constant power-of-two (1, 2, 4, 8, ...)"
               :detail (format nil "MULTIPLY by ~s" multiplier)))))

(def-cp1610-statement :invoke-super
  (unless (gethash *class-id* *parent-classes*)
    (load-classes))
  (if-let (parent-class (gethash *class-id* *parent-classes*))
    (format *output-stream* "~&~10tJSR     R5, Method~a~a"
            (cp1610-symbol parent-class)
            (cp1610-symbol (format nil "~a" *method-id*)))
    (error "Can't figure out parent class of ~a" *class-id*)))

(def-cp1610-statement :shift-left
  (let* ((target (getf ast-node-data :target))
         (count (getf ast-node-data :count 1)))
    (compile-cp1610-load target)
    (format *output-stream* "~&~10tSLL     R0, ~d" count)
    (when (stringp target)
      (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol target)))))

(def-cp1610-statement :shift-right
  (let* ((target (getf ast-node-data :target))
         (count (getf ast-node-data :count 1)))
    (compile-cp1610-load target)
    (format *output-stream* "~&~10tSARC    R0, ~d" count)
    (when (stringp target)
      (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol target)))))

;;; Expression / value emission

(defun cp1610-expr-is-constant-p (expr)
  (or (numberp expr)
      (and (stringp expr) (constant-p expr))))

(defun cp1610-value (expr &optional)
  (cond
    ((numberp expr) (format nil "~d" expr))
    ((and (stringp expr) (constant-p expr))
     (format nil "~d" (constant-value expr)))
    ((stringp expr) (cp1610-symbol expr))
    ((eq expr :self) "Self")
    ((and (listp expr) (eq (first expr) :of))
     (cp1610-symbol (format nil "~a-~a" (third expr) (second expr))))
    (t (format nil "~a" expr))))

(defun compile-cp1610-load (expr &optional (width 1) (reg :r0))
  "Load EXPR into REG. Uses MVII for immediates, MVI for memory.
WIDTH: 1 (byte) or 2 (word). For :subscript, scales index for element size (0-255 elements)."
  (cond
    ((numberp expr)
     (format *output-stream* "~&~10tMVII    #~d, ~a" expr reg))
    ((and (stringp expr) (constant-p expr))
     (format *output-stream* "~&~10tMVII    #~d, ~a" (constant-value expr) reg))
    ((stringp expr)
     (format *output-stream* "~&~10tMVI     ~a, ~a" (cp1610-symbol expr) reg))
    ((and (listp expr) (eq (first expr) :of))
     (let ((obj (third expr)))
       (when (member obj '(:self "Self" self) :test #'equal)
         (format *output-stream* "~&~10tMVII    #~a, R4"
                 (apply #'slot-symbol (rest expr)))
         (format *output-stream* "~&~10tADD     Self, R4")
         (format *output-stream* "~&~10tMVI@    R4, ~a" reg))))
    ((and (listp expr) (eq (first expr) :subscript))
     (compile-cp1610-load (third expr) 1 reg)
     (when (= (or width 1) 2)
       (format *output-stream* "~&~10tSLL     ~a, 1" reg))
     (format *output-stream* "~&~10tMVII    #~a, R4"
             (bare-data-assembly-symbol (second expr) *class-id*))
     (format *output-stream* "~&~10tADDR    ~a, R4" reg)
     (format *output-stream* "~&~10tMVI@    R4, ~a" reg))
    ((and (listp expr) (eq (first expr) :shift-left))
     (let ((n (if (numberp (third expr)) (third expr) 1)))
       (compile-cp1610-load (second expr) width reg)
       (dotimes (_ n) (format *output-stream* "~&~10tSLL     ~a, 1" reg))))
    ((and (listp expr) (eq (first expr) :shift-right))
     (let ((n (if (numberp (third expr)) (third expr) 1)))
       (compile-cp1610-load (second expr) width)
       (dotimes (_ n) (format *output-stream* "~&~10tSARC    ~a, 1" reg))))
    ((and (listp expr) (eq (first expr) :bit-and))
     (compile-cp1610-load (second expr) width)
     (let ((rhs (third expr)))
       (if (cp1610-expr-is-constant-p rhs)
           (format *output-stream* "~&~10tANDI    #~a, R0" (cp1610-value rhs))
           (progn (format *output-stream* "~&~10tMOVR    R0, R1")
                  (compile-cp1610-load rhs width)
                  (format *output-stream* "~&~10tANDR    R1, R0")))))
    ((and (listp expr) (eq (first expr) :bit-or))
     (compile-cp1610-load (second expr) width)
     (let ((rhs (third expr)))
       (if (cp1610-expr-is-constant-p rhs)
           (format *output-stream* "~&~10tORI     #~a, R0" (cp1610-value rhs))
           (progn (format *output-stream* "~&~10tMOVR    R0, R1")
                  (compile-cp1610-load rhs width)
                  (format *output-stream* "~&~10tORR     R1, R0")))))
    ((and (listp expr) (eq (first expr) :bit-xor))
     (compile-cp1610-load (second expr) width)
     (let ((rhs (third expr)))
       (if (cp1610-expr-is-constant-p rhs)
           (format *output-stream* "~&~10tXORI    #~a, R0" (cp1610-value rhs))
           (progn (format *output-stream* "~&~10tMOVR    R0, R1")
                  (compile-cp1610-load rhs width)
                  (format *output-stream* "~&~10tXORR    R1, R0")))))
    ((and (listp expr) (eq (first expr) :bit-not))
     (compile-cp1610-load (second expr) width)
     (format *output-stream* "~&~10tCOMR    ~a" reg))
    ((and (listp expr) (eq (first expr) :high))
     (let ((inner (second expr)))
       (if (and (stringp inner) (constant-p inner))
           (format *output-stream* "~&~10tMVII    #~d, ~a" (ash (constant-value inner) -8) reg)
           (progn
             (compile-cp1610-load inner 2 reg)
             (format *output-stream* "~&~10tSARC    ~a, 8" reg)))))
    ((and (listp expr) (eq (first expr) :add))
     (compile-cp1610-load (getf (rest expr) :from) width reg)
     (format *output-stream* "~&~10tMOVR    ~a, R1" reg)
     (compile-cp1610-load (getf (rest expr) :to) width :r0)
     (format *output-stream* "~&~10tADDR    R1, ~a" reg))
    (t
     (format *output-stream* "~&~10t;; Unsupported load ~s" expr))))

;;; MOVE

(defun compile-cp1610-move (stmt)
  (let* ((from (getf (rest stmt) :from))
         (to-dest (getf (rest stmt) :to))
         (to-w (operand-width to-dest))
         (from-w (expression-operand-width from))
         (from-bcd (operand-bcd-p from))
         (to-bcd (operand-bcd-p to-dest)))
    (cond
      ((and from-bcd (not to-bcd))
       (let ((w (or from-w 1)))
         (unless (<= w 2)
           (error 'backend-error :message
                  (format nil "BCD-to-binary MOVE width ~d not yet implemented for cp1610" w)
                  :cpu :cp1610 :detail stmt))
     (if (= w 1)
             (progn
               (compile-cp1610-load from)
               (format *output-stream* "~&~10tMOVR    R0, R1")
               (format *output-stream* "~&~10tANDI    #$F0, R0")
               (format *output-stream* "~&~10tSARC    R0, 4")
               (format *output-stream* "~&~10tMOVR    R0, R2")
               (format *output-stream* "~&~10tSLL     R0, 3")
               (format *output-stream* "~&~10tSLL     R2, 1")
               (format *output-stream* "~&~10tADDR    R2, R0")
               (format *output-stream* "~&~10tANDI    #$0F, R1")
               (format *output-stream* "~&~10tADDR    R1, R0"))
             (progn
               (compile-cp1610-load from)
               (format *output-stream* "~&~10tMOVR    R0, R4")
               (format *output-stream* "~&~10tANDI    #$FF, R4")
               (format *output-stream* "~&~10tSARC    R0, 8")
               (format *output-stream* "~&~10tMOVR    R0, R1")
               (format *output-stream* "~&~10tANDI    #$F0, R0")
               (format *output-stream* "~&~10tSARC    R0, 4")
               (format *output-stream* "~&~10tMOVR    R0, R2")
               (format *output-stream* "~&~10tSLL     R0, 3")
               (format *output-stream* "~&~10tSLL     R2, 1")
               (format *output-stream* "~&~10tADDR    R2, R0")
               (format *output-stream* "~&~10tANDI    #$0F, R1")
               (format *output-stream* "~&~10tADDR    R1, R0")
               (format *output-stream* "~&~10tMOVR    R0, R1")
               (format *output-stream* "~&~10tMOVR    R0, R2")
               (format *output-stream* "~&~10tSLL     R1, 6")
               (format *output-stream* "~&~10tSLL     R2, 5")
               (format *output-stream* "~&~10tADDR    R2, R1")
               (format *output-stream* "~&~10tMOVR    R1, R2")
               (format *output-stream* "~&~10tSLL     R2, 2")
               (format *output-stream* "~&~10tADDR    R2, R1")
               (format *output-stream* "~&~10tMOVR    R4, R0")
               (format *output-stream* "~&~10tMOVR    R0, R2")
               (format *output-stream* "~&~10tANDI    #$F0, R0")
               (format *output-stream* "~&~10tSARC    R0, 4")
               (format *output-stream* "~&~10tMOVR    R0, R3")
               (format *output-stream* "~&~10tSLL     R0, 3")
               (format *output-stream* "~&~10tSLL     R3, 1")
               (format *output-stream* "~&~10tADDR    R3, R0")
               (format *output-stream* "~&~10tANDI    #$0F, R2")
               (format *output-stream* "~&~10tADDR    R2, R0")
               (format *output-stream* "~&~10tADDR    R1, R0")))))
      ((and (not from-bcd) to-bcd)
       (let ((w (or to-w 1)))
         (unless (<= w 2)
           (error 'backend-error :message
                  (format nil "Binary-to-BCD MOVE width ~d not yet implemented for cp1610" w)
                  :cpu :cp1610 :detail stmt))
         (compile-cp1610-load from)
         (if (= w 1)
             (let ((loop (cp1610-label "bcd"))
                   (done (cp1610-label "bcdd")))
               (format *output-stream* "~&~10tMVII    #10, R1")
               (format *output-stream* "~&~10tMOVR    R0, R2")
               (format *output-stream* "~&~10tCLRR    R0")
               (format *output-stream* "~&~a:" loop)
               (format *output-stream* "~&~10tSUBR    R1, R2")
               (format *output-stream* "~&~10tBLT     ~a" done)
               (format *output-stream* "~&~10tINCR    R0")
               (format *output-stream* "~&~10tB       ~a" loop)
               (format *output-stream* "~&~a:" done)
               (format *output-stream* "~&~10tADDR    R1, R2")
               (format *output-stream* "~&~10tSLL     R0, 4")
               (format *output-stream* "~&~10tADDR    R2, R0"))
             (let ((l100 (cp1610-label "x1"))
                   (d100 (cp1610-label "x2"))
                   (l10a (cp1610-label "x3"))
                   (d10a (cp1610-label "x4"))
                   (l10b (cp1610-label "x5"))
                   (d10b (cp1610-label "x6")))
               (format *output-stream* "~&~10tMVII    #100, R1")
               (format *output-stream* "~&~10tMOVR    R0, R2")
               (format *output-stream* "~&~10tCLRR    R3")
               (format *output-stream* "~&~a:" l100)
               (format *output-stream* "~&~10tSUBR    R1, R2")
               (format *output-stream* "~&~10tBLT     ~a" d100)
               (format *output-stream* "~&~10tINCR    R3")
               (format *output-stream* "~&~10tB       ~a" l100)
               (format *output-stream* "~&~a:" d100)
               (format *output-stream* "~&~10tADDR    R1, R2")
               (format *output-stream* "~&~10tMOVR    R2, R4")
               (format *output-stream* "~&~10tMVII    #10, R1")
               (format *output-stream* "~&~10tMOVR    R3, R0")
               (format *output-stream* "~&~10tCLRR    R2")
               (format *output-stream* "~&~a:" l10a)
               (format *output-stream* "~&~10tSUBR    R1, R0")
               (format *output-stream* "~&~10tBLT     ~a" d10a)
               (format *output-stream* "~&~10tINCR    R2")
               (format *output-stream* "~&~10tB       ~a" l10a)
               (format *output-stream* "~&~a:" d10a)
               (format *output-stream* "~&~10tADDR    R1, R0")
               (format *output-stream* "~&~10tSLL     R2, 4")
               (format *output-stream* "~&~10tADDR    R0, R2")
               (format *output-stream* "~&~10tMVII    #10, R1")
               (format *output-stream* "~&~10tMOVR    R4, R0")
               (format *output-stream* "~&~10tCLRR    R3")
               (format *output-stream* "~&~a:" l10b)
               (format *output-stream* "~&~10tSUBR    R1, R0")
               (format *output-stream* "~&~10tBLT     ~a" d10b)
               (format *output-stream* "~&~10tINCR    R3")
               (format *output-stream* "~&~10tB       ~a" l10b)
               (format *output-stream* "~&~a:" d10b)
               (format *output-stream* "~&~10tADDR    R1, R0")
               (format *output-stream* "~&~10tSLL     R3, 4")
               (format *output-stream* "~&~10tADDR    R0, R3")
               (format *output-stream* "~&~10tMOVR    R2, R0")
               (format *output-stream* "~&~10tSLL     R0, 8")
               (format *output-stream* "~&~10tADDR    R3, R0")))))
      (t
       (compile-cp1610-load from)
       (when (and from-w to-w (> to-w from-w)
                  (numberp from-w) (numberp to-w))
         (cond
           ((and (not from-bcd) (operand-signed-p from))
            (let ((bits-to-shift (* (- to-w from-w) 8)))
              (format *output-stream* "~&~10tSLL     R0, ~d" bits-to-shift)
              (format *output-stream* "~&~10tSARC    R0, ~d" bits-to-shift)))
           ((not from-bcd)
            (when (and (= from-w 1) (>= to-w 2))
              (format *output-stream* "~&~10tANDI    #$FF, R0")))))))
    (cond
      ((stringp to-dest)
       (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol to-dest)))
      ((and (listp to-dest) (eq (first to-dest) :of))
       (let ((obj (third to-dest)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (format *output-stream* "~&~10tMVII    #~a, R4" (apply #'slot-symbol (rest to-dest)))
           (format *output-stream* "~&~10tADD     Self, R4")
           (format *output-stream* "~&~10tMVO@    R0, R4"))))
       ((and (listp to-dest) (eq (first to-dest) :subscript))
        (format *output-stream* "~&~10tMOVR    R0, R1")
        (compile-cp1610-load (third to-dest) 1)
        (when (= (or to-w 1) 2)
          (format *output-stream* "~&~10tSLL     R0, 1"))
        (format *output-stream* "~&~10tMVII    #~a, R4"
                (bare-data-assembly-symbol (second to-dest) *class-id*))
        (format *output-stream* "~&~10tADDR    R0, R4")
        (format *output-stream* "~&~10tMOVR    R1, R0")
        (format *output-stream* "~&~10tMVO@    R0, R4"))
      (t (format *output-stream* "~&~10t;; Unsupported store to ~s" to-dest)))))

;;; INVOKE

(defun compile-cp1610-invoke (stmt)
  (let ((object   (getf (rest stmt) :object))
        (method   (getf (rest stmt) :method))
        (returning (getf (rest stmt) :returning)))
    (let ((method-sym (cp1610-symbol (format nil "~a" method))))
      (cond
        ((member object '(:self "Self" self) :test #'equal)
         (format *output-stream* "~&~10tJSR     R5, Invoke~a~a" (cp1610-symbol *class-id*) method-sym))
        (t
         (let* ((obj-name (cp1610-symbol (format nil "~a" object)))
                (obj-class (or (var-class obj-name) "Unknown")))
           (format *output-stream* "~&~10tJSR     R5, Call~a~a" obj-class method-sym))))
      (when returning
        (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol (format nil "~a" returning)))))))

;;; CALL

(defun compile-cp1610-call (stmt)
  (let ((target (getf (rest stmt) :target))
        (service (getf (rest stmt) :service))
        (library (getf (rest stmt) :library)))
    (declare (ignore library))
    (let ((name (cp1610-symbol (format nil "~a" (or service target)))))
      (format *output-stream* "~&~10tJSR     R5, ~a" name))))

;;; IF

(defvar *cp1610-label* 0)

(defun cp1610-label (prefix)
  (format nil "@@~a_~36r" prefix (incf *cp1610-label*)))

(defun compile-cp1610-if (stmt)
  (let ((condition (getf (rest stmt) :condition))
        (then-stmts (getf (rest stmt) :then))
        (else-stmts (getf (rest stmt) :else))
        (label-else (cp1610-label "else"))
        (label-end (cp1610-label "end")))
    (compile-cp1610-condition condition label-else)
    (dolist (s (ensure-list then-stmts))
      (compile-statement :cp1610 (first s) (rest s)))
    (when (and else-stmts (not (null else-stmts)))
      (format *output-stream* "~&~10tB       ~a" label-end))
    (format *output-stream* "~&~a:" label-else)
    (when (and else-stmts (not (null else-stmts)))
      (dolist (s (ensure-list else-stmts))
        (compile-statement :cp1610 (first s) (rest s)))
      (format *output-stream* "~&~a:" label-end))))

(defun compile-cp1610-condition (condition branch-label)
  (assert (listp condition))
  (let* ((condition (cond
                      ((and (listp condition) (= 2 (length condition))
                            (or (eq (first condition) :not)
                                (string-equal (symbol-name (first condition)) "NOT")))
                       (list :not (second condition)))
                      (t condition)))
         (condition (or (normalize-relation-condition condition) condition))
         (op (relation-op-canonical (first condition))))
    (cond
      ((and (= (length condition) 3)
            (member op '(> < ≥ ≤ = ≠) :test #'string=))
       (let ((lhs (second condition)) (rhs (third condition)))
         (compile-cp1610-load lhs 1)
         (format *output-stream* "~&~10tMOVR    R0, R1")
         (compile-cp1610-load rhs 1)
         (format *output-stream* "~&~10tCMPR    R1, R0")
         (cond ((string= op "=") (format *output-stream* "~&~10tBNEQ    ~a" branch-label))
               ((string= op "≠") (format *output-stream* "~&~10tBEQ     ~a" branch-label))
               ((string= op ">") (format *output-stream* "~&~10tBLE     ~a" branch-label))
               ((string= op "<") (format *output-stream* "~&~10tBGE     ~a" branch-label))
               ((string= op "≥") (format *output-stream* "~&~10tBLT     ~a" branch-label))
               ((string= op "≤") (format *output-stream* "~&~10tBGT     ~a" branch-label)))))
      ((and (listp condition)
            (or (eq (first condition) :not)
                (eq (first condition) 'not)
                (string-equal (symbol-name (first condition)) "NOT"))
            (listp (second condition))
            (member (first (second condition)) '(= equal) :test #'eq))
       (let ((inner (second condition)))
         (cond
           ((or (and (numberp (second inner)) (zerop (second inner)))
                (and (numberp (third inner)) (zerop (third inner))))
            (let ((var (if (and (numberp (second inner)) (zerop (second inner)))
                           (third inner)
                           (second inner))))
              (compile-cp1610-load var 1)
              (format *output-stream* "~&~10tTSTR    R0")
              (format *output-stream* "~&~10tBEQ     ~a" branch-label)))
           (t
            (compile-cp1610-load (second inner) 1)
            (format *output-stream* "~&~10tMOVR    R0, R1")
            (compile-cp1610-load (third inner) 1)
            (format *output-stream* "~&~10tCMPR    R1, R0")
            (format *output-stream* "~&~10tBEQ     ~a" branch-label)))))
      ((and (listp condition) (eq (first condition) :is-zero))
     (compile-cp1610-load (second condition))
     (format *output-stream* "~&~10tTSTR    R0")
     (format *output-stream* "~&~10tBNEQ    ~a" branch-label))
      ((and (listp condition) (eq (first condition) :is-not-zero))
       (compile-cp1610-load (second condition))
       (format *output-stream* "~&~10tTSTR    R0")
       (format *output-stream* "~&~10tBEQ     ~a" branch-label))
      ((and (listp condition) (eq (first condition) :not-null))
       (compile-cp1610-load (second condition))
       (format *output-stream* "~&~10tTSTR    R0")
       (format *output-stream* "~&~10tBEQ     ~a" branch-label))
      ((and (listp condition) (eq (first condition) :null))
       (compile-cp1610-load (second condition))
       (format *output-stream* "~&~10tTSTR    R0")
       (format *output-stream* "~&~10tBNEQ    ~a" branch-label))
      ((and (listp condition) (eq (first condition) :and))
     (compile-cp1610-condition (second condition) branch-label)
     (compile-cp1610-condition (third condition) branch-label))
    ((and (listp condition) (eq (first condition) :or))
     (let ((label-cond2 (cp1610-label "or"))
           (label-skip (cp1610-label "skip")))
       (compile-cp1610-condition (second condition) label-cond2)
       (format *output-stream* "~&~10tB       ~a" label-skip)
       (format *output-stream* "~&~a:" label-cond2)
       (compile-cp1610-condition (third condition) branch-label)
       (format *output-stream* "~&~a:" label-skip)))
      (t (error "EIGHTBOL: condition ~s not implemented" condition)))))

;;; EVALUATE statement

(defun compile-cp1610-evaluate (stmt)
  (let ((subject (getf (rest stmt) :subject))
        (clauses (getf (rest stmt) :when-clauses))
        (label-end (cp1610-label "eval")))
    (dolist (clause (ensure-list clauses))
      (cond
        ((eq (first clause) :when-other)
         (dolist (s (ensure-list (second clause)))
           (compile-statement :cp1610 (first s) (rest s))))
        ((eq (first clause) :when)
         (let ((phrases (second clause))
               (stmts (third clause))
               (label-next (cp1610-label "when")))
           (cond
             ((eq phrases 'eightbol::any)
              (dolist (s (ensure-list stmts))
                (compile-statement :cp1610 (first s) (rest s)))
              (format *output-stream* "~&~10tB       ~a" label-end))
             ((or (eq phrases 'eightbol::true) (equal phrases "TRUE"))
              (compile-cp1610-load subject)
              (format *output-stream* "~&~10tTSTR    R0")
              (format *output-stream* "~&~10tBEQ     ~a" label-next)
              (dolist (s (ensure-list stmts))
                (compile-statement :cp1610 (first s) (rest s)))
              (format *output-stream* "~&~10tB       ~a" label-end)
              (format *output-stream* "~&~a:" label-next))
             ((or (eq phrases 'eightbol::false) (equal phrases "FALSE"))
              (compile-cp1610-load subject)
              (format *output-stream* "~&~10tTSTR    R0")
              (format *output-stream* "~&~10tBNEQ    ~a" label-next)
              (dolist (s (ensure-list stmts))
                (compile-statement :cp1610 (first s) (rest s)))
              (format *output-stream* "~&~10tB       ~a" label-end)
              (format *output-stream* "~&~a:" label-next))
             ((and (listp phrases) (eq (first phrases) :not))
              (compile-cp1610-load subject)
              (format *output-stream* "~&~10tMOVR    R0, R1")
              (compile-cp1610-load (second phrases))
              (format *output-stream* "~&~10tCMPR    R1, R0")
              (format *output-stream* "~&~10tBEQ     ~a" label-next)
              (dolist (s (ensure-list stmts))
                (compile-statement :cp1610 (first s) (rest s)))
              (format *output-stream* "~&~10tB       ~a" label-end)
              (format *output-stream* "~&~a:" label-next))
             ((and (listp phrases) (member (first phrases) '(:through :thru)))
              (let ((lo (second phrases)) (hi (third phrases)))
                (compile-cp1610-load subject)
                (format *output-stream* "~&~10tMOVR    R0, R1")
                (compile-cp1610-load lo)
                (format *output-stream* "~&~10tCMPR    R0, R1")
                (format *output-stream* "~&~10tBGT     ~a" label-next)
                (compile-cp1610-load hi)
                (format *output-stream* "~&~10tCMPR    R1, R0")
                (format *output-stream* "~&~10tBLT     ~a" label-next)
                (dolist (s (ensure-list stmts))
                  (compile-statement :cp1610 (first s) (rest s)))
                (format *output-stream* "~&~10tB       ~a" label-end)
                (format *output-stream* "~&~a:" label-next)))
             (t
              (let ((phrase-expr (if (listp phrases) (second phrases) phrases)))
                (compile-cp1610-load subject)
                (format *output-stream* "~&~10tMOVR    R0, R1")
                (compile-cp1610-load phrase-expr)
                (format *output-stream* "~&~10tCMPR    R1, R0")
                (format *output-stream* "~&~10tBNEQ    ~a" label-next)
                (dolist (s (ensure-list stmts))
                  (compile-statement :cp1610 (first s) (rest s)))
                (format *output-stream* "~&~10tB       ~a" label-end)
                (format *output-stream* "~&~a:" label-next))))))))
    (format *output-stream* "~&~a:" label-end)))

;;; INSPECT statement

(defun compile-cp1610-inspect (stmt)
  (let ((target (getf (rest stmt) :target))
        (tally (getf (rest stmt) :tallying))
        (conv-from (getf (rest stmt) :converting))
        (conv-to (getf (rest stmt) :to))
        (repl-by (getf (rest stmt) :by)))
    (let ((target-sym (cp1610-symbol (format nil "~a" target))))
      (cond
        (tally
         (let ((tally-sym (cp1610-symbol (format nil "~a" tally))))
           (format *output-stream* "~&~10t;; INSPECT ~a TALLYING ~a FOR CHARACTERS" target tally)
           (format *output-stream* "~&~10tMVII    #~a, R2" target-sym)
           (let ((label (cp1610-label "tally"))
                 (label-done (cp1610-label "tallyd"))
                 (label-skip (cp1610-label "tallys")))
             (format *output-stream* "~&~a:" label)
             (format *output-stream* "~&~10tMVI@    R2, R0")
             (format *output-stream* "~&~10tTSTR    R0")
             (format *output-stream* "~&~10tBEQ     ~a" label-done)
             (format *output-stream* "~&~10tMVI     ~a, R0" tally-sym)
             (format *output-stream* "~&~10tINCR    R0")
             (format *output-stream* "~&~10tMVO     R0, ~a" tally-sym)
             (format *output-stream* "~&~a:" label-skip)
             (format *output-stream* "~&~10tINCR    R2")
             (format *output-stream* "~&~10tB       ~a" label)
             (format *output-stream* "~&~a:" label-done))))
        (conv-from
         (format *output-stream* "~&~10t;; INSPECT ~a CONVERTING" target)
         (format *output-stream* "~&~10tMVII    #~a, R2" target-sym)
         (let ((label (cp1610-label "insp"))
               (label-next (cp1610-label "inspn"))
               (label-done (cp1610-label "inspd")))
           (format *output-stream* "~&~a:" label)
           (format *output-stream* "~&~10tMVI@    R2, R0")
           (format *output-stream* "~&~10tTSTR    R0")
           (format *output-stream* "~&~10tBEQ     ~a" label-done)
           (if (cp1610-expr-is-constant-p conv-from)
               (format *output-stream* "~&~10tCMPI    #~a, R0" (cp1610-value conv-from))
               (progn
                 (format *output-stream* "~&~10tMOVR    R0, R1")
                 (compile-cp1610-load conv-from)
                 (format *output-stream* "~&~10tCMPR    R0, R1")))
           (format *output-stream* "~&~10tBNEQ    ~a" label-next)
           (compile-cp1610-load conv-to)
           (format *output-stream* "~&~10tMVO@    R0, R2")
           (format *output-stream* "~&~a:" label-next)
           (format *output-stream* "~&~10tINCR    R2")
           (format *output-stream* "~&~10tB       ~a" label)
           (format *output-stream* "~&~a:" label-done)))
        (repl-by
         (let ((len (or (gethash (format nil "~a" target) *pic-size-table*) 64)))
           (format *output-stream* "~&~10t;; INSPECT ~a REPLACING CHARACTERS BY ~a" target repl-by)
           (compile-cp1610-load repl-by)
           (format *output-stream* "~&~10tMVII    #~a, R2" target-sym)
           (let ((label (cp1610-label "insp")))
             (format *output-stream* "~&~10tMVII    #~d, R1" len)
             (format *output-stream* "~&~a:" label)
             (format *output-stream* "~&~10tMVO@    R0, R2")
             (format *output-stream* "~&~10tDECR    R1")
             (format *output-stream* "~&~10tBNEQ    ~a" label))))))))

;;; ADD / SUBTRACT / COMPUTE / SET

(defun %cp1610-bcd-correct (w)
  "Emit software BCD correction for the low byte of R0 after ADDR.
W is the byte width (1 or 2). For w=2, corrects both bytes with carry."
  (let ((l1 (cp1610-label "bc"))
        (l2 (cp1610-label "bc2"))
        (l3 (cp1610-label "bc3"))
        (l4 (cp1610-label "bc4")))
    (format *output-stream* "~&~10tMOVR    R0, R2")
    (format *output-stream* "~&~10tANDI    #$FF, R2")
    (format *output-stream* "~&~10tMOVR    R2, R3")
    (format *output-stream* "~&~10tANDI    #$0F, R3")
    (format *output-stream* "~&~10tCMPI    #10, R3")
    (format *output-stream* "~&~10tBLT     ~a" l1)
    (format *output-stream* "~&~10tADDI    #6, R2")
    (format *output-stream* "~&~a:" l1)
    (format *output-stream* "~&~10tMOVR    R2, R3")
    (format *output-stream* "~&~10tANDI    #$F0, R3")
    (format *output-stream* "~&~10tCMPI    #$A0, R3")
    (format *output-stream* "~&~10tBLT     ~a" l2)
    (format *output-stream* "~&~10tADDI    #$60, R2")
    (format *output-stream* "~&~a:" l2)
    (format *output-stream* "~&~10tANDI    #$FF00, R0")
    (format *output-stream* "~&~10tADDR    R2, R0")
    (when (= w 2)
      (format *output-stream* "~&~10tMOVR    R0, R2")
      (format *output-stream* "~&~10tSARC    R0, 8")
      (format *output-stream* "~&~10tANDI    #$FF, R2")
      (format *output-stream* "~&~10tANDI    #$FF, R0")
      (format *output-stream* "~&~10tMOVR    R0, R3")
      (format *output-stream* "~&~10tANDI    #$0F, R3")
      (format *output-stream* "~&~10tCMPI    #10, R3")
      (format *output-stream* "~&~10tBLT     ~a" l3)
      (format *output-stream* "~&~10tADDI    #6, R0")
      (format *output-stream* "~&~a:" l3)
      (format *output-stream* "~&~10tMOVR    R0, R3")
      (format *output-stream* "~&~10tANDI    #$F0, R3")
      (format *output-stream* "~&~10tCMPI    #$A0, R3")
      (format *output-stream* "~&~10tBLT     ~a" l4)
      (format *output-stream* "~&~10tADDI    #$60, R0")
      (format *output-stream* "~&~a:" l4)
      (format *output-stream* "~&~10tANDI    #$FF, R0")
      (format *output-stream* "~&~10tSLL     R0, 8")
      (format *output-stream* "~&~10tADDR    R2, R0"))))

(defun compile-cp1610-add (stmt)
  (let* ((from (getf (rest stmt) :from))
         (to-op (getf (rest stmt) :to))
         (giving (getf (rest stmt) :giving))
         (result (or giving (and (stringp to-op) to-op)
                     (and (listp to-op) (eq (first to-op) :subscript) to-op)))
         (bcd-p (or (operand-bcd-p from) (operand-bcd-p to-op)))
         (w (max (operand-width result) (expression-operand-width from) (operand-width to-op))))
    (assert-pic-decimal-add-compiled :cp1610 stmt)
    (let ((df (%operand-pic-fractional-decimal-digits from))
          (dt (%operand-pic-fractional-decimal-digits to-op))
          (scale-done nil))
      (when (and (> dt df) (not (operand-bcd-p from)))
        (compile-cp1610-load from 1 :r0)
        (format *output-stream* "~&~10tSLL     R0, ~d" (* 4 (- dt df)))
        (setf scale-done :from))
      (when (and (> df dt) (not (operand-bcd-p to-op)))
        (compile-cp1610-load to-op 1 :r1)
        (format *output-stream* "~&~10tSLL     R1, ~d" (* 4 (- df dt)))
        (setf scale-done :to))
      (case scale-done
        (:from
         (format *output-stream* "~&~10tMOVR    R0, R1")
         (compile-cp1610-load to-op 1 :r0))
        (:to
         (compile-cp1610-load from 1 :r0))
        (t
         (compile-cp1610-load from 1 :r0)
         (compile-cp1610-load to-op 1 :r1))))
    (format *output-stream* "~&~10tADDR    R1, R0")
    (when bcd-p
      (%cp1610-bcd-correct w))
    (when result
      (cond
        ((stringp result)
         (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol (format nil "~a" result))))
        ((and (listp result) (eq (first result) :subscript))
         (let ((to-w (operand-width result)))
           (format *output-stream* "~&~10tMOVR    R0, R1")
           (compile-cp1610-load (third result) 1)
           (when (= (or to-w 1) 2)
             (format *output-stream* "~&~10tSLL     R0, 1"))
           (format *output-stream* "~&~10tMVII    #~a, R4"
                   (bare-data-assembly-symbol (second result) *class-id*))
           (format *output-stream* "~&~10tADDR    R0, R4")
           (format *output-stream* "~&~10tMOVR    R1, R0")
           (format *output-stream* "~&~10tMVO@    R0, R4")))
        (t (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol (format nil "~a" result))))))))

(defun compile-cp1610-subtract (stmt)
  (multiple-value-bind (minuend subtrahend)
      (subtract-statement-minuend-and-subtrahend stmt)
    (let* ((giving (getf (rest stmt) :giving))
           (dest (or giving minuend))
           (bcd-p (or (operand-bcd-p minuend) (operand-bcd-p subtrahend)))
           (w (max (operand-width dest) (expression-operand-width subtrahend) (operand-width minuend))))
    (assert-pic-decimal-subtract-compiled :cp1610 stmt)
    (let* ((dm (%operand-pic-fractional-decimal-digits minuend))
           (ds (%operand-pic-fractional-decimal-digits subtrahend))
           (did-scale (or (and (> ds dm) (not (operand-bcd-p minuend)))
                          (and (> dm ds) (not (operand-bcd-p subtrahend))))))
      (when (and (> ds dm) (not (operand-bcd-p minuend)))
        (compile-cp1610-load minuend 1 :r0)
        (format *output-stream* "~&~10tSLL     R0, ~d" (* 4 (- ds dm)))
        (format *output-stream* "~&~10tMOVR    R0, R1")
        (compile-cp1610-load subtrahend))
      (when (and (> dm ds) (not (operand-bcd-p subtrahend)))
        (compile-cp1610-load minuend 1 :r1)
        (compile-cp1610-load subtrahend)
        (format *output-stream* "~&~10tSLL     R0, ~d" (* 4 (- dm ds))))
      (unless did-scale
        (compile-cp1610-load minuend)
        (format *output-stream* "~&~10tMOVR    R0, R1")
        (compile-cp1610-load subtrahend)))
    (format *output-stream* "~&~10tSUBR    R0, R1")
    (format *output-stream* "~&~10tMOVR    R1, R0")
    (when bcd-p
      (%cp1610-bcd-correct w))
    (cond
      ((stringp dest)
       (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol (format nil "~a" dest))))
      ((and (listp dest) (eq (first dest) :subscript))
       (let ((dest-w (operand-width dest)))
         (format *output-stream* "~&~10tMOVR    R0, R1")
         (compile-cp1610-load (third dest) 1)
         (when (= (or dest-w 1) 2)
           (format *output-stream* "~&~10tSLL     R0, 1"))
         (format *output-stream* "~&~10tMVII    #~a, R4"
                 (bare-data-assembly-symbol (second dest) *class-id*))
         (format *output-stream* "~&~10tADDR    R0, R4")
         (format *output-stream* "~&~10tMOVR    R1, R0")
         (format *output-stream* "~&~10tMVO@    R0, R4")))
      (t (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol (format nil "~a" dest))))))))

(defun cp1610-store-r0-to-set-target (target target-w)
  "Store R0 into SET destination TARGET (identifier, :of, or :subscript)."
  (cond
    ((stringp target)
     (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol target)))
    ((and (listp target) (eq (first target) :of))
     (let ((obj (third target)))
       (when (member obj '(:self "Self" self) :test #'equal)
         (format *output-stream* "~&~10tMVII    #~a, R4" (apply #'slot-symbol (rest target)))
         (format *output-stream* "~&~10tADD     Self, R4")
         (format *output-stream* "~&~10tMVO@    R0, R4"))))
    ((and (listp target) (eq (first target) :subscript))
     (format *output-stream* "~&~10tMOVR    R0, R1")
     (compile-cp1610-load (third target) 1)
     (when (= (or target-w 1) 2)
       (format *output-stream* "~&~10tSLL     R0, 1"))
     (format *output-stream* "~&~10tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second target))))
     (format *output-stream* "~&~10tADDR    R0, R4")
     (format *output-stream* "~&~10tMOVR    R1, R0")
     (format *output-stream* "~&~10tMVO@    R0, R4"))
    (t (format *output-stream* "~&~10t;; Unsupported set ~s" target))))

(defun compile-cp1610-compute (stmt)
  (let* ((target (getf (rest stmt) :target))
         (expr (getf (rest stmt) :expression))
         (target-w (operand-width target)))
    (compile-cp1610-load expr)
    (cond
      ((stringp target)
       (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol (format nil "~a" target))))
      ((and (listp target) (eq (first target) :subscript))
       (format *output-stream* "~&~10tMOVR    R0, R1")
       (compile-cp1610-load (third target) 1)
       (when (= (or target-w 1) 2)
         (format *output-stream* "~&~10tSLL     R0, 1"))
       (format *output-stream* "~&~10tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second target))))
       (format *output-stream* "~&~10tADDR    R0, R4")
       (format *output-stream* "~&~10tMOVR    R1, R0")
       (format *output-stream* "~&~10tMVO@    R0, R4"))
      (t (format *output-stream* "~&~10tMVO     R0, ~a" (cp1610-symbol (format nil "~a" target)))))))

(defun compile-cp1610-set (stmt)
  (let* ((target (getf (rest stmt) :target))
         (value (getf (rest stmt) :value))
         (up-by (getf (rest stmt) :up-by))
         (down-by (getf (rest stmt) :down-by))
         (by-expr (getf (rest stmt) :by))
         (address-of (getf (rest stmt) :address-of))
         (to-self (getf (rest stmt) :to-self))
         (target-w (operand-width (or target to-self up-by down-by))))
    (cond
      (up-by
       (compile-cp1610-add (list :add :from by-expr :to up-by :giving nil)))
      (down-by
       (compile-cp1610-subtract (list :subtract :from by-expr :from-target down-by :giving nil)))
      ((and address-of target)
       (let ((src address-of) (dest target))
         (cond
           ((and (listp src) (eq :of (first src))
                 (member (third src) '(:self "Self" self) :test #'equal))
            (format *output-stream* "~&~10tMVII    #~a, R4" (apply #'slot-symbol (rest src)))
            (format *output-stream* "~&~10tADD     Self, R4")
            (format *output-stream* "~&~10tMOVR    R4, R0"))
           ((stringp src)
            (format *output-stream* "~&~10tMVII    #~a, R0" (cp1610-symbol src)))
           (t (format *output-stream* "~&~10t;; Unsupported SET ADDRESS OF source ~s" src)))
         (cp1610-store-r0-to-set-target dest target-w)))
      (to-self
       (format *output-stream* "~&~10tMOVR    Self, R0")
       (cp1610-store-r0-to-set-target to-self target-w))
      (t
       (compile-cp1610-load value)
       (cp1610-store-r0-to-set-target target target-w)))))

;;; PERFORM

(defun compile-cp1610-perform (stmt)
  (let ((proc (getf (rest stmt) :procedure))
        (times (getf (rest stmt) :times))
        (until (getf (rest stmt) :until)))
    (cond
      (times
       (let ((label (cp1610-label "perf")))
         (compile-cp1610-load times)
         (format *output-stream* "~&~10tMOVR    R0, R1")
         (format *output-stream* "~&~a:" label)
         (format *output-stream* "~&~10tJSR     R5, ~a" (cp1610-symbol (format nil "~a" proc)))
         (format *output-stream* "~&~10tDECR    R1")
         (format *output-stream* "~&~10tBNEQ    ~a" label)))
      (until
       (let ((label-loop (cp1610-label "loop"))
             (label-end (cp1610-label "end")))
         (format *output-stream* "~&~a:" label-loop)
         (compile-cp1610-condition until label-end)
         (format *output-stream* "~&~10tJSR     R5, ~a" (cp1610-symbol (format nil "~a" proc)))
         (format *output-stream* "~&~10tB       ~a" label-loop)
         (format *output-stream* "~&~a:" label-end)))
      (t
       (format *output-stream* "~&~10tJSR     R5, ~a" (cp1610-symbol (format nil "~a" proc)))))))

;;; STRING BLT

(defun cp1610-string-operand-address (operand)
  "Return as1600 address expression for STRING operand (identifier or :refmod)."
  (cond
    ((and (listp operand) (eq (first operand) :refmod))
     (let* ((base   (getf (rest operand) :base))
            (start  (getf (rest operand) :start))
            (base-str (cp1610-symbol (format nil "~a" base))))
       (if (and (integerp start) (= start 1))
           base-str
           (format nil "~a+~d" base-str (1- start)))))
    (t
     (cp1610-symbol (format nil "~a" operand)))))

(defun cp1610-para-label (name)
  (cp1610-symbol (format nil "~a_~a_~a" *class-id* (or *method-id* "") name)))

(defun compile-cp1610-paragraph (stmt)
  (let ((name (if (eq (first stmt) :paragraph)
                  (second stmt)
                  (or (getf (rest stmt) :paragraph) (second stmt)))))
    (when name
      (format *output-stream* "~&~a:" (cp1610-para-label (format nil "~a" name))))))

(defun compile-cp1610-goto (stmt)
  (let ((target (getf (rest stmt) :target))
        (targets (getf (rest stmt) :targets))
        (dep (getf (rest stmt) :depending-on)))
    (if dep
        (let ((target-list (or targets (when target (list target)))))
          (compile-cp1610-load dep)
          (when target-list
            (format *output-stream* "~&~10t;; GO DEPENDING ON (CMP/BEQ chain)")
            (loop for tgt in (butlast target-list) for i from 1
                  do (format *output-stream* "~&~10tCMPI    #~d, R0" i)
                     (format *output-stream* "~&~10tBEQ     ~a" (cp1610-para-label (format nil "~a" tgt))))
            (format *output-stream* "~&~10tB ~a" (cp1610-para-label (or target (first targets))))))
        (format *output-stream* "~&~10tB ~a"
                (cp1610-para-label (or target (first targets)))))))

(defun %cp1610-string-blt-length-expr (operand stmt)
  "Length for STRING BLT: LENGTH clause, else :length from :refmod plist."
  (or (getf (rest stmt) :length)
      (when (and (listp operand) (eq (first operand) :refmod))
        (getf (rest operand) :length))))

(defun compile-cp1610-string-blt (stmt)
  "Emit cp1610 block copy loop. Uses R2=src, R3=dest (R5 is return-addr for JSR)."
  (let* ((source (getf (rest stmt) :source))
         (dest (getf (rest stmt) :dest))
         (len-expr (or (%cp1610-string-blt-length-expr source stmt)
                        (%cp1610-string-blt-length-expr dest stmt)))
         (len (if (integerp len-expr) len-expr 64))
         (label (cp1610-label "blt")))
    (format *output-stream* "~&~10tMVII    #~a, R2" (cp1610-string-operand-address source))
    (format *output-stream* "~&~10tMVII    #~a, R3" (cp1610-string-operand-address dest))
    (format *output-stream* "~&~10tMVII    #~d, R1" len)
    (format *output-stream* "~&~a:" label)
    (format *output-stream* "~&~10tMVI@    R2, R0")
    (format *output-stream* "~&~10tMVO@    R0, R3")
    (format *output-stream* "~&~10tDECR    R1")
    (format *output-stream* "~&~10tBNEQ    ~a" label)))
