;; src/frontend-objective/objective-lexer.lisp — Tokenization for Objective-C source
;; Based on Objective-C syntax with 8-bit/16-bit system constraints
;; 
;; Heritage notes:
;; - Objective-C syntax retained (@interface/@implementation/@end keywords)
;; - Property access converted to message sends to getters/setters
;; - For loops converted to perform varying with manual iteration
;; - If/then/else blocks remain intact but simplified for 8-bit targets
;;; - @try/@catch/@finally converted to error logging (see :log-fault node)
;;; - @throw converted to debug-break
;
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *objective-keyword-alist*
  '(("@INTERFACE" . :AT-INTERFACE)
    ("@IMPLEMENTATION" . :AT-IMPLEMENTATION)
    ("@END" . :AT-END)
    ("@PROPERTY" . :AT-PROPERTY)
    ("@SELECTOR" . :AT-SELECTOR)
    ("@PROTOCOL" . :AT-PROTOCOL)
    ("@PUBLIC" . :AT-PUBLIC)
    ("@PRIVATE" . :AT-PRIVATE)
    ("@PROTECTED" . :AT-PROTECTED)
    ("@SYNTHESIZE" . :AT-SYNTHESIZE)
    ("@AUTORELEASEPOOL" . :AT-AUTORELEASEPOOL)
    ("@TRY" . :AT-TRY)
    ("@CATCH" . :AT-CATCH)
    ("@FINALLY" . :AT-FINALLY)
    ("@THROW" . :AT-THROW)
    ("@RETURN" . :AT-RETURN)
    ("IF" . :IF)
    ("ELSE" . :ELSE)
    ("FOR" . :FOR)
    ("WHILE" . :WHILE)
    ("DO" . :DO)
    ("RETURN" . :RETURN)
    ("BREAK" . :BREAK)
    ("CONTINUE" . :CONTINUE)
    ("SWITCH" . :SWITCH)
    ("CASE" . :CASE)
    ("DEFAULT" . :DEFAULT)
    ("SELF" . :SELF)
    ("SUPER" . :SUPER)
    ("NIL" . :NIL)
    ("YES" . :YES)
    ("NO" . :NO)
    ("TRUE" . :TRUE)
    ("FALSE" . :FALSE)
    ("ID" . :ID-TYPE)
    ("VOID" . :VOID)
    ("CLASS" . :CLASS)
    ("PROTOCOL" . :PROTOCOL))
  "Association list of Objective-C keywords to token symbols.")

(defparameter *objective-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("%" . :MODULO)
    ("=" . :EQUAL)
    ("==" . :EQUAL-EQUAL)
    ("!=" . :NOT-EQUAL)
    ("<>" . :NOT-EQUAL)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE)
    ("&&" . :AND-AND)
    ("||" . :OR-OR)
    ("!" . :NOT)
    ("[" . :LBRACKET)
    ("]" . :RBRACKET)
    ("." . :DOT)
    (":" . :COLON)
    (";" . :SEMICOLON)
    ("(" . :LPAREN)
    (")" . :RPAREN)
    ("{" . :LBRACE)
    ("}" . :RBRACE)
    ("," . :COMMA)
    ("->" . :ARROW)
    ("." . :DOT))
  "Association list of Objective-C operators to token symbols.")

(defun objective-token-type (lexeme)
  "Return token type for LEXEME, a string."
  (cond
    ((and (stringp lexeme) (char= (char lexeme 0) #\@))
     (or (cdr (assoc lexeme *objective-keyword-alist* :test #'string-equal))
         :AT-IDENT))
    ((and (stringp lexeme) (digit-char-p (char lexeme 0)))
     :NUMBER)
    ((and (stringp lexeme) (char= (char lexeme 0) #\"))
     :STRING)
    ((assoc lexeme *objective-keyword-alist* :test #'string-equal)
     (cdr (assoc lexeme *objective-keyword-alist* :test #'string-equal)))
    ((assoc lexeme *objective-operators-alist* :test #'string-equal)
     (cdr (assoc lexeme *objective-operators-alist* :test #'string-equal)))
    ((objective-valid-identifier-p lexeme)
     :IDENT)
    (t :UNKNOWN)))

(defun objective-valid-identifier-p (s)
  "Check if S is a valid Objective-C identifier (PascalCase or camelCase)."
  (and (stringp s)
       (plusp (length s))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\_)))
              s)))

(defun objective-lex-line (line)
  "Split LINE into token list of (type value) pairs.
Handles quoted strings, operators, identifiers, and Objective-C specific syntax."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (skip-whitespace ()
               (loop while (and (not (eof?))
                                (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (flush-token (start end type)
               (let ((text (coerce (subseq chars start end) 'string)))
                 (unless (zerop (length text))
                   (push (cons type text) tokens))))
             (scan-number (start)
               (loop while (and (not (eof?))
                                (or (digit-char-p (peek))
                                    (and (char= (peek) #\.)
                                         (digit-char-p (nth (1+ i) chars)))))
                     do (next-char))
               (flush-token start (1- i) :NUMBER))
             (scan-string (start)
               (next-char) ; skip opening quote
               (loop while (and (not (eof?)) (char/= (peek) #\"))
                     do (when (and (char= (peek) #\\) (not (eof?)))
                          (next-char)) ; skip escaped char
                        (next-char))
               (when (not (eof?)) (next-char)) ; skip closing quote
               (flush-token (1+ start) (1- i) :STRING))
             (scan-identifier (start)
               (loop while (and (not (eof?))
                                (or (alphanumericp (peek))
                                    (char= (peek) #\_)
                                    (char= (peek) #\@)))
                     do (next-char))
               (flush-token start (1- i) :IDENT)))
      (loop until (eof?)
            do (skip-whitespace)
               (cond
                 ((eof?) (return))
                 ((char= (peek) #\") (scan-string i))
                 ((digit-char-p (peek)) (scan-number i))
                 ((or (alphanumericp (peek)) (char= (peek) #\@) (char= (peek) #\_))
                  (scan-identifier i))
                 (t
                  (let* ((op1 (string (next-char)))
                         (op2 (when (not (eof?)) (string (peek))))
                         (op3 (when (and op2 (not (eof?))) (string (nth (1+ i) chars)))))
                    (cond
                      ((and op2 op3 (string= (concatenate 'string op1 op2 op3) "||="))
                       (next-char) (next-char)
                       (flush-token (1- i) i :OR-OR-EQUAL))
                      ((and op2 op3 (string= (concatenate 'string op1 op2 op3) "&&="))
                       (next-char) (next-char)
                       (flush-token (1- i) i :AND-AND-EQUAL))
                      ((and op2 (string= (concatenate 'string op1 op2) "=="))
                       (next-char)
                       (flush-token (1- i) i :EQUAL-EQUAL))
                      ((and op2 (string= (concatenate 'string op1 op2) "!="))
                       (next-char)
                       (flush-token (1- i) i :NOT-EQUAL))
                      ((and op2 (string= (concatenate 'string op1 op2) "<="))
                       (next-char)
                       (flush-token (1- i) i :LE))
                      ((and op2 (string= (concatenate 'string op1 op2) ">="))
                       (next-char)
                       (flush-token (1- i) i :GE))
                      ((and op2 (string= (concatenate 'string op1 op2) "&&"))
                       (next-char)
                       (flush-token (1- i) i :AND-AND))
                      ((and op2 (string= (concatenate 'string op1 op2) "||"))
                       (next-char)
                       (flush-token (1- i) i :OR-OR))
                      ((and op2 (string= (concatenate 'string op1 op2) "->"))
                       (next-char)
                       (flush-token (1- i) i :ARROW))
                      ((and op2 (string= (concatenate 'string op1 op2) "+="))
                       (next-char)
                       (flush-token (1- i) i :PLUS-EQUAL))
                      ((and op2 (string= (concatenate 'string op1 op2) "-="))
                       (next-char)
                       (flush-token (1- i) i :MINUS-EQUAL))
                      ((and op2 (string= (concatenate 'string op1 op2) "*="))
                       (next-char)
                       (flush-token (1- i) i :TIMES-EQUAL))
                      ((and op2 (string= (concatenate 'string op1 op2) "/="))
                       (next-char)
                       (flush-token (1- i) i :DIVIDE-EQUAL))
                      ((and op2 (string= (concatenate 'string op1 op2) "%="))
                       (next-char)
                       (flush-token (1- i) i :MODULO-EQUAL))
                      (t
                       (flush-token (1- i) i :OP))))))))
    (nreverse tokens)))

(defun objective-lex-source (source)
  "Lex complete Objective-C SOURCE string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (or (zerop (length trimmed))
                    (and (>= (length trimmed) 2)
                         (char= (char trimmed 0) #\/)
                         (char= (char trimmed 1) #\/)))
          (setf all-tokens (nconc all-tokens (objective-lex-line trimmed))))))
    all-tokens))

(defun objective-lex (source)
  "Lex Objective-C source string into token list for YACC."
  (let ((tokens (objective-lex-source source)))
    (mapcar (lambda (tok)
              (list (first tok) (second tok)))
            tokens)))

(provide 'objective-lexer)
