;;; Array-Example Program  
;;; Generated by EIGHTBOL

;;; Global Data Section
Inventory: .fill 8, ?
Status_Array: .fill 16, ?

;;; Program Code
Array_Example:
;;; MOVE 5 TO Inventory(1)
    lda #5
    ldy #0          ; Array index 0 (EIGHTBOL index 1)
    sta Inventory,y

;;; MOVE 10 TO Inventory(2)
    lda #10
    ldy #1          ; Array index 0 (EIGHTBOL index 2)
    sta Inventory,y

;;; ADD Inventory(1) TO Inventory(2) GIVING Inventory(3)
    ldy #0          ; Load Inventory(1)
    lda Inventory,y
    ldy #1          ; Add Inventory(2)
    clc
    adc Inventory,y
    ldy #2          ; Store in Inventory(3)
    sta Inventory,y

;;; SET $80 IN Status-Array(5)
    lda Status_Array+4   ; Element 4 (EIGHTBOL index 5)
    ora #$80
    sta Status_Array+4

;;; CLEAR $40 IN Status-Array(5)
    lda Status_Array+4
    and #$BF           ; Clear bit 6 ($40)
    sta Status_Array+4

;;; GOBACK
    rts
