;;; Arithmetic-Test Program
;;; Generated by EIGHTBOL

;;; Global Data Section
ByteA: .byte ?
ByteB: .byte ?
ByteC: .byte ?
WordA: .word ?
WordB: .word ?
WordC: .word ?

;;; Program Code
Arithmetic_Test:
;;; MOVE 10 TO ByteA
    lda #10
    sta ByteA

;;; MOVE 5 TO ByteB  
    lda #5
    sta ByteB

;;; ADD ByteA TO ByteB GIVING ByteC
    lda ByteA
    clc
    adc ByteB
    sta ByteC

;;; SUBTRACT ByteB FROM ByteA GIVING ByteC
    lda ByteA
    sec
    sbc ByteB
    sta ByteC

;;; MOVE 1000 TO WordA (16-bit)
    lda #<1000    ; Low byte
    sta WordA
    lda #>1000    ; High byte  
    sta WordA+1

;;; MOVE 500 TO WordB (16-bit)
    lda #<500     ; Low byte
    sta WordB
    lda #>500     ; High byte
    sta WordB+1

;;; ADD WordA TO WordB GIVING WordC (16-bit addition)
    lda WordA     ; Add low bytes
    clc
    adc WordB
    sta WordC
    
    lda WordA+1   ; Add high bytes with carry
    adc WordB+1
    sta WordC+1

;;; SUBTRACT WordB FROM WordA GIVING WordC (16-bit subtraction)
    lda WordA     ; Subtract low bytes
    sec
    sbc WordB
    sta WordC
    
    lda WordA+1   ; Subtract high bytes with borrow
    sbc WordB+1
    sta WordC+1

;;; GOBACK
    rts
