(require 'asdf)
(asdf:load-system :cl-change-case)
(asdf:load-system :yacc)
(asdf:load-system :serapeum)
(asdf:load-system :unix-opts)
(asdf:load-system :alexandria)
(asdf:load-system :cl-ppcre)
(asdf:load-system :local-time)
(asdf:load-system :split-sequence)
(asdf:load-system :uiop)
(asdf:load-system :fiveam)
(load "src/package.lisp")
(in-package :eightbol)
(format t "main exists: ~a~%" (fboundp 'main))
(format t "make-expression-add exists: ~a~%" (fboundp 'make-expression-add))