(require 'asdf)
(asdf:load-system :cl-change-case)
(asdf:load-system :yacc)
(asdf:load-system :serapeum)
(asdf:load-system :unix-opts)
(asdf:load-system :alexandria)
(asdf:load-system :cl-ppcre)
(asdf:load-system :local-time)
(asdf:load-system :split-sequence)
(asdf:load-system :uiop)
(asdf:load-system :fiveam)
(load "src/package.lisp")
(in-package :eightbol)
(format t "make-expression-add exists: ~a~%" (fboundp 'make-expression-add))
(format t "make-expression-subtract exists: ~a~%" (fboundp 'make-expression-subtract))
(format t "make-conditional-and exists: ~a~%" (fboundp 'make-conditional-and))
(format t "make-identifier exists: ~a~%" (fboundp 'make-identifier))