(require 'asdf)
(asdf:load-system :cl-change-case)
(asdf:load-system :yacc)
(asdf:load-system :serapeum)
(asdf:load-system :unix-opts)
(asdf:load-system :alexandria)
(asdf:load-system :cl-ppcre)
(asdf:load-system :local-time)
(asdf:load-system :split-sequence)
(asdf:load-system :uiop)
(asdf:load-system :fiveam)
(load "src/package.lisp")
(asdf:load-system :eightbol)
(format t "Testing make-expression-add: ~a~%" (fboundp 'make-expression-add))
(format t "Testing make-expression-subtract: ~a~%" (fboundp 'make-expression-subtract))
(format t "Testing make-conditional-and: ~a~%" (fboundp 'make-conditional-and))
(format t "Testing make-identifier: ~a~%" (fboundp 'make-identifier))