(in-package :eightbol)

(defun process-labels (tokens)
  "Convert IDENTIFIER: or NUMBER: patterns to (:label \"NAME\") tokens."
  (let ((result '())
        (prev nil))
    (dolist (tok tokens)
      (cond
        ((and (eq (first tok) :colon) (symbolp prev))
         (setf result (append (reverse (list (list :label (symbol-name prev)))) result))
         (setf prev nil))
        ((and (eq (first tok) :colon) (eq (second tok) :number))
         (setf result (append (list (list :label (second tok))) result))
         (setf prev nil))
        (t
         (setf prev (first tok))
         (push tok result))))
    (if (and (symbolp prev) (null (cdr result)))
        (append (list (list :label (symbol-name prev))) (reverse result))
        (reverse result))))

(defun pascal-lex-line (line)
  "Split LINE into token list of (type value) pairs.
Handles labels (IDENTIFIER:), numbers, strings, identifiers, and operators."
  (let ((tokens '())
        (chars (coerce line 'list))
        (current '()))
    (labels ((flush ()
               (when current
                 (let ((lexeme (coerce (nreverse current) 'string)))
                   (unless (zerop (length lexeme))
                     (let ((type (pascal-token-type lexeme)))
                       (push (list type lexeme) tokens))))
                 (setf current nil))))
      (do ((remaining-chars chars (cdr remaining-chars)))
          ((null remaining-chars))
        (let ((c (car remaining-chars)))
          (cond
            ((find c " \t\r\n")
             (flush))
            ((char= c #\")
             (flush)
             (let ((chars-in-string (list c)))
               (do ((rest (cdr remaining-chars) (cdr rest))
                    (nc (car (cdr remaining-chars)) (car rest)))
                   ((or (null rest) (char= nc #\")))
                 (push nc chars-in-string)
                 (setf remaining-chars rest))
               (when (car remaining-chars)
                 (push (car remaining-chars) chars-in-string))
               (push (list :string (coerce (nreverse chars-in-string) 'string)) tokens)))
            ((find c "+-*/=<>")
             (flush)
             (push (list :op (string c)) tokens))
            ((char= c #\:)
             (flush)
             (push (list :colon nil) tokens))
            ((char= c #\;)
             (flush)
             (push (list :semicolon nil) tokens))
            ((char= c #\Comma)
             (flush)
             (push (list :comma nil) tokens))
            ((char= c #\()
             (flush)
             (push (list :lparen nil) tokens))
            ((char= c #\))
             (flush)
             (push (list :rparen nil) tokens))
            (t
             (push c current)))))
      (flush)
      (process-labels (nreverse tokens)))))

(defun pascal-lex-source (source)
  "Lex complete Pascal SOURCE string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (or (zerop (length trimmed))
                    (char= #\; (char trimmed 0)))
          (setq all-tokens (append all-tokens (pascal-lex-line trimmed))))))
    all-tokens))
