;; src/backend-zork/backend-zork.lisp — Zork/Infocom Z-Machine bytecode backend
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defun zork-symbol (name)
  "Convert EIGHTBOL identifier to Z-Machine symbol (PascalCase)."
  (pascal-case (format nil "~a" name)))

(defun paragraph-label (name)
  "Return Z-Machine label for paragraph NAME."
  (zork-symbol (format nil "~a" name)))

;;; Top-level entry point

(defmethod compile-to-assembly (ast (cpu (eql :zork)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/Zork: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table
                          pic-size-table pic-width-table pic-frac-bits-table pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (let ((*output-stream* output-stream)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*service-bank-table* service-bank-table)
            (*usage-table* usage-table)
            (*sign-table* sign-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table)
            (*pic-frac-bits-table* pic-frac-bits-table)
            (*pic-nybble-semantics-table* pic-nybble-semantics-table))
        (format output-stream "; Zork/Infocom Z-Machine code~%")
        (format output-stream "; Generated by EIGHTBOL for Zork~%")
        (format output-stream "; DO NOT EDIT -- regenerate from ~a.cob~%~%" class-id)
        (format output-stream "(method ~a)~%" class-id)
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-zork-method method)))))))

;;; Method compilation

(defun compile-zork-method (method)
  (let ((*method-id* (getf (rest method) :method-id)))
    (declare (special *method-id*))
    (let* ((method-id *method-id*)
           (method-name (zork-symbol (format nil "~a" method-id)))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                        (getf (rest method) :statements))))
           (stmts (nth-value 1 (split-method-leading-assembly-entry
                                  (getf (rest method) :statements)))))
      (format *output-stream* "~%; Method: ~a~%" method-name)
      (format *output-stream* "(proc ~a ~%" method-name)
      (dolist (stmt stmts)
        (compile-statement :zork (first stmt) (rest stmt)))
      (format *output-stream* ")~%"))))

;;; Statement dispatch

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :goback)) ast-node-data)
  (format *output-stream* "  (ret)~%"))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :exit-method)) ast-node-data)
  (format *output-stream* "  (ret)~%"))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :exit-program)) ast-node-data)
  (format *output-stream* "  (ret)~%"))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :move)) ast-node-data)
  (let ((from (getf ast-node-data :from))
        (to (getf ast-node-data :to)))
    (compile-zork-load from)
    (compile-zork-store to)))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :add)) ast-node-data)
  (let ((from (getf ast-node-data :from))
        (to (getf ast-node-data :to))
        (giving (getf ast-node-data :giving)))
    (compile-zork-load to)
    (compile-zork-load from)
    (compile-zork-store (or giving to))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :subtract)) ast-node-data)
  (let ((from (getf ast-node-data :from))
        (to (getf ast-node-data :to))
        (giving (getf ast-node-data :giving)))
    (compile-zork-load to)
    (compile-zork-load from)
    (compile-zork-store (or giving to))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :compute)) ast-node-data)
  (let ((target (getf ast-node-data :target))
        (expression (getf ast-node-data :expression)))
    (compile-zork-load expression)
    (compile-zork-store target)))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :set)) ast-node-data)
  (let ((target (getf ast-node-data :target))
        (value (getf ast-node-data :value)))
    (compile-zork-load value)
    (compile-zork-store target)))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :if)) ast-node-data)
  (let ((condition (getf ast-node-data :condition))
        (then-stmts (getf ast-node-data :then))
        (else-stmts (getf ast-node-data :else))
        (else-label (gensym "ELSE"))
        (end-label (gensym "END")))
    (compile-zork-condition condition else-label)
    (dolist (s (ensure-list then-stmts))
      (compile-statement :zork (first s) (rest s)))
    (format *output-stream* "  (branch ~a)~%" else-label)
    (format *output-stream* "~a:~%" else-label)
    (dolist (s (ensure-list else-stmts))
      (compile-statement :zork (first s) (rest s)))
    (format *output-stream* "~a:~%" end-label)))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :call)) ast-node-data)
  (let ((target (getf ast-node-data :target)))
    (format *output-stream* "  (call ~a)~%" (zork-symbol (format nil "~a" target)))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :invoke)) ast-node-data)
  (let ((method (getf ast-node-data :method)))
    (format *output-stream* "  (call Invoke~a)~%" (zork-symbol (format nil "~a" method)))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :goto)) ast-node-data)
  (let ((target (getf ast-node-data :target)))
    (format *output-stream* "  (branch ~a)~%" (zork-symbol (format nil "~a" target)))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :procedure)) ast-node-data)
  (let ((name (first ast-node-data)))
    (when name
      (format *output-stream* "; Procedure: ~a~%" name))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :comment)) ast-node-data)
  (let ((text (first ast-node-data)))
    (format *output-stream* "; ~a~%" (if (listp text) (princ-to-string text) text))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :log-fault)) ast-node-data)
  (format *output-stream* "; LOG FAULT ~s~%" (getf ast-node-data :code)))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :debug-break)) ast-node-data)
  (format *output-stream* "; DEBUG BREAK ~s~%" (getf ast-node-data :code)))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :perform)) ast-node-data)
  (let ((procedure (getf ast-node-data :procedure))
        (body (getf ast-node-data :body)))
    (format *output-stream* "; PERFORM ~a~%" procedure)
    (dolist (s (ensure-list body))
      (compile-statement :zork (first s) (rest s)))))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :evaluate)) ast-node-data)
  (format *output-stream* "; EVALUATE not yet implemented for Zork~%"))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :inspect)) ast-node-data)
  (format *output-stream* "; INSPECT not yet implemented for Zork~%"))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :string-blt)) ast-node-data)
  (format *output-stream* "; STRING BLT not yet implemented for Zork~%"))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :break)) ast-node-data)
  (format *output-stream* "; BREAK not yet implemented for Zork~%"))

(defmethod compile-statement ((cpu (eql :zork)) (stmt-type (eql :continue)) ast-node-data)
  (format *output-stream* "; CONTINUE not yet implemented for Zork~%"))

;;; Expression loading

(defun compile-zork-load (expression)
  (cond
    ((numberp expression)
     (format *output-stream* "  (literal ~d)~%" expression))
    ((stringp expression)
     (format *output-stream* "  (literal \"~a\")~%" expression))
    ((and (listp expression) (eq (first expression) :of))
     (format *output-stream* "  (load-slot ~a)~%" (second expression)))
    (t
     (format *output-stream* "  (literal 0)~%"))))

(defun compile-zork-store (destination)
  (cond
    ((stringp destination)
     (format *output-stream* "  (store ~a)~%" (zork-symbol destination)))
    (t
     (format *output-stream* "; Unsupported store ~s for Zork" destination))))

(defun compile-zork-condition (condition false-label)
  (cond
    ((and (listp condition) (member (first condition) '(= equal) :test #'eq))
     (compile-zork-load (second condition))
     (compile-zork-load (third condition))
     (format *output-stream* "  (branch=~a)~%" false-label))
    ((and (listp condition) (eq (first condition) :is-zero))
     (compile-zork-load (second condition))
     (format *output-stream* "  (branch=~a)~%" false-label))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (compile-zork-load (second condition))
     (format *output-stream* "  (branch<>~a)~%" false-label))
    (t
     (format *output-stream* "; Unsupported condition ~s for Zork" condition)
     (format *output-stream* "  (branch ~a)~%" false-label))))
