;; Src/backend-m68k.lisp — Motorola 68000 code generation backend
;;
;; Targets the Motorola 68000 instruction set ONLY (not 68010, 68020, etc.).
;; The 68000 has:
;;   Data registers:    D0–D7
;;   Address registers: A0–A7 (A7 = stack pointer)
;;   Instructions: move, add, sub, cmp, and, or, eor, not, neg, clr
;;   Control: jsr, jmp, rts, bra, bcc/bcs/beq/bne/bmi/bpl/bvc/bvs
;;   Sizes: .b (byte), .w (word), .l (long)
;;
;; Output: GAS/AT&T-style 68000 assembly (move.b, move.w, etc.)
;; Uses: D0=accumulator, A0=address temp, D1=temp
(in-package :eightbol)

(defvar *output-stream* nil)

(defun m68k-symbol (name)
  "Convert EIGHTBOL identifier to m68k assembly symbol (PascalCase)."
  (pascal-case (format nil "~a" name)))

(defun paragraph-label (name)
  "Return assembly label for paragraph NAME.
   COBOL stabby-case (e.g. My-Para) maps to PascalCase (MyPara); underscores become part of one symbol."
  (declare (ignore _))
  (m68k-symbol (format nil "~a" name)))

(defmacro def-m68k-statement (statement-type &body body)
  `(defmethod compile-statement ((cpu (eql :m68k)) (statement-type (eql ,statement-type)) ast-node-data)
     ,@body))

(defmethod compile-to-assembly (ast (cpu (eql :m68k)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/m68k: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods  (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table
                          pic-size-table pic-width-table pic-frac-bits-table
                          pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (let ((*output-stream* output-stream)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*service-bank-table* service-bank-table)
            (*usage-table* usage-table)
            (*sign-table* sign-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table)
            (*pic-frac-bits-table* pic-frac-bits-table)
            (*pic-nybble-semantics-table* pic-nybble-semantics-table))
        (declare (ignore service-bank-table sign-table))
        (format output-stream
                "| ~a -- generated by EIGHTBOL for m68k (68000)~%| DO NOT EDIT -- regenerate from ~a.cob~2%"
                class-id class-id)
        (format output-stream "~&~10t.text")
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-m68k-method method)))))))

(defun compile-m68k-method (method)
  (let ((*method-id* (getf (rest method) :method-id)))
    (declare (special *method-id*))
    (let* ((method-id *method-id*)
           (dispatch-label (format nil "Method~a~a"
                                   (m68k-symbol *class-id*)
                                   (m68k-symbol (format nil "~a" method-id))))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                        (getf (rest method) :statements))))
           (statements (nth-value 1 (split-method-leading-assembly-entry
                                      (getf (rest method) :statements)))))
      (if custom-entry
          (progn
            (format *output-stream* "~&~%~a:" (m68k-symbol custom-entry))
            (format *output-stream* "~&~a:" dispatch-label))
          (format *output-stream* "~&~%~a:" dispatch-label))
      (dolist (statement (ensure-list statements))
        (compile-statement :m68k (first statement) (rest statement)))
      (format *output-stream* "~&~10trts"))))

(defmethod compile-statement :around ((cpu (eql :m68k)) statement-type ast-node-data)
  (emit-statement-source-comment *output-stream* (cons statement-type ast-node-data))
  (call-next-method))

;;; Individual statement methods

(def-m68k-statement :goback
  (format *output-stream* "~&~10trts"))

(def-m68k-statement :exit-method
  (format *output-stream* "~&~10trts"))

(def-m68k-statement :exit-program
  (format *output-stream* "~&~10trts"))

(def-m68k-statement :stop-run
  (format *output-stream* "~&~10trts"))

(def-m68k-statement :exit
  (format *output-stream* "~&~10trts"))

(def-m68k-statement :move
  (let ((statement (cons :move ast-node-data)))
    (compile-m68k-move statement)))

(def-m68k-statement :invoke
  (let ((statement (cons :invoke ast-node-data)))
    (compile-m68k-invoke statement)))

(def-m68k-statement :call
  (let ((statement (cons :call ast-node-data)))
    (compile-m68k-call statement)))

(def-m68k-statement :if
  (let ((statement (cons :if ast-node-data)))
    (compile-m68k-if statement)))

(def-m68k-statement :add
  (let ((statement (cons :add ast-node-data)))
    (compile-m68k-add statement)))

(def-m68k-statement :subtract
  (let ((statement (cons :subtract ast-node-data)))
    (compile-m68k-subtract statement)))

(def-m68k-statement :compute
  (let ((statement (cons :compute ast-node-data)))
    (compile-m68k-compute statement)))

(def-m68k-statement :set
  (let ((statement (cons :set ast-node-data)))
    (compile-m68k-set statement)))

(def-m68k-statement :log-fault
  (format *output-stream* "~&~10t| LOG FAULT ~s" (getf ast-node-data :code)))

(def-m68k-statement :debug-break
  (format *output-stream* "~&~10t| DEBUG BREAK ~s" (getf ast-node-data :code)))

(def-m68k-statement :perform
  (let ((statement (cons :perform ast-node-data)))
    (compile-m68k-perform statement)))

(def-m68k-statement :string-blt
  (let ((statement (cons :string-blt ast-node-data)))
    (compile-m68k-string-blt statement)))

(def-m68k-statement :goto
  (let ((statement (cons :goto ast-node-data)))
    (compile-m68k-goto statement)))

(def-m68k-statement :paragraph
   (let ((name (first ast-node-data)))
     (when name (format *output-stream* "~&~a:" (paragraph-label (format nil "~a" name))))))

(def-m68k-statement :evaluate
  (let ((statement (cons :evaluate ast-node-data)))
    (compile-m68k-evaluate statement)))

(def-m68k-statement :inspect
  (let ((statement (cons :inspect ast-node-data)))
    (compile-m68k-inspect statement)))

(def-m68k-statement :comment
  (format *output-stream* "~&~10t| ~a"
          (let ((text (first ast-node-data)))
            (if (listp text)
                (format nil "~{~a~%~10t| ~}" (mapcar (lambda (s) (if (stringp s) s (princ-to-string s))) text))
                (princ-to-string text)))))

(def-m68k-statement :copy
  (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
         (getf ast-node-data :name)))

(def-m68k-statement :divide
  (let* ((divisor (getf ast-node-data :divisor))
         (into (getf ast-node-data :into))
         (by (getf ast-node-data :by))
         (source (or by into))
         (dest (or (getf ast-node-data :giving) into))
         (signed (operand-signed-p (or source dest)))
         (width (operand-width (or source dest)))
         (suffix (if (= (or width 1) 2) ".w" ".b")))
    (if (and (expression-constant-p divisor)
             (power-of-two-p (expression-constant-value divisor)))
        (let ((shift (log2 (expression-constant-value divisor))))
          (when (or (operand-bcd-p source) (operand-bcd-p dest))
            (error 'source-error
                   :message "DIVIDE: cannot use with USAGE DECIMAL operands"
                   :detail (list :divisor divisor :source source :dest dest)))
          (unless (zerop shift)
            (compile-m68k-load (or source dest))
            (dotimes (_ shift)
              (if signed
                  (format *output-stream* "~&~10tasr~a   #1, %d0" suffix)
                  (format *output-stream* "~&~10tlsr~a   #1, %d0" suffix)))
            (when (stringp dest)
              (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol dest))))))
    (error 'source-error
           :message "DIVIDE: divisor must be constant power-of-two (1, 2, 4, 8, ...)"
           :detail (format nil "DIVIDE by ~s" divisor))))

(def-m68k-statement :multiply
  (let* ((multiplier (getf ast-node-data :multiplier))
         (by (getf ast-node-data :by))
         (giving (getf ast-node-data :giving))
         (source (or giving by))
         (dest (or giving by))
         (width (operand-width (or source dest)))
         (suffix (if (= (or width 1) 2) ".w" ".b")))
    (if (and (expression-constant-p multiplier)
             (power-of-two-p (expression-constant-value multiplier)))
        (let ((shift (log2 (expression-constant-value multiplier))))
          (when (or (operand-bcd-p source) (operand-bcd-p dest))
            (error 'source-error
                   :message "MULTIPLY: cannot use with USAGE DECIMAL operands"
                   :detail (list :multiplier multiplier :source source :dest dest)))
          (unless (zerop shift)
            (compile-m68k-load (or source dest))
            (dotimes (_ shift)
              (format *output-stream* "~&~10tlsl~a   #1, %d0" suffix))
            (when (stringp dest)
              (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol dest))))))
    (error 'source-error
           :message "MULTIPLY: multiplier must be constant power-of-two (1, 2, 4, 8, ...)"
           :detail (format nil "MULTIPLY by ~s" multiplier))))

(def-m68k-statement :invoke-super
  (unless (gethash *class-id* *parent-classes*)
    (load-classes))
  (if-let (parent-class (gethash *class-id* *parent-classes*))
    (format *output-stream* "~&~10tjsr     Method~a~a"
            (m68k-symbol parent-class)
            (m68k-symbol (format nil "~a" *method-id*)))
    (error "Can't figure out parent class of ~a" *class-id*)))

(def-m68k-statement :shift-left
  (let* ((target (getf ast-node-data :target))
         (count (getf ast-node-data :count 1))
         (width (operand-width target))
         (suffix (if (= (or width 1) 2) ".w" ".b")))
    (compile-m68k-load target)
    (dotimes (_ count) (format *output-stream* "~&~10tlsl~a   #1, %d0" suffix))
    (when (stringp target)
      (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol target)))))

(def-m68k-statement :shift-right
  (let* ((target (getf ast-node-data :target))
         (count (getf ast-node-data :count 1))
         (signed (operand-signed-p target))
         (width (operand-width target))
         (suffix (if (= (or width 1) 2) ".w" ".b")))
    (compile-m68k-load target)
    (dotimes (_ count)
      (if signed
          (format *output-stream* "~&~10tasr~a   #1, %d0" suffix)
          (format *output-stream* "~&~10tlsr~a   #1, %d0" suffix)))
    (when (stringp target)
      (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol target)))))

;;; Size suffix helper

(defun m68k-size-suffix (width)
  "Return .b or .w for width 1 or 2."
  (ecase (or width 1)
    (1 ".b")
    (2 ".w")))

;;; Expression loading

(defun compile-m68k-load (expression &optional (width (operand-width expression)))
  "Load EXPRESSION into D0. Uses .b for byte, .w for word."
  (let ((suffix (m68k-size-suffix width)))
    (cond
      ((numberp expression)
       (format *output-stream* "~&~10tmove~a  #~d, %d0" suffix expression))
      ((and (stringp expression) (constant-p expression))
       (format *output-stream* "~&~10tmove~a  #~d, %d0" suffix (constant-value expression)))
      ((stringp expression)
       (format *output-stream* "~&~10tmove~a  ~a, %d0" suffix (m68k-symbol expression)))
      ((and (listp expression) (eq (first expression) :of))
       (let ((slot (second expression)) (object (third expression)))
         (when (member object '(:self "Self" self) :test #'equal)
           (format *output-stream* "~&~10tmove.l  Self, %a0")
           (format *output-stream* "~&~10tmove~a  ~a(%a0), %d0"
                   suffix (slot-symbol slot *class-id*)))))
      ((and (listp expression) (eq (first expression) :subscript))
       (compile-m68k-load (third expression) 1)
       (when (= (or width 1) 2)
         (format *output-stream* "~&~10tadd.w   %d0, %d0"))
       (format *output-stream* "~&~10tmove.l  #~a, %a0" (m68k-symbol (format nil "~a" (second expression))))
       (format *output-stream* "~&~10tmove~a  (%a0,%d0.w), %d0" suffix))
      ((and (listp expression) (eq (first expression) :shift-left))
       (let ((n (if (numberp (third expression)) (third expression) 1)))
         (compile-m68k-load (second expression))
         (dotimes (_ n) (format *output-stream* "~&~10tlsl~a   #1, %d0" suffix))))
      ((and (listp expression) (eq (first expression) :shift-right))
       (let ((n (if (numberp (third expression)) (third expression) 1)))
         (compile-m68k-load (second expression))
         (dotimes (_ n) (format *output-stream* "~&~10tlsr~a   #1, %d0" suffix))))
      ((and (listp expression) (eq (first expression) :bit-and))
       (compile-m68k-load (second expression))
       (let ((rhs (third expression)))
         (if (m68k-expression-is-constant-p rhs)
             (format *output-stream* "~&~10tandi~a  #~a, %d0" suffix (m68k-value rhs))
             (progn (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
                    (compile-m68k-load rhs)
                    (format *output-stream* "~&~10tand~a   %d1, %d0" suffix)))))
      ((and (listp expression) (eq (first expression) :bit-or))
       (compile-m68k-load (second expression))
       (let ((rhs (third expression)))
         (if (m68k-expression-is-constant-p rhs)
             (format *output-stream* "~&~10tori~a   #~a, %d0" suffix (m68k-value rhs))
             (progn (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
                    (compile-m68k-load rhs)
                    (format *output-stream* "~&~10tor~a    %d1, %d0" suffix)))))
      ((and (listp expression) (eq (first expression) :bit-xor))
       (compile-m68k-load (second expression))
       (let ((rhs (third expression)))
         (if (m68k-expression-is-constant-p rhs)
             (format *output-stream* "~&~10teori~a  #~a, %d0" suffix (m68k-value rhs))
             (progn (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
                    (compile-m68k-load rhs)
                    (format *output-stream* "~&~10teor~a   %d1, %d0" suffix)))))
      ((and (listp expression) (eq (first expression) :bit-not))
       (compile-m68k-load (second expression))
       (format *output-stream* "~&~10tnot~a   %d0" suffix))
      (t (format *output-stream* "~&~10t| Unsupported load ~s" expression)))))

;;; MOVE

(defun compile-m68k-move (statement)
  (let* ((from (getf (rest statement) :from))
         (to   (getf (rest statement) :to))
         (to-width (operand-width to)))
    (compile-m68k-load from)
    (let ((suffix (m68k-size-suffix to-width)))
      (cond
        ((stringp to)
         (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol to)))
        ((and (listp to) (eq (first to) :of))
         (let ((slot (second to)) (object (third to)))
           (when (member object '(:self "Self" self) :test #'equal)
             (format *output-stream* "~&~10tmove.l  Self, %a0")
             (format *output-stream* "~&~10tmove~a  %d0, ~a(%a0)"
                     suffix (slot-symbol slot *class-id*)))))
        ((and (listp to) (eq (first to) :subscript))
         (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
         (compile-m68k-load (third to) 1)
         (when (= (or to-width 1) 2)
           (format *output-stream* "~&~10tadd.w   %d0, %d0"))
         (format *output-stream* "~&~10tmove.l  #~a, %a0" (m68k-symbol (format nil "~a" (second to))))
         (format *output-stream* "~&~10tmove~a  %d1, (%a0,%d0.w)" suffix))
        (t (format *output-stream* "~&~10t| Unsupported store to ~s" to))))))

;;; INVOKE

(defun compile-m68k-invoke (statement)
  (let ((object (getf (rest statement) :object))
        (method (getf (rest statement) :method))
        (returning (getf (rest statement) :returning)))
    (let ((method-sym (m68k-symbol (format nil "~a" method))))
      (cond
        ((member object '(:self "Self" self) :test #'equal)
         (format *output-stream* "~&~10tjsr     Invoke~a~a" (m68k-symbol *class-id*) method-sym))
        (t
         (let* ((object-name (m68k-symbol (format nil "~a" object)))
                (object-class (or (var-class object-name) "Unknown")))
           (format *output-stream* "~&~10tjsr     Call~a~a" object-class method-sym))))
      (when returning
        (format *output-stream* "~&~10tmove.b  %d0, ~a" (m68k-symbol (format nil "~a" returning)))))))

;;; CALL

(defun compile-m68k-call (statement)
  (let ((target (getf (rest statement) :target))
        (service (getf (rest statement) :service))
        (library (getf (rest statement) :library)))
    (declare (ignore library))
    (format *output-stream* "~&~10tjsr     ~a" (m68k-symbol (format nil "~a" (or service target))))))

;;; GOTO / paragraph labels

(defvar *m68k-label* 0)

(defun m68k-label (prefix)
  (format nil ".L~a~d" prefix (incf *m68k-label*)))

(defun compile-m68k-goto (statement)
  "Emit m68k GOTO: unconditional @code{jmp}, or compare chain when @code{:depending-on} is set."
  (let ((target (getf (rest statement) :target))
        (targets (getf (rest statement) :targets))
        (dep (getf (rest statement) :depending-on)))
    (if dep
        (let ((tgt-list (or targets (when target (list target)))))
          (when tgt-list
            (compile-m68k-load dep 1)
            (format *output-stream* "~&~10tmove.b  %d0, %d1")
            (let ((n (length tgt-list)))
              (loop for i from 1 below n
                    do (format *output-stream* "~&~10tmove.b  %d1, %d0")
                       (format *output-stream* "~&~10tcmp.b   #~d, %d0" i)
                       (format *output-stream* "~&~10tbeq     ~a"
                               (m68k-symbol (format nil "~a" (nth (1- i) tgt-list)))))
              (format *output-stream* "~&~10tjmp     ~a"
                      (m68k-symbol (format nil "~a" (nth (1- n) tgt-list)))))))
        (format *output-stream* "~&~10tjmp     ~a"
                (m68k-symbol (format nil "~a" (or target (first targets))))))))

;;; Constant / value helpers

(defun m68k-expression-is-constant-p (expression)
  (or (numberp expression)
      (and (stringp expression) (constant-p expression))))

(defun m68k-value (expression)
  (cond
    ((numberp expression) (format nil "~d" expression))
    ((and (stringp expression) (constant-p expression))
     (format nil "~d" (constant-value expression)))
    ((stringp expression) (m68k-symbol expression))
    ((eq expression :self) "Self")
    ((and (listp expression) (eq (first expression) :of))
     (m68k-symbol (format nil "~a-~a" (third expression) (second expression))))
    (t (format nil "~a" expression))))

;;; IF

(defun compile-m68k-if (statement)
  (let ((condition (getf (rest statement) :condition))
        (then-statements (getf (rest statement) :then))
        (else-statements (getf (rest statement) :else))
        (label-else (m68k-label "else"))
        (label-end (m68k-label "end")))
    (compile-m68k-condition condition label-else)
    (dolist (s (ensure-list then-statements))
      (compile-statement :m68k (first s) (rest s)))
    (when (and else-statements (not (null else-statements)))
      (format *output-stream* "~&~10tbra     ~a" label-end))
    (format *output-stream* "~&~a:" label-else)
    (when (and else-statements (not (null else-statements)))
      (dolist (s (ensure-list else-statements))
        (compile-statement :m68k (first s) (rest s)))
      (format *output-stream* "~&~a:" label-end))))

(defun compile-m68k-condition (condition branch-label)
  (cond
    ((and (listp condition) (member (first condition) '(= equal < less > greater) :test #'eq))
     (let* ((lhs (second condition)) (rhs (third condition)) (op (first condition))
            (suffix (m68k-size-suffix (max (or (operand-width lhs) 1)
                                           (or (operand-width rhs) 1)))))
       (compile-m68k-load lhs)
       (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
       (compile-m68k-load rhs)
       (format *output-stream* "~&~10tcmp~a   %d1, %d0" suffix)
       (ecase op
         ((= equal) (format *output-stream* "~&~10tbne     ~a" branch-label))
         ((< less)  (format *output-stream* "~&~10tbge     ~a" branch-label))
         ((> greater) (format *output-stream* "~&~10tble     ~a" branch-label)))))
    ((and (listp condition) (eq (first condition) :is-zero))
     (let ((ex (second condition))
           (suffix (m68k-size-suffix (operand-width ex))))
       (compile-m68k-load ex)
       (format *output-stream* "~&~10ttst~a   %d0" suffix)
       (format *output-stream* "~&~10tbne     ~a" branch-label)))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (let ((ex (second condition))
           (suffix (m68k-size-suffix (operand-width ex))))
       (compile-m68k-load ex)
       (format *output-stream* "~&~10ttst~a   %d0" suffix)
       (format *output-stream* "~&~10tbeq     ~a" branch-label)))
    ((and (listp condition) (eq (first condition) :and))
     (compile-m68k-condition (second condition) branch-label)
     (compile-m68k-condition (third condition) branch-label))
    ((and (listp condition) (eq (first condition) :or))
     (let ((label-cond2 (m68k-label "or"))
           (label-skip (m68k-label "skip")))
       (compile-m68k-condition (second condition) branch-label)
       (format *output-stream* "~&~10tbra     ~a" label-skip)
       (format *output-stream* "~&~a:" label-cond2)
       (compile-m68k-condition (third condition) branch-label)
       (format *output-stream* "~&~a:" label-skip)))
    (t (error "EIGHTBOL: condition ~s not implemented" condition))))

;;; EVALUATE

(defun compile-m68k-evaluate (statement)
  (let ((subject (getf (rest statement) :subject))
        (clauses (getf (rest statement) :when-clauses))
        (label-end (m68k-label "eval")))
    (dolist (clause (ensure-list clauses))
      (cond
        ((eq (first clause) :when-other)
         (dolist (s (ensure-list (second clause)))
           (compile-statement :m68k (first s) (rest s))))
        ((eq (first clause) :when)
         (let ((phrases (second clause))
               (statements (third clause))
               (label-next (m68k-label "when")))
           (cond
             ((eq phrases 'eightbol::any)
              (dolist (s (ensure-list statements))
                (compile-statement :m68k (first s) (rest s)))
              (format *output-stream* "~&~10tbra     ~a" label-end))
             ((or (eq phrases 'eightbol::true) (equal phrases "TRUE"))
              (compile-m68k-load subject)
              (format *output-stream* "~&~10ttst.b   %d0")
              (format *output-stream* "~&~10tbeq     ~a" label-next)
              (dolist (s (ensure-list statements))
                (compile-statement :m68k (first s) (rest s)))
              (format *output-stream* "~&~10tbra     ~a" label-end)
              (format *output-stream* "~&~a:" label-next))
             ((or (eq phrases 'eightbol::false) (equal phrases "FALSE"))
              (compile-m68k-load subject)
              (format *output-stream* "~&~10ttst.b   %d0")
              (format *output-stream* "~&~10tbne     ~a" label-next)
              (dolist (s (ensure-list statements))
                (compile-statement :m68k (first s) (rest s)))
              (format *output-stream* "~&~10tbra     ~a" label-end)
              (format *output-stream* "~&~a:" label-next))
             ((and (listp phrases) (eq (first phrases) :not))
              (let ((suffix (m68k-size-suffix (max (or (operand-width subject) 1)
                                                   (or (operand-width (second phrases)) 1)))))
                (compile-m68k-load subject)
                (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
                (compile-m68k-load (second phrases))
                (format *output-stream* "~&~10tcmp~a   %d1, %d0" suffix)
                (format *output-stream* "~&~10tbeq     ~a" label-next)
                (dolist (s (ensure-list statements))
                  (compile-statement :m68k (first s) (rest s)))
                (format *output-stream* "~&~10tbra     ~a" label-end)
                (format *output-stream* "~&~a:" label-next)))
             ((and (listp phrases) (member (first phrases) '(:through :thru)))
              (let* ((lo (second phrases)) (hi (third phrases))
                     (suffix (m68k-size-suffix (max (or (operand-width subject) 1)
                                                    (or (operand-width lo) 1)
                                                    (or (operand-width hi) 1)))))
                (compile-m68k-load subject)
                (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
                (compile-m68k-load lo)
                (format *output-stream* "~&~10tcmp~a   %d0, %d1" suffix)
                (format *output-stream* "~&~10tbgt     ~a" label-next)
                (compile-m68k-load hi)
                (format *output-stream* "~&~10tcmp~a   %d1, %d0" suffix)
                (format *output-stream* "~&~10tblt     ~a" label-next)
                (dolist (s (ensure-list statements))
                  (compile-statement :m68k (first s) (rest s)))
                (format *output-stream* "~&~10tbra     ~a" label-end)
                (format *output-stream* "~&~a:" label-next)))
              (t
               (let* ((phrase-expression (if (listp phrases) (second phrases) phrases))
                      (suffix (m68k-size-suffix (max (or (operand-width subject) 1)
                                                     (or (operand-width phrase-expression) 1)))))
                (compile-m68k-load subject)
                (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
                (compile-m68k-load phrase-expression)
                (format *output-stream* "~&~10tcmp~a   %d1, %d0" suffix)
                (format *output-stream* "~&~10tbne     ~a" label-next)
                (dolist (s (ensure-list statements))
                  (compile-statement :m68k (first s) (rest s)))
                (format *output-stream* "~&~10tbra     ~a" label-end)
                (format *output-stream* "~&~a:" label-next))))))))
    (format *output-stream* "~&~a:" label-end)))

;;; INSPECT

(defun compile-m68k-inspect (statement)
  (let* ((target (getf (rest statement) :target))
         (tally (getf (rest statement) :tallying))
         (conversion-from (getf (rest statement) :converting))
         (conversion-to (getf (rest statement) :to))
         (replacement-by (getf (rest statement) :by)))
    (let ((target-symbol (m68k-symbol (format nil "~a" target))))
      (cond
        (tally
         (let ((tally-symbol (m68k-symbol (format nil "~a" tally))))
           (format *output-stream* "~&~10t| INSPECT ~a TALLYING ~a FOR CHARACTERS" target tally)
           (format *output-stream* "~&~10tlea     ~a, %a0" target-symbol)
           (let ((label (m68k-label "tally"))
                 (label-done (m68k-label "tallyd"))
                 (label-skip (m68k-label "tallys")))
             (format *output-stream* "~&~a:" label)
             (format *output-stream* "~&~10tmove.b  (%a0)+, %d0")
             (format *output-stream* "~&~10ttst.b   %d0")
             (format *output-stream* "~&~10tbeq     ~a" label-done)
             (format *output-stream* "~&~10tmove.b  ~a, %d0" tally-symbol)
             (format *output-stream* "~&~10taddq.b  #1, %d0")
             (format *output-stream* "~&~10tmove.b  %d0, ~a" tally-symbol)
             (format *output-stream* "~&~a:" label-skip)
             (format *output-stream* "~&~10tbra     ~a" label)
             (format *output-stream* "~&~a:" label-done))))
        (conversion-from
         (format *output-stream* "~&~10t| INSPECT ~a CONVERTING" target)
         (format *output-stream* "~&~10tlea     ~a, %a0" target-symbol)
         (let ((label (m68k-label "insp"))
               (label-next (m68k-label "inspn"))
               (label-done (m68k-label "inspd")))
           (format *output-stream* "~&~a:" label)
           (format *output-stream* "~&~10tmove.b  (%a0), %d0")
           (format *output-stream* "~&~10ttst.b   %d0")
           (format *output-stream* "~&~10tbeq     ~a" label-done)
           (if (m68k-expression-is-constant-p conversion-from)
               (format *output-stream* "~&~10tcmp.b   #~d, %d0"
                       (if (numberp conversion-from) conversion-from
                           (constant-value (format nil "~a" conversion-from))))
               (progn (format *output-stream* "~&~10tmove.b  %d0, %d1")
                      (compile-m68k-load conversion-from 1)
                      (format *output-stream* "~&~10tcmp.b   %d0, %d1")))
           (format *output-stream* "~&~10tbne     ~a" label-next)
           (compile-m68k-load conversion-to 1)
           (format *output-stream* "~&~10tmove.b  %d0, (%a0)")
           (format *output-stream* "~&~a:" label-next)
           (format *output-stream* "~&~10taddq.l  #1, %a0")
           (format *output-stream* "~&~10tbra     ~a" label)
           (format *output-stream* "~&~a:" label-done)))
        (replacement-by
         (let ((length (or (pic-size (format nil "~a" target) *pic-size-table*) 64)))
           (format *output-stream* "~&~10t| INSPECT ~a REPLACING CHARACTERS BY ~a" target replacement-by)
           (compile-m68k-load replacement-by 1)
           (format *output-stream* "~&~10tlea     ~a, %a0" target-symbol)
           (let ((label (m68k-label "insp")))
             (format *output-stream* "~&~10tmove.w  #~d, %d1" length)
             (format *output-stream* "~&~a:" label)
             (format *output-stream* "~&~10tmove.b  %d0, (%a0)+")
             (format *output-stream* "~&~10tsubq.w  #1, %d1")
             (format *output-stream* "~&~10tbne     ~a" label))))))))

;;; ADD

(defun compile-m68k-add (statement)
  (let* ((from (getf (rest statement) :from))
         (to (getf (rest statement) :to))
         (giving (getf (rest statement) :giving))
         (result (or giving (and (stringp to) to)))
         (width (operand-width (or result to)))
         (bcd-p (when result (usage-bcd-p (expression-to-width-name result))))
         (suffix (m68k-size-suffix width)))
    (assert-pic-decimal-add-compiled :m68k statement)
    (when (and bcd-p (> (or width 1) 2))
      (dotimes (i width)
        (format *output-stream* "~&~10tmove.b  ~a+~d, %%d0" (m68k-symbol from) i)
        (format *output-stream* "~&~10tmove.b  ~a+~d, %%d1" (m68k-symbol to) i)
        (if (= i 0)
            (progn
              (format *output-stream* "~&~10tmoveq   #0, %%d2")
              (format *output-stream* "~&~10tmove    %%d2, %%ccr"))
            (format *output-stream* "~&~10tmove    %%ccr, %%d2"))
        (format *output-stream* "~&~10tabcd    %%d1, %%d0")
        (format *output-stream* "~&~10tmove.b  %%d0, ~a+~d" (m68k-symbol result) i))
      (return-from compile-m68k-add))
    (backend-unsupported-operand-width :m68k :add width 2)
    (compile-m68k-load to)
    (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
    (compile-m68k-load from)
    (if (and bcd-p (= (or width 1) 1))
        (progn
          (format *output-stream* "~&~10tmoveq   #0, %%d2")
          (format *output-stream* "~&~10tmove    %%d2, %%ccr")
          (format *output-stream* "~&~10tabcd    %%d1, %%d0"))
        (format *output-stream* "~&~10tadd~a   %d1, %d0" suffix))
    (when result
      (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol (format nil "~a" result))))))

;;; SUBTRACT

(defun compile-m68k-subtract (statement)
  (multiple-value-bind (minuend subtrahend)
      (subtract-statement-minuend-and-subtrahend statement)
    (let* ((giving (getf (rest statement) :giving))
           (dest (or giving minuend))
           (width (operand-width dest))
           (bcd-p (when dest (usage-bcd-p (expression-to-width-name dest))))
           (suffix (m68k-size-suffix width)))
      (assert-pic-decimal-subtract-compiled :m68k statement)
      (when (and bcd-p (> (or width 1) 2))
        (dotimes (i width)
          (format *output-stream* "~&~10tmove.b  ~a+~d, %%d1" (m68k-symbol minuend) i)
          (format *output-stream* "~&~10tmove.b  ~a+~d, %%d0" (m68k-symbol subtrahend) i)
          (if (= i 0)
              (progn
                (format *output-stream* "~&~10tmoveq   #0, %%d2")
                (format *output-stream* "~&~10tmove    %%d2, %%ccr"))
              (format *output-stream* "~&~10tmove    %%ccr, %%d2"))
          (format *output-stream* "~&~10tsbcd    %%d0, %%d1")
          (format *output-stream* "~&~10tmove.b  %%d1, ~a+~d" (m68k-symbol dest) i))
        (return-from compile-m68k-subtract))
      (backend-unsupported-operand-width :m68k :subtract width 2)
      (compile-m68k-load minuend)
      (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
      (compile-m68k-load subtrahend)
      (if (and bcd-p (= (or width 1) 1))
          (progn
            (format *output-stream* "~&~10tmoveq   #0, %%d2")
            (format *output-stream* "~&~10tmove    %%d2, %%ccr")
            (format *output-stream* "~&~10tsbcd    %%d0, %%d1")
            (format *output-stream* "~&~10tmove.b  %d1, %d0"))
          (progn
            (format *output-stream* "~&~10tsub~a   %d0, %d1" suffix)
            (format *output-stream* "~&~10tmove~a  %d1, %d0" suffix)))
      (let ((dest (or giving minuend)))
        (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol (format nil "~a" dest)))))))

;;; COMPUTE

(defun compile-m68k-compute (statement)
  (let* ((target (getf (rest statement) :target))
         (expression (getf (rest statement) :expression))
         (width (operand-width target))
         (suffix (m68k-size-suffix width)))
    (compile-m68k-load expression)
    (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol (format nil "~a" target)))))

;;; SET

(defun compile-m68k-set (statement)
  (let* ((target (getf (rest statement) :target))
         (value (getf (rest statement) :value))
         (width (operand-width target))
         (suffix (m68k-size-suffix width)))
    (compile-m68k-load value)
    (cond
      ((stringp target)
       (format *output-stream* "~&~10tmove~a  %d0, ~a" suffix (m68k-symbol target)))
      ((and (listp target) (eq (first target) :of))
       (let ((slot (second target)) (object (third target)))
         (when (member object '(:self "Self" self) :test #'equal)
           (format *output-stream* "~&~10tmove.l  Self, %a0")
           (format *output-stream* "~&~10tmove~a  %d0, ~a(%a0)"
                   suffix (slot-symbol slot *slot-table* *class-id*)))))
      ((and (listp target) (eq (first target) :subscript))
       (format *output-stream* "~&~10tmove~a  %d0, %d1" suffix)
       (compile-m68k-load (third target) 1)
       (when (= (or width 1) 2)
         (format *output-stream* "~&~10tadd.w   %d0, %d0"))
       (format *output-stream* "~&~10tmove.l  #~a, %a0" (m68k-symbol (format nil "~a" (second target))))
       (format *output-stream* "~&~10tmove~a  %d1, (%a0,%d0.w)" suffix))
      (t (format *output-stream* "~&~10t| Unsupported set ~s" target)))))

;;; PERFORM

(defun compile-m68k-perform (statement)
  (let ((procedure (getf (rest statement) :procedure))
        (times (getf (rest statement) :times))
        (until (getf (rest statement) :until)))
    (cond
      (times
       (let ((label (m68k-label "perf")))
         (compile-m68k-load times)
         (format *output-stream* "~&~10tmove.b  %d0, %d1")
         (format *output-stream* "~&~a:" label)
         (format *output-stream* "~&~10tjsr     ~a" (m68k-symbol (format nil "~a" procedure)))
         (format *output-stream* "~&~10tsubq.b  #1, %d1")
         (format *output-stream* "~&~10tbne     ~a" label)))
      (until
          (let ((label-loop (m68k-label "loop"))
                (label-end (m68k-label "end")))
            (format *output-stream* "~&~a:" label-loop)
            (compile-m68k-condition until label-end)
            (format *output-stream* "~&~10tjsr     ~a" (m68k-symbol (format nil "~a" procedure)))
            (format *output-stream* "~&~10tbra     ~a" label-loop)
            (format *output-stream* "~&~a:" label-end)))
      (t
       (format *output-stream* "~&~10tjsr     ~a" (m68k-symbol (format nil "~a" procedure)))))))

;;; STRING BLT (block copy)

(defun m68k-string-operand-address (operand)
  (cond
    ((and (listp operand) (eq (first operand) :refmod))
     (let* ((base (getf (rest operand) :base))
            (start (getf (rest operand) :start))
            (base-string (m68k-symbol (format nil "~a" base))))
       (if (and (integerp start) (= start 1))
           base-string
           (format nil "~a+~d" base-string (1- start)))))
    (t (m68k-symbol (format nil "~a" operand)))))

(defun compile-m68k-string-blt (statement)
  (let ((source (getf (rest statement) :source))
        (dest (getf (rest statement) :dest))
        (length (getf (rest statement) :length)))
    (let ((length-value (or (%string-blt-refmod-length source)
                            (%string-blt-refmod-length dest)
                            length 64))
          (source-address (m68k-string-operand-address source))
          (destination-address (m68k-string-operand-address dest)))
      (format *output-stream* "~&~10tlea     ~a, %a0" source-address)
      (format *output-stream* "~&~10tlea     ~a, %a1" destination-address)
      (let ((label (m68k-label "blt")))
        (format *output-stream* "~&~10tmove.w  #~d, %d1" length-value)
        (format *output-stream* "~&~a:" label)
        (format *output-stream* "~&~10tmove.b  (%a0)+, %d0")
        (format *output-stream* "~&~10tmove.b  %d0, (%a1)+")
        (format *output-stream* "~&~10tsubq.w  #1, %d1")
        (format *output-stream* "~&~10tbne     ~a" label)))))
