;; src/frontend-muddle/muddle-lexer.lisp — Tokenization for Muddle (MIT MDL)
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *muddle-keyword-alist*
  '((".IF" . :IF)
    (".ELSE" . :ELSE)
    (".THEN" . :THEN)
    (".ENDIF" . :ENDIF)
    (".WHILE" . :WHILE)
    (".ENDWHILE" . :ENDWHILE)
    (".FOR" . :FOR)
    (".ENDFOR" . :ENDFOR)
    (".EXIT" . :EXIT)
    (".RETURN" . :RETURN)
    (".DEFINE" . :DEFINE)
    (".SET" . :SET)
    (".GET" . :GET)
    (".PUT" . :PUT)
    (".CALL" . :CALL)
    (".GO" . :GO)
    (".THROW" . :THROW)
    (".CATCH" . :CATCH)
    (".FINALLY" . :FINALLY)
    ("AND" . :AND)
    ("OR" . :OR)
    ("NOT" . :NOT))
  "Association list of Muddle keywords to token symbols.")

(defparameter *muddle-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("^" . :POWER)
    ("=" . :EQUAL)
    ("/=" . :NE)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE))
  "Association list of Muddle operators to token symbols.")

(defun muddle-valid-identifier-p (s)
  "Check if S is a valid Muddle identifier."
  (and (stringp s)
       (plusp (length s))
       (or (alpha-char-p (char s 0))
           (char= (char s 0) #\-))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\-) (char= c #\_)))
              s)))

(defun muddle-lex-line (line)
  "Split LINE into token list of (type value) pairs."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (skip-whitespace ()
               (loop while (and (not (eof?)) (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (flush-token (start end type)
               (let ((text (coerce (subseq chars start end) 'string)))
                 (unless (zerop (length text))
                   (push (cons type text) tokens))))
             (scan-number (start)
               (loop while (and (not (eof?)) (digit-char-p (peek)))
                     do (next-char))
               (flush-token start i :number))
             (scan-string (start)
               (next-char)
               (loop while (and (not (eof?)) (char/= (peek) (char (coerce (subseq chars start (1+ start)) 'string) 0)))
                     do (next-char))
               (when (not (eof?)) (next-char))
               (flush-token (1+ start) (1- i) :string))
              (scan-identifier (start)
                (loop while (and (not (eof?))
                                 (or (alphanumericp (peek))
                                     (char= (peek) #\-)
                                     (char= (peek) #\_)))
                      do (next-char))
                (let ((text (coerce (subseq chars start i) 'string)))
                  (push (cons (or (cdr (assoc text *muddle-keyword-alist* :test #'string-equal))
                                  :ident)
                              text)
                        tokens))))
      (loop until (eof?)
            do (skip-whitespace)
               (cond
                 ((eof?) (return))
                 ((char= (peek) #\") (scan-string i))
                 ((char= (peek) #\|) (scan-string i))
                 ((digit-char-p (peek)) (scan-number i))
                 ((or (alpha-char-p (peek))
                      (char= (peek) #\-)
                      (char= (peek) #\_)) (scan-identifier i))
                 ((char= (peek) #\() (push (cons :lparen "(") tokens) (next-char))
                 ((char= (peek) #\)) (push (cons :rparen ")") tokens) (next-char))
                 ((char= (peek) #\,) (push (cons :comma ",") tokens) (next-char))
                 (t (next-char))))
      (nreverse tokens))))

(defun muddle-lex-source (source)
  "Lex complete Muddle source string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (zerop (length trimmed))
          (setf all-tokens (nconc all-tokens (muddle-lex-line trimmed))))))
    all-tokens))
