;; tests/backend-m68k-tests.lisp - Motorola 68000 backend statement tests
;;
;; Targets the Motorola 68000 instruction set.
;; Data registers: D0-D7, Address registers: A0-A7 (A7 = stack pointer)
;; Uses GAS/AT&T-style 68000 assembly.

(in-package :eightbol/test)

(fiveam:def-suite :backend-m68k
  :description "Motorola 68000 backend statement emission")
(in-suite :backend-m68k)

(defun m68k-asm (stmt &key (class-id "Character") (slots nil) (consts nil) (pic nil) (types nil))
  "Compile STMT inside a minimal method for m68k, return assembly string."
  (let ((*standard-output* (make-broadcast-stream)))
    (compile-method-ast-with-tables
     `(:method :method-id "M" :statements (,stmt))
     class-id :m68k
     :slot-table (or slots (make-hash-table :test 'equalp))
     :const-table (or consts (make-hash-table :test 'equalp))
     :pic-width-table (or pic (make-hash-table :test 'equalp))
     :type-table (or types (make-hash-table :test 'equalp)))))

(defun make-hash (&rest pairs)
  (let ((h (make-hash-table :test 'equalp)))
    (loop for (key value) on pairs by #'cddr
          do (setf (gethash key h) value))
    h))

;;;
;;;; Header and structure
;;;

(test m68k/header-contains-cpu-label
  "m68k output header contains 'generated by EIGHTBOL for m68k'."
  (let ((asm (m68k-asm '(:goback))))
    (is (search "generated by EIGHTBOL for m68k" asm))))

(test m68k/header-emits-text-directive
  "m68k output emits .text directive."
  (let ((asm (m68k-asm '(:goback))))
    (is (search ".text" asm))))

(test m68k/method-emits-rts
  "Method body ends with rts."
  (let ((asm (m68k-asm '(:goback))))
    (is (search "rts" asm))))

(test m68k/method-emits-dispatch-label
  "Method dispatch label is MethodClassName."
  (let ((asm (m68k-asm '(:goback) :class-id "Actor")))
    (is (search "MethodActorM" asm))))

;;;
;;;; Termination statements
;;;

(test m68k/goback
  "GOBACK emits rts."
  (let ((asm (m68k-asm '(:goback))))
    (is (search "rts" asm))))

(test m68k/exit-method
  "EXIT METHOD emits rts."
  (let ((asm (m68k-asm '(:exit-method))))
    (is (search "rts" asm))))

(test m68k/exit-program
  "EXIT PROGRAM emits rts."
  (let ((asm (m68k-asm '(:exit-program))))
    (is (search "rts" asm))))

(test m68k/stop-run
  "STOP RUN emits rts."
  (let ((asm (m68k-asm '(:stop-run))))
    (is (search "rts" asm))))

(test m68k/exit
  "EXIT emits rts."
  (let ((asm (m68k-asm '(:exit))))
    (is (search "rts" asm))))

;;;
;;;; MOVE statement
;;;

(test m68k/move-literal-to-var
  "MOVE literal TO var emits move. with immediate."
  (let ((asm (m68k-asm '(:move :from 42 :to "X"))))
    (is (search "move" asm))
    (is (search "42" asm))))

(test m68k/move-slot-of-self
  "MOVE slot OF Self loads via address register."
  (let ((slots (make-hash "HP" "Character")))
    (let ((asm (m68k-asm '(:move :from (:of "HP" :self) :to "Dest") :slots slots)))
      (is (search "move" asm)))))

(test m68k/move-named-constant
  "MOVE named constant uses symbolic immediate."
  (let ((consts (make-hash "song--heal--id" 42)))
    (let ((asm (m68k-asm '(:move :from "Song--Heal--ID" :to "X") :consts consts)))
      (is (search "move" asm))
      (is (search "Song_Heal_ID" asm)))))

;;;
;;;; ADD / SUBTRACT
;;;

(test m68k/add-literal-to-var
  "ADD literal TO var emits add instruction."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m68k-asm '(:+ :from "A" :to "B") :pic pic)))
      (is (search "add" asm)))))

(test m68k/add-16-bit
  "ADD of 2-byte values emits add instruction with word size."
  (let ((pic (make-hash "A" 2 "B" 2)))
    (let ((asm (m68k-asm '(:+ :from "A" :to "B") :pic pic)))
      (is (search "add" asm))
      (is (search ".w" asm)))))

(test m68k/subtract
  "SUBTRACT emits sub instruction."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m68k-asm '(:- :from "A" :from-target "B") :pic pic)))
      (is (search "sub" asm)))))

(test m68k/subtract-16-bit
  "SUBTRACT of 2-byte values emits sub instruction with word size."
  (let ((pic (make-hash "A" 2 "B" 2)))
    (let ((asm (m68k-asm '(:- :from "A" :from-target "B") :pic pic)))
      (is (search "sub" asm))
      (is (search ".w" asm)))))

;;;
;;;; COMPUTE
;;;

(test m68k/compute-literal
  "COMPUTE target = expr emits move."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (m68k-asm '(:compute :target "X" :expression 42) :pic pic)))
      (is (search "move" asm))
      (is (search "42" asm)))))

;;;
;;;; SET
;;;

(test m68k/set-literal
  "SET target TO value emits move."
  (let ((asm (m68k-asm '(:set :target "X" :value 99))))
    (is (search "move" asm))
    (is (search "99" asm))))

;;;
;;;; IF / conditionals
;;;

(test m68k/if-equal
  "IF a = b emits cmp and beq."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m68k-asm '(:if :condition (= "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test m68k/if-greater
  "IF a > b emits cmp and bgt."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m68k-asm '(:if :condition (:greater "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test m68k/if-less
  "IF a < b emits cmp and blt."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m68k-asm '(:if :condition (:less "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test m68k/if-else
  "IF/ELSE emits branch around else block."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m68k-asm '(:if :condition (= "A" "B")
                                    :then ((:move :from 1 :to "X"))
                                    :else ((:move :from 2 :to "Y")))
                             :pic pic :class-id "T")))
      (is (search "beq" asm)))))

;;;
;;;; INVOKE
;;;

(test m68k/invoke-self
  "INVOKE Self \"Method\" emits jsr to invoke stub."
  (let ((asm (m68k-asm '(:invoke :object "Self" :method "Connect")
                          :class-id "Character")))
    (is (search "jsr" asm))
    (is (search "InvokeCharacterConnect" asm))))

(test m68k/invoke-super
  "INVOKE SUPER emits jsr to parent class invoke stub."
  (let ((eightbol::*parent-classes* (make-hash "Character" "Actor"))
        (eightbol::*method-id* "Think")
        (eightbol::*class-id* "Character"))
    (let ((asm (m68k-asm '(:invoke-super))))
      (is (search "jsr" asm)))))

;;;
;;;; CALL
;;;

(test m68k/call
  "CALL target emits jsr."
  (let ((asm (m68k-asm '(:call :target "MoveDecalY"))))
    (is (search "jsr" asm))))

(test m68k/call-acc
  "CALL...USING loads argument then jsr."
  (let ((asm (m68k-asm '(:call-acc :target "Foo" :using 7))))
    (is (search "move" asm))
    (is (search "jsr" asm))))

;;;
;;;; PERFORM
;;;

(test m68k/perform-simple
  "PERFORM procedure emits jsr."
  (let ((asm (m68k-asm '(:perform :procedure "Foo"))))
    (is (search "jsr Foo" asm))))

(test m68k/perform-times
  "PERFORM TIMES n emits loop with decrement and conditional branch."
  (let ((asm (m68k-asm '(:perform :procedure "Foo" :times 3))))
    (is (search "jsr Foo" asm))))

(test m68k/perform-until
  "PERFORM UNTIL condition emits condition-checked loop."
  (let ((asm (m68k-asm '(:perform :procedure "Foo"
                                    :until (:greater "X" 0))
                          :class-id "T")))
    (is (search "jsr" asm))))

(test m68k/perform-with-body-until
  "PERFORM UNTIL with inline :body emits condition-checked loop."
  (let ((asm (m68k-asm '(:perform :until (= "Done" 0) :body ((:move :from 1 :to "X"))))))
    (is (search "cmp" asm))
    (is (search "beq" asm))))

(test m68k/perform-with-body-varying
  "PERFORM VARYING emits counter init, varying store, and increment."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (m68k-asm '(:perform :varying "X" :from 0 :by 1 :until (= "Done" 0)
                                    :body ((:move :from 1 :to "X")))
                         :pic pic)))
      (is (search "move" asm)))))

;;;
;;;; EVALUATE
;;;

(test m68k/evaluate-when
  "EVALUATE WHEN comparison emits cmp and conditional branch."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (m68k-asm '(:evaluate :subject "X"
                                      :when-clauses ((:when "A" ((:move :from 1 :to "X")))))
                             :pic pic :class-id "T")))
      (is (search "cmp" asm)))))

;;;
;;;; INSPECT
;;;

(test m68k/inspect-tallying
  "INSPECT TALLYING emits counting loop."
  (let ((pic (make-hash "Buf" 64 "Cnt" 1)))
    (let ((asm (m68k-asm '(:inspect :target "Buf" :tallying "Cnt") :pic pic)))
      (is (search "add" asm)))))

(test m68k/inspect-replacing
  "INSPECT REPLACING emits fill loop."
  (let ((pic (make-hash "Buf" 64)))
    (let ((asm (m68k-asm '(:inspect :target "Buf" :by 42) :pic pic)))
      (is (search "move" asm)))))

;;;
;;;; GOTO / PARAGRAPH
;;;

(test m68k/goto
  "GO TO target emits bra to label."
  (let ((asm (m68k-asm '(:goto :target "Exit"))))
    (is (search "bra" asm))))

(test m68k/paragraph
  "Paragraph emits label."
  (let ((asm (m68k-asm '(:paragraph "MyPara"))))
    (is (search "MyPara:" asm))))

;;;
;;;; LOG FAULT / DEBUG BREAK
;;;

(test m68k/log-fault
  "LOG FAULT emits comment."
  (let ((asm (m68k-asm '(:log-fault :code 1234))))
    (is (search "LOG FAULT" asm))))

(test m68k/debug-break
  "DEBUG BREAK emits comment."
  (let ((asm (m68k-asm '(:debug-break :code 42))))
    (is (search "DEBUG BREAK" asm))))

;;;
;;;; Comment statement
;;;

(test m68k/comment
  "Comment statement emits assembly comment."
  (let ((asm (m68k-asm '(:comment "this is a test"))))
    (is (search "this is a test" asm))))

;;;
;;;; STRING BLT
;;;

(test m68k/string-blt
  "STRING dest FROM src emits block copy loop."
  (let ((slots (make-hash "Src" "Character" "Dst" "Character")))
    (let ((asm (m68k-asm '(:string-blt :source "Src" :dest "Dst") :slots slots)))
      (is (search "move" asm))
      (is (search "cmp" asm)))))

;;;
;;;; UNSUPPORTED
;;;

(test m68k/divide-non-power-of-two-signals-error
  "DIVIDE with non-power-of-two on m68k signals source-error."
  (signals eightbol:source-error
    (m68k-asm '(:÷ :divisor 3 :into "B"))))

(test m68k/multiply-non-power-of-two-signals-error
  "MULTIPLY with non-power-of-two on m68k signals source-error."
  (signals eightbol:source-error
    (m68k-asm '(:× :multiplier 3 :on "B"))))
