;; tests/backend-m6800-tests.lisp - Motorola 6800 backend statement tests
;;
;; Minimal m6800 emitter for Vectrex-style Motorola-family workflows.
;; Uses plain 6800-like mnemonics (LDAA/STAA/CMPA/BEQ/BNE/JSR/JMP/RTS).

(in-package :eightbol/test)

(fiveam:def-suite :backend-m6800
  :description "Motorola 6800 backend statement emission")
(in-suite :backend-m6800)

(defun m6800-asm (stmt &key (class-id "Character") (slots nil) (consts nil) (pic nil) (types nil))
  "Compile STMT inside a minimal method for m6800, return assembly string."
  (let ((*standard-output* (make-broadcast-stream)))
    (compile-method-ast-with-tables
     `(:method :method-id "M" :statements (,stmt))
     class-id :m6800
     :slot-table (or slots (make-hash-table :test 'equalp))
     :const-table (or consts (make-hash-table :test 'equalp))
     :pic-width-table (or pic (make-hash-table :test 'equalp))
     :type-table (or types (make-hash-table :test 'equalp)))))

(defun make-hash (&rest pairs)
  (let ((h (make-hash-table :test 'equalp)))
    (loop for (key value) on pairs by #'cddr
          do (setf (gethash key h) value))
    h))

;;;
;;;; Header and structure
;;;

(test m6800/header-contains-cpu-label
  "m6800 output header contains 'generated by EIGHTBOL for m6800'."
  (let ((asm (m6800-asm '(:goback))))
    (is (search "generated by EIGHTBOL for m6800" asm))))

(test m6800/method-emits-dispatch-label
  "Method dispatch label is MethodClassName."
  (let ((asm (m6800-asm '(:goback) :class-id "Actor")))
    (is (search "MethodActorM" asm))))

;;;
;;;; Termination statements
;;;

(test m6800/goback
  "GOBACK emits RTS."
  (let ((asm (m6800-asm '(:goback))))
    (is (search "RTS" asm))))

(test m6800/exit-method
  "EXIT METHOD emits RTS."
  (let ((asm (m6800-asm '(:exit-method))))
    (is (search "RTS" asm))))

(test m6800/exit-program
  "EXIT PROGRAM emits RTS."
  (let ((asm (m6800-asm '(:exit-program))))
    (is (search "RTS" asm))))

;;;
;;;; MOVE statement
;;;

(test m6800/move-literal-to-var
  "MOVE literal TO var emits LDAA immediate and STAA."
  (let ((asm (m6800-asm '(:move :from 42 :to "X"))))
    (is (search "LDAA" asm))
    (is (search "42" asm))
    (is (search "STAA" asm))))

(test m6800/move-slot-of-self
  "MOVE slot OF Self loads via index register."
  (let ((slots (make-hash "HP" "Character")))
    (let ((asm (m6800-asm '(:move :from (:of "HP" :self) :to "Dest") :slots slots)))
      (is (search "LDX" asm))
      (is (search "LDAA" asm)))))

(test m6800/move-named-constant
  "MOVE named constant uses symbolic immediate."
  (let ((consts (make-hash "song--heal--id" 42)))
    (let ((asm (m6800-asm '(:move :from "Song--Heal--ID" :to "X") :consts consts)))
      (is (search "LDAA" asm))
      (is (search "Song_Heal_ID" asm)))))

;;;
;;;; ADD / SUBTRACT
;;;

(test m6800/add-literal-to-var
  "ADD literal TO var emits ABA (add accumulator)."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m6800-asm '(:+ :from "A" :to "B") :pic pic)))
      (is (search "ABA" asm)))))

(test m6800/subtract
  "SUBTRACT emits CBA or SBA."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m6800-asm '(:- :from "A" :from-target "B") :pic pic)))
      (is (or (search "CBA" asm) (search "SBA" asm))))))

;;;
;;;; IF / conditionals
;;;

(test m6800/if-equal
  "IF a = b emits CMPA and BNE."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m6800-asm '(:if :condition (= "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "CMPA" asm)))))

(test m6800/if-is-zero
  "IF a IS ZERO emits BNE."
  (let ((pic (make-hash "A" 1)))
    (let ((asm (m6800-asm '(:if :condition (:is-zero "A") :then ((:move :from 1 :to "A")))
                            :pic pic :class-id "T")))
      (is (search "BNE" asm)))))

(test m6800/if-else
  "IF/ELSE emits branch around else block."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (m6800-asm '(:if :condition (= "A" "B")
                                    :then ((:move :from 1 :to "X"))
                                    :else ((:move :from 2 :to "Y")))
                             :pic pic :class-id "T")))
      (is (search "BNE" asm)))))

;;;
;;;; CALL
;;;

(test m6800/call
  "CALL target emits JSR."
  (let ((asm (m6800-asm '(:call :target "MoveDecalY"))))
    (is (search "JSR" asm))))

(test m6800/call-acc
  "CALL...USING loads argument then JSR."
  (let ((asm (m6800-asm '(:call-acc :target "Foo" :using 7))))
    (is (search "LDAA" asm))
    (is (search "JSR" asm))))

;;;
;;;; PERFORM
;;;

(test m6800/perform-simple
  "PERFORM procedure emits JSR."
  (let ((asm (m6800-asm '(:perform :procedure "Foo"))))
    (is (search "JSR Foo" asm))))

(test m6800/perform-with-body-until
  "PERFORM UNTIL with inline :body emits condition-checked loop."
  (let ((asm (m6800-asm '(:perform :until (= "Done" 0) :body ((:move :from 1 :to "X"))))))
    (is (search "CMPA" asm))
    (is (search "BNE" asm))))

;;;
;;;; GOTO / PARAGRAPH
;;;

(test m6800/goto
  "GO TO target emits JMP to label."
  (let ((asm (m6800-asm '(:goto :target "Exit"))))
    (is (search "JMP" asm))))

(test m6800/paragraph
  "Paragraph emits label."
  (let ((asm (m6800-asm '(:paragraph "MyPara"))))
    (is (search "MyPara:" asm))))

;;;
;;;; LOG FAULT / DEBUG BREAK
;;;

(test m6800/log-fault
  "LOG FAULT emits comment."
  (let ((asm (m6800-asm '(:log-fault :code 1234))))
    (is (search "LOG FAULT" asm))))

(test m6800/debug-break
  "DEBUG BREAK emits comment."
  (let ((asm (m6800-asm '(:debug-break :code 42))))
    (is (search "DEBUG BREAK" asm))))

;;;
;;;; STRING BLT
;;;

(test m6800/string-blt
  "STRING dest FROM src emits block copy loop."
  (let ((slots (make-hash "Src" "Character" "Dst" "Character")))
    (let ((asm (m6800-asm '(:string-blt :source "Src" :dest "Dst") :slots slots)))
      (is (search "LDAA" asm))
      (is (search "STAA" asm)))))
