;; tests/backend-i286-tests.lisp - Intel 80286 backend statement tests
;;
;; The 80286 is a 16-bit CPU. Registers: AX, BX, CX, DX, SI, DI, BP, SP
;; Segment: CS, DS, SS, ES. Uses Intel syntax.

(in-package :eightbol/test)

(fiveam:def-suite :backend-i286
  :description "Intel 80286 backend statement emission")
(in-suite :backend-i286)

(defun i286-asm (stmt &key (class-id "Character") (slots nil) (consts nil) (pic nil) (types nil))
  "Compile STMT inside a minimal method for i286, return assembly string."
  (let ((*standard-output* (make-broadcast-stream)))
    (compile-method-ast-with-tables
     `(:method :method-id "M" :statements (,stmt))
     class-id :i286
     :slot-table (or slots (make-hash-table :test 'equalp))
     :const-table (or consts (make-hash-table :test 'equalp))
     :pic-width-table (or pic (make-hash-table :test 'equalp))
     :type-table (or types (make-hash-table :test 'equalp)))))

(defun make-hash (&rest pairs)
  (let ((h (make-hash-table :test 'equalp)))
    (loop for (key value) on pairs by #'cddr
          do (setf (gethash key h) value))
    h))

;;;
;;;; Header and structure
;;;

(test i286/header-contains-cpu-label
  "i286 output header contains 'generated by EIGHTBOL for i286'."
  (let ((asm (i286-asm '(:goback))))
    (is (search "generated by EIGHTBOL for i286" asm))))

(test i286/header-emits-directives
  "i286 output emits .286 and .model directives."
  (let ((asm (i286-asm '(:goback))))
    (is (search ".286" asm))
    (is (search ".model" asm))))

(test i286/method-emits-proc-endp
  "Method body emits proc and endp."
  (let ((asm (i286-asm '(:goback))))
    (is (search "proc" asm))
    (is (search "endp" asm))))

(test i286/method-emits-dispatch-label
  "Method dispatch label is MethodClassName."
  (let ((asm (i286-asm '(:goback) :class-id "Actor")))
    (is (search "MethodActorM" asm))))

;;;
;;;; Termination statements
;;;

(test i286/goback
  "GOBACK emits ret."
  (let ((asm (i286-asm '(:goback))))
    (is (search "ret" asm))))

(test i286/exit-method
  "EXIT METHOD emits ret."
  (let ((asm (i286-asm '(:exit-method))))
    (is (search "ret" asm))))

(test i286/exit-program
  "EXIT PROGRAM emits ret."
  (let ((asm (i286-asm '(:exit-program))))
    (is (search "ret" asm))))

(test i286/stop-run
  "STOP RUN emits ret."
  (let ((asm (i286-asm '(:stop-run))))
    (is (search "ret" asm))))

(test i286/exit
  "EXIT emits ret."
  (let ((asm (i286-asm '(:exit))))
    (is (search "ret" asm))))

;;;
;;;; MOVE statement
;;;

(test i286/move-literal-to-var
  "MOVE literal TO var emits mov immediate."
  (let ((asm (i286-asm '(:move :from 42 :to "X"))))
    (is (search "mov" asm))
    (is (search "42" asm))))

(test i286/move-slot-of-self
  "MOVE slot OF Self loads via base register."
  (let ((slots (make-hash "HP" "Character")))
    (let ((asm (i286-asm '(:move :from (:of "HP" :self) :to "Dest") :slots slots)))
      (is (search "mov" asm)))))

(test i286/move-named-constant
  "MOVE named constant uses symbolic immediate."
  (let ((consts (make-hash "song--heal--id" 42)))
    (let ((asm (i286-asm '(:move :from "Song--Heal--ID" :to "X") :consts consts)))
      (is (search "mov" asm))
      (is (search "Song_Heal_ID" asm)))))

;;;
;;;; ADD / SUBTRACT
;;;

(test i286/add-literal-to-var
  "ADD literal TO var emits add instruction."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (i286-asm '(:add :from "A" :to "B") :pic pic)))
      (is (search "add" asm)))))

(test i286/subtract
  "SUBTRACT emits sub instruction."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (i286-asm '(:subtract :from "A" :from-target "B") :pic pic)))
      (is (search "sub" asm)))))

;;;
;;;; COMPUTE
;;;

(test i286/compute-literal
  "COMPUTE target = expr emits mov."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (i286-asm '(:compute :target "X" :expression 42) :pic pic)))
      (is (search "mov" asm))
      (is (search "42" asm)))))

;;;
;;;; SET
;;;

(test i286/set-literal
  "SET target TO value emits mov."
  (let ((asm (i286-asm '(:set :target "X" :value 99))))
    (is (search "mov" asm))
    (is (search "99" asm))))

;;;
;;;; IF / conditionals
;;;

(test i286/if-equal
  "IF a = b emits cmp and je/jne."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (i286-asm '(:if :condition (= "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test i286/if-greater
  "IF a > b emits cmp and jg."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (i286-asm '(:if :condition (:greater "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test i286/if-less
  "IF a < b emits cmp and jl."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (i286-asm '(:if :condition (:less "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test i286/if-else
  "IF/ELSE emits branch around else block."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (i286-asm '(:if :condition (= "A" "B")
                                    :then ((:move :from 1 :to "X"))
                                    :else ((:move :from 2 :to "Y")))
                             :pic pic :class-id "T")))
      (is (search "jne" asm)))))

;;;
;;;; INVOKE
;;;

(test i286/invoke-self
  "INVOKE Self \"Method\" emits call to invoke stub."
  (let ((asm (i286-asm '(:invoke :object "Self" :method "Connect")
                          :class-id "Character")))
    (is (search "call" asm))
    (is (search "InvokeCharacterConnect" asm))))

(test i286/invoke-super
  "INVOKE SUPER emits call to parent class invoke stub."
  (let ((eightbol::*parent-classes* (make-hash "Character" "Actor"))
        (eightbol::*method-id* "Think")
        (eightbol::*class-id* "Character"))
    (let ((asm (i286-asm '(:invoke-super))))
      (is (search "call" asm)))))

;;;
;;;; CALL
;;;

(test i286/call
  "CALL target emits call."
  (let ((asm (i286-asm '(:call :target "MoveDecalY"))))
    (is (search "call" asm))))

(test i286/call-acc
  "CALL...USING loads argument then call."
  (let ((asm (i286-asm '(:call-acc :target "Foo" :using 7))))
    (is (search "mov" asm))
    (is (search "call" asm))))

;;;
;;;; PERFORM
;;;

(test i286/perform-simple
  "PERFORM procedure emits call."
  (let ((asm (i286-asm '(:perform :procedure "Foo"))))
    (is (search "call Foo" asm))))

(test i286/perform-times
  "PERFORM TIMES n emits loop with decrement and conditional branch."
  (let ((asm (i286-asm '(:perform :procedure "Foo" :times 3))))
    (is (search "call Foo" asm))))

(test i286/perform-until
  "PERFORM UNTIL condition emits condition-checked loop."
  (let ((asm (i286-asm '(:perform :procedure "Foo"
                                    :until (:greater "X" 0))
                          :class-id "T")))
    (is (search "call" asm))))

(test i286/perform-with-body-until
  "PERFORM UNTIL with inline :body emits condition-checked loop."
  (let ((asm (i286-asm '(:perform :until (= "Done" 0) :body ((:move :from 1 :to "X"))))))
    (is (search "cmp" asm))
    (is (search "je" asm))))

(test i286/perform-with-body-varying
  "PERFORM VARYING emits counter init, varying store, and increment."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (i286-asm '(:perform :varying "X" :from 0 :by 1 :until (= "Done" 0)
                                    :body ((:move :from 1 :to "X")))
                         :pic pic)))
      (is (search "mov" asm)))))

;;;
;;;; EVALUATE
;;;

(test i286/evaluate-when
  "EVALUATE WHEN comparison emits cmp and conditional branch."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (i286-asm '(:evaluate :subject "X"
                                      :when-clauses ((:when "A" ((:move :from 1 :to "X")))))
                             :pic pic :class-id "T")))
      (is (search "cmp" asm)))))

;;;
;;;; INSPECT
;;;

(test i286/inspect-tallying
  "INSPECT TALLYING emits counting loop."
  (let ((pic (make-hash "Buf" 64 "Cnt" 1)))
    (let ((asm (i286-asm '(:inspect :target "Buf" :tallying "Cnt") :pic pic)))
      (is (search "mov" asm)))))

(test i286/inspect-replacing
  "INSPECT REPLACING emits fill loop."
  (let ((pic (make-hash "Buf" 64)))
    (let ((asm (i286-asm '(:inspect :target "Buf" :by 42) :pic pic)))
      (is (search "mov" asm)))))

;;;
;;;; GOTO / PARAGRAPH
;;;

(test i286/goto
  "GO TO target emits jmp to label."
  (let ((asm (i286-asm '(:goto :target "Exit"))))
    (is (search "jmp" asm))))

(test i286/paragraph
  "Paragraph emits label."
  (let ((asm (i286-asm '(:paragraph "MyPara"))))
    (is (search "MyPara:" asm))))

;;;
;;;; LOG FAULT / DEBUG BREAK
;;;

(test i286/log-fault
  "LOG FAULT emits comment."
  (let ((asm (i286-asm '(:log-fault :code 1234))))
    (is (search "LOG FAULT" asm))))

(test i286/debug-break
  "DEBUG BREAK emits comment."
  (let ((asm (i286-asm '(:debug-break :code 42))))
    (is (search "DEBUG BREAK" asm))))

;;;
;;;; Comment statement
;;;

(test i286/comment
  "Comment statement emits assembly comment."
  (let ((asm (i286-asm '(:comment "this is a test"))))
    (is (search "this is a test" asm))))

;;;
;;;; STRING BLT
;;;

(test i286/string-blt
  "STRING dest FROM src emits block copy loop."
  (let ((slots (make-hash "Src" "Character" "Dst" "Character")))
    (let ((asm (i286-asm '(:string-blt :source "Src" :dest "Dst") :slots slots)))
      (is (search "mov" asm))
      (is (search "cmp" asm)))))

;;;
;;;; UNSUPPORTED
;;;

(test i286/divide-non-power-of-two-signals-error
  "DIVIDE with non-power-of-two on i286 signals source-error."
  (signals eightbol:source-error
    (i286-asm '(:divide :divisor 3 :into "B"))))

(test i286/multiply-non-power-of-two-signals-error
  "MULTIPLY with non-power-of-two on i286 signals source-error."
  (signals eightbol:source-error
    (i286-asm '(:multiply :multiplier 3 :on "B"))))
