;; tests/backend-rp2a03-tests.lisp - RP2A03 (NES) backend statement tests
;;
;; The RP2A03 is the CPU in the NES. It is a 6502 variant that LACKS decimal mode.
;; For BCD (USAGE PACKED-DECIMAL) variables, this backend emits software BCD routines.
;; Tests verify RP2A03-specific header and BCD handling.

(in-package :eightbol/test)

(fiveam:def-suite :backend-rp2a03
  :description "RP2A03 (NES) backend statement emission")
(in-suite :backend-rp2a03)

(defun rp2a03-asm (stmt &key (class-id "Character") (slots nil) (consts nil) (pic nil) (types nil))
  "Compile STMT inside a minimal method for RP2A03, return assembly string."
  (let ((*standard-output* (make-broadcast-stream)))
    (compile-method-ast-with-tables
     `(:method :method-id "M" :statements (,stmt))
     class-id :rp2a03
     :slot-table (or slots (make-hash-table :test 'equalp))
     :const-table (or consts (make-hash-table :test 'equalp))
     :pic-width-table (or pic (make-hash-table :test 'equalp))
     :type-table (or types (make-hash-table :test 'equalp)))))

(defun make-hash (&rest pairs)
  (let ((h (make-hash-table :test 'equalp)))
    (loop for (key value) on pairs by #'cddr
          do (setf (gethash key h) value))
    h))

;;;
;;;; Header and structure
;;;

(test rp2a03/header-contains-cpu-label
  "RP2A03 output header contains 'generated by EIGHTBOL for RP2A03'."
  (let ((asm (rp2a03-asm '(:goback))))
    (is (search "generated by EIGHTBOL for RP2A03" asm))))

(test rp2a03/header-mentions-no-decimal-mode
  "RP2A03 header mentions BCD operations use software routines."
  (let ((asm (rp2a03-asm '(:goback))))
    (is (search "BCD" asm))))

(test rp2a03/method-emits-block-structure
  "Method body opens with .block and ends with .bend."
  (let ((asm (rp2a03-asm '(:goback))))
    (is (search ": .block" asm))
    (is (search ".bend" asm))))

(test rp2a03/method-emits-cld
  "Method body emits cld to ensure binary mode."
  (let ((asm (rp2a03-asm '(:goback))))
    (is (search "cld" asm))))

(test rp2a03/method-emits-dispatch-label
  "Method dispatch label is MethodClassName."
  (let ((asm (rp2a03-asm '(:goback) :class-id "Actor")))
    (is (search "MethodActorM" asm))))

;;;
;;;; Termination statements
;;;

(test rp2a03/goback
  "GOBACK emits rts."
  (let ((asm (rp2a03-asm '(:goback))))
    (is (search "rts" asm))))

(test rp2a03/exit-method
  "EXIT METHOD emits rts."
  (let ((asm (rp2a03-asm '(:exit-method))))
    (is (search "rts" asm))))

(test rp2a03/stop-run
  "STOP RUN emits rts."
  (let ((asm (rp2a03-asm '(:stop-run))))
    (is (search "rts" asm))))

;;;
;;;; MOVE statement
;;;

(test rp2a03/move-literal-to-var
  "MOVE literal TO var emits lda # immediate and sta."
  (let ((asm (rp2a03-asm '(:move :from 42 :to "X"))))
    (is (search "lda #42" asm))
    (is (search "sta" asm))))

(test rp2a03/move-slot-of-self
  "MOVE slot OF Self loads via Self-relative address."
  (let ((slots (make-hash "HP" "Character")))
    (let ((asm (rp2a03-asm '(:move :from (:of "HP" :self) :to "Dest") :slots slots)))
      (is (search "ldy #CharacterHP" asm))
      (is (search "lda (Self), y" asm)))))

(test rp2a03/move-to-subscript
  "MOVE to subscripted destination computes offset via index."
  (let ((slots (make-hash "Arr" "Character" "Idx" "Character")))
    (let ((asm (rp2a03-asm '(:move :from 0 :to (:subscript "Arr" "Idx")) :slots slots)))
      (is (search "lda" asm))
      (is (search "sta" asm)))))

(test rp2a03/move-named-constant
  "MOVE named constant uses symbolic immediate."
  (let ((consts (make-hash "song--heal--id" 42)))
    (let ((asm (rp2a03-asm '(:move :from "Song--Heal--ID" :to "X") :consts consts)))
      (is (search "lda # Song_Heal_ID" asm)))))

;;;
;;;; ADD / SUBTRACT
;;;

(test rp2a03/add-literal-to-var
  "ADD literal TO var emits clc and adc."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (rp2a03-asm '(:+ :from "A" :to "B") :pic pic)))
      (is (search "clc" asm))
      (is (search "adc" asm)))))

(test rp2a03/add-16-bit
  "ADD of 2-byte values emits multibyte add sequence."
  (let ((pic (make-hash "A" 2 "B" 2)))
    (let ((asm (rp2a03-asm '(:+ :from "A" :to "B") :pic pic)))
      (is (search "adc" asm))
      (is (search "sta" asm)))))

(test rp2a03/subtract
  "SUBTRACT emits sec and sbc."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (rp2a03-asm '(:- :from "A" :from-target "B") :pic pic)))
      (is (search "sec" asm))
      (is (search "sbc" asm)))))

(test rp2a03/subtract-16-bit
  "SUBTRACT of 2-byte values emits multibyte subtract sequence."
  (let ((pic (make-hash "A" 2 "B" 2)))
    (let ((asm (rp2a03-asm '(:- :from "A" :from-target "B") :pic pic)))
      (is (search "sbc" asm))
      (is (search "sta" asm)))))

;;;
;;;; COMPUTE
;;;

(test rp2a03/compute-literal
  "COMPUTE target = expr emits load and store."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (rp2a03-asm '(:compute :target "X" :expression 42) :pic pic)))
      (is (search "lda #42" asm))
      (is (search "sta" asm)))))

;;;
;;;; SET
;;;

(test rp2a03/set-literal
  "SET target TO value emits lda and sta."
  (let ((asm (rp2a03-asm '(:set :target "X" :value 99))))
    (is (search "lda #99" asm))
    (is (search "sta" asm))))

;;;
;;;; IF / conditionals
;;;

(test rp2a03/if-equal
  "IF a = b emits compare and branch."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (rp2a03-asm '(:if :condition (= "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test rp2a03/if-else
  "IF/ELSE emits branch around else block."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (rp2a03-asm '(:if :condition (= "A" "B")
                                    :then ((:move :from 1 :to "X"))
                                    :else ((:move :from 2 :to "Y")))
                             :pic pic :class-id "T")))
      (is (search "bne" asm)))))

;;;
;;;; INVOKE
;;;

(test rp2a03/invoke-self
  "INVOKE Self \"Method\" emits .CallMethod."
  (let ((asm (rp2a03-asm '(:invoke :object "Self" :method "Connect")
                          :class-id "Character")))
    (is (search ".CallMethod" asm))
    (is (search "InvokeCharacterConnect" asm))))

(test rp2a03/invoke-super
  "INVOKE SUPER emits .CallMethod to parent class."
  (let ((eightbol::*parent-classes* (make-hash "Character" "Actor"))
        (eightbol::*method-id* "Think")
        (eightbol::*class-id* "Character"))
    (let ((asm (rp2a03-asm '(:invoke-super))))
      (is (search ".CallMethod" asm)))))

;;;
;;;; CALL
;;;

(test rp2a03/call
  "CALL target emits jsr."
  (let ((asm (rp2a03-asm '(:call :target "MoveDecalY"))))
    (is (search "jsr" asm))))

(test rp2a03/call-acc
  "CALL...USING loads argument then jsr."
  (let ((asm (rp2a03-asm '(:call-acc :target "Foo" :using 7))))
    (is (search "lda #7" asm))
    (is (search "jsr" asm))))

;;;
;;;; PERFORM
;;;

(test rp2a03/perform-simple
  "PERFORM procedure emits jsr."
  (let ((asm (rp2a03-asm '(:perform :procedure "Foo"))))
    (is (search "jsr Foo" asm))))

(test rp2a03/perform-with-body-until
  "PERFORM UNTIL with inline :body emits condition-checked loop."
  (let ((asm (rp2a03-asm '(:perform :until (= "Done" 0) :body ((:move :from 1 :to "X"))))))
    (is (search "lda Done" asm))
    (is (search "bne" asm))))

;;;
;;;; EVALUATE
;;;

(test rp2a03/evaluate-when
  "EVALUATE WHEN comparison emits compare and branch."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (rp2a03-asm '(:evaluate :subject "X"
                                      :when-clauses ((:when "A" ((:move :from 1 :to "X")))))
                             :pic pic :class-id "T")))
      (is (search "cmp" asm)))))

;;;
;;;; INSPECT
;;;

(test rp2a03/inspect-tallying
  "INSPECT TALLYING emits counting loop."
  (let ((pic (make-hash "Buf" 64 "Cnt" 1)))
    (let ((asm (rp2a03-asm '(:inspect :target "Buf" :tallying "Cnt") :pic pic)))
      (is (search "lda" asm)))))

(test rp2a03/inspect-replacing
  "INSPECT REPLACING emits fill loop."
  (let ((pic (make-hash "Buf" 64)))
    (let ((asm (rp2a03-asm '(:inspect :target "Buf" :by 42) :pic pic)))
      (is (search "lda" asm)))))

;;;
;;;; GOTO / PARAGRAPH
;;;

(test rp2a03/goto
  "GO TO target emits jmp to label."
  (let ((asm (rp2a03-asm '(:goto :target "Exit"))))
    (is (search "jmp" asm))))

(test rp2a03/paragraph
  "Paragraph emits label."
  (let ((asm (rp2a03-asm '(:paragraph "MyPara"))))
    (is (search "MyPara:" asm))))

;;;
;;;; LOG FAULT / DEBUG BREAK
;;;

(test rp2a03/log-fault
  "LOG FAULT emits .LogFault directive."
  (let ((asm (rp2a03-asm '(:log-fault :code 1234))))
    (is (search "LogFault" asm))))

(test rp2a03/debug-break
  "DEBUG BREAK emits comment."
  (let ((asm (rp2a03-asm '(:debug-break :code 42))))
    (is (search "DEBUG BREAK" asm))))

;;;
;;;; STRING BLT
;;;

(test rp2a03/string-blt
  "STRING dest FROM src emits block copy loop."
  (let ((slots (make-hash "Src" "Character" "Dst" "Character")))
    (let ((asm (rp2a03-asm '(:string-blt :source "Src" :dest "Dst") :slots slots)))
      (is (search "ldy #$00" asm))
      (is (search "lda" asm))
      (is (search "sta" asm)))))

;;;
;;;; UNSUPPORTED
;;;

(test rp2a03/divide-signals-error
  "DIVIDE on RP2A03 signals backend-error."
  (signals eightbol::backend-error
    (rp2a03-asm '(:÷ :from "A" :into "B"))))

(test rp2a03/multiply-signals-error
  "MULTIPLY on RP2A03 signals backend-error."
  (signals eightbol::backend-error
    (rp2a03-asm '(:× :by "A" :on "B"))))
