;; tests/backend-65c816-tests.lisp - 65C816 backend statement tests
;;
;; The 65C816 extends 65C02 with 16-bit accumulator/index registers and 24-bit addressing.
;; EIGHTBOL 65C816 backend delegates to the 6502 family emission code.
;; Tests verify delegation and 65C816-specific header generation.

(in-package :eightbol/test)

(fiveam:def-suite :backend-65c816
  :description "65C816 backend statement emission")
(in-suite :backend-65c816)

(defun 65c816-asm (stmt &key (class-id "Character") (slots nil) (consts nil) (pic nil) (types nil))
  "Compile STMT inside a minimal method for 65C816, return assembly string."
  (let ((*standard-output* (make-broadcast-stream)))
    (compile-method-ast-with-tables
     `(:method :method-id "M" :statements (,stmt))
     class-id :65c816
     :slot-table (or slots (make-hash-table :test 'equalp))
     :const-table (or consts (make-hash-table :test 'equalp))
     :pic-width-table (or pic (make-hash-table :test 'equalp))
     :type-table (or types (make-hash-table :test 'equalp)))))

(defun make-hash (&rest pairs)
  (let ((h (make-hash-table :test 'equalp)))
    (loop for (key value) on pairs by #'cddr
          do (setf (gethash key h) value))
    h))

;;;
;;;; Header and structure
;;;

(test 65c816/header-contains-cpu-label
  "65C816 output header contains 'generated by EIGHTBOL for 65c816'."
  (let ((asm (65c816-asm '(:goback))))
    (is (search "generated by EIGHTBOL for 65c816" asm))))

(test 65c816/method-emits-block-structure
  "Method body opens with .block and ends with .bend."
  (let ((asm (65c816-asm '(:goback))))
    (is (search ".block" asm))
    (is (search ".bend" asm))))

(test 65c816/method-emits-dispatch-label
  "Method dispatch label is MethodClassName."
  (let ((asm (65c816-asm '(:goback) :class-id "Actor")))
    (is (search "MethodActorM" asm))))

;;;
;;;; Termination statements (delegated from 6502)
;;;

(test 65c816/goback
  "GOBACK emits rts."
  (let ((asm (65c816-asm '(:goback))))
    (is (search "rts" asm))))

(test 65c816/exit-method
  "EXIT METHOD emits rts."
  (let ((asm (65c816-asm '(:exit-method))))
    (is (search "rts" asm))))

(test 65c816/stop-run
  "STOP RUN emits rts."
  (let ((asm (65c816-asm '(:stop-run))))
    (is (search "rts" asm))))

;;;
;;;; MOVE statement
;;;

(test 65c816/move-literal-to-var
  "MOVE literal TO var emits lda # immediate and sta."
  (let ((asm (65c816-asm '(:move :from 42 :to "X"))))
    (is (search "lda #42" asm))
    (is (search "sta" asm))))

(test 65c816/move-slot-of-self
  "MOVE slot OF Self loads via Self-relative address."
  (let ((slots (make-hash "HP" "Character")))
    (let ((asm (65c816-asm '(:move :from (:of "HP" :self) :to "Dest") :slots slots)))
      (is (search "ldy #CharacterHP" asm))
      (is (search "lda (Self), y" asm)))))

(test 65c816/move-named-constant
  "MOVE named constant uses symbolic immediate."
  (let ((consts (make-hash "song--heal--id" 42)))
    (let ((asm (65c816-asm '(:move :from "Song--Heal--ID" :to "X") :consts consts)))
      (is (search "lda # Song_Heal_ID" asm)))))

;;;
;;;; ADD / SUBTRACT
;;;

(test 65c816/add-literal-to-var
  "ADD literal TO var emits clc and adc."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (65c816-asm '(:add :from "A" :to "B") :pic pic)))
      (is (search "clc" asm))
      (is (search "adc" asm)))))

(test 65c816/subtract
  "SUBTRACT emits sec and sbc."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (65c816-asm '(:subtract :from "A" :from-target "B") :pic pic)))
      (is (search "sec" asm))
      (is (search "sbc" asm)))))

;;;
;;;; COMPUTE
;;;

(test 65c816/compute-literal
  "COMPUTE target = expr emits load and store."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (65c816-asm '(:compute :target "X" :expression 42) :pic pic)))
      (is (search "lda #42" asm))
      (is (search "sta" asm)))))

;;;
;;;; SET
;;;

(test 65c816/set-literal
  "SET target TO value emits lda and sta."
  (let ((asm (65c816-asm '(:set :target "X" :value 99))))
    (is (search "lda #99" asm))
    (is (search "sta" asm))))

;;;
;;;; IF / conditionals
;;;

(test 65c816/if-equal
  "IF a = b emits compare and branch."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (65c816-asm '(:if :condition (= "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (search "cmp" asm)))))

(test 65c816/if-else
  "IF/ELSE emits branch around else block."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (65c816-asm '(:if :condition (= "A" "B")
                                    :then ((:move :from 1 :to "X"))
                                    :else ((:move :from 2 :to "Y")))
                             :pic pic :class-id "T")))
      (is (search "bne" asm)))))

;;;
;;;; INVOKE
;;;

(test 65c816/invoke-self
  "INVOKE Self \"Method\" emits .CallMethod."
  (let ((asm (65c816-asm '(:invoke :object "Self" :method "Connect")
                          :class-id "Character")))
    (is (search ".CallMethod" asm))
    (is (search "InvokeCharacterConnect" asm))))

(test 65c816/invoke-super
  "INVOKE SUPER emits .CallMethod to parent class."
  (let ((eightbol::*parent-classes* (make-hash "Character" "Actor"))
        (eightbol::*method-id* "Think")
        (eightbol::*class-id* "Character"))
    (let ((asm (65c816-asm '(:invoke-super))))
      (is (search ".CallMethod" asm)))))

;;;
;;;; CALL
;;;

(test 65c816/call
  "CALL target emits jsr."
  (let ((asm (65c816-asm '(:call :target "MoveDecalY"))))
    (is (search "jsr" asm))))

(test 65c816/call-acc
  "CALL...USING loads argument then jsr."
  (let ((asm (65c816-asm '(:call-acc :target "Foo" :using 7))))
    (is (search "lda #7" asm))
    (is (search "jsr" asm))))

;;;
;;;; PERFORM
;;;

(test 65c816/perform-simple
  "PERFORM procedure emits jsr."
  (let ((asm (65c816-asm '(:perform :procedure "Foo"))))
    (is (search "jsr Foo" asm))))

(test 65c816/perform-with-body-until
  "PERFORM UNTIL with inline :body emits condition-checked loop."
  (let ((asm (65c816-asm '(:perform :until (= "Done" 0) :body ((:move :from 1 :to "X"))))))
    (is (search "lda Done" asm))
    (is (search "bne" asm))))

;;;
;;;; EVALUATE
;;;

(test 65c816/evaluate-when
  "EVALUATE WHEN comparison emits compare and branch."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (65c816-asm '(:evaluate :subject "X"
                                      :when-clauses ((:when "A" ((:move :from 1 :to "X")))))
                             :pic pic :class-id "T")))
      (is (search "cmp" asm)))))

;;;
;;;; INSPECT
;;;

(test 65c816/inspect-tallying
  "INSPECT TALLYING emits counting loop."
  (let ((pic (make-hash "Buf" 64 "Cnt" 1)))
    (let ((asm (65c816-asm '(:inspect :target "Buf" :tallying "Cnt") :pic pic)))
      (is (search "lda" asm)))))

(test 65c816/inspect-replacing
  "INSPECT REPLACING emits fill loop."
  (let ((pic (make-hash "Buf" 64)))
    (let ((asm (65c816-asm '(:inspect :target "Buf" :by 42) :pic pic)))
      (is (search "lda" asm)))))

;;;
;;;; GOTO / PARAGRAPH
;;;

(test 65c816/goto
  "GO TO target emits jmp to label."
  (let ((asm (65c816-asm '(:goto :target "Exit"))))
    (is (search "jmp" asm))))

(test 65c816/paragraph
  "Paragraph emits label."
  (let ((asm (65c816-asm '(:paragraph "MyPara"))))
    (is (search "MyPara:" asm))))

;;;
;;;; LOG FAULT / DEBUG BREAK
;;;

(test 65c816/log-fault
  "LOG FAULT emits comment."
  (let ((asm (65c816-asm '(:log-fault :code 1234))))
    (is (search "LOG FAULT" asm))))

(test 65c816/debug-break
  "DEBUG BREAK emits comment."
  (let ((asm (65c816-asm '(:debug-break :code 42))))
    (is (search "DEBUG BREAK" asm))))

;;;
;;;; STRING BLT
;;;

(test 65c816/string-blt
  "STRING dest FROM src emits block copy loop."
  (let ((slots (make-hash "Src" "Character" "Dst" "Character")))
    (let ((asm (65c816-asm '(:string-blt :source "Src" :dest "Dst") :slots slots)))
      (is (search "ldy #$00" asm))
      (is (search "lda" asm))
      (is (search "sta" asm)))))

;;;
;;;; UNSUPPORTED
;;;

(test 65c816/divide-signals-error
  "DIVIDE on 65C816 signals backend-error."
  (signals eightbol::backend-error
    (65c816-asm '(:divide :from "A" :into "B"))))

(test 65c816/multiply-signals-error
  "MULTIPLY on 65C816 signals backend-error."
  (signals eightbol::backend-error
    (65c816-asm '(:multiply :by "A" :on "B"))))
