;; tests/backend-stack-tests.lisp - Stack machine backend statement tests
;;
;; Generic stack-based virtual machine backend for code generation.
;; Uses a simple stack model with operations for PUSH, POP, ADD, SUB, etc.
;; Useful for bytecode or intermediate representation generation.

(in-package :eightbol/test)

(fiveam:def-suite :backend-stack
  :description "Stack machine backend statement emission")
(in-suite :backend-stack)

(defun stack-asm (stmt &key (class-id "Character") (slots nil) (consts nil) (pic nil) (types nil))
  "Compile STMT inside a minimal method for stack machine, return assembly string."
  (let ((*standard-output* (make-broadcast-stream)))
    (compile-method-ast-with-tables
     `(:method :method-id "M" :statements (,stmt))
     class-id :stack
     :slot-table (or slots (make-hash-table :test 'equalp))
     :const-table (or consts (make-hash-table :test 'equalp))
     :pic-width-table (or pic (make-hash-table :test 'equalp))
     :type-table (or types (make-hash-table :test 'equalp)))))

(defun make-hash (&rest pairs)
  (let ((h (make-hash-table :test 'equalp)))
    (loop for (key value) on pairs by #'cddr
          do (setf (gethash key h) value))
    h))

;;;
;;;; Header and structure
;;;

(test stack/header-contains-cpu-label
  "Stack output header contains 'generated by EIGHTBOL for Stack Machine'."
  (let ((asm (stack-asm '(:goback))))
    (is (search "generated by EIGHTBOL for Stack Machine" asm))))

(test stack/method-emits-dispatch-label
  "Method dispatch label is MethodClassName."
  (let ((asm (stack-asm '(:goback) :class-id "Actor")))
    (is (search "MethodActorM" asm))))

(test stack/method-emits-return
  "Method body ends with return for GOBACK."
  (let ((asm (stack-asm '(:goback))))
    (is (search "return" asm))))

;;;
;;;; Termination statements
;;;

(test stack/goback
  "GOBACK emits return."
  (let ((asm (stack-asm '(:goback))))
    (is (search "return" asm))))

(test stack/exit-method
  "EXIT METHOD emits return."
  (let ((asm (stack-asm '(:exit-method))))
    (is (search "return" asm))))

(test stack/exit-program
  "EXIT PROGRAM emits return."
  (let ((asm (stack-asm '(:exit-program))))
    (is (search "return" asm))))

(test stack/stop-run
  "STOP RUN emits return."
  (let ((asm (stack-asm '(:stop-run))))
    (is (search "return" asm))))

(test stack/exit
  "EXIT emits return."
  (let ((asm (stack-asm '(:exit))))
    (is (search "return" asm))))

;;;
;;;; MOVE statement
;;;

(test stack/move-literal-to-var
  "MOVE literal TO var emits push immediate."
  (let ((asm (stack-asm '(:move :from 42 :to "X"))))
    (is (search "push" asm))
    (is (search "42" asm))))

(test stack/move-slot-of-self
  "MOVE slot OF Self pushes from memory."
  (let ((slots (make-hash "HP" "Character")))
    (let ((asm (stack-asm '(:move :from (:of "HP" :self) :to "Dest") :slots slots)))
      (is (or (search "push" asm) (search "load" asm))))))

(test stack/move-named-constant
  "MOVE named constant uses symbolic immediate."
  (let ((consts (make-hash "song--heal--id" 42)))
    (let ((asm (stack-asm '(:move :from "Song--Heal--ID" :to "X") :consts consts)))
      (is (search "push" asm))
      (is (search "Song_Heal_ID" asm)))))

;;;
;;;; ADD / SUBTRACT
;;;

(test stack/add-literal-to-var
  "ADD literal TO var emits add instruction."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (stack-asm '(:add :from "A" :to "B") :pic pic)))
      (is (search "add" asm)))))

(test stack/add-16-bit
  "ADD of 2-byte values emits add instruction."
  (let ((pic (make-hash "A" 2 "B" 2)))
    (let ((asm (stack-asm '(:add :from "A" :to "B") :pic pic)))
      (is (search "add" asm)))))

(test stack/subtract
  "SUBTRACT emits sub instruction."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (stack-asm '(:subtract :from "A" :from-target "B") :pic pic)))
      (is (search "sub" asm)))))

(test stack/subtract-16-bit
  "SUBTRACT of 2-byte values emits sub instruction."
  (let ((pic (make-hash "A" 2 "B" 2)))
    (let ((asm (stack-asm '(:subtract :from "A" :from-target "B") :pic pic)))
      (is (search "sub" asm)))))

;;;
;;;; COMPUTE
;;;

(test stack/compute-literal
  "COMPUTE target = expr emits push."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (stack-asm '(:compute :target "X" :expression 42) :pic pic)))
      (is (search "push" asm))
      (is (search "42" asm)))))

;;;
;;;; SET
;;;

(test stack/set-literal
  "SET target TO value emits push."
  (let ((asm (stack-asm '(:set :target "X" :value 99))))
    (is (search "push" asm))
    (is (search "99" asm))))

;;;
;;;; IF / conditionals
;;;

(test stack/if-equal
  "IF a = b emits compare and conditional branch."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (stack-asm '(:if :condition (= "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (or (search "cmp" asm) (search "compare" asm))))))

(test stack/if-greater
  "IF a > b emits compare and conditional branch."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (stack-asm '(:if :condition (:greater "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (or (search "cmp" asm) (search "compare" asm))))))

(test stack/if-less
  "IF a < b emits compare and conditional branch."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (stack-asm '(:if :condition (:less "A" "B") :then ((:move :from 0 :to "X"))
                            :class-id "T") :pic pic)))
      (is (or (search "cmp" asm) (search "compare" asm))))))

(test stack/if-else
  "IF/ELSE emits branch around else block."
  (let ((pic (make-hash "A" 1 "B" 1)))
    (let ((asm (stack-asm '(:if :condition (= "A" "B")
                                    :then ((:move :from 1 :to "X"))
                                    :else ((:move :from 2 :to "Y")))
                             :pic pic :class-id "T")))
      (is (search "jne" asm)))))

;;;
;;;; INVOKE
;;;

(test stack/invoke-self
  "INVOKE Self \"Method\" emits call to invoke stub."
  (let ((asm (stack-asm '(:invoke :object "Self" :method "Connect")
                          :class-id "Character")))
    (is (search "call" asm))
    (is (search "InvokeCharacterConnect" asm))))

(test stack/invoke-super
  "INVOKE SUPER emits call to parent class invoke stub."
  (let ((eightbol::*parent-classes* (make-hash "Character" "Actor"))
        (eightbol::*method-id* "Think")
        (eightbol::*class-id* "Character"))
    (let ((asm (stack-asm '(:invoke-super))))
      (is (search "call" asm)))))

;;;
;;;; CALL
;;;

(test stack/call
  "CALL target emits call."
  (let ((asm (stack-asm '(:call :target "MoveDecalY"))))
    (is (search "call" asm))))

(test stack/call-acc
  "CALL...USING loads argument then call."
  (let ((asm (stack-asm '(:call-acc :target "Foo" :using 7))))
    (is (search "push" asm))
    (is (search "call" asm))))

;;;
;;;; PERFORM
;;;

(test stack/perform-simple
  "PERFORM procedure emits call."
  (let ((asm (stack-asm '(:perform :procedure "Foo"))))
    (is (search "call Foo" asm))))

(test stack/perform-times
  "PERFORM TIMES n emits loop with decrement and conditional branch."
  (let ((asm (stack-asm '(:perform :procedure "Foo" :times 3))))
    (is (search "call Foo" asm))))

(test stack/perform-until
  "PERFORM UNTIL condition emits condition-checked loop."
  (let ((asm (stack-asm '(:perform :procedure "Foo"
                                    :until (:greater "X" 0))
                          :class-id "T")))
    (is (search "call" asm))))

(test stack/perform-with-body-until
  "PERFORM UNTIL with inline :body emits condition-checked loop."
  (let ((asm (stack-asm '(:perform :until (= "Done" 0) :body ((:move :from 1 :to "X"))))))
    (is (or (search "cmp" asm) (search "compare" asm)))
    (is (search "je" asm))))

(test stack/perform-with-body-varying
  "PERFORM VARYING emits counter init, varying store, and increment."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (stack-asm '(:perform :varying "X" :from 0 :by 1 :until (= "Done" 0)
                                    :body ((:move :from 1 :to "X")))
                         :pic pic)))
      (is (search "push" asm)))))

;;;
;;;; EVALUATE
;;;

(test stack/evaluate-when
  "EVALUATE WHEN comparison emits compare and conditional branch."
  (let ((pic (make-hash "X" 1)))
    (let ((asm (stack-asm '(:evaluate :subject "X"
                                      :when-clauses ((:when "A" ((:move :from 1 :to "X")))))
                             :pic pic :class-id "T")))
      (is (or (search "cmp" asm) (search "compare" asm))))))

;;;
;;;; INSPECT
;;;

(test stack/inspect-tallying
  "INSPECT TALLYING emits counting loop."
  (let ((pic (make-hash "Buf" 64 "Cnt" 1)))
    (let ((asm (stack-asm '(:inspect :target "Buf" :tallying "Cnt") :pic pic)))
      (is (search "push" asm)))))

(test stack/inspect-replacing
  "INSPECT REPLACING emits fill loop."
  (let ((pic (make-hash "Buf" 64)))
    (let ((asm (stack-asm '(:inspect :target "Buf" :by 42) :pic pic)))
      (is (search "push" asm)))))

;;;
;;;; GOTO / PARAGRAPH
;;;

(test stack/goto
  "GO TO target emits jmp to label."
  (let ((asm (stack-asm '(:goto :target "Exit"))))
    (is (search "jmp" asm))))

(test stack/paragraph
  "Paragraph emits label."
  (let ((asm (stack-asm '(:paragraph "MyPara"))))
    (is (search "MyPara:" asm))))

;;;
;;;; LOG FAULT / DEBUG BREAK
;;;

(test stack/log-fault
  "LOG FAULT emits comment."
  (let ((asm (stack-asm '(:log-fault :code 1234))))
    (is (search "LOG FAULT" asm))))

(test stack/debug-break
  "DEBUG BREAK emits comment."
  (let ((asm (stack-asm '(:debug-break :code 42))))
    (is (search "DEBUG BREAK" asm))))

;;;
;;;; STRING BLT
;;;

(test stack/string-blt
  "STRING dest FROM src emits block copy loop."
  (let ((slots (make-hash "Src" "Character" "Dst" "Character")))
    (let ((asm (stack-asm '(:string-blt :source "Src" :dest "Dst") :slots slots)))
      (is (search "push" asm)))))
