;; src/backend-stack.lisp — Stack-machine code generation backend
;;
;; Generic stack-based virtual machine backend for code generation.
;; Uses a simple stack model with operations for PUSH, POP, ADD, SUB, etc.
;; Useful for bytecode or intermediate representation generation.
;;
;; Registers/Stack: TOS (top-of-stack), stack-based parameters and locals.
;; Instructions: push, pop, add, sub, mul, div, call, return, jmp, je, etc.
(in-package :eightbol)

;;; CPU variant and output management
(defvar *output-stream* nil
  "Stream for stack machine code output; rebound during compilation.")

(defun stack-symbol (name)
  "Convert EIGHTBOL identifier to stack machine symbol (PascalCase).
COBOL stabby-case supported."
  (pascal-case (format nil "~a" name)))

;;; Top-level entry point

(defmethod compile-to-assembly (ast (cpu (eql :stack)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/STACK: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table
                          usage-table sign-table pic-size-table pic-width-table
                          pic-frac-bits-table pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (declare (ignore service-bank-table usage-table sign-table pic-frac-bits-table pic-nybble-semantics-table))
      (let ((*output-stream* output-stream)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table))
        (format output-stream
                "; ~a -- generated by EIGHTBOL for Stack Machine~%;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
                class-id class-id)
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-stack-method method)))))))

;;; Method compilation

(defun compile-stack-method (method)
  (let ((*method-id* (getf (rest method) :method-id)))
    (declare (special *method-id*))
    (let* ((method-id *method-id*)
           (dispatch-label (format nil "Method~a~a"
                                   (stack-symbol *class-id*)
                                   (stack-symbol (format nil "~a" method-id))))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                       (getf (rest method) :statements))))
           (statements (nth-value 1 (split-method-leading-assembly-entry
                                     (getf (rest method) :statements))))
           (last-statement (car (last statements))))
      (if custom-entry
          (progn
            (format *output-stream* "~%~a:~%" (stack-symbol custom-entry))
            (format *output-stream* "~a:~%" dispatch-label))
          (format *output-stream* "~%~a:~%" dispatch-label))
      (dolist (stmt statements)
        (compile-statement :stack (first stmt) (rest stmt)))
      (unless (and last-statement (listp last-statement)
                   (member (first last-statement)
                           '(:goback :exit-method :exit-program :exit :stop-run)))
        (format *output-stream* "~10Treturn~%")))))

;;; Statement handlers using generic dispatch

(defmacro def-stack-statement (statement-type (ast-node-data) &body body)
  "Define compile-statement for :stack CPU."
  `(defmethod compile-statement ((cpu (eql :stack)) (statement-type (eql ,statement-type)) ,ast-node-data)
     ,@body))

;;; Minimal statement handlers for core operations

(def-stack-statement :goback (_)
  (declare (ignore _))
  (format *output-stream* "~10Treturn~%"))

(def-stack-statement :exit-method (_)
  (declare (ignore _))
  (format *output-stream* "~10Treturn~%"))

(def-stack-statement :exit-program (_)
  (declare (ignore _))
  (format *output-stream* "~10Treturn~%"))

(def-stack-statement :stop-run (_)
  (declare (ignore _))
  (format *output-stream* "~10Treturn~%"))

(def-stack-statement :exit (_)
  (declare (ignore _))
  (format *output-stream* "~10Treturn~%"))

(def-stack-statement :move (ast-node-data)
  (let ((from (getf ast-node-data :from))
        (to (getf ast-node-data :to)))
    (format *output-stream* "~10T; MOVE ~a to ~a~%" from to)
    (format *output-stream* "~10Tpush ~a~%" from)
    (format *output-stream* "~10Tpop ~a~%" to)))

(def-stack-statement :invoke (ast-node-data)
  (let ((method (getf ast-node-data :method))
        (object (getf ast-node-data :object)))
    (format *output-stream* "~10T; INVOKE ~a.~a~%" object method)
    (format *output-stream* "~10Tcall Method~a~a~%"
            (stack-symbol (format nil "~a" object))
            (stack-symbol (format nil "~a" method)))))

(def-stack-statement :call (ast-node-data)
  (let ((target (getf ast-node-data :target)))
    (format *output-stream* "~10Tcall ~a~%" (stack-symbol target))))

(def-stack-statement :if (ast-node-data)
  (let ((condition (getf ast-node-data :condition))
        (then-stmts (getf ast-node-data :then))
        (else-stmts (getf ast-node-data :else)))
    (format *output-stream* "~10T; IF condition: ~a~%" condition)
    (format *output-stream* "~10Tpush ~a~%" condition)
    (let ((else-label (format nil "else_~d" (random 100000)))
          (end-label (format nil "end_~d" (random 100000))))
      (format *output-stream* "~10Tjz ~a~%" else-label)
      (dolist (stmt then-stmts)
        (compile-statement :stack (first stmt) (rest stmt)))
      (format *output-stream* "~10Tjmp ~a~%" end-label)
      (format *output-stream* "~a:~%" else-label)
      (dolist (stmt else-stmts)
        (compile-statement :stack (first stmt) (rest stmt)))
      (format *output-stream* "~a:~%" end-label))))

(def-stack-statement :add (ast-node-data)
  (let ((from (getf ast-node-data :from))
        (to (getf ast-node-data :to)))
    (format *output-stream* "~10T; ADD ~a to ~a~%" from to)
    (format *output-stream* "~10Tpush ~a~%" from)
    (format *output-stream* "~10Tpush ~a~%" to)
    (format *output-stream* "~10Tadd~%")
    (format *output-stream* "~10Tpop ~a~%" to)))

(def-stack-statement :subtract (ast-node-data)
  (let ((from (getf ast-node-data :from))
        (from-target (getf ast-node-data :from-target)))
    (format *output-stream* "~10T; SUBTRACT ~a from ~a~%" from from-target)
    (format *output-stream* "~10Tpush ~a~%" from-target)
    (format *output-stream* "~10Tpush ~a~%" from)
    (format *output-stream* "~10Tsub~%")
    (format *output-stream* "~10Tpop ~a~%" from-target)))

;;; Dialogue, Print, and Input statement handlers

(def-stack-statement :dialogue (ast-node-data)
  "Emit dialogue call with text string, speaker, and optional phonemes.
Sets up dialogue ID and speaker, then calls dialogue handler.
Uses deduplication IDs generated by the Fountain compiler approach."
  (let ((text (getf ast-node-data :text))
        (speaker (or (getf ast-node-data :speaker) "Narrator")))
    ;; Emit dialogue ID reference (deduplication handled upstream)
    (format *output-stream* "~10T; Dialogue: ~a | ~a~%" text speaker)
    ;; Push dialogue ID onto stack
    (format *output-stream* "~10Tpush DialogueID_~a~%" (normalize-identifier-to-pascal-case text))
    ;; Push speaker ID onto stack
    (format *output-stream* "~10Tpush ~a~%" (normalize-identifier-to-pascal-case speaker))
    ;; Call dialogue dispatcher
    (format *output-stream* "~10Tcall DoDialogue~%")))

(def-stack-statement :print (ast-node-data)
  "Emit print/output statement.
Pushes value onto stack and calls print handler."
  (let ((value (getf ast-node-data :value)))
    (format *output-stream* "~10T; Print: ~a~%" value)
    ;; Push value onto stack
    (format *output-stream* "~10Tpush ~a~%" value)
    ;; Call print output routine
    (format *output-stream* "~10Tcall DoPrint~%")))

(def-stack-statement :input (ast-node-data)
  "Emit input statement.
Reads input and stores into target identifier."
  (let ((target (getf ast-node-data :target)))
    (format *output-stream* "~10T; Input to ~a~%" target)
    ;; Call input routine (returns value on stack)
    (format *output-stream* "~10Tcall DoInput")
    ;; Store result to target
    (format *output-stream* "~10Tpop ~a~%" target)))

;;; Fallback for unimplemented statements

(defmethod compile-statement ((cpu (eql :stack)) statement-type ast-node-data)
  (declare (ignore ast-node-data))
  (format *output-stream* "~10T; UNIMPLEMENTED: ~a~%" statement-type))
