;; src/backend-forth/backend-forth-part1.lisp — Forth bytecode code generation part 1
;;; Copyright © 2026 Interworldly Adventuring, LLC
;;
;; Entry point and method compilation for Forth bytecode backend.
;; Emits bytecodes defined in Phantasia Enums.s:
;;   ForthEOL       = $00
;;   ForthPushWord  = $01
;;   ForthSetByte   = $02
;;   ForthSetWord   = $03
;;   ForthGetByte   = $04
;;   ForthGetWord   = $05
;;   ForthExecute   = $06
;;   ForthDup       = $07
;;   ForthDrop      = $08
;;   ForthUnless    = $09
;;   ForthWhen      = $0a
;;   ForthGo        = $0b
;;   ForthSwap      = $0c
;;   ForthPushByte  = $0d
(in-package :eightbol)

;;; CPU state and output management
(defvar *output-stream* nil
  "Stream for Forth bytecode output; rebound during compilation.")

(defvar *forth-method-id* nil
  "Current method ID being compiled for Forth bytecode.")

(defvar *forth-class-id* nil
  "Current class ID being compiled for Forth bytecode.")

(defvar *forth-label-counter* 0
  "Counter for generating unique bytecode labels.")

(defvar *forth-method-entry-point* nil
  "Label for the entry point of the current method.")

;;; Bytecode constants
(defconstant +forth-eol+ #x00 "End of line / procedure end marker.")
(defconstant +forth-push-word+ #x01 "Push 16-bit value onto stack.")
(defconstant +forth-set-byte+ #x02 "Store byte to memory.")
(defconstant +forth-set-word+ #x03 "Store 16-bit value to memory.")
(defconstant +forth-get-byte+ #x04 "Load byte from memory.")
(defconstant +forth-get-word+ #x05 "Load 16-bit value from memory.")
(defconstant +forth-execute+ #x06 "Execute forth word / call subroutine.")
(defconstant +forth-dup+ #x07 "Duplicate top of stack.")
(defconstant +forth-drop+ #x08 "Drop top of stack.")
(defconstant +forth-unless+ #x09 "Branch if top of stack is zero.")
(defconstant +forth-when+ #x0a "Branch if top of stack is nonzero.")
(defconstant +forth-go+ #x0b "Unconditional branch.")
(defconstant +forth-swap+ #x0c "Swap top two stack items.")
(defconstant +forth-push-byte+ #x0d "Push 8-bit value onto stack.")

;;; Symbol table management (lazy initialization)
(defun forth-symbol-table ()
  "Return or initialize the Forth symbol table for the current class."
  *const-table*)

;;; Helper: Generate unique label
(defun forth-make-label (&optional prefix)
  "Generate a unique bytecode label."
  (incf *forth-label-counter*)
  (format nil "~a_~d" (or prefix "L") *forth-label-counter*))

;;; Identifier conversion to PascalCase
(defun forth-symbol (name)
  "Convert EIGHTBOL identifier to PascalCase symbol for Forth bytecode."
  (pascal-case (format nil "~a" name)))

;;; Top-level entry point
(defmethod compile-to-assembly (ast (cpu (eql :forth)) output-stream)
  "Compile AST to Forth bytecode, writing to OUTPUT-STREAM.

Validates that AST is a :program node and contains a methods list.
Binds dynamic variables for class and method context, then compiles
each method sequentially, emitting bytecode sequences."
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/FORTH: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table
                          usage-table sign-table pic-size-table pic-width-table
                          pic-frac-bits-table pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (declare (ignore service-bank-table usage-table sign-table
                       pic-frac-bits-table pic-nybble-semantics-table))
      (let ((*output-stream* output-stream)
            (*forth-class-id* class-id)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table)
            (*forth-label-counter* 0))
        (format output-stream
                "; ~a -- generated by EIGHTBOL Forth bytecode backend~%;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
                class-id class-id)
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-forth-method method)))))))

;;; Method compilation
(defun compile-forth-method (method)
  "Compile one METHOD to Forth bytecode.

Emits method header with label, processes statements, and terminates
with ForthEOL marker. Handles custom assembly entry points if present."
  (let ((*forth-method-id* (getf (rest method) :method-id)))
    (declare (special *forth-method-id*))
    (let* ((method-id *forth-method-id*)
           (dispatch-label (format nil "Method~a~a"
                                   (forth-symbol *forth-class-id*)
                                   (forth-symbol (format nil "~a" method-id))))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                       (getf (rest method) :statements))))
           (statements (nth-value 1 (split-method-leading-assembly-entry
                                     (getf (rest method) :statements))))
           (last-statement (car (last statements))))
      (if custom-entry
          (progn
            (format *output-stream* "~%~a:~%" (forth-symbol custom-entry))
            (format *output-stream* "~a:~%" dispatch-label))
          (format *output-stream* "~%~a:~%" dispatch-label))
      
      ;; Emit statements
      (dolist (stmt statements)
        (compile-statement :forth (first stmt) (rest stmt)))
      
      ;; Emit return marker if last statement isn't already a return
      (unless (and last-statement (listp last-statement)
                   (member (first last-statement)
                           '(:goback :exit-method :exit-program :exit :stop-run)))
        (forth-emit-eol))
      
      ;; Emit method footer
      (format *output-stream* "~%"))))

;;; Public bytecode emission interface
(defun forth-emit-byte (byte-value)
  "Emit a single bytecode byte to output."
  (format *output-stream* ".byte #x~2,'0x~%" byte-value))

(defun forth-emit-word (word-value)
  "Emit a 16-bit bytecode word to output (little-endian: low byte first)."
  (let ((low (logand word-value #xff))
        (high (logand (ash word-value -8) #xff)))
    (format *output-stream* ".byte #x~2,'0x, #x~2,'0x~%" low high)))

(defun forth-emit-opcode (opcode &rest operands)
  "Emit an opcode with optional operands.

OPCODE is a bytecode constant (e.g., +forth-dup+).
OPERANDS are additional bytes to emit after the opcode."
  (format *output-stream* ".byte #x~2,'0x" opcode)
  (dolist (operand operands)
    (format *output-stream* ", #x~2,'0x" operand))
  (format *output-stream* "~%"))

(defun forth-emit-eol ()
  "Emit ForthEOL marker (#x00) to signal end of procedure."
  (forth-emit-opcode +forth-eol+))

;;; Symbol management
(defun forth-get-variable-address (var-name)
  "Look up address of variable VAR-NAME in symbol table.
Returns address or signals error if not found."
  (let ((addr (gethash var-name (forth-symbol-table))))
    (unless addr
      (error "EIGHTBOL/FORTH: variable ~s not found in symbol table" var-name))
    addr))

(defun forth-get-constant-value (const-name)
  "Look up value of constant CONST-NAME in symbol table.
Returns value or signals error if not found."
  (let ((value (gethash const-name (forth-symbol-table))))
    (unless value
      (error "EIGHTBOL/FORTH: constant ~s not found in symbol table" const-name))
    value))
