;; src/basic-lexer.lisp — Tokenization for Dartmouth BASIC source
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *basic-keyword-alist*
  '(("REM" . :REM)
    ("LET" . :LET)
    ("FOR" . :FOR)
    ("TO" . :TO)
    ("STEP" . :STEP)
    ("NEXT" . :NEXT)
    ("IF" . :IF)
    ("THEN" . :THEN)
    ("ELSE" . :ELSE)
    ("GOTO" . :GOTO)
    ("GOSUB" . :GOSUB)
    ("RETURN" . :RETURN)
    ("LOG" . :LOG)
    ("FAULT" . :FAULT)
    ("STOP" . :STOP)
    ("METHOD" . :METHOD)
    ("ON" . :ON)
    ("CLASS" . :CLASS)
    ("PROCEDURE" . :PROCEDURE)
    ("END" . :END)
    ("WHILE" . :WHILE)
    ("UNTIL" . :UNTIL)
    ("DO" . :DO)
    ("LIBRARY" . :LIBRARY)
    ("AND" . :AND)
    ("OR" . :OR)
    ("NOT" . :NOT))
  "Association list of BASIC keywords to token symbols.")

(defparameter *basic-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("=" . :EQUAL)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE)
    ("<>" . :NE)
    ("." . :DOT))
  "Association list of BASIC operators to token symbols.")

(defun basic-token-type (lexeme)
  "Return token type for LEXEME, a string."
  (cond
    ((and (stringp lexeme) (digit-char-p (char lexeme 0)))
     :NUMBER)
((and (stringp lexeme) (char= (char lexeme 0) #\"))
      :STRING)
    ((assoc lexeme *basic-keyword-alist* :test #'string-equal)
      (cdr (assoc lexeme *basic-keyword-alist* :test #'string-equal)))
    ((assoc lexeme *basic-operators-alist* :test #'string-equal)
      (cdr (assoc lexeme *basic-operators-alist* :test #'string-equal)))
    ((string= lexeme "(") :lparen)
    ((string= lexeme ")") :rparen)
    ((string= lexeme ",") :comma)
    ((string= lexeme ":") :colon)
    ((basic-valid-identifier-p lexeme) :ident)
    (t :unknown)))

(defun basic-valid-identifier-p (s)
  "Check if S is a valid PascalCase alphanumeric BASIC identifier."
  (and (stringp s)
       (plusp (length s))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\$) (char= c #\_)))
              s)))

(defun basic-lex-line (line)
  "Split LINE into token list of (type value) pairs.
Handles quoted strings, operators, and identifiers."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (skip-whitespace ()
               (loop while (and (not (eof?)) (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (flush-token (start end type)
               (let ((text (coerce (subseq chars start end) 'string)))
                 (unless (zerop (length text))
                   (push (cons type text) tokens))))
             (scan-number (start)
               (loop while (and (not (eof?)) (digit-char-p (peek)))
                     do (next-char))
               (flush-token start (1- i) :number))
             (scan-string (start)
               (next-char) ; skip opening quote
               (loop while (and (not (eof?)) (char/= (peek) #\"))
                     do (next-char))
               (when (not (eof?)) (next-char)) ; skip closing quote
               (flush-token (1+ start) (1- i) :string))
             (scan-identifier (start)
               (loop while (and (not (eof?))
                                (or (alphanumericp (peek))
                                    (char= (peek) #\$)
                                    (char= (peek) #\_)))
                     do (next-char))
               (flush-token start (1- i) :ident)))
      (loop until (eof?)
            do (skip-whitespace)
               (cond
                 ((eof?) (return))
                 ((char= (peek) #\") (scan-string i))
                 ((digit-char-p (peek)) (scan-number i))
                 ((or (alphanumericp (peek))
                      (char= (peek) #\$)
                      (char= (peek) #\_)) (scan-identifier i))
                 (t
                  (let ((op1 (string (next-char)))
                        (op2 (when (not (eof?)) (string (peek)))))
                    (cond
                      ((and op2 (string= op2 "=")
                            (member (concatenate 'string op1 op2) '("=<" ">=" "<>")
                                    :test #'string-equal))
                       (next-char) ; consume second char
                       (flush-token (1- i) i :op))
                      (t
                       (flush-token (1- i) i :op)))))))
      (nreverse tokens))))

(defun basic-lex-source (source)
  "Lex complete BASIC SOURCE string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (or (zerop (length trimmed))
                    (char= #\; (char trimmed 0))
                    (char= #\' (char trimmed 0)))
          (setf all-tokens (nconc all-tokens (basic-lex-line trimmed))))))
    all-tokens))

(defun basic-parse-line-prefix (tokens)
  "Parse line number and optional quoted label from start of TOKENS.
Returns (values line-number label remaining-tokens)."
  (let ((lineno nil)
        (label nil))
    (when (and tokens (eq (first (first tokens)) :number))
      (setf lineno (second (first tokens)))
      (setf tokens (rest tokens))
      (when (and tokens (eq (first (first tokens)) :string))
        (setf label (second (first tokens)))
        (setf tokens (rest tokens))
        (when (and tokens (eq (first (first tokens)) :colon))
          (setf tokens (rest tokens)))))
    (values lineno label tokens)))

