(defun count-parens-to-line (filename target-line)
  (with-open-file (stream filename :direction :input)
    (let ((open 0) (close 0) (line-num 1) char)
      (loop while (and (setq char (read-char stream nil nil))
                       (< line-num target-line))
            do (when (char= char #\Newline)
                 (incf line-num))
               (cond ((char= char #\() (incf open))
                     ((char= char #\)) (incf close)))))
      (values open close (- open close))))

(let* ((open 0) (close 0) (diff 0))
  (multiple-value-bind (o c d)
      (count-parens-to-line "src/frontend-fortran/fortran-lexer.lisp" 116)
    (setf open o close c diff d)
    (format t "Up to line 116: Open: ~a, Close: ~a, Diff: ~a~%" open close diff)))
