(defun count-parens-to-line (filename target-line)
  (with-open-file (stream filename :direction :input)
    (let ((open 0) (close 0) (line-num 1) char)
      (loop while (and (setq char (read-char stream nil nil))
                       (< line-num target-line))
            do (when (char= char #\Newline)
                 (incf line-num))
               (cond ((char= char #\() (incf open))
                     ((char= char #\)) (incf close)))))
      (values open close (- open close))))

(let ((lines '(10 20 30 40 50 60 70 80 90 100 110 115 116 117 118 119 120 130 140 150 160 170 180 190 200)))
  (format t "Line~10sOpen~8sClose~8sDiff~8sChange~%")
  (let ((prev-diff 0))
    (dolist (line lines)
      (multiple-value-bind (open close diff)
          (count-parens-to-line "src/frontend-fortran/fortran-lexer.lisp" line)
        (format t "~10d~8d~8d~8d~8d~%" line open close diff (- diff prev-diff))
        (setf prev-diff diff)))))
