(load "~/quicklisp/setup.lisp")
(ql:quickload :cl-change-case)
(ql:quickload :serapeum)
(ql:quickload :yacc)
(ql:quickload :alexandria)
(ql:quickload :unix-opts)
(load "src/package.lisp")
(load "src/grammar-build.lisp")
(in-package :eightbol)
(defun test-constructors ()
  (let* ((add (make-expression-add (make-identifier "A")
                                   (make-identifier "B")))
         (sub (make-expression-subtract (make-identifier "C")
                                        (make-identifier "D")))
         (mul (make-expression-multiply (make-identifier "E")
                                        (make-identifier "F")))
         (div (make-expression-divide (make-identifier "G")
                                      (make-identifier "H"))))
    (format t "Constructor functions work.~%")))
(test-constructors)
