;; src/frontend-agi/agi-lexer.lisp — Tokenization for AGI language
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *agi-keyword-alist*
  '(("IF" . :IF)
    ("ELSE" . :ELSE)
    ("THEN" . :THEN)
    ("GOSUB" . :GOSUB)
    ("GOTO" . :GOTO)
    ("NEWROOM" . :NEWROOM)
    ("LOADLOGICS" . :LOADLOGICS)
    ("RETURN" . :RETURN)
    ("QUIT" . :QUIT)
    ("ASSIGN" . :ASSIGN)
    ("INCREMENT" . :INCREMENT)
    ("DECREMENT" . :DECREMENT)
    ("SET" . :SET)
    ("RESET" . :RESET)
    ("SAID" . :SAID)
    ("TEST" . :TEST)
    ("POSN" . :POSN)
    ("CONTROLLER" . :CONTROLLER)
    ("HAVEKEY" . :HAVEKEY)
    ("AND" . :AND)
    ("OR" . :OR))
  "Association list of AGI keywords to token symbols.")

(defparameter *agi-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("=" . :EQUAL)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE)
    ("<>" . :NE)
    ("<<" . :LSHIFT)
    (">>" . :RSHIFT)
    ("." . :DOT))
  "Association list of AGI operators to token symbols.")

(defun agi-valid-identifier-p (s)
  "Check if S is a valid AGI identifier."
  (and (stringp s)
       (plusp (length s))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\$) (char= c #\_)))
              s)))

(defun agi-lex-line (line)
  "Tokenize an AGI source line into (token-type . lexeme) pairs."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (skip-whitespace ()
               (loop while (and (not (eof?)) (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (scan-number (start)
               (loop while (and (not (eof?)) (digit-char-p (peek)))
                     do (next-char))
               (let ((text (coerce (subseq chars start i) 'string)))
                 (push (cons :number text) tokens)))
             (scan-string (start)
               (next-char) ; skip opening quote
               (loop while (and (not (eof?)) (char/= (peek) #\"))
                     do (next-char))
               (when (not (eof?)) (next-char)) ; skip closing quote
               (let ((text (coerce (subseq chars (1+ start) (1- i)) 'string)))
                 (push (cons :string text) tokens)))
             (scan-identifier (start)
               (loop while (and (not (eof?)) (or (alphanumericp (peek)) (char= (peek) #\_)))
                     do (next-char))
               (let ((text (coerce (subseq chars start i) 'string))
                     (upper-text (string-upcase (coerce (subseq chars start i) 'string))))
                 (let ((keyword (assoc upper-text *agi-keyword-alist* :test #'string-equal)))
                   (if keyword
                       (push (cons (cdr keyword) text) tokens)
                       (push (cons :ident text) tokens)))))
             (scan-operator ()
               (let ((c1 (peek)))
                 (cond
                   ((eof?) nil)
                   ((and (not (eof?)) (< (1+ i) (length chars))
                         (or (and (char= c1 #\<) (char= (nth (1+ i) chars) #\=))
                             (and (char= c1 #\>) (char= (nth (1+ i) chars) #\=))
                             (and (char= c1 #\<) (char= (nth (1+ i) chars) #\>))
                             (and (char= c1 #\<) (char= (nth (1+ i) chars) #\<))
                             (and (char= c1 #\>) (char= (nth (1+ i) chars) #\>))))
                    (let ((op (coerce (list c1 (nth (1+ i) chars)) 'string)))
                      (next-char) (next-char)
                      (let ((kw (assoc op *agi-operators-alist* :test #'string-equal)))
                        (when kw (push (cons (cdr kw) op) tokens)))))
                   (t
                    (let ((op (coerce (list c1) 'string)))
                      (next-char)
                      (let ((kw (assoc op *agi-operators-alist* :test #'string-equal)))
                        (cond
                          (kw (push (cons (cdr kw) op) tokens))
                          ((char= c1 #\() (push (cons :lparen "(") tokens))
                          ((char= c1 #\)) (push (cons :rparen ")") tokens))
                          ((char= c1 #\,) (push (cons :comma ",") tokens))
                          ((char= c1 #\:) (push (cons :colon ":") tokens))))))))))
      (loop until (eof?) do
        (skip-whitespace)
        (unless (eof?)
          (let ((c (peek)))
            (cond
              ((digit-char-p c) (scan-number i))
              ((char= c #\") (scan-string i))
              ((or (alpha-char-p c) (char= c #\_)) (scan-identifier i))
              (t (scan-operator))))))
      (nreverse tokens))))