;; src/backend-m6800.lisp — Motorola 6800 code generation backend
;;
;; Minimal m6800 emitter intended for Vectrex-style Motorola-family workflows.
;; Uses plain 6800-like mnemonics (LDAA/STAA/CMPA/BEQ/BNE/JSR/JMP/RTS) and
;; direct symbols for generated labels.
(in-package :eightbol)

(defvar *output-stream* nil)

(defun m6800-symbol (name)
  "Convert EIGHTBOL identifier to m6800 assembly symbol (PascalCase)."
  (pascal-case (format nil "~a" name)))

;;; def-m6800-statement macro — compiles through the generic compile-statement

(defmacro def-m6800-statement (statement-type &body body)
  `(defmethod compile-statement ((cpu (eql :m6800)) (statement-type (eql ,statement-type)) ast-node-data)
     (let ((statement (cons statement-type ast-node-data)))
       ,@body)))

;;; Top-level entry point

(defmethod compile-to-assembly (ast (cpu (eql :m6800)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/m6800: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table
                          pic-size-table pic-width-table pic-frac-bits-table pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (let ((*output-stream* output-stream)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*service-bank-table* service-bank-table)
            (*usage-table* usage-table)
            (*sign-table* sign-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table)
            (*pic-frac-bits-table* pic-frac-bits-table)
            (*pic-nybble-semantics-table* pic-nybble-semantics-table))
        (format output-stream
                "; ~a -- generated by EIGHTBOL for m6800~%; DO NOT EDIT -- regenerate from ~a.cob~2%"
                class-id class-id)
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-m6800-method method)))))))

;;; Method compilation

(defun compile-m6800-method (method)
  (let ((*method-id* (getf (rest method) :method-id)))
    (declare (special *method-id*))
    (let* ((method-id *method-id*)
           (dispatch-label (format nil "Method~a~a"
                                   (m6800-symbol *class-id*)
                                   (m6800-symbol (format nil "~a" method-id))))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                        (getf (rest method) :statements))))
           (stmts (nth-value 1 (split-method-leading-assembly-entry
                                 (getf (rest method) :statements)))))
      (if custom-entry
          (progn
            (format *output-stream* "~&~%~a:" (m6800-symbol custom-entry))
            (format *output-stream* "~&~a:" dispatch-label))
          (format *output-stream* "~&~%~a:" dispatch-label))
      (dolist (stmt stmts)
        (compile-statement :m6800 (first stmt) (rest stmt)))
      (format *output-stream* "~&~8tRTS"))))

;;; Expression / value emission

(defun compile-m6800-load-a (expression &optional (width (operand-width expression)))
  (declare (ignore width))
  (cond
    ((numberp expression)
     (format *output-stream* "~&~8tLDAA    #~d" expression))
    ((and (stringp expression) (constant-p expression))
     (format *output-stream* "~&~8tLDAA    #~d" (constant-value expression)))
    ((stringp expression)
     (format *output-stream* "~&~8tLDAA    ~a" (bare-data-assembly-symbol expression *class-id*)))
    ((and (listp expression) (eq (first expression) :of))
     (let ((slot (second expression)) (obj (third expression)))
       (if (member obj '(:self "Self" self) :test #'equal)
           (progn
             (format *output-stream* "~&~8tLDX     Self")
             (format *output-stream* "~&~8tLDAA    ~a,X" (slot-symbol slot *class-id*)))
           (format *output-stream* "~&~8t; Unsupported OF target ~s for m6800 load" obj))))
    (t
     (format *output-stream* "~&~8t; Unsupported load ~s for m6800" expression)
     (format *output-stream* "~&~8tLDAA    #0"))))

(defun compile-m6800-store-a (destination)
  (cond
    ((stringp destination)
     (format *output-stream* "~&~8tSTAA    ~a" (bare-data-assembly-symbol destination *class-id*)))
    ((and (listp destination) (eq (first destination) :of))
     (let ((slot (second destination)) (obj (third destination)))
       (if (member obj '(:self "Self" self) :test #'equal)
           (progn
             (format *output-stream* "~&~8tLDX     Self")
             (format *output-stream* "~&~8tSTAA    ~a,X" (slot-symbol slot *class-id*)))
           (format *output-stream* "~&~8t; Unsupported OF target ~s for m6800 store" obj))))
    (t
     (format *output-stream* "~&~8t; Unsupported store ~s for m6800" destination))))

;;; Labels

(defvar *m6800-label-counter* 0)

(defun m6800-label (prefix)
  (format nil "L~a~d" prefix (incf *m6800-label-counter*)))

;;; Condition compilation

(defun compile-m6800-condition (condition false-label)
  (cond
    ((and (listp condition) (member (first condition) '(= equal) :test #'eq))
     (compile-m6800-load-a (second condition))
     (format *output-stream* "~&~8tTAB")
     (compile-m6800-load-a (third condition))
     (format *output-stream* "~&~8tCBA")
     (format *output-stream* "~&~8tBNE     ~a" false-label))
    ((and (listp condition) (eq (first condition) :is-zero))
     (compile-m6800-load-a (second condition))
     (format *output-stream* "~&~8tBNE     ~a" false-label))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (compile-m6800-load-a (second condition))
     (format *output-stream* "~&~8tBEQ     ~a" false-label))
    (t
     (format *output-stream* "~&~8t; Unsupported condition ~s for m6800" condition)
     (format *output-stream* "~&~8tJMP     ~a" false-label))))

;;; Statement dispatch — :around method for source comments

(defmethod compile-statement :around ((cpu (eql :m6800)) stmt-type ast-node-data)
  (emit-statement-source-comment *output-stream* (cons stmt-type ast-node-data))
  (call-next-method))

;;; Individual statement methods

(def-m6800-statement :goback
  (format *output-stream* "~&~8tRTS"))

(def-m6800-statement :exit-method
  (format *output-stream* "~&~8tRTS"))

(def-m6800-statement :exit-program
  (format *output-stream* "~&~8tRTS"))

(def-m6800-statement :exit
  (format *output-stream* "~&~8tRTS"))

(def-m6800-statement :stop-run
  (format *output-stream* "~&~8tRTS"))

(def-m6800-statement :move
  (compile-m6800-load-a (getf statement :from))
  (compile-m6800-store-a (getf statement :to)))

(def-m6800-statement :set
  (compile-m6800-load-a (getf statement :value))
  (compile-m6800-store-a (getf statement :target)))

(def-m6800-statement :if
  (let ((false-label (m6800-label "IfFalse"))
        (end-label (m6800-label "IfEnd"))
        (then-stmts (ensure-list (getf statement :then)))
        (else-stmts (ensure-list (getf statement :else))))
    (compile-m6800-condition (getf statement :condition) false-label)
    (dolist (s then-stmts)
      (compile-statement :m6800 (first s) (rest s)))
    (when else-stmts
      (format *output-stream* "~&~8tJMP     ~a" end-label))
    (format *output-stream* "~&~a:" false-label)
    (dolist (s else-stmts)
      (compile-statement :m6800 (first s) (rest s)))
    (when else-stmts
      (format *output-stream* "~&~a:" end-label))))

(def-m6800-statement :call
  (let ((target (or (getf statement :service) (getf statement :target) "UnknownCall")))
    (format *output-stream* "~&~8tJSR     ~a" (m6800-symbol target))))

(def-m6800-statement :invoke
  (let ((method (or (getf statement :method) "UnknownMethod")))
    (format *output-stream* "~&~8tJSR     Invoke~a~a"
            (m6800-symbol *class-id*)
            (m6800-symbol method))))

(def-m6800-statement :goto
  (let ((target (or (getf statement :target) (first (getf statement :targets)))))
    (format *output-stream* "~&~8tJMP     ~a" (m6800-symbol target))))

(def-m6800-statement :paragraph
  (let ((name (first ast-node-data)))
    (when name
      (format *output-stream* "~&~a:" (m6800-symbol (format nil "~a" name))))))

(def-m6800-statement :add
  (let* ((to (getf statement :to))
         (from (getf statement :from))
         (result (or (getf statement :giving) to))
         (bcd-p (when result (usage-bcd-p result))))
    (assert-pic-decimal-add-compiled :m6800 statement)
    (compile-m6800-load-a to)
    (format *output-stream* "~&~8tTAB")
    (compile-m6800-load-a from)
    (format *output-stream* "~&~8tABA")
    (when bcd-p
      (let ((ok1 (m6800-label "ad1")) (ok2 (m6800-label "ad2")))
        (format *output-stream* "~&~8tTAB")
        (format *output-stream* "~&~8tANDA    #$0F")
        (format *output-stream* "~&~8tCMPA    #10")
        (format *output-stream* "~&~8tBLO     ~a" ok1)
        (format *output-stream* "~&~8tLDAA    B")
        (format *output-stream* "~&~8tADDA    #6")
        (format *output-stream* "~&~8tTAB")
        (format *output-stream* "~&~a:" ok1)
        (format *output-stream* "~&~8tLDAA    B")
        (format *output-stream* "~&~8tANDA    #$F0")
        (format *output-stream* "~&~8tCMPA    #$A0")
        (format *output-stream* "~&~8tBLO     ~a" ok2)
        (format *output-stream* "~&~8tLDAA    B")
        (format *output-stream* "~&~8tADDA    #$60")
        (format *output-stream* "~&~8tTAB")
        (format *output-stream* "~&~a:" ok2)
        (format *output-stream* "~&~8tLDAA    B")))
    (compile-m6800-store-a result)))

(def-m6800-statement :subtract
  (assert-pic-decimal-subtract-compiled :m6800 statement)
  (multiple-value-bind (minuend subtrahend)
      (subtract-statement-minuend-and-subtrahend statement)
    (let* ((result (or (getf statement :giving) minuend))
           (bcd-p (when result (usage-bcd-p result))))
      (compile-m6800-load-a minuend)
      (format *output-stream* "~&~8tTAB")
      (compile-m6800-load-a subtrahend)
      (format *output-stream* "~&~8tSBA")
      (when bcd-p
        (let ((ok1 (m6800-label "sb1")) (ok2 (m6800-label "sb2")))
          (format *output-stream* "~&~8tTAB")
          (format *output-stream* "~&~8tANDA    #$0F")
          (format *output-stream* "~&~8tCMPA    #10")
          (format *output-stream* "~&~8tBLO     ~a" ok1)
          (format *output-stream* "~&~8tLDAA    B")
          (format *output-stream* "~&~8tSUBA    #6")
          (format *output-stream* "~&~8tTAB")
          (format *output-stream* "~&~a:" ok1)
          (format *output-stream* "~&~8tLDAA    B")
          (format *output-stream* "~&~8tANDA    #$F0")
          (format *output-stream* "~&~8tCMPA    #$A0")
          (format *output-stream* "~&~8tBLO     ~a" ok2)
          (format *output-stream* "~&~8tLDAA    B")
          (format *output-stream* "~&~8tSUBA    #$60")
          (format *output-stream* "~&~8tTAB")
          (format *output-stream* "~&~a:" ok2)
          (format *output-stream* "~&~8tLDAA    B")))
      (compile-m6800-store-a result))))

(def-m6800-statement :compute
  (compile-m6800-load-a (getf statement :expression))
  (compile-m6800-store-a (getf statement :target)))

(def-m6800-statement :perform
  (format *output-stream* "~&~8t; PERFORM not yet implemented for m6800"))

(def-m6800-statement :evaluate
  (format *output-stream* "~&~8t; EVALUATE not yet implemented for m6800"))

(def-m6800-statement :inspect
  (format *output-stream* "~&~8t; INSPECT not yet implemented for m6800"))

(def-m6800-statement :string-blt
  (format *output-stream* "~&~8t; STRING BLT not yet implemented for m6800"))

(def-m6800-statement :log-fault
  (format *output-stream* "~&~8t; LOG FAULT ~s" (getf statement :code)))

(def-m6800-statement :debug-break
  (format *output-stream* "~&~8t; DEBUG BREAK ~s" (getf statement :code)))

(def-m6800-statement :divide
  (let* ((divisor (getf statement :divisor))
         (into (getf statement :into))
         (by (getf statement :by))
         (source (or by into))
         (dest (or (getf statement :giving) into))
         (signed (operand-signed-p (or source dest))))
    (if (and (expression-constant-p divisor)
             (power-of-two-p (expression-constant-value divisor)))
        (let ((shift (log2 (expression-constant-value divisor))))
          (when (or (operand-bcd-p source) (operand-bcd-p dest))
            (error 'source-error
                   :message "DIVIDE: cannot use with USAGE DECIMAL operands"
                   :detail (list :divisor divisor :source source :dest dest)))
          (unless (zerop shift)
            (compile-m6800-load-a (or source dest))
            (dotimes (_ shift)
              (if signed (format *output-stream* "~&~8tASRA") (format *output-stream* "~&~8tLSRA")))
            (compile-m6800-store-a dest)))
        (error 'source-error
               :message "DIVIDE: divisor must be constant power-of-two (1, 2, 4, 8, ...)"
               :detail (format nil "DIVIDE by ~s" divisor)))))

(def-m6800-statement :multiply
  (let* ((multiplier (getf statement :multiplier))
         (by (getf statement :by))
         (giving (getf statement :giving))
         (source (or giving by))
         (dest (or giving by)))
    (if (and (expression-constant-p multiplier)
             (power-of-two-p (expression-constant-value multiplier)))
        (let ((shift (log2 (expression-constant-value multiplier))))
          (when (or (operand-bcd-p source) (operand-bcd-p dest))
            (error 'source-error
                   :message "MULTIPLY: cannot use with USAGE DECIMAL operands"
                   :detail (list :multiplier multiplier :source source :dest dest)))
          (unless (zerop shift)
            (compile-m6800-load-a (or source dest))
            (dotimes (_ shift)
              (format *output-stream* "~&~8tASLA"))
            (compile-m6800-store-a dest)))
        (error 'source-error
               :message "MULTIPLY: multiplier must be constant power-of-two (1, 2, 4, 8, ...)"
               :detail (format nil "MULTIPLY by ~s" multiplier)))))

(def-m6800-statement :comment
  (format *output-stream* "~&~8t; ~a"
          (let ((text (first ast-node-data)))
            (if (listp text)
                (format nil "~{~a~%~8t; ~}" (mapcar (lambda (s) (if (stringp s) s (princ-to-string s))) text))
                (princ-to-string text)))))

(def-m6800-statement :invoke-super
  (unless (gethash *class-id* *parent-classes*)
    (load-classes))
  (if-let (parent-class (gethash *class-id* *parent-classes*))
    (format *output-stream* "~&~8tJSR     Method~a~a"
            (m6800-symbol parent-class)
            (m6800-symbol (format nil "~a" *method-id*)))
    (error "Can't figure out parent class of ~a" *class-id*)))

(def-m6800-statement :shift-left
  (let* ((target (getf statement :target))
         (count (getf statement :count 1)))
    (compile-m6800-load-a target)
    (dotimes (_ count)
      (format *output-stream* "~&~8tASLA"))
    (compile-m6800-store-a target)))

(def-m6800-statement :shift-right
  (let* ((target (getf statement :target))
         (count (getf statement :count 1))
         (signed (operand-signed-p target)))
    (compile-m6800-load-a target)
    (dotimes (_ count)
      (if signed
          (format *output-stream* "~&~8tASRA")
          (format *output-stream* "~&~8tLSRA")))
    (compile-m6800-store-a target)))

(def-m6800-statement :copy
  (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
         (getf statement :name)))
