;; src/frontend-garry/garry-lexer.lisp — Tokenization for Garry Kitchen's GameMaker language
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *garry-keyword-alist*
  '(("EVENT" . :event)
    ("IF" . :if)
    ("THEN" . :then)
    ("ELSE" . :else)
    ("ENDIF" . :endif)
    ("FOR" . :for)
    ("TO" . :to)
    ("STEP" . :step)
    ("NEXT" . :next)
    ("WHILE" . :while)
    ("WEND" . :wend)
    ("DO" . :do)
    ("LOOP" . :loop)
    ("GOTO" . :goto)
    ("GOSUB" . :gosub)
    ("RETURN" . :return)
    ("END" . :end)
    ("REM" . :rem)
    ("PRINT" . :print)
    ("INPUT" . :input)
    ("LET" . :let)
    ("SET" . :set)
    ("MOVE" . :move)
    ("DRAW" . :draw)
    ("SPRITE" . :sprite)
    ("BACKGROUND" . :background)
    ("SOUND" . :sound)
    ("WAIT" . :wait)
    ("CLS" . :cls)
    ("COLOR" . :color)
    ("PLOT" . :plot)
    ("LINE" . :line)
    ("CIRCLE" . :circle)
    ("TEXT" . :text)
    ("VAR" . :var)
    ("DIM" . :dim)
    ("AS" . :as)
    ("INT" . :int)
    ("STRING" . :string)
    ("FLOAT" . :float)
    ("AND" . :and)
    ("OR" . :or)
    ("NOT" . :not)
    ("GOTO" . :goto))
  "Association list of Garry GameMaker keywords to token symbols.")

(defparameter *garry-operators-alist*
  '(("+" . :plus)
    ("-" . :minus)
    ("*" . :times)
    ("/" . :divide)
    ("=" . :equal)
    ("<>" . :ne)
    ("<" . :lt)
    (">" . :gt)
    ("<=" . :le)
    (">=" . :ge)
    ("(" . :lparen)
    (")" . :rparen)
    ("," . :comma)
    (":" . :colon)
    (";" . :semicolon))
  "Association list of Garry operators to token symbols.")

(defun garry-normalize-identifier (s)
  "Normalize identifier S for comparison (Garry is case-insensitive)."
  (string-upcase s))

(defun garry-valid-identifier-p (s)
  "Check if S is a valid Garry identifier."
  (and (stringp s)
       (plusp (length s))
       (or (alpha-char-p (char s 0)) (char= (char s 0) #\_))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\_)))
              s)))

(defun garry-parse-number-literal (text)
  "Parse a number literal TEXT in decimal or hex format."
  (cond
    ((cl-ppcre:scan "^(?:&h|#x|0x)[0-9a-fA-F]+$" text)
     (let* ((hex-str (cl-ppcre:register-groups-bind (h) ("^(?:&h|#x|0x)([0-9a-fA-F]+)$" text) h)))
       (values (parse-integer hex-str :radix 16) :number)))
    ((cl-ppcre:scan "^(?:&o|#o|0o)[0-7]+$" text)
     (let* ((oct-str (cl-ppcre:register-groups-bind (o) ("^(?:&o|#o|0o)([0-7]+)$" text) o)))
       (values (parse-integer oct-str :radix 8) :number)))
    ((cl-ppcre:scan "^-?\\d+$" text)
     (values (parse-integer text) :number))
    (t (error "Invalid number literal: ~A" text))))

(defun garry-lex-line (line)
  "Split LINE into token list of (type value) pairs."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (peek-ahead (n) (nth (+ i n) chars))
             (flush-token (start end type)
               (let ((text (coerce (subseq chars start end) 'string)))
                 (unless (zerop (length text))
                   (push (cons type text) tokens))))
             (skip-whitespace ()
               (loop while (and (not (eof?)) (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (scan-number-literal (start)
               (loop while (and (not (eof?))
                                (or (digit-char-p (peek))
                                    (char= (peek) #\.)
                                    (and (char= (peek) #\#)
                                         (or (char= (peek-ahead 1) #\x) (char= (peek-ahead 1) #\o)))
                                    (and (char= (peek) #\&)
                                         (or (char= (peek-ahead 1) #\h) (char= (peek-ahead 1) #\o)))))
                     do (next-char))
               (let ((text (coerce (subseq chars start i) 'string)))
                 (handler-case
                     (multiple-value-bind (value type) (garry-parse-number-literal text)
                       (push (cons type (format nil "~A" value)) tokens))
                   (error (c)
                     (warn "Failed to parse number literal ~A: ~A" text c)
                     (flush-token start i :number)))))
             (scan-string (start)
               (next-char)
               (loop while (and (not (eof?)) (char/= (peek) #\"))
                     do (next-char))
               (when (not (eof?)) (next-char))
               (flush-token (1+ start) (1- i) :string))
             (scan-atom (start)
               (loop while (and (not (eof?))
                                (or (alphanumericp (peek))
                                    (char= (peek) #\_)
                                    (char= (peek) #\$)))
                     do (next-char))
               (let* ((text (coerce (subseq chars start i) 'string))
                      (normalized (garry-normalize-identifier text)))
                 (push (cons (or (cdr (assoc normalized *garry-keyword-alist* :test #'string-equal))
                                 :atom)
                             normalized)
                       tokens)))
             (scan-operator (start)
               (let ((one (char start 0))
                     (two (and (< (+ i 1) (length chars))
                               (format nil "~A~A" (peek) (peek-ahead 1)))))
                 (cond
                   ((and two (member two '("<>" "<=" ">=") :test #'string=))
                    (incf i) (incf i)
                    (push (cons (cdr (assoc two *garry-operators-alist* :test #'string=)) two) tokens))
                   (t
                    (incf i)
                    (push (cons (cdr (assoc (string one) *garry-operators-alist* :test #'string=))
                                (string one))
                          tokens)))))
             (scan-line ()
               (skip-whitespace)
               (loop until (eof?)
                     do (cond
                          ((or (char= (peek) #\") (char= (peek) #\apostrophe)) (scan-string i))
                          ((digit-char-p (peek)) (scan-number-literal i))
                          ((or (alpha-char-p (peek)) (char= (peek) #\_)) (scan-atom i))
                          (t (scan-operator i))))))
      (scan-line)))
  (nreverse tokens))

(defun garry-lex-source (source)
  "Lex complete Garry source string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (or (zerop (length trimmed))
                    (string= "REM" (subseq trimmed 0 (min 3 (length trimmed)))))
          (setf all-tokens (nconc all-tokens (garry-lex-line trimmed))))))
    all-tokens))
