;; src/frontend-zil/zil-lexer.lisp — Tokenization for ZIL
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *zil-keyword-alist*
  '(("<IF>" . :IF)
    ("<ELSE>" . :ELSE)
    ("<THEN>" . :THEN)
    ("<WHILE>" . :WHILE)
    ("<FOR>" . :FOR)
    ("<BREAK>" . :BREAK)
    ("<CONTINUE>" . :CONTINUE)
    ("<RETURN>" . :RETURN)
    ("<DEFINE>" . :DEFINE)
    ("<SET>" . :SET)
    ("<SETG>" . :SETG)
    ("<GET>" . :GET)
    ("<PUT>" . :PUT)
    ("<CALL>" . :CALL)
    ("<GO>" . :GO)
    ("<EXIT>" . :EXIT)
    ("<LABEL>" . :LABEL)
    ("<ASSERT>" . :ASSERT)
    ("<WAIT>" . :WAIT)
    ("<STOP>" . :STOP)
    ("<START>" . :START)
    ("<FADE>" . :FADE)
    ("<RESTORE>" . :RESTORE)
    ("<SAVE>" . :SAVE)
    ("<RESTART>" . :RESTART)
    ("<VERSION>" . :VERSION)
    ("<OBJECT>" . :OBJECT)
    ("<PROPERTY>" . :PROPERTY)
    ("<GLOBAL>" . :GLOBAL)
    ("<LOCAL>" . :LOCAL)
    ("<P>" . :PROPACCESS))
  "Association list of ZIL keywords to token symbols.")

(defparameter *zil-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("=" . :EQUAL)
    ("<>" . :NE)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE)
    ("AND" . :AND)
    ("OR" . :OR)
    ("NOT" . :NOT))
  "Association list of ZIL operators to token symbols.")

(defun zil-valid-identifier-p (s)
  "Check if S is a valid ZIL identifier (case-insensitive with hyphens)."
  (and (stringp s)
       (plusp (length s))
       (or (alpha-char-p (char s 0))
           (char= (char s 0) #\-))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\-) (char= c #\_) (char= c #\?)))
              s)))

(defun zil-lex-line (line)
  "Split LINE into token list of (type value) pairs."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (flet ((peek () (nth i chars))
           (next-char () (prog1 (nth i chars) (incf i)))
           (eof? () (>= i (length chars)))
           (flush-token (start end type)
             (let ((text (coerce (subseq chars start end) 'string)))
               (unless (zerop (length text))
                 (push (cons type text) tokens)))))
      (labels ((skip-whitespace ()
                 (loop while (and (not (eof?)) (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                       do (next-char)))
               (scan-number (start)
                 (loop while (and (not (eof?)) (digit-char-p (peek)))
                       do (next-char))
                 (flush-token start i :number))
               (scan-string (start)
                 (next-char)
                 (loop while (and (not (eof?)) (char/= (peek) #\"))
                       do (next-char))
                 (when (not (eof?)) (next-char))
                 (flush-token (1+ start) (1- i) :string))
               (scan-atom (start)
                 (loop while (and (not (eof?))
                                  (or (alphanumericp (peek))
                                      (char= (peek) #\-)
                                      (char= (peek) #\_)
                                      (char= (peek) #\?)))
                       do (next-char))
                 (let ((text (coerce (subseq chars start i) 'string)))
                   (push (cons (or (cdr (assoc text *zil-keyword-alist* :test #'string-equal))
                                   :atom)
                               text)
                         tokens))))
        (loop until (eof?)
              do (skip-whitespace)
                 (cond
                   ((eof?) (return))
                   ((char= (peek) #\") (scan-string i))
                   ((digit-char-p (peek)) (scan-number i))
                   ((or (alpha-char-p (peek))
                        (char= (peek) #\-)
                        (char= (peek) #\_)
                        (char= (peek) #\?)) (scan-atom i))
                   ((char= (peek) #\<)
                    (let ((start i))
                      (next-char)
                      (loop while (and (not (eof?)) (char/= (peek) #\>))
                            do (next-char))
                      (when (not (eof?)) (next-char))
                      (let ((text (coerce (subseq chars start i) 'string)))
                        (push (cons (or (cdr (assoc text *zil-keyword-alist* :test #'string-equal))
                                        :keyword)
                                    text)
                              tokens))))
                   ((char= (peek) #\() (push (cons :lparen "(") tokens) (next-char))
                   ((char= (peek) #\)) (push (cons :rparen ")") tokens) (next-char))
                   ((char= (peek) #\') (push (cons :quote "'") tokens) (next-char))
                   ((char= (peek) #\,) (push (cons :comma ",") tokens) (next-char))
                   (t (next-char))))
        (nreverse tokens)))))

(defun zil-lex-source (source)
  "Lex complete ZIL source string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (zerop (length trimmed))
          (setf all-tokens (nconc all-tokens (zil-lex-line trimmed))))))
    all-tokens))
