;; src/frontend-burgermistress/burger-lexer.lisp — Tokenization for Burgermistress scripting
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *burgermistress-keyword-alist*
  '(("IF" . :IF)
    ("ELSE" . :ELSE)
    ("THEN" . :THEN)
    ("ENDIF" . :ENDIF)
    ("WHILE" . :WHILE)
    ("WEND" . :WEND)
    ("FOR" . :FOR)
    ("TO" . :TO)
    ("STEP" . :STEP)
    ("NEXT" . :NEXT)
    ("DO" . :DO)
    ("LOOP" . :LOOP)
    ("UNTIL" . :UNTIL)
    ("EXIT" . :EXIT)
    ("SUB" . :SUB)
    ("END" . :END)
    ("FUNCTION" . :FUNCTION)
    ("CALL" . :CALL)
    ("RETURN" . :RETURN)
    ("GOSUB" . :GOSUB)
    ("AND" . :AND)
    ("OR" . :OR)
    ("NOT" . :NOT)
    ("DIM" . :DIM)
    ("AS" . :AS)
    ("INTEGER" . :INTEGER)
    ("STRING" . :STRING)
    ("BOOLEAN" . :BOOLEAN)
    ("DOUBLE" . :DOUBLE))
  "Association list of Burgermistress keywords to token symbols.")

(defparameter *burgermistress-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("=" . :EQUAL)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE)
    ("<>" . :NE)
    ("<<" . :LSHIFT)
    (">>" . :RSHIFT)
    ("." . :DOT))
  "Association list of Burgermistress operators to token symbols.")

(defun burgermistress-valid-identifier-p (s)
  "Check if S is a valid Burgermistress identifier (lowerCamelCase or UpperCamelCase)."
  (and (stringp s)
       (plusp (length s))
       (alpha-char-p (char s 0))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\_)))
              s)))

(defun burgermistress-lex-line (line)
  "Split LINE into token list of (type value) pairs."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (skip-whitespace ()
               (loop while (and (not (eof?)) (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (flush-token (start end type)
               (let ((text (coerce (subseq chars start end) 'string)))
                 (unless (zerop (length text))
                   (push (cons type text) tokens))))
             (scan-number (start)
               (loop while (and (not (eof?)) (digit-char-p (peek)))
                     do (next-char))
               (flush-token start i :number))
             (scan-string (start)
               (next-char) ; skip opening quote
               (loop while (and (not (eof?)) (char/= (peek) #\"))
                     do (next-char))
               (when (not (eof?)) (next-char)) ; skip closing quote
               (flush-token (1+ start) (1- i) :string))
              (scan-identifier (start)
                (loop while (and (not (eof?))
                                 (or (alphanumericp (peek))
                                     (char= (peek) #\_)))
                      do (next-char))
                (let ((text (coerce (subseq chars start i) 'string)))
                  (push (cons (or (cdr (assoc text *burgermistress-keyword-alist* :test #'string-equal))
                                  :ident)
                              text)
                        tokens))))
      (loop until (eof?)
            do (skip-whitespace)
               (cond
                 ((eof?) (return))
                 ((char= (peek) #\") (scan-string i))
                 ((digit-char-p (peek)) (scan-number i))
                 ((or (alphanumericp (peek)) (char= (peek) #\_)) (scan-identifier i))
                 (t
                  (let ((op1 (string (next-char)))
                        (op2 (when (not (eof?)) (string (peek)))))
                    (cond
                      ((and op2 (member (concatenate 'string op1 op2) '("<<" ">>" "<=" ">=" "<>")
                                        :test #'string-equal))
                       (next-char)
                       (flush-token (1- i) i :op))
                      (t (flush-token (1- i) i :op)))))))
      (nreverse tokens))))

(defun burgermistress-lex-source (source)
  "Lex complete Burgermistress source string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (or (zerop (length trimmed))
                    (char= #\' (char trimmed 0)))
          (setf all-tokens (nconc all-tokens (burgermistress-lex-line trimmed))))))
    all-tokens))
