;; src/backend-f8.lisp — Fairchild F8 (Channel F) code generation backend
;;
;; Emits Fairchild F8 assembly (Turner/Fairchild mnemonics): A accumulator,
;; DC0 data counter, LM/ST, DCI, LI/AI/CI, LR H/DC0, branches BR/BZ/BNZ/etc.,
;; PI/POP subroutine call/return. 16-bit values use scratch 10 (lo) and 11 (hi).
;; Scratch 6–9 are codegen temps. See also: eightbol-compile +cpu-display-names+.
(in-package :eightbol)

(defvar *output-stream* nil)

(defun f8-symbol (name)
  "Convert EIGHTBOL identifier to F8 assembly symbol (PascalCase). COBOL stabby-case supported."
  (pascal-case (format nil "~a" name)))

(defun %f8-self-pointer-to-dc0 ()
  "*Self at label Self → DC0 (16-bit pointer from memory, little-endian)."
  (format *output-stream* "~&~10tDCI Self")
  (format *output-stream* "~&~10tLM")
  (format *output-stream* "~&~10tLR 10, A")
  (format *output-stream* "~&~10tLM")
  (format *output-stream* "~&~10tLR 11, A")
  (format *output-stream* "~&~10tLR H, DC0"))

(defun %f8-dc0-add-slot-offset (slot-name)
  "Add slot byte offset (symbol) to DC0 via LI + ADC."
  (format *output-stream* "~&~10tLI ~a" (slot-symbol slot-name *class-id*))
  (format *output-stream* "~&~10tADC"))

(defun %f8-dc0-to-10-11 ()
  "Copy 16-bit DC0 into scratch 10 (lo) and 11 (hi) via @code{LR DC0, H} (Turner F8 manual)."
  (format *output-stream* "~&~10tLR DC0, H"))

(defun %f8-load-byte-at-dc0 ()
  (format *output-stream* "~&~10tLM"))

(defun %f8-store-a-via-dc0 ()
  (format *output-stream* "~&~10tST"))

(defun %f8-dc0-bump-by-count (count-register loop-label done-label)
  "Add 1 to DC0 COUNT-REGISTER times (COUNT-REGISTER must be scratch 0..11)."
  (format *output-stream* "~&~a:" loop-label)
  (format *output-stream* "~&~10tLR A, ~d" count-register)
  (format *output-stream* "~&~10tCI 0")
  (format *output-stream* "~&~10tBZ ~a" done-label)
  (format *output-stream* "~&~10tDS ~d" count-register)
  (format *output-stream* "~&~10tLI 1")
  (format *output-stream* "~&~10tADC")
  (format *output-stream* "~&~10tBR ~a" loop-label)
  (format *output-stream* "~&~a:" done-label))

;;; def-f8-statement macro — compiles through the generic compile-statement

(defmacro def-f8-statement (statement-type &body body)
  `(defmethod compile-statement ((cpu (eql :f8)) (statement-type (eql ,statement-type)) ast-node-data)
     (let ((statement (cons statement-type ast-node-data)))
       (declare (ignorable statement))
       ,@body)))

;;; Top-level entry point

(defmethod compile-to-assembly (ast (cpu (eql :f8)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/F8: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table
                          usage-table sign-table pic-size-table
                          pic-width-table pic-frac-bits-table
                          pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (declare (ignore service-bank-table))
      (let ((*output-stream* output-stream)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*usage-table* usage-table)
            (*sign-table* sign-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table)
            (*pic-frac-bits-table* pic-frac-bits-table)
            (*pic-nybble-semantics-table* pic-nybble-semantics-table))
        (format output-stream
                ";;; ~a -- generated by EIGHTBOL for F8 (Channel F)
;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
                class-id class-id)
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-f8-method method)))))))

;;; Method compilation

(defun compile-f8-method (method)
  (let ((*method-id* (getf (rest method) :method-id)))
    (declare (special *method-id*))
    (let* ((method-id *method-id*)
           (dispatch-label (format nil "Method~a~a"
                                   (f8-symbol *class-id*)
                                   (f8-symbol (format nil "~a" method-id))))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                       (getf (rest method) :statements))))
           (statements (nth-value 1 (split-method-leading-assembly-entry
                                     (getf (rest method) :statements))))
           (last-statement (car (last statements))))
      (if custom-entry
          (progn
            (format *output-stream* "~&~%~a:" (f8-symbol custom-entry))
            (format *output-stream* "~&~a:" dispatch-label))
          (format *output-stream* "~&~%~a:" dispatch-label))
      (dolist (stmt statements)
        (compile-statement :f8 (first stmt) (rest stmt)))
      (unless (and last-statement (listp last-statement)
                   (member (first last-statement)
                           '(:goback :exit-method :exit-program :exit :stop-run)))
        (format *output-stream* "~&~10tPOP")))))

;;; GOTO / paragraph labels (simple jmp or DEPENDING ON chain)

(defun compile-f8-goto (statement)
  "Emit F8 GOTO: unconditional @code{JMP}, or compare/@code{BZ} chain when @code{:depending-on} is set."
  (let ((target (getf (rest statement) :target))
        (targets (getf (rest statement) :targets))
        (dep (getf (rest statement) :depending-on)))
    (if dep
        (let ((tgt-list (or targets (when target (list target)))))
          (when tgt-list
            (compile-f8-load dep 1)
            (format *output-stream* "~&~10tLR 8, A")
            (let ((n (length tgt-list)))
              (loop for i from 1 below n
                    do (format *output-stream* "~&~10tLR A, 8")
                       (format *output-stream* "~&~10tCI ~d" i)
                       (format *output-stream* "~&~10tBZ ~a"
                               (f8-symbol (format nil "~a" (nth (1- i) tgt-list)))))
              (format *output-stream* "~&~10tJMP ~a"
                      (f8-symbol (format nil "~a" (nth (1- n) tgt-list)))))))
        (format *output-stream* "~&~10tJMP ~a"
                (f8-symbol (format nil "~a" (or target (first targets))))))))

;;; Statement dispatch — :around method for source comments

(defmethod compile-statement :around ((cpu (eql :f8)) stmt-type ast-node-data)
  (emit-statement-source-comment *output-stream* (cons stmt-type ast-node-data))
  (call-next-method))

;;; Individual statement methods

(def-f8-statement :goback
  (format *output-stream* "~&~10tPOP"))

(def-f8-statement :exit-method
  (format *output-stream* "~&~10tPOP"))

(def-f8-statement :exit-program
  (format *output-stream* "~&~10tPOP"))

(def-f8-statement :stop-run
  (format *output-stream* "~&~10tPOP"))

(def-f8-statement :exit
  (format *output-stream* "~&~10tPOP"))

(def-f8-statement :move
  (let ((stmt (cons :move ast-node-data)))
    (compile-f8-move stmt)))

(def-f8-statement :invoke
  (let ((stmt (cons :invoke ast-node-data)))
    (compile-f8-invoke stmt)))

(def-f8-statement :call
  (let ((stmt (cons :call ast-node-data)))
    (compile-f8-call stmt)))

(def-f8-statement :if
  (let ((stmt (cons :if ast-node-data)))
    (compile-f8-if stmt)))

(def-f8-statement :add
  (let ((stmt (cons :add ast-node-data)))
    (compile-f8-add stmt)))

(def-f8-statement :subtract
  (let ((stmt (cons :subtract ast-node-data)))
    (compile-f8-subtract stmt)))

(def-f8-statement :compute
  (let ((stmt (cons :compute ast-node-data)))
    (compile-f8-compute stmt)))

(def-f8-statement :set
  (let ((stmt (cons :set ast-node-data)))
    (compile-f8-set stmt)))

(def-f8-statement :log-fault
  (format *output-stream* "~&~10t;; LOG FAULT ~s" (getf ast-node-data :code)))

(def-f8-statement :debug-break
  (format *output-stream* "~&~10t;; DEBUG BREAK ~s" (getf ast-node-data :code)))

(def-f8-statement :perform
  (let ((stmt (cons :perform ast-node-data)))
    (compile-f8-perform stmt)))

(def-f8-statement :string-blt
  (let ((stmt (cons :string-blt ast-node-data)))
    (compile-f8-string-blt stmt)))

(def-f8-statement :goto
  (let ((stmt (cons :goto ast-node-data)))
    (compile-f8-goto stmt)))

(def-f8-statement :paragraph
   (let ((name (first ast-node-data)))
     (when name (format *output-stream* "~&~a:" (f8-symbol (format nil "~a_~a_~a" *class-id* (or *method-id* "") name))))))

(def-f8-statement :evaluate
  (let ((stmt (cons :evaluate ast-node-data)))
    (compile-f8-evaluate stmt)))

(def-f8-statement :inspect
  (let ((stmt (cons :inspect ast-node-data)))
    (compile-f8-inspect stmt)))

(def-f8-statement :comment
  (format *output-stream* "~&~10t;; ~a"
          (let ((text (first ast-node-data)))
            (if (listp text)
                (format nil "~{~a~%~10t;; ~}" (mapcar (lambda (s) (if (stringp s) s (princ-to-string s))) text))
                (princ-to-string text)))))

(def-f8-statement :copy
  (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
         (getf ast-node-data :name)))

(def-f8-statement :divide
  (let* ((divisor (getf ast-node-data :divisor))
         (into (getf ast-node-data :into))
         (by (getf ast-node-data :by))
         (source (or by into))
         (dest (or (getf ast-node-data :giving) into)))
    (if (and (expression-constant-p divisor)
             (power-of-two-p (expression-constant-value divisor)))
        (let ((shift-value (log2 (expression-constant-value divisor))))
          (unless (zerop shift-value)
            (compile-f8-load (or source dest) 1)
            (dotimes (_ shift-value) (format *output-stream* "~&~10tSR 1"))
            (%f8-store-dest dest)))
        (error 'source-error
               :message "DIVIDE: divisor must be constant power-of-two (1, 2, 4, 8, ...)"
               :detail (format nil "DIVIDE by ~s" divisor)))))

(def-f8-statement :multiply
  (let* ((multiplier (getf ast-node-data :multiplier))
         (by (getf ast-node-data :by))
         (giving (getf ast-node-data :giving))
         (source (or giving by))
         (dest (or giving by)))
    (if (and (expression-constant-p multiplier)
             (power-of-two-p (expression-constant-value multiplier)))
        (let ((shift-value (log2 (expression-constant-value multiplier))))
          (unless (zerop shift-value)
            (compile-f8-load (or source dest) 1)
            (dotimes (_ shift-value) (format *output-stream* "~&~10tSL 1"))
            (%f8-store-dest dest)))
        (error 'source-error
               :message "MULTIPLY: multiplier must be constant power-of-two (1, 2, 4, 8, ...)"
               :detail (format nil "MULTIPLY by ~s" multiplier)))))

(def-f8-statement :invoke-super
  (unless (gethash *class-id* *parent-classes*)
    (load-classes))
  (if-let (parent-class (gethash *class-id* *parent-classes*))
    (format *output-stream* "~&~10tPI Method~a~a"
            (f8-symbol parent-class)
            (f8-symbol (format nil "~a" *method-id*)))
    (error "Can't figure out parent class of ~a" *class-id*)))

(def-f8-statement :shift-left
  (let* ((target (getf ast-node-data :target))
         (count (getf ast-node-data :count 1)))
    (compile-f8-load target 1)
    (dotimes (_ count) (format *output-stream* "~&~10tSL 1"))
    (%f8-store-dest target)))

(def-f8-statement :shift-right
  (let* ((target (getf ast-node-data :target))
         (count (getf ast-node-data :count 1)))
    (compile-f8-load target 1)
    (dotimes (_ count) (format *output-stream* "~&~10tSR 1"))
    (%f8-store-dest target)))

;;; Expression / value emission

(defun compile-f8-load (expr &optional (width (operand-width expr)))
  "Load EXPR into A (width 1) or scratch 10-11 lo/hi (width 2)."
  (labels ((load-word-immediate (value)
             (format *output-stream* "~&~10tLI ~d" (logand value #xff))
             (format *output-stream* "~&~10tLR 10, A")
             (format *output-stream* "~&~10tLI ~d" (logand (ash value -8) #xff))
             (format *output-stream* "~&~10tLR 11, A")))
    (cond
      ((numberp expr)
       (if (= (or width 1) 2)
           (load-word-immediate expr)
           (format *output-stream* "~&~10tLI ~d" expr)))
      ((and (stringp expr) (constant-p expr))
       (compile-f8-load (constant-value expr) width))
      ((stringp expr)
       (if (= (or width 1) 2)
           (progn
             (format *output-stream* "~&~10tDCI ~a" (slot-symbol expr *class-id*))
             (%f8-load-byte-at-dc0)
             (format *output-stream* "~&~10tLR 10, A")
             (%f8-load-byte-at-dc0)
             (format *output-stream* "~&~10tLR 11, A"))
           (progn
             (format *output-stream* "~&~10tDCI ~a" (slot-symbol expr *class-id*))
             (%f8-load-byte-at-dc0))))
      ((and (listp expr) (eq (first expr) :of))
       (let ((slot (second expr)) (obj (third expr)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (%f8-self-pointer-to-dc0)
           (%f8-dc0-add-slot-offset slot)
           (if (= (or width 1) 2)
               (progn
                 (%f8-load-byte-at-dc0)
                 (format *output-stream* "~&~10tLR 10, A")
                 (%f8-load-byte-at-dc0)
                 (format *output-stream* "~&~10tLR 11, A"))
               (%f8-load-byte-at-dc0)))))
      ((and (listp expr) (eq (first expr) :subscript))
       (compile-f8-load (third expr) 1)
       (format *output-stream* "~&~10tLR 6, A")
       (when (= (or width 1) 2)
         (format *output-stream* "~&~10tLR A, 6")
         (format *output-stream* "~&~10tSL 1")
         (format *output-stream* "~&~10tLR 6, A"))
       (format *output-stream* "~&~10tDCI ~a" (slot-symbol (second expr) *class-id*))
       (let ((loop-label (f8-label "ix"))
             (done-label (f8-label "ixd")))
         (%f8-dc0-bump-by-count 6 loop-label done-label))
       (if (= (or width 1) 2)
           (progn
             (%f8-load-byte-at-dc0)
             (format *output-stream* "~&~10tLR 10, A")
             (%f8-load-byte-at-dc0)
             (format *output-stream* "~&~10tLR 11, A"))
           (%f8-load-byte-at-dc0)))
      ((and (listp expr) (eq (first expr) :shift-left))
       (let ((n (if (numberp (third expr)) (third expr) 1)))
         (compile-f8-load (second expr))
         (dotimes (_ n) (format *output-stream* "~&~10tSL 1"))))
      ((and (listp expr) (eq (first expr) :shift-right))
       (let ((n (if (numberp (third expr)) (third expr) 1)))
         (compile-f8-load (second expr))
         (dotimes (_ n) (format *output-stream* "~&~10tSR 1"))))
      ((and (listp expr) (eq (first expr) :bit-and))
       (compile-f8-load (second expr))
       (let ((rhs (third expr)))
         (if (f8-expr-is-constant-p rhs)
             (format *output-stream* "~&~10tNI ~a" (f8-value rhs))
             (progn (format *output-stream* "~&~10tLR 8, A")
                    (compile-f8-load rhs)
                    (format *output-stream* "~&~10tNS 8")))))
      ((and (listp expr) (eq (first expr) :bit-or))
       (compile-f8-load (second expr))
       (let ((rhs (third expr)))
         (if (f8-expr-is-constant-p rhs)
             (format *output-stream* "~&~10tOI ~a" (f8-value rhs))
             (progn
               (format *output-stream* "~&~10tLR 8, A")
               (compile-f8-load rhs)
               (format *output-stream* "~&~10tCOM")
               (format *output-stream* "~&~10tLR 9, A")
               (format *output-stream* "~&~10tLR A, 8")
               (format *output-stream* "~&~10tCOM")
               (format *output-stream* "~&~10tNS 9")
               (format *output-stream* "~&~10tCOM")))))
      ((and (listp expr) (eq (first expr) :bit-xor))
       (compile-f8-load (second expr))
       (let ((rhs (third expr)))
         (if (f8-expr-is-constant-p rhs)
             (format *output-stream* "~&~10tXI ~a" (f8-value rhs))
             (progn (format *output-stream* "~&~10tLR 8, A")
                    (compile-f8-load rhs)
                    (format *output-stream* "~&~10tXS 8")))))
      ((and (listp expr) (eq (first expr) :bit-not))
       (compile-f8-load (second expr))
       (format *output-stream* "~&~10tCOM"))
      (t (format *output-stream* "~&~10t;; Unsupported load ~s" expr)))))

;;; NOTE: bit-or with variable RHS is approximated; prefer OI with constant.

(defun %f8-store-dest (dest &optional word-pair-p)
  "Store value: A (byte) or scratch 10-11 (word if WORD-PAIR-P) to DEST."
  (let ((w (operand-width dest)))
    (cond
      ((stringp dest)
       (if (or word-pair-p (= (or w 1) 2))
           (progn
             (format *output-stream* "~&~10tDCI ~a" (slot-symbol dest *class-id*))
             (format *output-stream* "~&~10tLR A, 10")
             (%f8-store-a-via-dc0)
             (format *output-stream* "~&~10tLR A, 11")
             (%f8-store-a-via-dc0))
           (progn
             (format *output-stream* "~&~10tDCI ~a" (slot-symbol dest *class-id*))
             (%f8-store-a-via-dc0))))
      ((and (listp dest) (eq (first dest) :of))
       (let ((slot (second dest)) (obj (third dest)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (%f8-self-pointer-to-dc0)
           (%f8-dc0-add-slot-offset slot)
           (if (or word-pair-p (= (or w 1) 2))
               (progn
                 (format *output-stream* "~&~10tLR A, 10")
                 (%f8-store-a-via-dc0)
                 (format *output-stream* "~&~10tLR A, 11")
                 (%f8-store-a-via-dc0))
               (%f8-store-a-via-dc0)))))
      ((and (listp dest) (eq (first dest) :subscript))
       (when word-pair-p
         (format *output-stream* "~&~10tLR 12, 10")
         (format *output-stream* "~&~10tLR 13, 11"))
       (unless word-pair-p
         (format *output-stream* "~&~10tLR 12, A"))
       (compile-f8-load (third dest) 1)
       (format *output-stream* "~&~10tLR 6, A")
       (when (= (or w 1) 2)
         (format *output-stream* "~&~10tLR A, 6")
         (format *output-stream* "~&~10tSL 1")
         (format *output-stream* "~&~10tLR 6, A"))
       (format *output-stream* "~&~10tDCI ~a" (slot-symbol (second dest) *class-id*))
       (let ((loop-label (f8-label "stx"))
             (done-label (f8-label "std")))
         (%f8-dc0-bump-by-count 6 loop-label done-label))
       (if (or word-pair-p (= (or w 1) 2))
           (progn
             (format *output-stream* "~&~10tLR A, 12")
             (%f8-store-a-via-dc0)
             (format *output-stream* "~&~10tLR A, 13")
             (%f8-store-a-via-dc0))
           (progn
             (format *output-stream* "~&~10tLR A, 12")
             (%f8-store-a-via-dc0))))
      (t (format *output-stream* "~&~10t;; Unsupported store to ~s" dest)))))

;;; MOVE

(defun compile-f8-move (statement)
  (let* ((from (getf (rest statement) :from))
         (to (getf (rest statement) :to))
         (from-width (operand-width from))
         (to-width (operand-width to))
         (word-result-p (= (max (or from-width 1) (or to-width 1)) 2)))
    (compile-f8-load from (if word-result-p 2 1))
    (%f8-store-dest to word-result-p)))

;;; INVOKE

(defun compile-f8-invoke (statement)
  (let ((object (getf (rest statement) :object))
        (method (getf (rest statement) :method))
        (returning (getf (rest statement) :returning)))
    (let ((method-sym (f8-symbol (format nil "~a" method))))
      (cond
        ((member object '(:self "Self" self) :test #'equal)
         (format *output-stream* "~&~10tPI Invoke~a~a" (f8-symbol *class-id*) method-sym))
        (t
         (let* ((obj-name (f8-symbol (format nil "~a" object)))
                (obj-class (or (var-class obj-name) "Unknown")))
           (format *output-stream* "~&~10tPI Call~a~a" obj-class method-sym)))))
    (when returning
      (let ((return-width (operand-width returning)))
        (%f8-store-dest returning (= (or return-width 1) 2))))))

;;; CALL

(defun compile-f8-call (statement)
  (let ((target (getf (rest statement) :target))
        (service (getf (rest statement) :service)))
    (format *output-stream* "~&~10tPI ~a" (f8-symbol (format nil "~a" (or service target))))))

(defvar *f8-label* 0)

(defun f8-label (prefix)
  (format nil "_~a~d" prefix (incf *f8-label*)))

(defun %f8-emit-16bit-zero-test (skip-label)
  (format *output-stream* "~&~10tLR A, 10")
  (format *output-stream* "~&~10tCI 0")
  (format *output-stream* "~&~10tBNZ ~a" skip-label)
  (format *output-stream* "~&~10tLR A, 11")
  (format *output-stream* "~&~10tCI 0")
  (format *output-stream* "~&~10tBNZ ~a" skip-label))

;;; IF / condition

(defun compile-f8-if (statement)
  (let ((condition (getf (rest statement) :condition))
        (then-statements (getf (rest statement) :then))
        (else-statements (getf (rest statement) :else))
        (else-label (f8-label "else"))
        (end-label (f8-label "end")))
    (compile-f8-condition condition else-label)
    (dolist (s (ensure-list then-statements))
      (compile-statement :f8 (first s) (rest s)))
    (when (and else-statements (not (null else-statements)))
      (format *output-stream* "~&~10tJMP ~a" end-label))
    (format *output-stream* "~&~a:" else-label)
    (when (and else-statements (not (null else-statements)))
      (dolist (s (ensure-list else-statements))
        (compile-statement :f8 (first s) (rest s)))
      (format *output-stream* "~&~a:" end-label))))

(defun compile-f8-condition (condition branch-label)
  (cond
    ((and (listp condition) (member (first condition) '(= equal < less > greater) :test #'eq))
     (let* ((lhs (second condition))
            (rhs (third condition))
            (op (first condition))
            (w (max (or (operand-width lhs) 1)
                    (or (operand-width rhs) 1))))
       (if (= w 2)
           (progn
             (compile-f8-load lhs 2)
             (format *output-stream* "~&~10tLR 12, 10")
             (format *output-stream* "~&~10tLR 13, 11")
             (compile-f8-load rhs 2)
             (%f8-negate-16-10)
             (%f8-add-16)
             (ecase op
               ((= equal)
                (format *output-stream* "~&~10tLR A, 10")
                (format *output-stream* "~&~10tCI 0")
                (format *output-stream* "~&~10tBNZ ~a" branch-label)
                (format *output-stream* "~&~10tLR A, 11")
                (format *output-stream* "~&~10tCI 0")
                (format *output-stream* "~&~10tBNZ ~a" branch-label))
               ((< less)
                (format *output-stream* "~&~10tLR A, 11")
                (format *output-stream* "~&~10tBM ~a" branch-label))
               ((> greater)
                (format *output-stream* "~&~10tLR A, 11")
                (format *output-stream* "~&~10tBZ ~a" branch-label)
                (format *output-stream* "~&~10tBP ~a" branch-label))))
           (progn
             (compile-f8-load lhs 1)
             (format *output-stream* "~&~10tLR 8, A")
             (compile-f8-load rhs 1)
             (ecase op
               ((= equal)
                (format *output-stream* "~&~10tXS 8")
                (format *output-stream* "~&~10tBNZ ~a" branch-label))
               ((< less)
                (format *output-stream* "~&~10tLR 9, A")
                (format *output-stream* "~&~10tLR A, 8")
                (format *output-stream* "~&~10tCOM")
                (format *output-stream* "~&~10tINC")
                (format *output-stream* "~&~10tAS 9")
                (format *output-stream* "~&~10tBM ~a" branch-label))
               ((> greater)
                (format *output-stream* "~&~10tLR 9, A")
                (format *output-stream* "~&~10tLR A, 8")
                (format *output-stream* "~&~10tCOM")
                (format *output-stream* "~&~10tINC")
                (format *output-stream* "~&~10tAS 9")
                (format *output-stream* "~&~10tBZ ~a" branch-label)
                (format *output-stream* "~&~10tBP ~a" branch-label)))))))
    ((and (listp condition) (eq (first condition) :is-zero))
     (let* ((ex (second condition))
            (w (operand-width ex)))
       (compile-f8-load ex)
       (if (= (or w 1) 2)
           (%f8-emit-16bit-zero-test branch-label)
           (progn
             (format *output-stream* "~&~10tCI 0")
             (format *output-stream* "~&~10tBNZ ~a" branch-label)))))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (let* ((ex (second condition))
            (w (operand-width ex)))
       (compile-f8-load ex)
       (if (= (or w 1) 2)
           (let ((skip-label (f8-label "snz")))
             (format *output-stream* "~&~10tLR A, 10")
             (format *output-stream* "~&~10tCI 0")
             (format *output-stream* "~&~10tBNZ ~a" skip-label)
             (format *output-stream* "~&~10tLR A, 11")
             (format *output-stream* "~&~10tCI 0")
             (format *output-stream* "~&~10tBZ ~a" branch-label)
             (format *output-stream* "~&~a:" skip-label))
           (progn
             (format *output-stream* "~&~10tCI 0")
             (format *output-stream* "~&~10tBZ ~a" branch-label)))))
    ((and (listp condition) (eq (first condition) :and))
     (compile-f8-condition (second condition) branch-label)
     (compile-f8-condition (third condition) branch-label))
    ((and (listp condition) (eq (first condition) :or))
     (let ((second-condition-label (f8-label "or"))
           (skip-label (f8-label "skip")))
       (compile-f8-condition (second condition) second-condition-label)
       (format *output-stream* "~&~10tJMP ~a" skip-label)
       (format *output-stream* "~&~a:" second-condition-label)
       (compile-f8-condition (third condition) branch-label)
       (format *output-stream* "~&~a:" skip-label)))
    (t (error "EIGHTBOL: condition ~s not implemented" condition))))

(defun f8-value (expr)
  (cond
    ((numberp expr) (format nil "~d" expr))
    ((and (stringp expr) (constant-p expr))
     (format nil "~d" (constant-value expr)))
    ((stringp expr) (f8-symbol expr))
    ((eq expr :self) "Self")
    ((and (listp expr) (eq (first expr) :of))
     (f8-symbol (format nil "~a-~a" (third expr) (second expr))))
    (t (format nil "~a" expr))))

(defun f8-expr-is-constant-p (expr)
  "True if EXPR is a numeric literal or EIGHTBOL constant."
  (or (numberp expr)
      (and (stringp expr) (constant-p expr))))

;;; EVALUATE statement

(defun compile-f8-evaluate (statement)
  (let ((subject (getf (rest statement) :subject))
        (clauses (getf (rest statement) :when-clauses))
        (end-label (f8-label "eval")))
    (dolist (clause (ensure-list clauses))
      (cond
        ((eq (first clause) :when-other)
         (dolist (s (ensure-list (second clause)))
           (compile-statement :f8 (first s) (rest s))))
        ((eq (first clause) :when)
         (let ((phrases (second clause))
               (statements (third clause))
               (next-label (f8-label "when")))
           (cond
             ((eq phrases 'eightbol::any)
              (dolist (s (ensure-list statements))
                (compile-statement :f8 (first s) (rest s)))
              (format *output-stream* "~&~10tJMP ~a" end-label))
             ((or (eq phrases 'eightbol::true) (equal phrases "TRUE"))
              (let ((subject-width (operand-width subject))
                    (true-run-label (f8-label "etr")))
                (compile-f8-load subject)
                (if (= (or subject-width 1) 2)
                    (progn
                      (format *output-stream* "~&~10tLR A, 10")
                      (format *output-stream* "~&~10tCI 0")
                      (format *output-stream* "~&~10tBNZ ~a" true-run-label)
                      (format *output-stream* "~&~10tLR A, 11")
                      (format *output-stream* "~&~10tCI 0")
                      (format *output-stream* "~&~10tBZ ~a" next-label)
                      (format *output-stream* "~&~a:" true-run-label))
                    (progn
                      (format *output-stream* "~&~10tCI 0")
                      (format *output-stream* "~&~10tBZ ~a" next-label)))
                (dolist (s (ensure-list statements))
                  (compile-statement :f8 (first s) (rest s)))
                (format *output-stream* "~&~10tJMP ~a" end-label)
                (format *output-stream* "~&~a:" next-label)))
             ((or (and (symbolp phrases) (string= (symbol-name phrases) "FALSE"))
                  (equal phrases "FALSE"))
              (let ((subject-width (operand-width subject)))
                (compile-f8-load subject)
                (if (= (or subject-width 1) 2)
                    (progn
                      (format *output-stream* "~&~10tLR A, 10")
                      (format *output-stream* "~&~10tCI 0")
                      (format *output-stream* "~&~10tBNZ ~a" next-label)
                      (format *output-stream* "~&~10tLR A, 11")
                      (format *output-stream* "~&~10tCI 0")
                      (format *output-stream* "~&~10tBNZ ~a" next-label))
                    (progn
                      (format *output-stream* "~&~10tCI 0")
                      (format *output-stream* "~&~10tBNZ ~a" next-label)))
                (dolist (s (ensure-list statements))
                  (compile-statement :f8 (first s) (rest s)))
                (format *output-stream* "~&~10tJMP ~a" end-label)
                (format *output-stream* "~&~a:" next-label)))
             ((and (listp phrases) (eq (first phrases) :not))
              (compile-f8-load subject)
              (format *output-stream* "~&~10tLR 8, A")
              (compile-f8-load (second phrases))
              (format *output-stream* "~&~10tXS 8")
              (format *output-stream* "~&~10tCI 0")
              (format *output-stream* "~&~10tBZ ~a" next-label)
              (dolist (s (ensure-list statements))
                (compile-statement :f8 (first s) (rest s)))
              (format *output-stream* "~&~10tJMP ~a" end-label)
              (format *output-stream* "~&~a:" next-label))
             ((and (listp phrases) (member (first phrases) '(:through :thru)))
              (let* ((low (second phrases))
                     (high (third phrases))
                     (size-width (max (or (operand-width subject) 1)
                                      (or (operand-width low) 1)
                                      (or (operand-width high) 1))))
                (compile-f8-load subject)
                (when (= size-width 2)
                  (format *output-stream* "~&~10tLR 8, 10")
                  (format *output-stream* "~&~10tLR 9, 11"))
                (when (= size-width 1)
                  (format *output-stream* "~&~10tLR 8, A"))
                (compile-f8-load low)
                (when (= size-width 2)
                  (format *output-stream* "~&~10t;; | EVALUATE THROUGH: 16-bit compare simplified"))
                (format *output-stream* "~&~10tLR 9, A")
                (format *output-stream* "~&~10tLR A, 8")
                (format *output-stream* "~&~10tCOM")
                (format *output-stream* "~&~10tINC")
                (format *output-stream* "~&~10tAS 9")
                (format *output-stream* "~&~10tBM ~a" next-label)
                (compile-f8-load high)
                (format *output-stream* "~&~10tLR 9, A")
                (format *output-stream* "~&~10tLR A, 8")
                (format *output-stream* "~&~10tCOM")
                (format *output-stream* "~&~10tINC")
                (format *output-stream* "~&~10tAS 9")
                (format *output-stream* "~&~10tBP ~a" next-label)
                (dolist (s (ensure-list statements))
                  (compile-statement :f8 (first s) (rest s)))
                (format *output-stream* "~&~10tJMP ~a" end-label)
                (format *output-stream* "~&~a:" next-label)))
             (t
              (let* ((phrase-expression (if (listp phrases) (second phrases) phrases))
                     (size-width (max (or (operand-width subject) 1)
                                      (or (operand-width phrase-expression) 1))))
                (compile-f8-load subject)
                (when (= size-width 2)
                  (format *output-stream* "~&~10tLR 12, 10")
                  (format *output-stream* "~&~10tLR 13, 11"))
                (when (= size-width 1)
                  (format *output-stream* "~&~10tLR 8, A"))
                (compile-f8-load phrase-expression)
                (if (= size-width 2)
                    (progn
                      (format *output-stream* "~&~10tLR A, 10")
                      (format *output-stream* "~&~10tXS 12")
                      (format *output-stream* "~&~10tBNZ ~a" next-label)
                      (format *output-stream* "~&~10tLR A, 11")
                      (format *output-stream* "~&~10tXS 13")
                      (format *output-stream* "~&~10tBNZ ~a" next-label))
                    (progn
                      (format *output-stream* "~&~10tXS 8")
                      (format *output-stream* "~&~10tBNZ ~a" next-label)))
                (dolist (s (ensure-list statements))
                  (compile-statement :f8 (first s) (rest s)))
                (format *output-stream* "~&~10tJMP ~a" end-label)
                (format *output-stream* "~&~a:" next-label)))))))
      (format *output-stream* "~&~a:" end-label))))

;;; INSPECT statement

(defun compile-f8-inspect (statement)
  (let ((target (getf (rest statement) :target))
        (tally (getf (rest statement) :tallying))
        (converting-from (getf (rest statement) :converting))
        (converting-to (getf (rest statement) :to))
        (replacing-by (getf (rest statement) :by)))
    (let ((target-symbol (f8-symbol (format nil "~a" target))))
      (cond
        (tally
         (let ((tally-symbol (f8-symbol (format nil "~a" tally))))
           (format *output-stream* "~&~10t;; INSPECT ~a TALLYING ~a" target tally)
           (format *output-stream* "~&~10tDCI ~a" target-symbol)
           (format *output-stream* "~&~10tLR Q, DC0")
           (let ((loop-label (f8-label "tly")) (done-label (f8-label "tld")))
             (format *output-stream* "~&~a:" loop-label)
             (format *output-stream* "~&~10tLR DC0, Q")
             (%f8-load-byte-at-dc0)
             (format *output-stream* "~&~10tLR 9, A")
             (format *output-stream* "~&~10tLR Q, DC0")
             (format *output-stream* "~&~10tLR A, 9")
             (format *output-stream* "~&~10tCI 0")
             (format *output-stream* "~&~10tBZ ~a" done-label)
             (format *output-stream* "~&~10tDCI ~a" tally-symbol)
             (%f8-load-byte-at-dc0)
             (format *output-stream* "~&~10tINC")
             (format *output-stream* "~&~10tLR 8, A")
             (format *output-stream* "~&~10tDCI ~a" tally-symbol)
             (format *output-stream* "~&~10tLR A, 8")
             (%f8-store-a-via-dc0)
             (format *output-stream* "~&~10tBR ~a" loop-label)
             (format *output-stream* "~&~a:" done-label))))
        (converting-from
         (format *output-stream* "~&~10t;; INSPECT ~a CONVERTING" target)
         (format *output-stream* "~&~10tDCI ~a" target-symbol)
         (format *output-stream* "~&~10tLR Q, DC0")
         (let ((loop-label (f8-label "ins")) (next-label (f8-label "inn")) (done-label (f8-label "ind")))
           (format *output-stream* "~&~a:" loop-label)
           (format *output-stream* "~&~10tLR DC0, Q")
           (%f8-load-byte-at-dc0)
           (format *output-stream* "~&~10tLR 9, A")
           (format *output-stream* "~&~10tLR Q, DC0")
           (format *output-stream* "~&~10tLR A, 9")
           (format *output-stream* "~&~10tCI 0")
           (format *output-stream* "~&~10tBZ ~a" done-label)
           (if (f8-expr-is-constant-p converting-from)
               (format *output-stream* "~&~10tCI ~a" (f8-value converting-from))
               (progn
                 (format *output-stream* "~&~10tLR 8, A")
                 (compile-f8-load converting-from 1)
                 (format *output-stream* "~&~10tXS 8")))
           (format *output-stream* "~&~10tBNZ ~a" next-label)
           (compile-f8-load converting-to 1)
           (format *output-stream* "~&~10tLR DC0, Q")
           (format *output-stream* "~&~10tLI 255")
           (format *output-stream* "~&~10tADC")
           (%f8-store-a-via-dc0)
           (format *output-stream* "~&~10tLR Q, DC0")
           (format *output-stream* "~&~10tBR ~a" loop-label)
           (format *output-stream* "~&~a:" next-label)
           (format *output-stream* "~&~10tBR ~a" loop-label)
           (format *output-stream* "~&~a:" done-label)))
        (replacing-by
         (let ((length (or (gethash (format nil "~a" target) *pic-size-table*) 64)))
           (format *output-stream* "~&~10t;; INSPECT ~a REPLACING" target)
           (compile-f8-load replacing-by 1)
           (format *output-stream* "~&~10tDCI ~a" target-symbol)
           (format *output-stream* "~&~10tLI ~d" length)
           (format *output-stream* "~&~10tLR 6, A")
           (let ((loop-label (f8-label "irp")))
             (format *output-stream* "~&~a:" loop-label)
             (%f8-store-a-via-dc0)
             (format *output-stream* "~&~10tDS 6")
             (format *output-stream* "~&~10tLR A, 6")
             (format *output-stream* "~&~10tCI 0")
             (format *output-stream* "~&~10tBNZ ~a" loop-label))))))))

(defun %f8-add-16 ()
  "10:11 += 12:13 (unsigned with carry)."
  (format *output-stream* "~&~10tLR A, 10")
  (format *output-stream* "~&~10tAS 12")
  (format *output-stream* "~&~10tLR 10, A")
  (format *output-stream* "~&~10tLR A, 11")
  (format *output-stream* "~&~10tLNK")
  (format *output-stream* "~&~10tAS 13")
  (format *output-stream* "~&~10tLR 11, A"))

(defun %f8-negate-16-10 ()
  "Two's complement negate 10:11 in place."
  (let ((skip-label (f8-label "f8n")))
    (format *output-stream* "~&~10tLR A, 10")
    (format *output-stream* "~&~10tCOM")
    (format *output-stream* "~&~10tINC")
    (format *output-stream* "~&~10tLR 10, A")
    (format *output-stream* "~&~10tLR A, 10")
    (format *output-stream* "~&~10tCI 0")
    (format *output-stream* "~&~10tBNZ ~a" skip-label)
    (format *output-stream* "~&~10tDS 11")
    (format *output-stream* "~&~a:" skip-label)
    (format *output-stream* "~&~10tLR A, 11")
    (format *output-stream* "~&~10tCOM")
    (format *output-stream* "~&~10tINC")
    (format *output-stream* "~&~10tLR 11, A")))

;;; ADD

(defun compile-f8-add (statement)
  (let* ((from (getf (rest statement) :from))
         (to (getf (rest statement) :to))
         (giving (getf (rest statement) :giving))
         (result (or giving (and (stringp to) to)))
         (w (operand-width (or result to)))
         (bcd-p (when result (usage-bcd-p (expression-to-width-name result)))))
    (assert-pic-decimal-add-compiled :f8 statement)
    (when (and bcd-p (> (or w 1) 2))
      (dotimes (i w)
        (compile-f8-load from 1)
        (format *output-stream* "~&~10tLR 8, A")
        (compile-f8-load to 1)
        (format *output-stream* "~&~10tAS 8")
        (format *output-stream* "~&~10tASD 8")
        (%f8-store-dest result nil))
      (return-from compile-f8-add))
    (backend-unsupported-operand-width :f8 :add w 2)
    (if (= (or w 1) 2)
        (progn
          (compile-f8-load to 2)
          (format *output-stream* "~&~10tLR 12, 10")
          (format *output-stream* "~&~10tLR 13, 11")
          (compile-f8-load from 2)
          (if bcd-p
              (format *output-stream* "~&~10t;; | BCD 16-bit ADD — use AMD/ASD sequence per runtime")
              (%f8-add-16))
          (when result
            (%f8-store-dest result t)))
        (progn
          (compile-f8-load to 1)
          (format *output-stream* "~&~10tLR 8, A")
          (compile-f8-load from 1)
          (format *output-stream* "~&~10tAS 8")
          (when bcd-p (format *output-stream* "~&~10tASD 8"))
          (when result
            (%f8-store-dest result nil))))))

;;; SUBTRACT

(defun compile-f8-subtract (statement)
  (multiple-value-bind (minuend subtrahend)
      (subtract-statement-minuend-and-subtrahend statement)
    (let* ((giving (getf (rest statement) :giving))
           (dest (or giving minuend))
           (w (operand-width dest))
           (bcd-p (when dest (usage-bcd-p (expression-to-width-name dest)))))
      (assert-pic-decimal-subtract-compiled :f8 statement)
      (when (and bcd-p (> (or w 1) 2))
        (dotimes (i w)
          (compile-f8-load minuend 1)
          (format *output-stream* "~&~10tLR 8, A")
          (compile-f8-load subtrahend 1)
          (format *output-stream* "~&~10tCOM")
          (format *output-stream* "~&~10tINC")
          (format *output-stream* "~&~10tAS 8")
          ;; Software BCD subtract correction (no DAS on F8)
          (format *output-stream* "~&~10tLR 9, A")
          (format *output-stream* "~&~10tNI $0F")
          (format *output-stream* "~&~10tCI 10")
          (format *output-stream* "~&~10tBZ ~a" (f8-label "fs1"))
          (format *output-stream* "~&~10tBNC ~a" (f8-label "fs1"))
          (format *output-stream* "~&~10tLR A, 9")
          (format *output-stream* "~&~10tAI $F0")
          (format *output-stream* "~&~10tLR 9, A")
          (format *output-stream* "~&~a:" (f8-label "fs1"))
          (format *output-stream* "~&~10tLR A, 9")
          (format *output-stream* "~&~10tNI $F0")
          (format *output-stream* "~&~10tCI $A0")
          (format *output-stream* "~&~10tBZ ~a" (f8-label "fs2"))
          (format *output-stream* "~&~10tBNC ~a" (f8-label "fs2"))
          (format *output-stream* "~&~10tLR A, 9")
          (format *output-stream* "~&~10tAI $A0")
          (format *output-stream* "~&~10tLR 9, A")
          (format *output-stream* "~&~a:" (f8-label "fs2"))
          (format *output-stream* "~&~10tLR A, 9")
          (%f8-store-dest dest nil))
        (return-from compile-f8-subtract))
      (if (= (or w 1) 2)
          (progn
            (compile-f8-load minuend 2)
            (format *output-stream* "~&~10tLR 12, 10")
            (format *output-stream* "~&~10tLR 13, 11")
            (compile-f8-load subtrahend 2)
            (unless bcd-p
              (%f8-negate-16-10)
              (%f8-add-16))
            (when bcd-p (format *output-stream* "~&~10t;; | BCD 16-bit SUB — deferred"))
            (%f8-store-dest dest t))
          (progn
            (compile-f8-load minuend 1)
            (format *output-stream* "~&~10tLR 8, A")
            (compile-f8-load subtrahend 1)
            (format *output-stream* "~&~10tCOM")
            (format *output-stream* "~&~10tINC")
            (format *output-stream* "~&~10tAS 8")
            (when bcd-p (format *output-stream* "~&~10t;; | BCD byte subtract — deferred"))
            (%f8-store-dest dest nil))))))

;;; COMPUTE

(defun compile-f8-compute (statement)
  (let* ((target (getf (rest statement) :target))
         (expr (getf (rest statement) :expression))
         (w (operand-width target)))
    (compile-f8-load expr w)
    (%f8-store-dest target (= (or w 1) 2))))

;;; SET

(defun compile-f8-set (statement)
  (let ((target (getf (rest statement) :target))
        (value (getf (rest statement) :value))
        (up-by (getf (rest statement) :up-by))
        (down-by (getf (rest statement) :down-by))
        (by-expr (getf (rest statement) :by))
        (address-of (getf (rest statement) :address-of))
        (to-self (getf (rest statement) :to-self)))
    (cond
      (up-by
       (compile-f8-add
        (list :add :from by-expr :to up-by :giving nil)))
      (down-by
       (compile-f8-subtract
        (list :subtract :from by-expr :from-target down-by :giving nil)))
      ((and address-of target)
       (let ((src address-of) (dest target))
         (cond
           ((slot-of-self-p src)
            (%f8-self-pointer-to-dc0)
            (%f8-dc0-add-slot-offset (second (slot-of-expression src)))
            (%f8-dc0-to-10-11))
           ((stringp src)
            ;; Load 16-bit address of symbol (not value at symbol).
            ;; F8 LI loads low byte; HIGH operator gets high byte.
            (let ((sym (slot-symbol src *class-id*)))
              (format *output-stream* "~&~10tLI ~a" sym)
              (format *output-stream* "~&~10tLR 10, A")
              (format *output-stream* "~&~10tLI HIGH(~a)" sym)
              (format *output-stream* "~&~10tLR 11, A")))
           (t (error "EIGHTBOL: unsupported SET ADDRESS OF source ~s for F8" src)))
         (%f8-store-dest dest t)))
      (to-self
       (%f8-self-pointer-to-dc0)
       (%f8-store-dest to-self t))
      (t
       (compile-f8-load value)
       (%f8-store-dest target nil)))))

;;; PERFORM

(defun compile-f8-perform (statement)
  (let ((procedure (getf (rest statement) :procedure))
        (times (getf (rest statement) :times))
        (until (getf (rest statement) :until)))
    (cond
      (times
       (let ((loop-label (f8-label "perf"))
             (done-label (f8-label "pfd"))
             (times-width (operand-width times)))
         (compile-f8-load times)
         (if (= (or times-width 1) 2)
             (progn
               (format *output-stream* "~&~10tLR 6, 10")
               (format *output-stream* "~&~10t;; | PERFORM count in 6 (lo) only if word — simplify"))
             (format *output-stream* "~&~10tLR 6, A"))
         (format *output-stream* "~&~a:" loop-label)
         (format *output-stream* "~&~10tLR A, 6")
         (format *output-stream* "~&~10tCI 0")
         (format *output-stream* "~&~10tBZ ~a" done-label)
         (format *output-stream* "~&~10tPI ~a" (f8-symbol (format nil "~a" procedure)))
         (format *output-stream* "~&~10tDS 6")
         (format *output-stream* "~&~10tBR ~a" loop-label)
         (format *output-stream* "~&~a:" done-label)))
      (until
          (let ((loop-label (f8-label "uloop"))
                (end-label (f8-label "uend")))
            (format *output-stream* "~&~a:" loop-label)
            (compile-f8-condition until end-label)
            (format *output-stream* "~&~10tPI ~a" (f8-symbol (format nil "~a" procedure)))
            (format *output-stream* "~&~10tBR ~a" loop-label)
            (format *output-stream* "~&~a:" end-label)))
      (t
       (format *output-stream* "~&~10tPI ~a" (f8-symbol (format nil "~a" procedure)))))))

;;; STRING BLT

(defun %f8-string-operand-length-expr (source stmt)
  "Return length expression for STRING BLT from STMT or SOURCE :refmod.

@table @asis
@item STMT
@code{:string-blt} statement; use @code{(rest stmt)} for the plist.
@item SOURCE
@code{:source} operand — for @code{:refmod}, read @code{:length} from @code{(cdr source)} with @code{safe-getf}.
@end table

Same rule as @code{string-operand-length-expr} / @code{%z80-string-operand-length-expr}: do not @code{getf} on the full @code{(:refmod ...)} cell."
  (or (safe-getf (rest stmt) :length)
      (when (and (listp source) (eq (first source) :refmod))
        (safe-getf (rest source) :length))))

(defun f8-string-operand-address (operand)
  (cond
    ((and (listp operand) (eq (first operand) :refmod))
     (let* ((base (getf (rest operand) :base))
            (start (getf (rest operand) :start))
            (base-str (f8-symbol (format nil "~a" base))))
       (if (and (integerp start) (= start 1))
           base-str
           (format nil "~a+~d" base-str (1- start)))))
    (t (f8-symbol (format nil "~a" operand)))))

(defun compile-f8-string-blt (statement)
  "Emit F8 STRING block copy (DELIMITED BY SIZE). Uses scratch 7 as count.

Length from @code{:length}, SOURCE @code{:refmod}, or DEST @code{:refmod} via
@code{%f8-string-operand-length-expr}; non-constant length defaults to 64."
  (let* ((source (safe-getf (rest statement) :source))
         (dest (safe-getf (rest statement) :dest))
         (len-expr (or (%f8-string-operand-length-expr source statement)
                       (when (and (listp dest) (eq (first dest) :refmod))
                         (safe-getf (rest dest) :length))))
         (len (cond ((integerp len-expr) len-expr)
                    ((and len-expr (f8-expr-is-constant-p len-expr))
                     (if (numberp len-expr)
                         len-expr
                         (constant-value len-expr)))
                    (t 64))))
    (let ((src-address (f8-string-operand-address source))
          (dst-address (f8-string-operand-address dest))
          (loop-label (f8-label "blt"))
          (done-label (f8-label "bld")))
      (format *output-stream* "~&~10t;; STRING BLT ~d bytes ~a -> ~a" len src-address dst-address)
      (format *output-stream* "~&~10tLI ~d" len)
      (format *output-stream* "~&~10tLR 7, A")
      (format *output-stream* "~&~10tDCI ~a" src-address)
      (format *output-stream* "~&~10tLR Q, DC0")
      (format *output-stream* "~&~10tDCI ~a" dst-address)
      (format *output-stream* "~&~10tLR DC0, H")
      (format *output-stream* "~&~a:" loop-label)
      (format *output-stream* "~&~10tLR A, 7")
      (format *output-stream* "~&~10tCI 0")
      (format *output-stream* "~&~10tBZ ~a" done-label)
      (format *output-stream* "~&~10tLR DC0, Q")
      (%f8-load-byte-at-dc0)
      (format *output-stream* "~&~10tLR 8, A")
      (format *output-stream* "~&~10tLR Q, DC0")
      (format *output-stream* "~&~10tLR H, DC0")
      (format *output-stream* "~&~10tLR A, 8")
      (%f8-store-a-via-dc0)
      (format *output-stream* "~&~10tLR DC0, H")
      (format *output-stream* "~&~10tDS 7")
      (format *output-stream* "~&~10tBR ~a" loop-label)
      (format *output-stream* "~&~a:" done-label))))
