;; src/frontend-sci/sci-lexer.lisp — Tokenization for SCI (Sierra Creative Interpreter)
;;; Copyright © 2026 Interworldly Adventuring, LLC
(in-package :eightbol)

(defparameter *sci-keyword-alist*
  '(("if" . :IF)
    ("else" . :ELSE)
    ("then" . :THEN)
    ("while" . :WHILE)
    ("for" . :FOR)
    ("foreach" . :FOREACH)
    ("break" . :BREAK)
    ("continue" . :CONTINUE)
    ("return" . :RETURN)
    ("define" . :DEFINE)
    ("setq" . :SETQ)
    ("set" . :SET)
    ("get" . :GET)
    ("put" . :PUT)
    ("call" . :CALL)
    ("proc" . :PROC)
    ("method" . :METHOD)
    ("class" . :CLASS)
    ("instance" . :INSTANCE)
    ("send" . :SEND)
    ("super" . :SUPER)
    ("self" . :SELF)
    ("print" . :PRINT)
    ("format" . :FORMAT)
    ("strcat" . :STRCAT)
    ("strlen" . :STRLEN)
    ("substr" . :SUBSTR)
    ("upcase" . :UPCASE)
    ("downcase" . :DOWNCASE)
    ("numtostr" . :NUMTOSTR)
    ("strtonum" . :STRTONUM))
  "Association list of SCI keywords to token symbols.")

(defparameter *sci-operators-alist*
  '(("+" . :PLUS)
    ("-" . :MINUS)
    ("*" . :TIMES)
    ("/" . :DIVIDE)
    ("=" . :EQUAL)
    ("<>" . :NE)
    ("<" . :LT)
    (">" . :GT)
    ("<=" . :LE)
    (">=" . :GE)
    ("&" . :AND)
    ("|" . :OR)
    ("!" . :NOT))
  "Association list of SCI operators to token symbols.")

(defun sci-valid-identifier-p (s)
  "Check if S is a valid SCI identifier."
  (and (stringp s)
       (plusp (length s))
       (or (alpha-char-p (char s 0))
           (char= (char s 0) #\_))
       (every (lambda (c)
                (or (alphanumericp c) (char= c #\_)))
              s)))

(defun sci-lex-line (line)
  "Split LINE into token list of (type value) pairs."
  (let ((tokens '())
        (chars (coerce line 'list))
        (i 0))
    (labels ((peek () (nth i chars))
             (next-char () (prog1 (nth i chars) (incf i)))
             (eof? () (>= i (length chars)))
             (skip-whitespace ()
               (loop while (and (not (eof?)) (find (peek) '(#\Space #\Tab #\Return #\Newline)))
                     do (next-char)))
             (flush-token (start end type)
               (let ((text (coerce (subseq chars start end) 'string)))
                 (unless (zerop (length text))
                   (push (cons type text) tokens))))
             (scan-number (start)
               (loop while (and (not (eof?)) (digit-char-p (peek)))
                     do (next-char))
               (flush-token start i :number))
             (scan-string (start)
               (next-char)
               (loop while (and (not (eof?)) (char/= (peek) #\"))
                     do (next-char))
               (when (not (eof?)) (next-char))
               (flush-token (1+ start) (1- i) :string))
              (scan-identifier (start)
                (loop while (and (not (eof?))
                                 (or (alphanumericp (peek))
                                     (char= (peek) #\_)))
                      do (next-char))
                (let ((text (coerce (subseq chars start i) 'string)))
                  (push (cons (or (cdr (assoc text *sci-keyword-alist* :test #'string-equal))
                                  :ident)
                              text)
                        tokens))))
      (loop until (eof?)
            do (skip-whitespace)
               (cond
                 ((eof?) (return))
                 ((char= (peek) #\") (scan-string i))
                 ((digit-char-p (peek)) (scan-number i))
                 ((or (alpha-char-p (peek)) (char= (peek) #\_)) (scan-identifier i))
                 ((char= (peek) #\() (push (cons :lparen "(") tokens) (next-char))
                 ((char= (peek) #\)) (push (cons :rparen ")") tokens) (next-char))
                 ((char= (peek) #\') (push (cons :quote "'") tokens) (next-char))
                 ((char= (peek) #\,) (push (cons :comma ",") tokens) (next-char))
                 (t (next-char))))
      (nreverse tokens))))

(defun sci-lex-source (source)
  "Lex complete SCI source string into token stream."
  (let ((all-tokens '()))
    (dolist (line (split-sequence:split-sequence #\Newline source))
      (let ((trimmed (string-trim '(#\Space #\Tab #\Return #\Linefeed) line)))
        (unless (or (zerop (length trimmed))
                    (char= #\; (char trimmed 0)))
          (setf all-tokens (nconc all-tokens (sci-lex-line trimmed))))))
    all-tokens))
