;; src/backend-Z80.lisp — Zilog Z80 code generation backend
;;
;; The Z80 is an 8-bit CPU with: Registers: A, B, C, D, E, H, L, BC, DE,
;; HL, IX, IY, SP; Instructions: ld, push, pop, add, adc, sub, sbc, and,
;; or, xor, cp; Control: jp, jr, call, ret, djnz; Note: Z80 capital-Z is
;; intentional (Zilog's own branding)
;;
;; Output: Z80 assembly (lowercase, common syntax: ld a,(hl), etc.)
;;
;; Uses: A=accumulator, HL=ptr/result, BC=count, DE=dest-ptr/temp (prefer over stack)
(in-package :eightbol)

;;; Shared helpers (symbol naming)

(defun z80-symbol (name)
 "Convert EIGHTBOL identifier to Z80 assembly symbol (PascalCase). COBOL stabby-case supported."
 (pascal-case (format nil "~a" name)))

;;; Top-level entry point

(defmethod compile-to-assembly (ast (cpu (eql :z80)) output-stream)
 (unless (and (listp ast) (eq (first ast) :program))
 (error "EIGHTBOL/Z80: expected :program AST node, got ~s" (first ast)))
 (let* ((class-id (getf (rest ast) :class-id))
 (methods (getf (rest ast) :methods)))
 (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table
                                   pic-size-table pic-width-table pic-frac-bits-table
                                   pic-nybble-semantics-table)
 (load-copybook-tables class-id)
 (let ((*output-stream* output-stream)
 (*class-id* class-id)
 (*slot-table* slot-table)
 (*type-table* type-table)
 (*const-table* const-table)
 (*service-bank-table* service-bank-table)
 (*usage-table* usage-table)
 (*sign-table* sign-table)
 (*pic-size-table* pic-size-table)
 (*pic-width-table* pic-width-table)
 (*pic-frac-bits-table* pic-frac-bits-table)
 (*pic-nybble-semantics-table* pic-nybble-semantics-table))
 (format output-stream
 "~&;;; ~a -- generated by EIGHTBOL for Z80~%;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
 class-id class-id)
 (dolist (method (ensure-list methods))
 (when (and (listp method) (eq (first method) :method))
 (compile-z80-method output-stream method class-id
 slot-table type-table const-table pic-size-table pic-width-table)))))))

;;; Method compilation

(defun compile-z80-method (out method class-id slot-table type-table const-table pic-size-table pic-width-table)
  (let ((*slot-table* slot-table)
        (*type-table* type-table)
        (*const-table* const-table)
        (*pic-size-table* pic-size-table)
        (*pic-width-table* pic-width-table)
        (*class-id* class-id))
    (declare (special *slot-table* *type-table* *const-table* *pic-size-table*
                      *pic-width-table* *class-id*))
    (let* ((method-id (getf (rest method) :method-id))
           (stmts (ensure-list (getf (rest method) :statements)))
           (last-stmt (car (last stmts))))
      (format out "~&Method~a~a:"
              (z80-symbol class-id) (z80-symbol (format nil "~a" method-id)))
      (dolist (stmt stmts)
        (compile-z80-statement out stmt class-id slot-table type-table const-table
                               pic-size-table pic-width-table))
      (unless (and last-stmt (listp last-stmt)
                     (member (first last-stmt)
                             '(:goback :exit-method :exit-program :exit :stop-run)))
        (format out "~&~10tret")))))

;;; GOTO / paragraph labels (simple jp or DEPENDING ON chain)

(defun compile-z80-goto (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
  "Emit Z80 GOTO: unconditional @code{jp}, or compare chain when @code{:depending-on} is set."
  (let ((target (getf (rest stmt) :target))
        (targets (getf (rest stmt) :targets))
        (dep (getf (rest stmt) :depending-on)))
    (if dep
        (let ((tgt-list (or targets (when target (list target)))))
          (when tgt-list
            (compile-z80-load out dep class-id slot-table const-table pic-width-table 1)
            (format out "~&~10tld b, a")
            (let ((n (length tgt-list)))
              (loop for i from 1 below n
                    do (format out "~&~10tld a, b")
                       (format out "~&~10tcp ~d" i)
                       (format out "~&~10tjp z, ~a"
                               (z80-symbol (format nil "~a" (nth (1- i) tgt-list)))))
              (format out "~&~10tjp ~a"
                      (z80-symbol (format nil "~a" (nth (1- n) tgt-list)))))))
        (format out "~&~10tjp ~a"
                (z80-symbol (format nil "~a" (or target (first targets))))))))

;;; Statement dispatch

(defun compile-z80-statement (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
 (unless (and (listp stmt) (first stmt)) (return-from compile-z80-statement))
 (emit-statement-source-comment out stmt)
 (ecase (first stmt)
 (:goback
 (format out "~&~10tret"))
 (:exit-method (format out "~&~10tret"))
 (:exit-program (format out "~&~10tret"))
 (:stop-run (format out "~&~10tret"))
 (:exit (format out "~&~10tret"))
 (:move
 (compile-z80-move out stmt class-id slot-table const-table pic-width-table))
 (:invoke
 (compile-z80-invoke out stmt class-id type-table pic-width-table))
 (:call
 (compile-z80-call out stmt))
 (:if
 (compile-z80-if out stmt class-id slot-table type-table const-table pic-size-table pic-width-table))
 (:add
 (compile-z80-add out stmt class-id slot-table const-table pic-width-table))
 (:subtract
 (compile-z80-subtract out stmt class-id slot-table const-table pic-width-table))
 (:compute
 (compile-z80-compute out stmt class-id slot-table const-table pic-width-table))
 (:set
 (compile-z80-set out stmt class-id slot-table const-table pic-width-table))
 (:log-fault
 (format out "~&~10t;; LOG FAULT ~s" (getf (rest stmt) :code)))
 (:debug-break
 (format out "~&~10t;; DEBUG BREAK ~s" (getf (rest stmt) :code)))
 (:perform
 (compile-z80-perform out stmt class-id slot-table type-table const-table pic-width-table))
 (:string-blt
 (compile-z80-string-blt out stmt class-id slot-table const-table))
 (:goto
 (format out "~&~10tjp ~a" (z80-symbol (format nil "~a" (or (getf (rest stmt) :target) (first (getf (rest stmt) :targets)))))))
 (:paragraph
 (let ((name (if (eq (first stmt) :paragraph)
                  (second stmt)
                  (or (getf (rest stmt) :paragraph) (second stmt)))))
 (when name (format out "~&~a:" (z80-symbol (format nil "~a" name))))))
 (:evaluate
 (compile-z80-evaluate out stmt class-id slot-table type-table const-table pic-size-table pic-width-table))
 (:inspect
 (compile-z80-inspect out stmt class-id slot-table const-table pic-size-table pic-width-table))
 (:copy (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
 (getf (rest stmt) :name)))))

;;; Expression / value emission

(defun z80-expr-is-constant-p (expr const-table)
  "True if EXPR is a compile-time constant. CONST-TABLE is ignored; use *CONST-TABLE*."
  (declare (ignore const-table))
  (or (numberp expr)
      (and (stringp expr) (constant-p expr))))

(defun z80-value (expr &optional const-table)
  "Return assembly text for EXPR. CONST-TABLE is ignored; *CONST-TABLE* is used."
  (declare (ignore const-table))
  (cond
    ((numberp expr) (format nil "~d" expr))
    ((and (stringp expr) (constant-p expr))
     (format nil "~d" (constant-value expr)))
    ((stringp expr) (bare-data-assembly-symbol expr *class-id*))
 ((eq expr :self) "Self")
 ((and (listp expr) (eq (first expr) :of))
 (z80-symbol (format nil "~a-~a" (third expr) (second expr))))
 (t (format nil "~a" expr))))

(defun compile-z80-load (out expr class-id slot-table const-table pic-width-table &optional (width (operand-width expr pic-width-table)))
 "Load EXPR into A (width=1) or HL (width=2). Uses ld a,n / ld hl,#n for immediates, ld a,(addr) / ld hl,(addr) for memory."
 (cond
 ((numberp expr)
 (if (= (or width 1) 2)
 (format out "~&~10tld hl, #~d" expr)
 (format out "~&~10tld a, ~d" expr)))
 ((and (stringp expr) (constant-p expr))
 (if (= (or width 1) 2)
 (format out "~&~10tld hl, #~d" (constant-value expr))
 (format out "~&~10tld a, ~d" (constant-value expr))))
 ((stringp expr)
 (if (= (or width 1) 2)
 (format out "~&~10tld hl, (~a)" (bare-data-assembly-symbol expr class-id))
 (format out "~&~10tld a, (~a)" (bare-data-assembly-symbol expr class-id))))
 ((and (listp expr) (eq (first expr) :of))
 (let ((slot (second expr)) (obj (third expr)))
 (when (member obj '(:self "Self" self) :test #'equal)
 (format out "~&~10tld hl, (Self)")
 (format out "~&~10tld de, #~a" (slot-symbol slot class-id))
 (format out "~&~10tadd hl, de")
 (if (= (or width 1) 2)
 (progn
 (format out "~&~10tld a, (hl)")
 (format out "~&~10tinc hl")
 (format out "~&~10tld h, (hl)")
 (format out "~&~10tld l, a"))
 (format out "~&~10tld a, (hl)")))))
 ((and (listp expr) (eq (first expr) :subscript))
 (compile-z80-load out (third expr) class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tld c, a")
 (format out "~&~10tld b, 0")
 (format out "~&~10tld hl, ~a" (bare-data-assembly-symbol (second expr) class-id))
 (format out "~&~10tadd hl, bc")
 (when (= (or width 1) 2)
 (format out "~&~10tadd hl, bc"))
 (if (= (or width 1) 2)
 (progn
 (format out "~&~10tld a, (hl)")
 (format out "~&~10tinc hl")
 (format out "~&~10tld h, (hl)")
 (format out "~&~10tld l, a"))
 (format out "~&~10tld a, (hl)")))
 ((and (listp expr) (eq (first expr) :shift-left))
 (let ((n (if (numberp (third expr)) (third expr) 1)))
 (compile-z80-load out (second expr) class-id slot-table const-table pic-width-table)
 (dotimes (_ n) (format out "~&~10tadd a, a"))))
 ((and (listp expr) (eq (first expr) :shift-right))
 (let ((n (if (numberp (third expr)) (third expr) 1)))
 (compile-z80-load out (second expr) class-id slot-table const-table pic-width-table)
 (dotimes (_ n) (format out "~&~10tsrl a"))))
 ((and (listp expr) (eq (first expr) :bit-and))
 (compile-z80-load out (second expr) class-id slot-table const-table pic-width-table)
 (let ((rhs (third expr)))
 (if (z80-expr-is-constant-p rhs const-table)
 (format out "~&~10tand ~a" (z80-value rhs const-table))
 (progn (format out "~&~10tld b, a")
 (compile-z80-load out rhs class-id slot-table const-table pic-width-table)
 (format out "~&~10tand b")))))
 ((and (listp expr) (eq (first expr) :bit-or))
 (compile-z80-load out (second expr) class-id slot-table const-table pic-width-table)
 (let ((rhs (third expr)))
 (if (z80-expr-is-constant-p rhs const-table)
 (format out "~&~10tor ~a" (z80-value rhs const-table))
 (progn (format out "~&~10tld b, a")
 (compile-z80-load out rhs class-id slot-table const-table pic-width-table)
 (format out "~&~10tor b")))))
 ((and (listp expr) (eq (first expr) :bit-xor))
 (compile-z80-load out (second expr) class-id slot-table const-table pic-width-table)
 (let ((rhs (third expr)))
 (if (z80-expr-is-constant-p rhs const-table)
 (format out "~&~10txor ~a" (z80-value rhs const-table))
 (progn (format out "~&~10tld b, a")
 (compile-z80-load out rhs class-id slot-table const-table pic-width-table)
 (format out "~&~10txor b")))))
 ((and (listp expr) (eq (first expr) :bit-not))
 (compile-z80-load out (second expr) class-id slot-table const-table pic-width-table)
 (format out "~&~10tcpl"))
 (t
 (format out "~&~10t;; Unsupported load ~s" expr))))

;;; MOVE

(defun compile-z80-move (out stmt class-id slot-table const-table pic-width-table)
 (let ((from (getf (rest stmt) :from))
 (to (getf (rest stmt) :to))
 (from-w (expression-operand-width from pic-width-table))
 (to-w (operand-width to pic-width-table)))
 (backend-unsupported-operand-width :z80 :move (max from-w to-w) 2)
 (compile-z80-load out from class-id slot-table const-table pic-width-table)
 (cond
 ((stringp to)
 (if (= (or to-w 1) 2)
 (format out "~&~10tld (~a), hl" (bare-data-assembly-symbol to class-id))
 (format out "~&~10tld (~a), a" (bare-data-assembly-symbol to class-id))))
 ((and (listp to) (eq (first to) :of))
 (let ((slot (second to)) (obj (third to)))
 (when (member obj '(:self "Self" self) :test #'equal)
 (if (= (or to-w 1) 2)
 (progn
 (format out "~&~10tpush hl")
 (format out "~&~10tld hl, (Self)")
 (format out "~&~10tld de, #~a" (slot-symbol slot class-id))
 (format out "~&~10tadd hl, de")
 (format out "~&~10tpop de")
 (format out "~&~10tld (hl), e")
 (format out "~&~10tinc hl")
 (format out "~&~10tld (hl), d"))
 (progn
 (format out "~&~10tld hl, (Self)")
 (format out "~&~10tld de, #~a" (slot-symbol slot class-id))
 (format out "~&~10tadd hl, de")
 (format out "~&~10tld (hl), a"))))))
 ((and (listp to) (eq (first to) :subscript))
 (if (= (or to-w 1) 2)
 (progn
 (format out "~&~10tpush hl")
 (compile-z80-load out (third to) class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tld c, a")
 (format out "~&~10tld b, 0")
 (format out "~&~10tld hl, ~a" (bare-data-assembly-symbol (second to) class-id))
 (format out "~&~10tadd hl, bc")
 (format out "~&~10tadd hl, bc")
 (format out "~&~10tpop de")
 (format out "~&~10tld (hl), e")
 (format out "~&~10tinc hl")
 (format out "~&~10tld (hl), d"))
 (progn
 (format out "~&~10tpush af")
 (compile-z80-load out (third to) class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tld c, a")
 (format out "~&~10tld b, 0")
 (format out "~&~10tld hl, ~a" (bare-data-assembly-symbol (second to) class-id))
 (format out "~&~10tadd hl, bc")
 (format out "~&~10tpop af")
 (format out "~&~10tld (hl), a"))))
 (t (format out "~&~10t;; Unsupported store to ~s" to)))))

;;; INVOKE

(defun compile-z80-invoke (out stmt class-id type-table pic-width-table)
  (declare (ignore type-table))
  (let ((object (getf (rest stmt) :object))
        (method (getf (rest stmt) :method))
        (returning (getf (rest stmt) :returning)))
    (let ((method-sym (z80-symbol (format nil "~a" method))))
      (cond
        ((member object '(:self "Self" self) :test #'equal)
         (format out "~&~10tcall Invoke~a~a" (z80-symbol class-id) method-sym))
        (t
         (let* ((obj-name (z80-symbol (format nil "~a" object)))
                (obj-class (or (var-class obj-name) "Unknown")))
           (format out "~&~10tcall Call~a~a" obj-class method-sym)))))
    (when returning
      (let ((ret-w (operand-width returning pic-width-table)))
        (if (= (or ret-w 1) 2)
            (format out "~&~10tld (~a), hl" (bare-data-assembly-symbol returning class-id))
            (format out "~&~10tld (~a), a" (bare-data-assembly-symbol returning class-id)))))))

;;; CALL

(defun compile-z80-call (out stmt)
 (let ((target (getf (rest stmt) :target))
 (service (getf (rest stmt) :service))
 (library (getf (rest stmt) :library)))
 (declare (ignore library))
 (let ((name (z80-symbol (format nil "~a" (or service target)))))
 (format out "~&~10tcall ~a" name))))

;;; IF

(defvar *z80-label* 0)

(defun z80-label (prefix)
 (format nil "_~a~d" prefix (incf *z80-label*)))

(defun compile-z80-if (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
 (let ((condition (getf (rest stmt) :condition))
 (then-stmts (getf (rest stmt) :then))
 (else-stmts (getf (rest stmt) :else))
 (lbl-else (z80-label "else"))
 (lbl-end (z80-label "end")))
 (compile-z80-condition out condition class-id slot-table type-table const-table pic-width-table lbl-else)
 (dolist (s (ensure-list then-stmts))
 (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (when (and else-stmts (not (null else-stmts)))
 (format out "~&~10tjp ~a" lbl-end))
 (format out "~&~a:" lbl-else)
 (when (and else-stmts (not (null else-stmts)))
 (dolist (s (ensure-list else-stmts))
 (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (format out "~&~a:" lbl-end))))

(defun compile-z80-condition (out condition class-id slot-table type-table const-table pic-width-table branch-label)
 (cond
 ((and (listp condition) (member (first condition) '(= equal < less > greater) :test #'eq))
 (let ((lhs (second condition)) (rhs (third condition)) (op (first condition))
 (w (max (or (operand-width lhs pic-width-table) 1)
 (or (operand-width rhs pic-width-table) 1))))
 (if (= w 2)
 (progn
 (compile-z80-load out lhs class-id slot-table const-table pic-width-table 2)
 (format out "~&~10tpush hl")
 (compile-z80-load out rhs class-id slot-table const-table pic-width-table 2)
 (format out "~&~10tpop de")
 (format out "~&~10tor a")
 (format out "~&~10tsbc hl, de")
 (ecase op
 ((= equal) (format out "~&~10tjp nz, ~a" branch-label))
 ((< less) (format out "~&~10tjp nc, ~a" branch-label))
 ((> greater)
 (format out "~&~10tjp z, ~a" branch-label)
 (format out "~&~10tjp nc, ~a" branch-label))))
 (progn
 (compile-z80-load out lhs class-id slot-table const-table pic-width-table)
 (format out "~&~10tld b, a")
 (compile-z80-load out rhs class-id slot-table const-table pic-width-table)
 (format out "~&~10tcp b")
 (ecase op
 ((= equal) (format out "~&~10tjp nz, ~a" branch-label))
 ((< less) (format out "~&~10tjp nc, ~a" branch-label))
 ((> greater) (format out "~&~10tjp c, ~a" branch-label)))))))
 ((and (listp condition) (eq (first condition) :is-zero))
 (let ((ex (second condition))
 (w (operand-width ex pic-width-table)))
 (compile-z80-load out ex class-id slot-table const-table pic-width-table)
 (if (= (or w 1) 2)
 (progn
 (format out "~&~10tld a, h")
 (format out "~&~10tor l"))
 (format out "~&~10tor a"))
 (format out "~&~10tjp nz, ~a" branch-label)))
 ((and (listp condition) (eq (first condition) :is-not-zero))
 (let ((ex (second condition))
 (w (operand-width ex pic-width-table)))
 (compile-z80-load out ex class-id slot-table const-table pic-width-table)
 (if (= (or w 1) 2)
 (progn
 (format out "~&~10tld a, h")
 (format out "~&~10tor l"))
 (format out "~&~10tor a"))
 (format out "~&~10tjp z, ~a" branch-label)))
 ((and (listp condition) (eq (first condition) :and))
 (compile-z80-condition out (second condition) class-id slot-table type-table const-table pic-width-table branch-label)
 (compile-z80-condition out (third condition) class-id slot-table type-table const-table pic-width-table branch-label))
 ((and (listp condition) (eq (first condition) :or))
 (let ((lbl-cond2 (z80-label "or"))
 (lbl-skip (z80-label "skip")))
 (compile-z80-condition out (second condition) class-id slot-table type-table const-table pic-width-table lbl-cond2)
 (format out "~&~10tjp ~a" lbl-skip)
 (format out "~&~a:" lbl-cond2)
 (compile-z80-condition out (third condition) class-id slot-table type-table const-table pic-width-table branch-label)
 (format out "~&~a:" lbl-skip)))
 ((and (listp condition) (eq (first condition) :bit-and))
 (compile-z80-load out condition class-id slot-table const-table pic-width-table)
 (format out "~&~10tor a")
 (format out "~&~10tjp z, ~a" branch-label))
 ((and (listp condition) (eq (first condition) :not)
 (listp (second condition)) (member (first (second condition)) '(= equal)))
 (let ((inner (second condition)))
 (compile-z80-load out (second inner) class-id slot-table const-table pic-width-table)
 (format out "~&~10tld b, a")
 (compile-z80-load out (third inner) class-id slot-table const-table pic-width-table)
 (format out "~&~10tcp b")
 (format out "~&~10tjp z, ~a" branch-label)))
 (t
 (format out "~&~10t;; Unsupported condition ~s" condition)
 (format out "~&~10tjp ~a" branch-label))))

;;; EVALUATE statement

(defun compile-z80-evaluate (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
 (let ((subject (getf (rest stmt) :subject))
 (clauses (getf (rest stmt) :when-clauses))
 (lbl-end (z80-label "eval")))
 (dolist (clause (ensure-list clauses))
 (cond
 ((eq (first clause) :when-other)
 (dolist (s (ensure-list (second clause)))
 (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table)))
 ((eq (first clause) :when)
 (let ((phrases (second clause))
 (stmts (third clause))
 (lbl-next (z80-label "when")))
 (cond
 ((eq phrases 'eightbol::any)
 (dolist (s (ensure-list stmts))
 (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (format out "~&~10tjp ~a" lbl-end))
 ((or (eq phrases 'eightbol::true) (equal phrases "TRUE"))
 (compile-z80-load out subject class-id slot-table const-table pic-width-table)
 (if (= (or (operand-width subject pic-width-table) 1) 2)
     (progn (format out "~&~10tld a, h")
            (format out "~&~10tor l"))
     (format out "~&~10tor a"))
 (format out "~&~10tjp z, ~a" lbl-next)
 (dolist (s (ensure-list stmts))
   (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (format out "~&~10tjp ~a" lbl-end)
 (format out "~&~a:" lbl-next))
 ((or (and (symbolp phrases) (string= (symbol-name phrases) "FALSE"))
      (equal phrases "FALSE"))
 (compile-z80-load out subject class-id slot-table const-table pic-width-table)
 (if (= (or (operand-width subject pic-width-table) 1) 2)
     (progn (format out "~&~10tld a, h")
            (format out "~&~10tor l"))
     (format out "~&~10tor a"))
 (format out "~&~10tjp nz, ~a" lbl-next)
 (dolist (s (ensure-list stmts))
   (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (format out "~&~10tjp ~a" lbl-end)
 (format out "~&~a:" lbl-next))
 ((and (listp phrases) (eq (first phrases) :not))
 (compile-z80-load out subject class-id slot-table const-table pic-width-table)
 (format out "~&~10tld b, a")
 (compile-z80-load out (second phrases) class-id slot-table const-table pic-width-table)
 (format out "~&~10tcp b")
 (format out "~&~10tjp z, ~a" lbl-next)
 (dolist (s (ensure-list stmts))
 (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (format out "~&~10tjp ~a" lbl-end)
 (format out "~&~a:" lbl-next))
 ((and (listp phrases) (member (first phrases) '(:through :thru)))
 (let ((lo (second phrases)) (hi (third phrases)))
 (compile-z80-load out subject class-id slot-table const-table pic-width-table)
 (format out "~&~10tld b, a")
 (compile-z80-load out lo class-id slot-table const-table pic-width-table)
 (format out "~&~10tcp b")
 (format out "~&~10tjp c, ~a" lbl-next)
 (compile-z80-load out hi class-id slot-table const-table pic-width-table)
 (format out "~&~10tld c, a")
 (format out "~&~10tld a, b")
 (format out "~&~10tcp c")
 (format out "~&~10tjp nc, ~a" lbl-next)
 (dolist (s (ensure-list stmts))
 (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (format out "~&~10tjp ~a" lbl-end)
 (format out "~&~a:" lbl-next)))
 (t
 (let ((phrase-expr (if (listp phrases) (second phrases) phrases)))
 (compile-z80-load out subject class-id slot-table const-table pic-width-table)
 (format out "~&~10tld b, a")
 (compile-z80-load out phrase-expr class-id slot-table const-table pic-width-table)
 (format out "~&~10tcp b")
 (format out "~&~10tjp nz, ~a" lbl-next))
 (dolist (s (ensure-list stmts))
 (compile-z80-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
 (format out "~&~10tjp ~a" lbl-end)
 (format out "~&~a:" lbl-next)))))))
 (format out "~&~a:" lbl-end)))

;;; INSPECT statement

(defun compile-z80-inspect (out stmt class-id slot-table const-table pic-size-table pic-width-table)
 (let ((target (getf (rest stmt) :target))
 (tally (getf (rest stmt) :tallying))
 (conv-from (getf (rest stmt) :converting))
 (conv-to (getf (rest stmt) :to))
 (repl-by (getf (rest stmt) :by)))
 (let ((tgt-sym (z80-symbol (format nil "~a" target))))
 (cond
 (tally
 (let ((tally-sym (z80-symbol (format nil "~a" tally))))
 (format out "~&~10t;; INSPECT ~a TALLYING ~a FOR CHARACTERS" target tally)
 (format out "~&~10tld hl, ~a" tgt-sym)
 (let ((lbl (z80-label "tally"))
 (lbl-done (z80-label "tallyd"))
 (lbl-skip (z80-label "tallys")))
 (format out "~&~a:" lbl)
 (format out "~&~10tld a, (hl)")
 (format out "~&~10tor a")
 (format out "~&~10tjp z, ~a" lbl-done)
 (format out "~&~10tld a, (~a)" tally-sym)
 (format out "~&~10tinc a")
 (format out "~&~10tld (~a), a" tally-sym)
 (format out "~&~a:" lbl-skip)
 (format out "~&~10tinc hl")
 (format out "~&~10tjp ~a" lbl)
 (format out "~&~a:" lbl-done))))
 (conv-from
 (format out "~&~10t;; INSPECT ~a CONVERTING" target)
 (format out "~&~10tld hl, ~a" tgt-sym)
 (let ((lbl (z80-label "insp"))
 (lbl-next (z80-label "inspn"))
 (lbl-done (z80-label "inspd")))
 (format out "~&~a:" lbl)
 (format out "~&~10tld a, (hl)")
 (format out "~&~10tor a")
 (format out "~&~10tjp z, ~a" lbl-done)
 (if (z80-expr-is-constant-p conv-from const-table)
 (format out "~&~10tcp ~a" (z80-value conv-from const-table))
 (progn
 (format out "~&~10tld b, a")
 (compile-z80-load out conv-from class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tcp b")))
 (format out "~&~10tjp nz, ~a" lbl-next)
 (compile-z80-load out conv-to class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tld (hl), a")
 (format out "~&~a:" lbl-next)
 (format out "~&~10tinc hl")
 (format out "~&~10tjp ~a" lbl)
 (format out "~&~a:" lbl-done)))
 (repl-by
 (let ((len (or (pic-size (format nil "~a" target)) 64)))
 (format out "~&~10t;; INSPECT ~a REPLACING CHARACTERS BY ~a" target repl-by)
 (compile-z80-load out repl-by class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tld hl, ~a" tgt-sym)
 (let ((lbl (z80-label "insp")))
 (format out "~&~10tld b, ~d" len)
 (format out "~&~a:" lbl)
 (format out "~&~10tld (hl), a")
 (format out "~&~10tinc hl")
 (format out "~&~10tdjnz ~a" lbl))))))))

;;; ADD / SUBTRACT / COMPUTE / SET

(defun compile-z80-add (out stmt class-id slot-table const-table pic-width-table)
  (let* ((from (getf (rest stmt) :from))
         (to (getf (rest stmt) :to))
         (giving (getf (rest stmt) :giving))
         (result (or giving (and (stringp to) to)))
         (w (max (operand-width (or result to) pic-width-table)
                 (expression-operand-width from pic-width-table)
                 (operand-width to pic-width-table)))
         (bcd-p (when result (usage-bcd-p (expr-to-width-name result)))))
    (backend-unsupported-operand-width :z80 :add w 2)
    (if (= (or w 1) 2)
        (progn
          ;; 16-bit: use DE for temp (ex de,hl) instead of stack
          (compile-z80-load out to class-id slot-table const-table pic-width-table 2)
          (format out "~&~10tex de, hl")
          (compile-z80-load out from class-id slot-table const-table pic-width-table 2)
          (format out "~&~10tadd hl, de")
          (when result
            (format out "~&~10tld (~a), hl" (z80-symbol (format nil "~a" result)))))
        (progn
          (compile-z80-load out to class-id slot-table const-table pic-width-table)
          (format out "~&~10tld b, a")
          (compile-z80-load out from class-id slot-table const-table pic-width-table)
          (format out "~&~10tadd a, b")
          (when bcd-p (format out "~&~10tdaa"))
          (let ((dest (or giving (and (stringp to) to))))
            (when dest
              (format out "~&~10tld (~a), a" (z80-symbol (format nil "~a" dest)))))))))

(defun compile-z80-subtract (out stmt class-id slot-table const-table pic-width-table)
  (let* ((from (getf (rest stmt) :from))
         (from-target (getf (rest stmt) :from-target))
         (giving (getf (rest stmt) :giving))
         (dest (or giving from-target))
         (w (max (operand-width dest pic-width-table)
                 (expression-operand-width from pic-width-table)
                 (operand-width from-target pic-width-table)))
         (bcd-p (when dest (usage-bcd-p (expr-to-width-name dest)))))
    (backend-unsupported-operand-width :z80 :subtract w 2)
    (if (= (or w 1) 2)
        (progn
          ;; 16-bit: use DE for temp; HL=from_target, DE=from, then ex de,hl for sbc
          (compile-z80-load out from-target class-id slot-table const-table pic-width-table 2)
          (format out "~&~10tex de, hl")
          (compile-z80-load out from class-id slot-table const-table pic-width-table 2)
          (format out "~&~10tex de, hl")
          (format out "~&~10tscf")
          (format out "~&~10tsbc hl, de")
          (format out "~&~10tld (~a), hl" (z80-symbol (format nil "~a" dest))))
        (progn
          (compile-z80-load out from-target class-id slot-table const-table pic-width-table)
          (format out "~&~10tld b, a")
          (compile-z80-load out from class-id slot-table const-table pic-width-table)
          (format out "~&~10tld c, a")
          (format out "~&~10tld a, b")
          (format out "~&~10tsub c")
          ;; Z80 has no DAS; BCD subtract needs software correction (deferred)
          (format out "~&~10tld (~a), a" (z80-symbol (format nil "~a" dest)))))))

(defun compile-z80-compute (out stmt class-id slot-table const-table pic-width-table)
 (let* ((target (getf (rest stmt) :target))
 (expr (getf (rest stmt) :expression))
 (w (max (operand-width target pic-width-table)
         (expression-operand-width expr pic-width-table))))
 (backend-unsupported-operand-width :z80 :compute w 2)
 (compile-z80-load out expr class-id slot-table const-table pic-width-table)
 (if (= (or w 1) 2)
 (format out "~&~10tld (~a), hl" (bare-data-assembly-symbol target class-id))
 (format out "~&~10tld (~a), a" (bare-data-assembly-symbol target class-id)))))

(defun compile-z80-set (out stmt class-id slot-table const-table pic-width-table)
 (let* ((target (getf (rest stmt) :target))
       (value (getf (rest stmt) :value))
       (up-by (getf (rest stmt) :up-by))
       (down-by (getf (rest stmt) :down-by))
       (by-expr (getf (rest stmt) :by))
       (address-of (getf (rest stmt) :address-of))
       (to-self (getf (rest stmt) :to-self))
       (w (operand-width (or target to-self up-by down-by) pic-width-table)))
  (cond
   (up-by
    (compile-z80-add out (list :add :from by-expr :to up-by :giving nil) class-id slot-table const-table pic-width-table))
   (down-by
    (compile-z80-subtract out (list :subtract :from by-expr :from-target down-by :giving nil) class-id slot-table const-table pic-width-table))
   ((and address-of target)
    (let ((src address-of) (dest target))
      (cond
        ((and (listp src) (eq :of (first src))
              (member (third src) '(:self "Self" self) :test #'equal))
         (format out "~&~10tld hl, (Self)")
         (format out "~&~10tld de, #~a" (slot-symbol (second src) class-id))
         (format out "~&~10tadd hl, de"))
        ((stringp src)
         (format out "~&~10tld hl, ~a" (bare-data-assembly-symbol src class-id))))
      (cond
        ((stringp dest)
         (format out "~&~10tld (~a), hl" (bare-data-assembly-symbol dest class-id)))
        (t (format out "~&~10t;; Unsupported SET ADDRESS OF target ~s" dest)))))
   (to-self
    (format out "~&~10tld hl, (Self)")
    (format out "~&~10tld (~a), hl" (bare-data-assembly-symbol to-self class-id)))
   (t
 (compile-z80-load out value class-id slot-table const-table pic-width-table)
 (cond
 ((stringp target)
 (if (= (or w 1) 2)
 (format out "~&~10tld (~a), hl" (bare-data-assembly-symbol target class-id))
 (format out "~&~10tld (~a), a" (bare-data-assembly-symbol target class-id))))
 ((and (listp target) (eq (first target) :of))
 (let ((slot (second target)) (obj (third target)))
 (when (member obj '(:self "Self" self) :test #'equal)
 (if (= (or w 1) 2)
 (progn
 (format out "~&~10tex de, hl")
 (format out "~&~10tld hl, (Self)")
 (format out "~&~10tld bc, #~a" (slot-symbol slot class-id))
 (format out "~&~10tadd hl, bc")
 (format out "~&~10tld (hl), e")
 (format out "~&~10tinc hl")
 (format out "~&~10tld (hl), d"))
 (progn
 (format out "~&~10tld hl, (Self)")
 (format out "~&~10tld de, #~a" (slot-symbol slot class-id))
 (format out "~&~10tadd hl, de")
 (format out "~&~10tld (hl), a"))))))
 ((and (listp target) (eq (first target) :subscript))
 (if (= (or w 1) 2)
 (progn
 (format out "~&~10tex de, hl")
 (compile-z80-load out (third target) class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tld c, a")
 (format out "~&~10tld b, 0")
 (format out "~&~10tld hl, ~a" (bare-data-assembly-symbol (second target) class-id))
 (format out "~&~10tadd hl, bc")
 (format out "~&~10tadd hl, bc")
 (format out "~&~10tld (hl), e")
 (format out "~&~10tinc hl")
 (format out "~&~10tld (hl), d"))
 (progn
 (format out "~&~10tld b, a")
 (compile-z80-load out (third target) class-id slot-table const-table pic-width-table 1)
 (format out "~&~10tld c, a")
 (format out "~&~10tld a, b")
 (format out "~&~10tld b, 0")
 (format out "~&~10tld hl, ~a" (bare-data-assembly-symbol (second target) class-id))
 (format out "~&~10tadd hl, bc")
 (format out "~&~10tld (hl), a"))))
   (t (format out "~&~10t;; Unsupported set ~s" target)))))))

;;; PERFORM

(defun compile-z80-perform (out stmt class-id slot-table type-table const-table pic-width-table)
 (let ((proc (getf (rest stmt) :procedure))
 (times (getf (rest stmt) :times))
 (until (getf (rest stmt) :until)))
 (cond
 (times
 (let ((lbl (z80-label "perf"))
 (lbl-done (z80-label "perfd"))
 (times-w (operand-width times pic-width-table)))
 (compile-z80-load out times class-id slot-table const-table pic-width-table)
 (if (= (or times-w 1) 2)
 (progn
 (format out "~&~10tld b, h")
 (format out "~&~10tld c, l")
 (format out "~&~a:" lbl)
 (format out "~&~10tld a, b")
 (format out "~&~10tor c")
 (format out "~&~10tjp z, ~a" lbl-done)
 (format out "~&~10tpush bc")
 (format out "~&~10tcall ~a" (z80-symbol (format nil "~a" proc)))
 (format out "~&~10tpop bc")
 (format out "~&~10tdec bc")
 (format out "~&~10tjp ~a" lbl)
 (format out "~&~a:" lbl-done))
 (progn
 (format out "~&~10tld b, a")
 (format out "~&~a:" lbl)
 (format out "~&~10tpush bc")
 (format out "~&~10tcall ~a" (z80-symbol (format nil "~a" proc)))
 (format out "~&~10tpop bc")
 (format out "~&~10tdjnz ~a" lbl)))))
 (until
 (let ((lbl-loop (z80-label "loop"))
 (lbl-end (z80-label "end")))
 (format out "~&~a:" lbl-loop)
 (compile-z80-condition out until class-id slot-table type-table const-table pic-width-table lbl-end)
 (format out "~&~10tcall ~a" (z80-symbol (format nil "~a" proc)))
 (format out "~&~10tjp ~a" lbl-loop)
 (format out "~&~a:" lbl-end)))
 (t
 (format out "~&~10tcall ~a" (z80-symbol (format nil "~a" proc)))))))
 
;;; STRING BLT

(defun %z80-string-operand-length-expr (source stmt)
  "Return length expression for STRING BLT from STMT or SOURCE :refmod.

@table @asis
@item STMT
Full @code{:string-blt} AST plist (e.g. from @code{parse-eightbol-string}).
@item SOURCE
@code{:source} field; may be a string/symbol or @code{(:refmod ...)} with plist in @code{cdr}.
@end table

@noindent
Matches @code{string-operand-length-expr} in the 6502 backend: @code{LENGTH} clause,
else @code{:length} from reference modification on SOURCE."
  (or (safe-getf (rest stmt) :length)
      (when (and (listp source) (eq (first source) :refmod))
        (safe-getf (rest source) :length))))

(defun z80-string-operand-address (operand)
 "Return Z80 address expression for STRING operand (identifier or :refmod)."
 (cond
 ((and (listp operand) (eq (first operand) :refmod))
 (let* ((base (getf (rest operand) :base))
 (start (getf (rest operand) :start))
 (base-str (z80-symbol (format nil "~a" base))))
 (if (and (integerp start) (= start 1))
 base-str
 (format nil "~a+~d" base-str (1- start)))))
 (t
 (z80-symbol (format nil "~a" operand)))))

(defun compile-z80-string-blt (out stmt class-id slot-table const-table)
 "Emit Z80 block copy loop. Uses HL=src, DE=dest, BC=count."
 (let* ((source (safe-getf (rest stmt) :source))
 (dest (safe-getf (rest stmt) :dest))
 (len-expr (%z80-string-operand-length-expr source stmt))
 (len (cond ((integerp len-expr) len-expr)
 ((and len-expr (z80-expr-is-constant-p len-expr const-table))
 (z80-value len-expr const-table))
 (t 64))))
 (let ((src-addr (z80-string-operand-address source))
 (dst-addr (z80-string-operand-address dest)))
 (format out "~&~10tld hl, ~a" src-addr)
 (format out "~&~10tld de, ~a" dst-addr)
 (let ((lbl (z80-label "blt")))
 (format out "~&~10tld bc, ~d" len)
 (format out "~&~a:" lbl)
 (format out "~&~10tld a, (hl)")
 (format out "~&~10tld (de), a")
 (format out "~&~10tinc hl")
 (format out "~&~10tinc de")
 (format out "~&~10tdec bc")
 (format out "~&~10tld a, b")
 (format out "~&~10tor c")
 (format out "~&~10tjp nz, ~a" lbl)))))

