;; src/backend-i286.lisp — Intel 80286 code generation backend
;;
;; The 80286 is a 16-bit CPU. Registers: AX, BX, CX, DX, SI, DI, BP, SP
;; Segment: CS, DS, SS, ES. Instructions: mov, add, sub, cmp, call, ret, jmp, jz, jnz
;;
;; Output: Intel syntax (mov ax, bx; mov al, [si])
;; Uses: AL/AX=accumulator, BX=temp, SI=index, DI=dest-ptr, CX=count
;;
;; Structure based on backend-Z80.lisp for consistency.
(in-package :eightbol)

;;; ---------------------------------------------------------------
;;; Shared helpers (symbol naming)
;;; ---------------------------------------------------------------

(defun i286-symbol (name)
  "Convert EIGHTBOL identifier to i286 assembly symbol (PascalCase)."
  (to-pascal-case (format nil "~a" name)))

;;; ---------------------------------------------------------------
;;; Top-level entry point
;;; ---------------------------------------------------------------

(defmethod compile-to-assembly (ast (cpu (eql :i286)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/i286: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods  (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table pic-size-table pic-width-table)
        (load-copybook-tables class-id)
      (let ((*usage-table* usage-table)
            (*sign-table* sign-table))
        (declare (ignore service-bank-table sign-table))
        (format output-stream
                "~&;;; ~a -- generated by EIGHTBOL for i286 (80286)~%;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
                class-id class-id)
        (format output-stream "~&~8t.286~%")
        (format output-stream "~&~8t.model small~%")
        (format output-stream "~&~8t.code~2%")
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-i286-method output-stream method class-id
                                slot-table type-table const-table pic-size-table pic-width-table)))))))

;;; ---------------------------------------------------------------
;;; Method compilation
;;; ---------------------------------------------------------------

(defun compile-i286-method (out method class-id slot-table type-table const-table pic-size-table pic-width-table)
  (let ((method-id  (getf (rest method) :method-id))
        (statements (getf (rest method) :statements)))
    (format out "~&Method~a~a proc"
            (i286-symbol class-id) (i286-symbol (format nil "~a" method-id)))
    (dolist (stmt (ensure-list statements))
      (compile-i286-statement out stmt class-id slot-table type-table const-table pic-size-table pic-width-table))
    (format out "~&~8tret")
    (format out "~&Method~a~a endp"
            (i286-symbol class-id) (i286-symbol (format nil "~a" method-id)))))

;;; ---------------------------------------------------------------
;;; Statement dispatch
;;; ---------------------------------------------------------------

(defun compile-i286-statement (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
  (unless (and (listp stmt) (first stmt)) (return-from compile-i286-statement))
  (ecase (first stmt)
    (:goback (format out "~&~8tret"))
    (:exit-method (format out "~&~8tret"))
    (:exit-program (format out "~&~8tret"))
    (:exit (format out "~&~8tret"))
    (:stop-run (format out "~&~8tret"))
    (:move (compile-i286-move out stmt class-id slot-table const-table pic-width-table))
    (:invoke (compile-i286-invoke out stmt class-id type-table pic-width-table))
    (:call (compile-i286-call out stmt))
    (:if (compile-i286-if out stmt class-id slot-table type-table const-table pic-size-table pic-width-table))
    (:add (compile-i286-add out stmt class-id slot-table const-table pic-width-table))
    (:subtract (compile-i286-subtract out stmt class-id slot-table const-table pic-width-table))
    (:compute (compile-i286-compute out stmt class-id slot-table const-table pic-width-table))
    (:set (compile-i286-set out stmt class-id slot-table const-table pic-width-table))
    (:log-fault (format out "~&~8t; LOG FAULT ~s" (getf (rest stmt) :code)))
    (:debug-break (format out "~&~8t; DEBUG BREAK ~s" (getf (rest stmt) :code)))
    (:perform (compile-i286-perform out stmt class-id slot-table type-table const-table pic-width-table))
    (:string-blt (compile-i286-string-blt out stmt class-id slot-table const-table))
    (:goto
     (format out "~&~8tjmp     ~a" (i286-symbol (format nil "~a" (or (getf (rest stmt) :target) (first (getf (rest stmt) :targets)))))))
    (:paragraph
     (let ((name (or (getf (rest stmt) :paragraph) (second stmt))))
       (when name (format out "~&~a:" (i286-symbol (format nil "~a" name))))))
    (:evaluate (compile-i286-evaluate out stmt class-id slot-table type-table const-table pic-size-table pic-width-table))
    (:inspect (compile-i286-inspect out stmt class-id slot-table const-table pic-size-table pic-width-table))
    (:copy (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
                  (getf (rest stmt) :name)))))

;;; ---------------------------------------------------------------
;;; Register helpers
;;; ---------------------------------------------------------------

(defun i286-reg (width)
  "Return accumulator register for width: al (byte) or ax (word)."
  (if (= (or width 1) 2) "ax" "al"))

(defun i286-temp-reg (width)
  "Return temp register for width: bl (byte) or bx (word)."
  (if (= (or width 1) 2) "bx" "bl"))

;;; ---------------------------------------------------------------
;;; Expression / value emission
;;; ---------------------------------------------------------------

(defun i286-expr-is-constant-p (expr const-table)
  (or (numberp expr)
      (and (stringp expr) (constant-p expr const-table))))

(defun i286-value (expr const-table)
  (cond
    ((numberp expr) (format nil "~d" expr))
    ((and (stringp expr) (constant-p expr const-table))
     (format nil "~d" (constant-value expr const-table)))
    ((stringp expr) (i286-symbol expr))
    ((eq expr :self) "Self")
    ((and (listp expr) (eq (first expr) :of))
     (i286-symbol (format nil "~a-~a" (third expr) (second expr))))
    (t (format nil "~a" expr))))

(defun compile-i286-load (out expr class-id slot-table const-table pic-width-table &optional (width (operand-width expr pic-width-table)))
  "Load EXPR into AL (width=1) or AX (width=2). Intel syntax: mov al, n / mov ax, n."
  (let ((reg (i286-reg width)))
    (cond
      ((numberp expr)
       (format out "~&~8tmov     ~a, ~d" reg expr))
      ((and (stringp expr) (constant-p expr const-table))
       (format out "~&~8tmov     ~a, ~d" reg (constant-value expr const-table)))
      ((stringp expr)
       (format out "~&~8tmov     ~a, ~a" reg (i286-symbol expr)))
      ((and (listp expr) (eq (first expr) :of))
       (let ((slot (second expr)) (obj (third expr)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (format out "~&~8tmov     bx, offset Self")
           (format out "~&~8tmov     bx, [bx]")
           (format out "~&~8tmov     ~a, [bx+~a]" reg (slot-symbol slot slot-table class-id)))))
      ((and (listp expr) (eq (first expr) :subscript))
       (let ((arr-name (second expr)) (idx-expr (third expr)))
         (compile-i286-load out idx-expr class-id slot-table const-table pic-width-table 1)
         (format out "~&~8tmov     ah, 0")
         (format out "~&~8tmov     bx, offset ~a" (i286-symbol (format nil "~a" arr-name)))
         (when (= (or width 1) 2)
           (format out "~&~8tshl     ax, 1"))
         (format out "~&~8tadd     bx, ax")
         (format out "~&~8tmov     ~a, [bx]" reg)))
      ((and (listp expr) (eq (first expr) :shift-left))
       (let ((n (if (numberp (third expr)) (third expr) 1)))
         (compile-i286-load out (second expr) class-id slot-table const-table pic-width-table)
         (dotimes (_ n) (format out "~&~8tshl     ~a, 1" reg))))
      ((and (listp expr) (eq (first expr) :shift-right))
       (let ((n (if (numberp (third expr)) (third expr) 1)))
         (compile-i286-load out (second expr) class-id slot-table const-table pic-width-table)
         (dotimes (_ n) (format out "~&~8tshr     ~a, 1" reg))))
      ((and (listp expr) (eq (first expr) :bit-and))
       (compile-i286-load out (second expr) class-id slot-table const-table pic-width-table)
       (let ((rhs (third expr)))
         (if (i286-expr-is-constant-p rhs const-table)
             (format out "~&~8tand     ~a, ~a" reg (i286-value rhs const-table))
             (progn
               (format out "~&~8tmov     cx, ~a" reg)
               (compile-i286-load out rhs class-id slot-table const-table pic-width-table)
               (format out "~&~8tand     ~a, cx" reg)))))
      ((and (listp expr) (eq (first expr) :bit-or))
       (compile-i286-load out (second expr) class-id slot-table const-table pic-width-table)
       (let ((rhs (third expr)))
         (if (i286-expr-is-constant-p rhs const-table)
             (format out "~&~8tor      ~a, ~a" reg (i286-value rhs const-table))
             (progn
               (format out "~&~8tmov     cx, ~a" reg)
               (compile-i286-load out rhs class-id slot-table const-table pic-width-table)
               (format out "~&~8tor      ~a, cx" reg)))))
      ((and (listp expr) (eq (first expr) :bit-xor))
       (compile-i286-load out (second expr) class-id slot-table const-table pic-width-table)
       (let ((rhs (third expr)))
         (if (i286-expr-is-constant-p rhs const-table)
             (format out "~&~8txor     ~a, ~a" reg (i286-value rhs const-table))
             (progn
               (format out "~&~8tmov     cx, ~a" reg)
               (compile-i286-load out rhs class-id slot-table const-table pic-width-table)
               (format out "~&~8txor     ~a, cx" reg)))))
      ((and (listp expr) (eq (first expr) :bit-not))
       (compile-i286-load out (second expr) class-id slot-table const-table pic-width-table)
       (format out "~&~8tnot     ~a" reg))
      (t (format out "~&~8t; Unsupported load ~s" expr)))))

;;; ---------------------------------------------------------------
;;; MOVE
;;; ---------------------------------------------------------------

(defun compile-i286-move (out stmt class-id slot-table const-table pic-width-table)
  (let ((from (getf (rest stmt) :from))
        (to   (getf (rest stmt) :to))
        (to-w (operand-width to pic-width-table))
        (reg  (i286-reg to-w)))
    (compile-i286-load out from class-id slot-table const-table pic-width-table)
    (cond
      ((stringp to)
       (format out "~&~8tmov     ~a, ~a" (i286-symbol to) reg))
      ((and (listp to) (eq (first to) :of))
       (let ((slot (second to)) (obj (third to)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (format out "~&~8tmov     bx, offset Self")
           (format out "~&~8tmov     bx, [bx]")
           (format out "~&~8tmov     [bx+~a], ~a" (slot-symbol slot slot-table class-id) reg))))
      ((and (listp to) (eq (first to) :subscript))
       (let ((arr-name (second to)) (idx-expr (third to)))
         (format out "~&~8tmov     ~a, ~a" (i286-temp-reg to-w) reg)
         (compile-i286-load out idx-expr class-id slot-table const-table pic-width-table 1)
         (format out "~&~8tmov     ah, 0")
         (format out "~&~8tmov     si, offset ~a" (i286-symbol (format nil "~a" arr-name)))
         (when (= (or to-w 1) 2)
           (format out "~&~8tshl     ax, 1"))
         (format out "~&~8tadd     si, ax")
         (format out "~&~8tmov     [si], ~a" (i286-temp-reg to-w))))
      (t (format out "~&~8t; Unsupported store to ~s" to)))))

;;; ---------------------------------------------------------------
;;; INVOKE / CALL
;;; ---------------------------------------------------------------

(defun compile-i286-invoke (out stmt class-id type-table pic-width-table)
  (let ((object   (getf (rest stmt) :object))
        (method   (getf (rest stmt) :method))
        (returning (getf (rest stmt) :returning)))
    (let ((method-sym (i286-symbol (format nil "~a" method))))
      (cond
        ((member object '(:self "Self" self) :test #'equal)
         (format out "~&~8tcall    Invoke~a~a" (i286-symbol class-id) method-sym))
        (t
         (let* ((obj-name (i286-symbol (format nil "~a" object)))
                (obj-class (or (var-class obj-name type-table) "Unknown")))
           (format out "~&~8tcall    Call~a~a" obj-class method-sym))))
      (when returning
        (let ((ret-w (operand-width returning pic-width-table))
              (reg (i286-reg ret-w)))
          (format out "~&~8tmov     ~a, ~a" (i286-symbol (format nil "~a" returning)) reg))))))

(defun compile-i286-call (out stmt)
  (let ((target (getf (rest stmt) :target))
        (service (getf (rest stmt) :service)))
    (let ((name (i286-symbol (format nil "~a" (or service target)))))
      (format out "~&~8tcall    ~a" name))))

;;; ---------------------------------------------------------------
;;; IF / condition
;;; ---------------------------------------------------------------

(defvar *i286-label* 0)

(defun i286-label (prefix)
  (format nil "L~a~d" prefix (incf *i286-label*)))

(defun compile-i286-if (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
  (let ((condition (getf (rest stmt) :condition))
        (then-stmts (getf (rest stmt) :then))
        (else-stmts (getf (rest stmt) :else))
        (lbl-else (i286-label "else"))
        (lbl-end (i286-label "end")))
    (compile-i286-condition out condition class-id slot-table type-table const-table pic-width-table lbl-else)
    (dolist (s (ensure-list then-stmts))
      (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
    (when (and else-stmts (not (null else-stmts)))
      (format out "~&~8tjmp     ~a" lbl-end))
    (format out "~&~a:" lbl-else)
    (when (and else-stmts (not (null else-stmts)))
      (dolist (s (ensure-list else-stmts))
        (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
      (format out "~&~a:" lbl-end))))

(defun compile-i286-condition (out condition class-id slot-table type-table const-table pic-width-table branch-label)
  (cond
    ((and (listp condition) (member (first condition) '(= equal < less > greater) :test #'eq))
     (let ((lhs (second condition)) (rhs (third condition)) (op (first condition))
           (w (max (or (operand-width lhs pic-width-table) 1)
                   (or (operand-width rhs pic-width-table) 1)))
           (acc (i286-reg w))
           (tmp (i286-temp-reg w)))
       (compile-i286-load out lhs class-id slot-table const-table pic-width-table)
       (format out "~&~8tmov     ~a, ~a" tmp acc)
       (compile-i286-load out rhs class-id slot-table const-table pic-width-table)
       (format out "~&~8tcmp     ~a, ~a" acc tmp)
       (ecase op
         ((= equal) (format out "~&~8tjne     ~a" branch-label))
         ((< less)  (format out "~&~8tjge     ~a" branch-label))
         ((> greater) (format out "~&~8tjle     ~a" branch-label)))))
    ((and (listp condition) (eq (first condition) :is-zero))
     (let ((ex (second condition))
           (reg (i286-reg (operand-width ex pic-width-table))))
       (compile-i286-load out ex class-id slot-table const-table pic-width-table)
       (format out "~&~8tor      ~a, ~a" reg reg)
       (format out "~&~8tjnz     ~a" branch-label)))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (let ((ex (second condition))
           (reg (i286-reg (operand-width ex pic-width-table))))
       (compile-i286-load out ex class-id slot-table const-table pic-width-table)
       (format out "~&~8tor      ~a, ~a" reg reg)
       (format out "~&~8tjz      ~a" branch-label)))
    ((and (listp condition) (eq (first condition) :and))
     (compile-i286-condition out (second condition) class-id slot-table type-table const-table pic-width-table branch-label)
     (compile-i286-condition out (third condition) class-id slot-table type-table const-table pic-width-table branch-label))
    ((and (listp condition) (eq (first condition) :or))
     (let ((lbl-cond2 (i286-label "or"))
           (lbl-skip (i286-label "skip")))
       (compile-i286-condition out (second condition) class-id slot-table type-table const-table pic-width-table lbl-cond2)
       (format out "~&~8tjmp     ~a" lbl-skip)
       (format out "~&~a:" lbl-cond2)
       (compile-i286-condition out (third condition) class-id slot-table type-table const-table pic-width-table branch-label)
       (format out "~&~a:" lbl-skip)))
    ((and (listp condition) (eq (first condition) :bit-and))
     (compile-i286-load out condition class-id slot-table const-table pic-width-table)
     (format out "~&~8tor      al, al")
     (format out "~&~8tjnz     ~a" branch-label))
    ((and (listp condition) (eq (first condition) :not)
          (listp (second condition)) (member (first (second condition)) '(= equal)))
     (let ((inner (second condition)))
       (compile-i286-load out (second inner) class-id slot-table const-table pic-width-table)
       (format out "~&~8tmov     bl, al")
       (compile-i286-load out (third inner) class-id slot-table const-table pic-width-table)
       (format out "~&~8tcmp     al, bl")
       (format out "~&~8tje      ~a" branch-label)))
    (t
     (format out "~&~8t; Unsupported condition ~s" condition)
     (format out "~&~8tjmp     ~a" branch-label))))

;;; ---------------------------------------------------------------
;;; EVALUATE statement
;;; ---------------------------------------------------------------

(defun compile-i286-evaluate (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
  (let ((subject (getf (rest stmt) :subject))
        (clauses (getf (rest stmt) :when-clauses))
        (lbl-end (i286-label "eval")))
    (dolist (clause (ensure-list clauses))
      (cond
        ((eq (first clause) :when-other)
         (dolist (s (ensure-list (second clause)))
           (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table)))
        ((eq (first clause) :when)
         (let ((phrases (second clause))
               (stmts (third clause))
               (lbl-next (i286-label "when")))
           (cond
             ((eq phrases 'eightbol::any)
              (dolist (s (ensure-list stmts))
                (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
              (format out "~&~8tjmp     ~a" lbl-end))
             ((or (eq phrases 'eightbol::true) (equal phrases "TRUE"))
              (compile-i286-load out subject class-id slot-table const-table pic-width-table)
              (format out "~&~8tor      al, al")
              (format out "~&~8tjz      ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
              (format out "~&~8tjmp     ~a" lbl-end)
              (format out "~&~a:" lbl-next))
             ((or (eq phrases 'eightbol::false) (equal phrases "FALSE"))
              (compile-i286-load out subject class-id slot-table const-table pic-width-table)
              (format out "~&~8tor      al, al")
              (format out "~&~8tjnz     ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
              (format out "~&~8tjmp     ~a" lbl-end)
              (format out "~&~a:" lbl-next))
             ((and (listp phrases) (eq (first phrases) :not))
              (compile-i286-load out subject class-id slot-table const-table pic-width-table)
              (format out "~&~8tmov     bl, al")
              (compile-i286-load out (second phrases) class-id slot-table const-table pic-width-table)
              (format out "~&~8tcmp     al, bl")
              (format out "~&~8tje      ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
              (format out "~&~8tjmp     ~a" lbl-end)
              (format out "~&~a:" lbl-next))
             ((and (listp phrases) (member (first phrases) '(:through :thru)))
              (let ((lo (second phrases)) (hi (third phrases)))
                (compile-i286-load out subject class-id slot-table const-table pic-width-table)
                (format out "~&~8tmov     bl, al")
                (compile-i286-load out lo class-id slot-table const-table pic-width-table)
                (format out "~&~8tcmp     bl, al")
                (format out "~&~8tja      ~a" lbl-next)
                (compile-i286-load out hi class-id slot-table const-table pic-width-table)
                (format out "~&~8tcmp     al, bl")
                (format out "~&~8tja      ~a" lbl-next)
                (dolist (s (ensure-list stmts))
                  (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
                (format out "~&~8tjmp     ~a" lbl-end)
                (format out "~&~a:" lbl-next)))
             (t
              (let ((phrase-expr (if (listp phrases) (second phrases) phrases)))
                (compile-i286-load out subject class-id slot-table const-table pic-width-table)
                (format out "~&~8tmov     bl, al")
                (compile-i286-load out phrase-expr class-id slot-table const-table pic-width-table)
                (format out "~&~8tcmp     al, bl")
                (format out "~&~8tjne     ~a" lbl-next)
                (dolist (s (ensure-list stmts))
                  (compile-i286-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
                (format out "~&~8tjmp     ~a" lbl-end)
                (format out "~&~a:" lbl-next))))))))
    (format out "~&~a:" lbl-end)))

;;; ---------------------------------------------------------------
;;; INSPECT statement
;;; ---------------------------------------------------------------

(defun compile-i286-inspect (out stmt class-id slot-table const-table pic-size-table pic-width-table)
  (let ((target (getf (rest stmt) :target))
        (tally (getf (rest stmt) :tallying))
        (conv-from (getf (rest stmt) :converting))
        (conv-to (getf (rest stmt) :to))
        (repl-by (getf (rest stmt) :by)))
    (let ((tgt-sym (i286-symbol (format nil "~a" target))))
      (cond
        (tally
         (let ((tally-sym (i286-symbol (format nil "~a" tally))))
           (format out "~&~8t; INSPECT ~a TALLYING ~a FOR CHARACTERS" target tally)
           (format out "~&~8tmov     si, offset ~a" tgt-sym)
           (let ((lbl (i286-label "tally")) (lbl-done (i286-label "tallyd")))
             (format out "~&~a:" lbl)
             (format out "~&~8tmov     al, [si]")
             (format out "~&~8tor      al, al")
             (format out "~&~8tjz      ~a" lbl-done)
             (format out "~&~8tmov     al, ~a" tally-sym)
             (format out "~&~8tinc     al")
             (format out "~&~8tmov     ~a, al" tally-sym)
             (format out "~&~8tinc     si")
             (format out "~&~8tjmp     ~a" lbl)
             (format out "~&~a:" lbl-done))))
        (conv-from
         (format out "~&~8t; INSPECT ~a CONVERTING" target)
         (format out "~&~8tmov     si, offset ~a" tgt-sym)
         (let ((lbl (i286-label "insp")) (lbl-next (i286-label "inspn")) (lbl-done (i286-label "inspd")))
           (format out "~&~a:" lbl)
           (format out "~&~8tmov     al, [si]")
           (format out "~&~8tor      al, al")
           (format out "~&~8tjz      ~a" lbl-done)
           (if (i286-expr-is-constant-p conv-from const-table)
               (format out "~&~8tcmp     al, ~a" (i286-value conv-from const-table))
               (progn
                 (format out "~&~8tmov     bl, al")
                 (compile-i286-load out conv-from class-id slot-table const-table pic-width-table 1)
                 (format out "~&~8tcmp     al, bl")))
           (format out "~&~8tjne     ~a" lbl-next)
           (compile-i286-load out conv-to class-id slot-table const-table pic-width-table 1)
           (format out "~&~8tmov     [si], al")
           (format out "~&~a:" lbl-next)
           (format out "~&~8tinc     si")
           (format out "~&~8tjmp     ~a" lbl)
           (format out "~&~a:" lbl-done)))
        (repl-by
         (let ((len (or (pic-size (format nil "~a" target) pic-size-table) 64)))
           (format out "~&~8t; INSPECT ~a REPLACING CHARACTERS BY ~a" target repl-by)
           (compile-i286-load out repl-by class-id slot-table const-table pic-width-table 1)
           (format out "~&~8tmov     si, offset ~a" tgt-sym)
           (let ((lbl (i286-label "insp")))
             (format out "~&~8tmov     cx, ~d" len)
             (format out "~&~a:" lbl)
             (format out "~&~8tmov     [si], al")
             (format out "~&~8tinc     si")
             (format out "~&~8tloop    ~a" lbl))))))))

;;; ---------------------------------------------------------------
;;; ADD / SUBTRACT / COMPUTE / SET
;;; ---------------------------------------------------------------

(defun compile-i286-add (out stmt class-id slot-table const-table pic-width-table)
  (let ((from (getf (rest stmt) :from))
        (to (getf (rest stmt) :to))
        (giving (getf (rest stmt) :giving))
        (result (or giving (and (stringp to) to) (and (listp to) (eq (first to) :subscript) to)))
        (w (operand-width (or result to) pic-width-table))
        (bcd-p (when result (usage-bcd-p (expr-to-width-name result))))
        (acc (i286-reg w))
        (tmp (i286-temp-reg w)))
    (compile-i286-load out to class-id slot-table const-table pic-width-table)
    (format out "~&~8tmov     ~a, ~a" tmp acc)
    (compile-i286-load out from class-id slot-table const-table pic-width-table)
    (format out "~&~8tadd     ~a, ~a" acc tmp)
    (when (and bcd-p (= (or w 1) 1)) (format out "~&~8tdaa"))
    (when result
      (cond
        ((stringp result)
         (format out "~&~8tmov     ~a, ~a" (i286-symbol result) acc))
        ((and (listp result) (eq (first result) :subscript))
         (let ((arr-name (second result)) (idx-expr (third result)))
           (format out "~&~8tmov     ~a, ~a" (i286-temp-reg w) acc)
           (compile-i286-load out idx-expr class-id slot-table const-table pic-width-table 1)
           (format out "~&~8tmov     ah, 0")
           (format out "~&~8tmov     si, offset ~a" (i286-symbol (format nil "~a" arr-name)))
           (when (= (or w 1) 2)
             (format out "~&~8tshl     ax, 1"))
           (format out "~&~8tadd     si, ax")
           (format out "~&~8tmov     [si], ~a" (i286-temp-reg w))))
        (t (format out "~&~8t; Unsupported add result ~s" result))))))

(defun compile-i286-subtract (out stmt class-id slot-table const-table pic-width-table)
  (let ((from (getf (rest stmt) :from))
        (from-target (getf (rest stmt) :from-target))
        (giving (getf (rest stmt) :giving))
        (dest (or giving from-target))
        (w (operand-width dest pic-width-table))
        (bcd-p (when dest (usage-bcd-p (expr-to-width-name dest))))
        (acc (i286-reg w))
        (tmp (i286-temp-reg w)))
    (compile-i286-load out from-target class-id slot-table const-table pic-width-table)
    (format out "~&~8tmov     ~a, ~a" tmp acc)
    (compile-i286-load out from class-id slot-table const-table pic-width-table)
    (format out "~&~8tsub     ~a, ~a" tmp acc)
    (when (and bcd-p (= (or w 1) 1)) (format out "~&~8tdas"))
    (format out "~&~8tmov     ~a, ~a" acc tmp)
    (cond
      ((stringp dest)
       (format out "~&~8tmov     ~a, ~a" (i286-symbol dest) acc))
      ((and (listp dest) (eq (first dest) :subscript))
       (let ((arr-name (second dest)) (idx-expr (third dest)))
         (format out "~&~8tmov     ~a, ~a" (i286-temp-reg w) acc)
         (compile-i286-load out idx-expr class-id slot-table const-table pic-width-table 1)
         (format out "~&~8tmov     ah, 0")
         (format out "~&~8tmov     si, offset ~a" (i286-symbol (format nil "~a" arr-name)))
         (when (= (or w 1) 2)
           (format out "~&~8tshl     ax, 1"))
         (format out "~&~8tadd     si, ax")
         (format out "~&~8tmov     [si], ~a" (i286-temp-reg w))))
      (t (format out "~&~8t; Unsupported subtract dest ~s" dest)))))

(defun compile-i286-compute (out stmt class-id slot-table const-table pic-width-table)
  (let ((target (getf (rest stmt) :target))
        (expr (getf (rest stmt) :expression))
        (w (operand-width target pic-width-table))
        (reg (i286-reg w)))
    (compile-i286-load out expr class-id slot-table const-table pic-width-table)
    (cond
      ((stringp target)
       (format out "~&~8tmov     ~a, ~a" (i286-symbol target) reg))
      ((and (listp target) (eq (first target) :subscript))
       (let ((arr-name (second target)) (idx-expr (third target)))
         (format out "~&~8tmov     ~a, ~a" (i286-temp-reg w) reg)
         (compile-i286-load out idx-expr class-id slot-table const-table pic-width-table 1)
         (format out "~&~8tmov     ah, 0")
         (format out "~&~8tmov     si, offset ~a" (i286-symbol (format nil "~a" arr-name)))
         (when (= (or w 1) 2)
           (format out "~&~8tshl     ax, 1"))
         (format out "~&~8tadd     si, ax")
         (format out "~&~8tmov     [si], ~a" (i286-temp-reg w))))
      (t (format out "~&~8t; Unsupported compute target ~s" target)))))

(defun compile-i286-set (out stmt class-id slot-table const-table pic-width-table)
  (let ((target (getf (rest stmt) :target))
        (value (getf (rest stmt) :value))
        (w (operand-width target pic-width-table))
        (reg (i286-reg w)))
    (compile-i286-load out value class-id slot-table const-table pic-width-table)
    (cond
      ((stringp target)
       (format out "~&~8tmov     ~a, ~a" (i286-symbol target) reg))
      ((and (listp target) (eq (first target) :of))
       (let ((slot (second target)) (obj (third target)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (format out "~&~8tmov     bx, offset Self")
           (format out "~&~8tmov     bx, [bx]")
           (format out "~&~8tmov     [bx+~a], ~a" (slot-symbol slot slot-table class-id) reg))))
      ((and (listp target) (eq (first target) :subscript))
       (let ((arr-name (second target)) (idx-expr (third target)))
         (format out "~&~8tmov     ~a, ~a" (i286-temp-reg w) reg)
         (compile-i286-load out idx-expr class-id slot-table const-table pic-width-table 1)
         (format out "~&~8tmov     ah, 0")
         (format out "~&~8tmov     si, offset ~a" (i286-symbol (format nil "~a" arr-name)))
         (when (= (or w 1) 2)
           (format out "~&~8tshl     ax, 1"))
         (format out "~&~8tadd     si, ax")
         (format out "~&~8tmov     [si], ~a" (i286-temp-reg w))))
      (t (format out "~&~8t; Unsupported set ~s" target)))))

;;; ---------------------------------------------------------------
;;; PERFORM
;;; ---------------------------------------------------------------

(defun compile-i286-perform (out stmt class-id slot-table type-table const-table pic-width-table)
  (let ((proc (getf (rest stmt) :procedure))
        (times (getf (rest stmt) :times))
        (until (getf (rest stmt) :until)))
    (cond
      (times
       (let ((lbl (i286-label "perf")))
         (compile-i286-load out times class-id slot-table const-table pic-width-table)
         (format out "~&~8tmov     cl, al")
         (format out "~&~a:" lbl)
         (format out "~&~8tcall    ~a" (i286-symbol (format nil "~a" proc)))
         (format out "~&~8tdec     cl")
         (format out "~&~8tjnz     ~a" lbl)))
      (until
       (let ((lbl-loop (i286-label "loop"))
             (lbl-end (i286-label "end")))
         (format out "~&~a:" lbl-loop)
         (compile-i286-condition out until class-id slot-table type-table const-table pic-width-table lbl-end)
         (format out "~&~8tcall    ~a" (i286-symbol (format nil "~a" proc)))
         (format out "~&~8tjmp     ~a" lbl-loop)
         (format out "~&~a:" lbl-end)))
      (t
       (format out "~&~8tcall    ~a" (i286-symbol (format nil "~a" proc)))))))

;;; ---------------------------------------------------------------
;;; STRING BLT
;;; ---------------------------------------------------------------

(defun i286-string-operand-address (operand)
  "Return Intel address expression for STRING operand (identifier or :refmod)."
  (cond
    ((and (listp operand) (eq (first operand) :refmod))
     (let* ((base (getf (rest operand) :base))
            (start (getf (rest operand) :start))
            (base-str (i286-symbol (format nil "~a" base))))
       (if (and (integerp start) (= start 1))
           (format nil "offset ~a" base-str)
           (format nil "offset ~a+~d" base-str (1- start)))))
    (t (format nil "offset ~a" (i286-symbol (format nil "~a" operand))))))

(defun compile-i286-string-blt (out stmt class-id slot-table const-table)
  (declare (ignore class-id slot-table const-table))
  (let ((source (getf (rest stmt) :source))
        (dest (getf (rest stmt) :dest))
        (length (getf (rest stmt) :length)))
    (let ((len (or (and (listp source) (getf source :length))
                   (and (listp dest) (getf dest :length))
                   length 64))
          (src-addr (i286-string-operand-address source))
          (dst-addr (i286-string-operand-address dest)))
      (format out "~&~8tmov     si, ~a" src-addr)
      (format out "~&~8tmov     di, ~a" dst-addr)
      (let ((lbl (i286-label "blt")))
        (format out "~&~8tmov     cx, ~d" len)
        (format out "~&~a:" lbl)
        (format out "~&~8tmov     al, [si]")
        (format out "~&~8tmov     [di], al")
        (format out "~&~8tinc     si")
        (format out "~&~8tinc     di")
        (format out "~&~8tloop    ~a" lbl)))))
