;; src/backend-m6800.lisp — Motorola 6800 code generation backend
;;
;; Minimal m6800 emitter intended for Vectrex-style Motorola-family workflows.
;; Uses plain 6800-like mnemonics (LDAA/STAA/CMPA/BEQ/BNE/JSR/JMP/RTS) and
;; direct symbols for generated labels.
(in-package :eightbol)

(defun m6800-symbol (name)
  "Convert EIGHTBOL identifier to m6800 assembly symbol (PascalCase)."
  (pascal-case (format nil "~a" name)))

(defmethod compile-to-assembly (ast (cpu (eql :m6800)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/m6800: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table
                                     usage-table sign-table pic-size-table pic-width-table pic-frac-bits-table
                                     pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (declare (ignore service-bank-table usage-table sign-table pic-frac-bits-table pic-nybble-semantics-table))
      (format output-stream
              "; ~a -- generated by EIGHTBOL for m6800~%; DO NOT EDIT -- regenerate from ~a.cob~2%"
              class-id class-id)
      (dolist (method (ensure-list methods))
        (when (and (listp method) (eq (first method) :method))
          (compile-m6800-method output-stream method class-id
                                slot-table type-table const-table pic-size-table pic-width-table))))))

(defun compile-m6800-method (out method class-id slot-table type-table const-table pic-size-table pic-width-table)
  (let ((*slot-table* slot-table)
        (*type-table* type-table)
        (*const-table* const-table)
        (*pic-size-table* pic-size-table)
        (*pic-width-table* pic-width-table)
        (*class-id* class-id)
        (*method-id* (getf (rest method) :method-id)))
    (declare (special *slot-table* *type-table* *const-table* *pic-size-table*
                      *pic-width-table* *class-id* *method-id*))
    (let* ((method-id (getf (rest method) :method-id))
           (dispatch-label (format nil "Method~a~a"
                                   (m6800-symbol class-id)
                                   (m6800-symbol (format nil "~a" method-id))))
           (custom-entry (nth-value 0 (split-method-leading-assembly-entry
                                       (getf (rest method) :statements))))
           (stmts (nth-value 1 (split-method-leading-assembly-entry
                                (getf (rest method) :statements)))))
      (if custom-entry
          (progn
            (format out "~&~%~a:" (m6800-symbol custom-entry))
            (format out "~&~a:" dispatch-label))
          (format out "~&~%~a:" dispatch-label))
      (dolist (stmt stmts)
        (compile-m6800-statement out stmt class-id slot-table type-table const-table pic-size-table pic-width-table))
      (format out "~&~8tRTS"))))

(defun compile-m6800-load-a (out expr class-id slot-table const-table pic-width-table)
  (declare (ignore slot-table pic-width-table))
  (cond
    ((numberp expr)
     (format out "~&~8tLDAA    #~d" expr))
    ((and (stringp expr) (constant-p expr))
     (format out "~&~8tLDAA    #~d" (constant-value expr)))
    ((stringp expr)
     (format out "~&~8tLDAA    ~a" (bare-data-assembly-symbol expr class-id)))
    ((and (listp expr) (eq (first expr) :of))
     (let ((slot (second expr)) (obj (third expr)))
       (if (member obj '(:self "Self" self) :test #'equal)
           (progn
             (format out "~&~8tLDX     Self")
             (format out "~&~8tLDAA    ~a,X" (slot-symbol slot class-id)))
           (format out "~&~8t; Unsupported OF target ~s for m6800 load" obj))))
    (t
     (format out "~&~8t; Unsupported load ~s for m6800" expr)
     (format out "~&~8tLDAA    #0"))))

(defun compile-m6800-store-a (out dest class-id)
  (cond
    ((stringp dest)
     (format out "~&~8tSTAA    ~a" (bare-data-assembly-symbol dest class-id)))
    ((and (listp dest) (eq (first dest) :of))
     (let ((slot (second dest)) (obj (third dest)))
       (if (member obj '(:self "Self" self) :test #'equal)
           (progn
             (format out "~&~8tLDX     Self")
             (format out "~&~8tSTAA    ~a,X" (slot-symbol slot class-id)))
           (format out "~&~8t; Unsupported OF target ~s for m6800 store" obj))))
    (t
     (format out "~&~8t; Unsupported store ~s for m6800" dest))))

(defvar *m6800-label-counter* 0)

(defun m6800-label (prefix)
  (format nil "L~a~d" prefix (incf *m6800-label-counter*)))

(defun compile-m6800-condition (out condition class-id slot-table type-table const-table pic-width-table false-label)
  (declare (ignore type-table))
  (cond
    ((and (listp condition) (member (first condition) '(= equal) :test #'eq))
     (compile-m6800-load-a out (second condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tTAB")
     (compile-m6800-load-a out (third condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tCBA")
     (format out "~&~8tBNE     ~a" false-label))
    ((and (listp condition) (eq (first condition) :is-zero))
     (compile-m6800-load-a out (second condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tBNE     ~a" false-label))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (compile-m6800-load-a out (second condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tBEQ     ~a" false-label))
    (t
     (format out "~&~8t; Unsupported condition ~s for m6800" condition)
     (format out "~&~8tJMP     ~a" false-label))))

(defun compile-m6800-statement (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
  (unless (and (listp stmt) (first stmt))
    (return-from compile-m6800-statement))
  (emit-statement-source-comment out stmt)
  (ecase (first stmt)
    (:goback (format out "~&~8tRTS"))
    (:exit-method (format out "~&~8tRTS"))
    (:exit-program (format out "~&~8tRTS"))
    (:exit (format out "~&~8tRTS"))
    (:stop-run (format out "~&~8tRTS"))
    (:move
     (compile-m6800-load-a out (getf (rest stmt) :from) class-id slot-table const-table pic-width-table)
     (compile-m6800-store-a out (getf (rest stmt) :to) class-id))
    (:set
     (compile-m6800-load-a out (getf (rest stmt) :value) class-id slot-table const-table pic-width-table)
     (compile-m6800-store-a out (getf (rest stmt) :target) class-id))
    (:if
     (let ((false-label (m6800-label "IfFalse"))
           (end-label (m6800-label "IfEnd"))
           (then-stmts (ensure-list (getf (rest stmt) :then)))
           (else-stmts (ensure-list (getf (rest stmt) :else))))
       (compile-m6800-condition out (getf (rest stmt) :condition)
                                class-id slot-table type-table const-table pic-width-table false-label)
       (dolist (s then-stmts)
         (compile-m6800-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
       (when else-stmts
         (format out "~&~8tJMP     ~a" end-label))
       (format out "~&~a:" false-label)
       (dolist (s else-stmts)
         (compile-m6800-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
       (when else-stmts
         (format out "~&~a:" end-label))))
    (:call
     (let ((target (or (getf (rest stmt) :service) (getf (rest stmt) :target) "UnknownCall")))
       (format out "~&~8tJSR     ~a" (m6800-symbol target))))
    (:invoke
     (let ((method (or (getf (rest stmt) :method) "UnknownMethod")))
       (format out "~&~8tJSR     Invoke~a~a"
               (m6800-symbol class-id)
               (m6800-symbol method))))
    (:goto
     (let ((target (or (getf (rest stmt) :target) (first (getf (rest stmt) :targets)))))
       (format out "~&~8tJMP     ~a" (m6800-symbol target))))
    (:paragraph
     (let ((name (if (eq (first stmt) :paragraph)
                     (second stmt)
                     (or (getf (rest stmt) :paragraph) (second stmt)))))
       (when name
         (format out "~&~a:" (m6800-symbol (format nil "~a" name))))))
    (:add
     (let* ((to (getf (rest stmt) :to))
            (from (getf (rest stmt) :from))
            (result (or (getf (rest stmt) :giving) to))
            (bcd-p (when result (usage-bcd-p result))))
       (assert-pic-decimal-add-compiled :m6800 stmt)
       (compile-m6800-load-a out to class-id slot-table const-table pic-width-table)
       (format out "~&~8tTAB")
       (compile-m6800-load-a out from class-id slot-table const-table pic-width-table)
       (format out "~&~8tABA")
       (when bcd-p
         (let ((ok1 (m6800-label "ad1")) (ok2 (m6800-label "ad2")))
           (format out "~&~8tTAB")
           (format out "~&~8tANDA    #$0F")
           (format out "~&~8tCMPA    #10")
           (format out "~&~8tBLO     ~a" ok1)
           (format out "~&~8tLDAA    B")
           (format out "~&~8tADDA    #6")
           (format out "~&~8tTAB")
           (format out "~&~a:" ok1)
           (format out "~&~8tLDAA    B")
           (format out "~&~8tANDA    #$F0")
           (format out "~&~8tCMPA    #$A0")
           (format out "~&~8tBLO     ~a" ok2)
           (format out "~&~8tLDAA    B")
           (format out "~&~8tADDA    #$60")
           (format out "~&~8tTAB")
           (format out "~&~a:" ok2)
           (format out "~&~8tLDAA    B")))
       (compile-m6800-store-a out result class-id)))
    (:subtract
     (assert-pic-decimal-subtract-compiled :m6800 stmt)
     (multiple-value-bind (minuend subtrahend)
         (subtract-statement-minuend-and-subtrahend stmt)
       (let* ((result (or (getf (rest stmt) :giving) minuend))
              (bcd-p (when result (usage-bcd-p result))))
         (compile-m6800-load-a out minuend class-id slot-table const-table pic-width-table)
         (format out "~&~8tTAB")
         (compile-m6800-load-a out subtrahend class-id slot-table const-table pic-width-table)
         (format out "~&~8tSBA")
         (when bcd-p
           (let ((ok1 (m6800-label "sb1")) (ok2 (m6800-label "sb2")))
             (format out "~&~8tTAB")
             (format out "~&~8tANDA    #$0F")
             (format out "~&~8tCMPA    #10")
             (format out "~&~8tBLO     ~a" ok1)
             (format out "~&~8tLDAA    B")
             (format out "~&~8tSUBA    #6")
             (format out "~&~8tTAB")
             (format out "~&~a:" ok1)
             (format out "~&~8tLDAA    B")
             (format out "~&~8tANDA    #$F0")
             (format out "~&~8tCMPA    #$A0")
             (format out "~&~8tBLO     ~a" ok2)
             (format out "~&~8tLDAA    B")
             (format out "~&~8tSUBA    #$60")
             (format out "~&~8tTAB")
             (format out "~&~a:" ok2)
             (format out "~&~8tLDAA    B")))
         (compile-m6800-store-a out result class-id))))
    (:compute
     (compile-m6800-load-a out (getf (rest stmt) :expression) class-id slot-table const-table pic-width-table)
     (compile-m6800-store-a out (getf (rest stmt) :target) class-id))
    (:perform (format out "~&~8t; PERFORM not yet implemented for m6800"))
    (:evaluate (format out "~&~8t; EVALUATE not yet implemented for m6800"))
    (:inspect (format out "~&~8t; INSPECT not yet implemented for m6800"))
    (:string-blt (format out "~&~8t; STRING BLT not yet implemented for m6800"))
    (:log-fault (format out "~&~8t; LOG FAULT ~s" (getf (rest stmt) :code)))
    (:debug-break (format out "~&~8t; DEBUG BREAK ~s" (getf (rest stmt) :code)))
    (:divide
     (let* ((divisor (getf (rest stmt) :divisor))
            (into (getf (rest stmt) :into))
            (by (getf (rest stmt) :by))
            (source (or by into))
            (dest (or (getf (rest stmt) :giving) into))
            (signed (operand-signed-p (or source dest))))
       (if (and (expression-constant-p divisor)
                (power-of-two-p (expression-constant-value divisor)))
           (let ((shift (log2 (expression-constant-value divisor))))
             (unless (zerop shift)
               (compile-m6800-load-a out (or source dest) class-id slot-table const-table pic-width-table)
               (dotimes (_ shift)
                 (if signed (format out "~&~8tASRA") (format out "~&~8tLSRA")))
               (compile-m6800-store-a out dest class-id)))
           (error 'source-error
                  :message "DIVIDE: divisor must be constant power-of-two (1, 2, 4, 8, ...)"
                  :detail (format nil "DIVIDE by ~s" divisor)))))
    (:multiply
     (let* ((multiplier (getf (rest stmt) :multiplier))
            (by (getf (rest stmt) :by))
            (giving (getf (rest stmt) :giving))
            (source (or giving by))
            (dest (or giving by)))
       (if (and (expression-constant-p multiplier)
                (power-of-two-p (expression-constant-value multiplier)))
           (let ((shift (log2 (expression-constant-value multiplier))))
             (unless (zerop shift)
               (compile-m6800-load-a out (or source dest) class-id slot-table const-table pic-width-table)
               (dotimes (_ shift)
                 (format out "~&~8tASLA"))
               (compile-m6800-store-a out dest class-id)))
           (error 'source-error
                  :message "MULTIPLY: multiplier must be constant power-of-two (1, 2, 4, 8, ...)"
                  :detail (format nil "MULTIPLY by ~s" multiplier)))))
    (:comment
     (format out "~&~8t; ~a"
             (let ((text (second stmt)))
               (if (listp text)
                   (format nil "~{~a~%~8t; ~}" (mapcar (lambda (s) (if (stringp s) s (princ-to-string s))) text))
                   (princ-to-string text)))))
    (:invoke-super
     (unless (gethash *class-id* *parent-classes*)
       (load-classes))
     (if-let (parent-class (gethash *class-id* *parent-classes*))
       (format out "~&~8tJSR     Method~a~a"
               (m6800-symbol parent-class)
               (m6800-symbol (format nil "~a" *method-id*)))
       (error "Can't figure out parent class of ~a" *class-id*)))
    (:shift-left
     (let* ((target (getf (rest stmt) :target))
            (count (getf (rest stmt) :count 1)))
       (compile-m6800-load-a out target class-id slot-table const-table pic-width-table)
       (dotimes (_ count)
         (format out "~&~8tASLA"))
       (compile-m6800-store-a out target class-id)))
    (:shift-right
     (let* ((target (getf (rest stmt) :target))
            (count (getf (rest stmt) :count 1))
            (signed (operand-signed-p target)))
       (compile-m6800-load-a out target class-id slot-table const-table pic-width-table)
       (dotimes (_ count)
         (if signed
             (format out "~&~8tASRA")
             (format out "~&~8tLSRA")))
       (compile-m6800-store-a out target class-id)))
    (:copy (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
                  (getf (rest stmt) :name)))))
