;; src/backend-cp1610.lisp — CP1610 (Intellivision) code generation backend
;;
;; The GI CP1610 is a 16-bit RISC-like CPU used in the Mattel Intellivision.
;;   16-bit registers: R0–R7 (R5 = return addr for JSR, R6 = stack pointer)
;;   Instructions: MVII (move imm), MVI (load), MVO (store), ADDR, SUBR
;;   JSR R5, label — call subroutine (return addr in R5)
;;   JR R5 — return
;;
;; Output: as1600 assembler syntax (Intellivision).
;; Variables map to 16-bit memory; 8-bit EIGHTBOL values use low byte.
(in-package :eightbol)

;;; ---------------------------------------------------------------
;;; Shared helpers (symbol naming)
;;; ---------------------------------------------------------------

(defun cp1610-symbol (name)
  "Convert EIGHTBOL identifier to CP1610 assembly symbol (PascalCase)."
  (to-pascal-case (format nil "~a" name)))

;;; ---------------------------------------------------------------
;;; Top-level entry point
;;; ---------------------------------------------------------------

(defmethod compile-to-assembly (ast (cpu (eql :cp1610)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/CP1610: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods  (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table pic-size-table pic-width-table)
        (load-copybook-tables class-id)
      (declare (ignore service-bank-table usage-table sign-table))
      (let ((*output-stream* output-stream))
        (format *output-stream*
              ";;; ~a -- generated by EIGHTBOL for CP1610 (Intellivision)~%;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
              class-id class-id)
        (format *output-stream*  "~&~8tROMW    16")
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-cp1610-method method class-id
                                  slot-table type-table const-table pic-size-table pic-width-table)))))))

;;; ---------------------------------------------------------------
;;; Method compilation
;;; ---------------------------------------------------------------

(defun compile-cp1610-method (method class-id slot-table type-table const-table pic-size-table pic-width-table)
  (let ((method-id  (getf (rest method) :method-id))
        (statements (getf (rest method) :statements)))
    (format *output-stream* "~&~%Method~a~a PROC"
            (cp1610-symbol class-id) (cp1610-symbol (format nil "~a" method-id)))
    (dolist (stmt (ensure-list statements))
      (compile-cp1610-statement *output-stream* stmt class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
    (format *output-stream* "~&~8tJR      R5")
    (format *output-stream* "~&~8tENDP")))

;;; ---------------------------------------------------------------
;;; Statement dispatch
;;; ---------------------------------------------------------------

(defun compile-cp1610-statement (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table &optional method-id)
  (unless (and (listp stmt) (first stmt)) (return-from compile-cp1610-statement))
  (ecase (first stmt)
    (:goback
     (format out "~&~8tJR      R5"))
    (:exit-method (format out "~&~8tJR      R5"))
    (:exit-program (format out "~&~8tJR      R5"))
    (:stop-run (format out "~&~8tJR      R5"))
    (:exit (format out "~&~8tJR      R5"))
    (:move
     (compile-cp1610-move out stmt class-id slot-table const-table pic-width-table))
    (:invoke
     (compile-cp1610-invoke out stmt class-id type-table))
    (:call
     (compile-cp1610-call out stmt))
    (:if
     (compile-cp1610-if out stmt class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
    (:add
     (compile-cp1610-add out stmt class-id slot-table const-table pic-width-table))
    (:subtract
     (compile-cp1610-subtract out stmt class-id slot-table const-table pic-width-table))
    (:compute
     (compile-cp1610-compute out stmt class-id slot-table const-table pic-width-table))
    (:set
     (compile-cp1610-set out stmt class-id slot-table const-table pic-width-table))
    (:log-fault
     (format out "~&~8t;; LOG FAULT ~s" (getf (rest stmt) :code)))
    (:debug-break
     (format out "~&~8t;; DEBUG BREAK ~s" (getf (rest stmt) :code)))
    (:perform
     (compile-cp1610-perform out stmt class-id slot-table type-table const-table))
    (:string-blt
     (compile-cp1610-string-blt out stmt class-id slot-table const-table))
    (:goto
     (compile-cp1610-goto out stmt class-id slot-table const-table method-id))
    (:paragraph
     (compile-cp1610-paragraph out stmt class-id method-id))
    (:evaluate
     (compile-cp1610-evaluate out stmt class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
    (:inspect
     (compile-cp1610-inspect out stmt class-id slot-table const-table pic-size-table))
    (:copy
     (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
            (getf (rest stmt) :name)))))

;;; ---------------------------------------------------------------
;;; Expression / value emission
;;; ---------------------------------------------------------------

(defun cp1610-expr-is-constant-p (expr const-table)
  (or (numberp expr)
      (and (stringp expr) (constant-p expr const-table))))

(defun cp1610-value (expr &optional const-table)
  (cond
    ((numberp expr) (format nil "~d" expr))
    ((and (stringp expr) (constant-p expr const-table))
     (format nil "~d" (constant-value expr const-table)))
    ((stringp expr) (cp1610-symbol expr))
    ((eq expr :self) "Self")
    ((and (listp expr) (eq (first expr) :of))
     (cp1610-symbol (format nil "~a-~a" (third expr) (second expr))))
    (t (format nil "~a" expr))))

(defun compile-cp1610-load (out expr class-id slot-table const-table &optional (width 1))
  "Load EXPR into R0. Uses MVII for immediates, MVI for memory.
WIDTH: 1 (byte) or 2 (word). For :subscript, scales index for element size (0-255 elements)."
  (cond
    ((numberp expr)
     (format out "~&~8tMVII    #~d, R0" expr))
    ((and (stringp expr) (constant-p expr const-table))
     (format out "~&~8tMVII    #~d, R0" (constant-value expr const-table)))
    ((stringp expr)
     (format out "~&~8tMVI     ~a, R0" (cp1610-symbol expr)))
    ((and (listp expr) (eq (first expr) :of))
     (let ((slot (second expr)) (obj (third expr)))
       (when (member obj '(:self "Self" self) :test #'equal)
         (format out "~&~8tMVII    #~a, R4"
                 (slot-symbol slot slot-table class-id))
         (format out "~&~8tADD     Self, R4")
         (format out "~&~8tMVI@    R4, R0"))))
    ((and (listp expr) (eq (first expr) :subscript))
     ;; base(index): R4 = base + index*width. Index 0-255 supported.
     (compile-cp1610-load out (third expr) class-id slot-table const-table 1)
     (when (= (or width 1) 2)
       (format out "~&~8tSLL     R0, 1"))
     (format out "~&~8tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second expr))))
     (format out "~&~8tADDR    R0, R4")
     (format out "~&~8tMVI@    R4, R0"))
    ((and (listp expr) (eq (first expr) :shift-left))
     (let ((n (if (numberp (third expr)) (third expr) 1)))
       (compile-cp1610-load out (second expr) class-id slot-table const-table width)
       (dotimes (_ n) (format out "~&~8tSLL     R0, 1"))))
    ((and (listp expr) (eq (first expr) :shift-right))
     (let ((n (if (numberp (third expr)) (third expr) 1)))
       (compile-cp1610-load out (second expr) class-id slot-table const-table width)
       (dotimes (_ n) (format out "~&~8tSARC    R0, 1"))))
    ((and (listp expr) (eq (first expr) :bit-and))
     (compile-cp1610-load out (second expr) class-id slot-table const-table width)
     (let ((rhs (third expr)))
       (if (cp1610-expr-is-constant-p rhs const-table)
           (format out "~&~8tANDI    #~a, R0" (cp1610-value rhs const-table))
           (progn (format out "~&~8tMOVR    R0, R1")
                  (compile-cp1610-load out rhs class-id slot-table const-table width)
                  (format out "~&~8tANDR    R1, R0")))))
    ((and (listp expr) (eq (first expr) :bit-or))
     (compile-cp1610-load out (second expr) class-id slot-table const-table width)
     (let ((rhs (third expr)))
       (if (cp1610-expr-is-constant-p rhs const-table)
           (format out "~&~8tORI     #~a, R0" (cp1610-value rhs const-table))
           (progn (format out "~&~8tMOVR    R0, R1")
                  (compile-cp1610-load out rhs class-id slot-table const-table width)
                  (format out "~&~8tORR     R1, R0")))))
    ((and (listp expr) (eq (first expr) :bit-xor))
     (compile-cp1610-load out (second expr) class-id slot-table const-table width)
     (let ((rhs (third expr)))
       (if (cp1610-expr-is-constant-p rhs const-table)
           (format out "~&~8tXORI    #~a, R0" (cp1610-value rhs const-table))
           (progn (format out "~&~8tMOVR    R0, R1")
                  (compile-cp1610-load out rhs class-id slot-table const-table width)
                  (format out "~&~8tXORR    R1, R0")))))
    ((and (listp expr) (eq (first expr) :bit-not))
     (compile-cp1610-load out (second expr) class-id slot-table const-table width)
     (format out "~&~8tCOMR    R0"))
    (t
     (format out "~&~8t;; Unsupported load ~s" expr))))

;;; ---------------------------------------------------------------
;;; MOVE
;;; ---------------------------------------------------------------

(defun compile-cp1610-move (out stmt class-id slot-table const-table pic-width-table)
  (let ((from (getf (rest stmt) :from))
        (to-dest (getf (rest stmt) :to))
        (to-w (operand-width to-dest pic-width-table)))
    (compile-cp1610-load out from class-id slot-table const-table (operand-width from pic-width-table))
    (cond
      ((stringp to-dest)
       (format out "~&~8tMVO     R0, ~a" (cp1610-symbol to-dest)))
      ((and (listp to-dest) (eq (first to-dest) :of))
       (let ((slot (second to-dest)) (obj (third to-dest)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (format out "~&~8tMVII    #~a, R4" (slot-symbol slot slot-table class-id))
           (format out "~&~8tADD     Self, R4")
           (format out "~&~8tMVO@    R0, R4"))))
      ((and (listp to-dest) (eq (first to-dest) :subscript))
       (format out "~&~8tMOVR    R0, R1")
       (compile-cp1610-load out (third to-dest) class-id slot-table const-table 1)
       (when (= (or to-w 1) 2)
         (format out "~&~8tSLL     R0, 1"))
       (format out "~&~8tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second to-dest))))
       (format out "~&~8tADDR    R0, R4")
       (format out "~&~8tMOVR    R1, R0")
       (format out "~&~8tMVO@    R0, R4"))
      (t (format out "~&~8t;; Unsupported store to ~s" to-dest)))))

;;; ---------------------------------------------------------------
;;; INVOKE
;;; ---------------------------------------------------------------

(defun compile-cp1610-invoke (out stmt class-id type-table)
  (let ((object   (getf (rest stmt) :object))
        (method   (getf (rest stmt) :method))
        (returning (getf (rest stmt) :returning)))
    (let ((method-sym (cp1610-symbol (format nil "~a" method))))
      (cond
        ((member object '(:self "Self" self) :test #'equal)
         (format out "~&~8tJSR     R5, Invoke~a~a" (cp1610-symbol class-id) method-sym))
        (t
         (let* ((obj-name (cp1610-symbol (format nil "~a" object)))
                (obj-class (or (var-class obj-name type-table) "Unknown")))
           (format out "~&~8tJSR     R5, Call~a~a" obj-class method-sym))))
      (when returning
        (format out "~&~8tMVO     R0, ~a" (cp1610-symbol (format nil "~a" returning)))))))

;;; ---------------------------------------------------------------
;;; CALL
;;; ---------------------------------------------------------------

(defun compile-cp1610-call (out stmt)
  (let ((target (getf (rest stmt) :target))
        (service (getf (rest stmt) :service))
        (library (getf (rest stmt) :library)))
    (let ((name (cp1610-symbol (format nil "~a" (or service target)))))
      (format out "~&~8tJSR     R5, ~a" name))))

;;; ---------------------------------------------------------------
;;; IF
;;; ---------------------------------------------------------------

(defvar *cp1610-label* 0)

(defun cp1610-label (prefix)
  (format nil "@@~a~d" prefix (incf *cp1610-label*)))

(defun compile-cp1610-if (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table &optional method-id)
  (let ((condition (getf (rest stmt) :condition))
        (then-stmts (getf (rest stmt) :then))
        (else-stmts (getf (rest stmt) :else))
        (lbl-else (cp1610-label "else"))
        (lbl-end (cp1610-label "end")))
    (compile-cp1610-condition out condition class-id slot-table type-table const-table lbl-else)
    (dolist (s (ensure-list then-stmts))
      (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
    (when (and else-stmts (not (null else-stmts)))
      (format out "~&~8tB       ~a" lbl-end))
    (format out "~&~a:" lbl-else)
    (when (and else-stmts (not (null else-stmts)))
      (dolist (s (ensure-list else-stmts))
        (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
      (format out "~&~a:" lbl-end))))

(defun compile-cp1610-condition (out condition class-id slot-table type-table const-table branch-label)
  (cond
    ((and (listp condition) (member (first condition) '(= equal < less > greater) :test #'eq))
     (let ((lhs (second condition)) (rhs (third condition)) (op (first condition)))
       (compile-cp1610-load out lhs class-id slot-table const-table)
       (format out "~&~8tMOVR    R0, R1")
       (compile-cp1610-load out rhs class-id slot-table const-table)
       (format out "~&~8tCMPR    R1, R0")
       (ecase op
         ((= equal) (format out "~&~8tBNEQ    ~a" branch-label))
         ((< less)  (format out "~&~8tBGE     ~a" branch-label))
         ((> greater) (format out "~&~8tBLE     ~a" branch-label)))))
    ((and (listp condition) (eq (first condition) :is-zero))
     (compile-cp1610-load out (second condition) class-id slot-table const-table)
     (format out "~&~8tTSTR    R0")
     (format out "~&~8tBNEQ    ~a" branch-label))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (compile-cp1610-load out (second condition) class-id slot-table const-table)
     (format out "~&~8tTSTR    R0")
     (format out "~&~8tBEQ     ~a" branch-label))
    ((and (listp condition) (eq (first condition) :and))
     (compile-cp1610-condition out (second condition) class-id slot-table type-table const-table branch-label)
     (compile-cp1610-condition out (third condition) class-id slot-table type-table const-table branch-label))
    ((and (listp condition) (eq (first condition) :or))
     (let ((lbl-cond2 (cp1610-label "or"))
           (lbl-skip (cp1610-label "skip")))
       (compile-cp1610-condition out (second condition) class-id slot-table type-table const-table lbl-cond2)
       (format out "~&~8tB       ~a" lbl-skip)
       (format out "~&~a:" lbl-cond2)
       (compile-cp1610-condition out (third condition) class-id slot-table type-table const-table branch-label)
       (format out "~&~a:" lbl-skip)))
    (t (error "EIGHTBOL: condition ~s not implemented" condition))))

;;; ---------------------------------------------------------------
;;; EVALUATE statement
;;; ---------------------------------------------------------------

(defun compile-cp1610-evaluate (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table &optional method-id)
  (let ((subject (getf (rest stmt) :subject))
        (clauses (getf (rest stmt) :when-clauses))
        (lbl-end (cp1610-label "eval")))
    (dolist (clause (ensure-list clauses))
      (cond
        ((eq (first clause) :when-other)
         (dolist (s (ensure-list (second clause)))
           (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id)))
        ((eq (first clause) :when)
         (let ((phrases (second clause))
               (stmts (third clause))
               (lbl-next (cp1610-label "when")))
           (cond
             ((eq phrases 'eightbol::any)
              (dolist (s (ensure-list stmts))
                (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
              (format out "~&~8tB       ~a" lbl-end))
             ((or (eq phrases 'eightbol::true) (equal phrases "TRUE"))
              (compile-cp1610-load out subject class-id slot-table const-table)
              (format out "~&~8tTSTR    R0")
              (format out "~&~8tBEQ     ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
              (format out "~&~8tB       ~a" lbl-end)
              (format out "~&~a:" lbl-next))
             ((or (eq phrases 'eightbol::false) (equal phrases "FALSE"))
              (compile-cp1610-load out subject class-id slot-table const-table)
              (format out "~&~8tTSTR    R0")
              (format out "~&~8tBNEQ    ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
              (format out "~&~8tB       ~a" lbl-end)
              (format out "~&~a:" lbl-next))
             ((and (listp phrases) (eq (first phrases) :not))
              (compile-cp1610-load out subject class-id slot-table const-table)
              (format out "~&~8tMOVR    R0, R1")
              (compile-cp1610-load out (second phrases) class-id slot-table const-table)
              (format out "~&~8tCMPR    R1, R0")
              (format out "~&~8tBEQ     ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
              (format out "~&~8tB       ~a" lbl-end)
              (format out "~&~a:" lbl-next))
             ((and (listp phrases) (member (first phrases) '(:through :thru)))
              (let ((lo (second phrases)) (hi (third phrases)))
                (compile-cp1610-load out subject class-id slot-table const-table)
                (format out "~&~8tMOVR    R0, R1")
                (compile-cp1610-load out lo class-id slot-table const-table)
                (format out "~&~8tCMPR    R0, R1")
                (format out "~&~8tBGT     ~a" lbl-next)
                (compile-cp1610-load out hi class-id slot-table const-table)
                (format out "~&~8tCMPR    R1, R0")
                (format out "~&~8tBLT     ~a" lbl-next)
                (dolist (s (ensure-list stmts))
                  (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
                (format out "~&~8tB       ~a" lbl-end)
                (format out "~&~a:" lbl-next)))
             (t
              (let ((phrase-expr (if (listp phrases) (second phrases) phrases)))
                (compile-cp1610-load out subject class-id slot-table const-table)
                (format out "~&~8tMOVR    R0, R1")
                (compile-cp1610-load out phrase-expr class-id slot-table const-table)
                (format out "~&~8tCMPR    R1, R0")
                (format out "~&~8tBNEQ    ~a" lbl-next)
                (dolist (s (ensure-list stmts))
                  (compile-cp1610-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table method-id))
                (format out "~&~8tB       ~a" lbl-end)
                (format out "~&~a:" lbl-next))))))))
    (format out "~&~a:" lbl-end)))

;;; ---------------------------------------------------------------
;;; INSPECT statement
;;; ---------------------------------------------------------------

(defun compile-cp1610-inspect (out stmt class-id slot-table const-table pic-size-table)
  (let ((target (getf (rest stmt) :target))
        (tally (getf (rest stmt) :tallying))
        (conv-from (getf (rest stmt) :converting))
        (conv-to (getf (rest stmt) :to))
        (repl-by (getf (rest stmt) :by)))
    (let ((tgt-sym (cp1610-symbol (format nil "~a" target))))
      (cond
        (tally
         (let ((tally-sym (cp1610-symbol (format nil "~a" tally))))
           (format out "~&~8t;; INSPECT ~a TALLYING ~a FOR CHARACTERS" target tally)
           (format out "~&~8tMVII    #~a, R2" tgt-sym)
           (let ((lbl (cp1610-label "tally"))
                 (lbl-done (cp1610-label "tallyd"))
                 (lbl-skip (cp1610-label "tallys")))
             (format out "~&~a:" lbl)
             (format out "~&~8tMVI@    R2, R0")
             (format out "~&~8tTSTR    R0")
             (format out "~&~8tBEQ     ~a" lbl-done)
             (format out "~&~8tMVI     ~a, R0" tally-sym)
             (format out "~&~8tINCR    R0")
             (format out "~&~8tMVO     R0, ~a" tally-sym)
             (format out "~&~a:" lbl-skip)
             (format out "~&~8tINCR    R2")
             (format out "~&~8tB       ~a" lbl)
             (format out "~&~a:" lbl-done))))
        (conv-from
         (format out "~&~8t;; INSPECT ~a CONVERTING" target)
         (format out "~&~8tMVII    #~a, R2" tgt-sym)
         (let ((lbl (cp1610-label "insp"))
               (lbl-next (cp1610-label "inspn"))
               (lbl-done (cp1610-label "inspd")))
           (format out "~&~a:" lbl)
           (format out "~&~8tMVI@    R2, R0")
           (format out "~&~8tTSTR    R0")
           (format out "~&~8tBEQ     ~a" lbl-done)
           (if (cp1610-expr-is-constant-p conv-from const-table)
               (format out "~&~8tCMPI    #~a, R0" (cp1610-value conv-from const-table))
               (progn
                 (format out "~&~8tMOVR    R0, R1")
                 (compile-cp1610-load out conv-from class-id slot-table const-table)
                 (format out "~&~8tCMPR    R0, R1")))
           (format out "~&~8tBNEQ    ~a" lbl-next)
           (compile-cp1610-load out conv-to class-id slot-table const-table)
           (format out "~&~8tMVO@    R0, R2")
           (format out "~&~a:" lbl-next)
           (format out "~&~8tINCR    R2")
           (format out "~&~8tB       ~a" lbl)
           (format out "~&~a:" lbl-done)))
        (repl-by
         (let ((len (or (pic-size (format nil "~a" target) pic-size-table) 64)))
           (format out "~&~8t;; INSPECT ~a REPLACING CHARACTERS BY ~a" target repl-by)
           (compile-cp1610-load out repl-by class-id slot-table const-table)
           (format out "~&~8tMVII    #~a, R2" tgt-sym)
           (let ((lbl (cp1610-label "insp")))
             (format out "~&~8tMVII    #~d, R1" len)
             (format out "~&~a:" lbl)
             (format out "~&~8tMVO@    R0, R2")
             (format out "~&~8tDECR    R1")
             (format out "~&~8tBNEQ    ~a" lbl))))))))

;;; ---------------------------------------------------------------
;;; ADD / SUBTRACT / COMPUTE / SET
;;; ---------------------------------------------------------------

(defun compile-cp1610-add (out stmt class-id slot-table const-table pic-width-table)
  (let ((from (getf (rest stmt) :from))
        (to-op (getf (rest stmt) :to))
        (giving (getf (rest stmt) :giving))
        (result (or giving (and (stringp to-op) to-op) (and (listp to-op) (eq (first to-op) :subscript) to-op))))
    (compile-cp1610-load out from class-id slot-table const-table (operand-width from pic-width-table))
    (format out "~&~8tMOVR    R0, R1")
    (compile-cp1610-load out to-op class-id slot-table const-table (operand-width to-op pic-width-table))
    (format out "~&~8tADDR    R1, R0")
    (when result
      (cond
        ((stringp result)
         (format out "~&~8tMVO     R0, ~a" (cp1610-symbol (format nil "~a" result))))
        ((and (listp result) (eq (first result) :subscript))
         (let ((to-w (operand-width result pic-width-table)))
           (format out "~&~8tMOVR    R0, R1")
           (compile-cp1610-load out (third result) class-id slot-table const-table 1)
           (when (= (or to-w 1) 2)
             (format out "~&~8tSLL     R0, 1"))
           (format out "~&~8tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second result))))
           (format out "~&~8tADDR    R0, R4")
           (format out "~&~8tMOVR    R1, R0")
           (format out "~&~8tMVO@    R0, R4")))
        (t (format out "~&~8tMVO     R0, ~a" (cp1610-symbol (format nil "~a" result))))))))

(defun compile-cp1610-subtract (out stmt class-id slot-table const-table pic-width-table)
  (let ((from (getf (rest stmt) :from))
        (from-target (getf (rest stmt) :from-target))
        (giving (getf (rest stmt) :giving))
        (dest (or giving from-target)))
    (compile-cp1610-load out from-target class-id slot-table const-table (operand-width from-target pic-width-table))
    (format out "~&~8tMOVR    R0, R1")
    (compile-cp1610-load out from class-id slot-table const-table (operand-width from pic-width-table))
    (format out "~&~8tSUBR    R0, R1")
    (format out "~&~8tMOVR    R1, R0")
    (cond
      ((stringp dest)
       (format out "~&~8tMVO     R0, ~a" (cp1610-symbol (format nil "~a" dest))))
      ((and (listp dest) (eq (first dest) :subscript))
       (let ((dest-w (operand-width dest pic-width-table)))
         (format out "~&~8tMOVR    R0, R1")
         (compile-cp1610-load out (third dest) class-id slot-table const-table 1)
         (when (= (or dest-w 1) 2)
           (format out "~&~8tSLL     R0, 1"))
         (format out "~&~8tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second dest))))
         (format out "~&~8tADDR    R0, R4")
         (format out "~&~8tMOVR    R1, R0")
         (format out "~&~8tMVO@    R0, R4")))
      (t (format out "~&~8tMVO     R0, ~a" (cp1610-symbol (format nil "~a" dest)))))))

(defun compile-cp1610-compute (out stmt class-id slot-table const-table pic-width-table)
  (let ((target (getf (rest stmt) :target))
        (expr (getf (rest stmt) :expression))
        (tgt-w (operand-width (getf (rest stmt) :target) pic-width-table)))
    (compile-cp1610-load out expr class-id slot-table const-table (operand-width expr pic-width-table))
    (cond
      ((stringp target)
       (format out "~&~8tMVO     R0, ~a" (cp1610-symbol (format nil "~a" target))))
      ((and (listp target) (eq (first target) :subscript))
       (format out "~&~8tMOVR    R0, R1")
       (compile-cp1610-load out (third target) class-id slot-table const-table 1)
       (when (= (or tgt-w 1) 2)
         (format out "~&~8tSLL     R0, 1"))
       (format out "~&~8tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second target))))
       (format out "~&~8tADDR    R0, R4")
       (format out "~&~8tMOVR    R1, R0")
       (format out "~&~8tMVO@    R0, R4"))
      (t (format out "~&~8tMVO     R0, ~a" (cp1610-symbol (format nil "~a" target)))))))

(defun compile-cp1610-set (out stmt class-id slot-table const-table pic-width-table)
  (let ((target (getf (rest stmt) :target))
        (value (getf (rest stmt) :value))
        (tgt-w (operand-width (getf (rest stmt) :target) pic-width-table)))
    (compile-cp1610-load out value class-id slot-table const-table (operand-width value pic-width-table))
    (cond
      ((stringp target)
       (format out "~&~8tMVO     R0, ~a" (cp1610-symbol target)))
      ((and (listp target) (eq (first target) :of))
       (let ((slot (second target)) (obj (third target)))
         (when (member obj '(:self "Self" self) :test #'equal)
           (format out "~&~8tMVII    #~a, R4" (slot-symbol slot slot-table class-id))
           (format out "~&~8tADD     Self, R4")
           (format out "~&~8tMVO@    R0, R4"))))
      ((and (listp target) (eq (first target) :subscript))
       (format out "~&~8tMOVR    R0, R1")
       (compile-cp1610-load out (third target) class-id slot-table const-table 1)
       (when (= (or tgt-w 1) 2)
         (format out "~&~8tSLL     R0, 1"))
       (format out "~&~8tMVII    #~a, R4" (cp1610-symbol (format nil "~a" (second target))))
       (format out "~&~8tADDR    R0, R4")
       (format out "~&~8tMOVR    R1, R0")
       (format out "~&~8tMVO@    R0, R4"))
      (t (format out "~&~8t;; Unsupported set ~s" target)))))

;;; ---------------------------------------------------------------
;;; PERFORM
;;; ---------------------------------------------------------------

(defun compile-cp1610-perform (out stmt class-id slot-table type-table const-table)
  (let ((proc (getf (rest stmt) :procedure))
        (times (getf (rest stmt) :times))
        (until (getf (rest stmt) :until)))
    (cond
      (times
       (let ((lbl (cp1610-label "perf")))
         (compile-cp1610-load out times class-id slot-table const-table)
         (format out "~&~8tMOVR    R0, R1")
         (format out "~&~a:" lbl)
         (format out "~&~8tJSR     R5, ~a" (cp1610-symbol (format nil "~a" proc)))
         (format out "~&~8tDECR    R1")
         (format out "~&~8tBNEQ    ~a" lbl)))
      (until
       (let ((lbl-loop (cp1610-label "loop"))
             (lbl-end (cp1610-label "end")))
         (format out "~&~a:" lbl-loop)
         (compile-cp1610-condition out until class-id slot-table type-table const-table lbl-end)
         (format out "~&~8tJSR     R5, ~a" (cp1610-symbol (format nil "~a" proc)))
         (format out "~&~8tB       ~a" lbl-loop)
         (format out "~&~a:" lbl-end)))
      (t
       (format out "~&~8tJSR     R5, ~a" (cp1610-symbol (format nil "~a" proc)))))))

;;; ---------------------------------------------------------------
;;; STRING BLT
;;; ---------------------------------------------------------------

(defun cp1610-string-operand-address (operand)
  "Return as1600 address expression for STRING operand (identifier or :refmod)."
  (cond
    ((and (listp operand) (eq (first operand) :refmod))
     (let* ((base   (getf (rest operand) :base))
            (start  (getf (rest operand) :start))
            (base-str (cp1610-symbol (format nil "~a" base))))
       (if (and (integerp start) (= start 1))
           base-str
           (format nil "~a+~d" base-str (1- start)))))
    (t
     (cp1610-symbol (format nil "~a" operand)))))

(defun cp1610-para-label (name class-id method-id)
  (cp1610-symbol (format nil "~a_~a_~a" class-id (or method-id "") name)))

(defun compile-cp1610-paragraph (out stmt class-id method-id)
  (let ((name (or (getf (rest stmt) :paragraph) (second stmt))))
    (when name
      (format out "~&~a:" (cp1610-para-label (format nil "~a" name) class-id method-id)))))

(defun compile-cp1610-goto (out stmt class-id slot-table const-table method-id)
  (let ((target (getf (rest stmt) :target))
        (targets (getf (rest stmt) :targets))
        (dep (getf (rest stmt) :depending-on)))
    (if dep
        (let ((tgt-list (or targets (when target (list target)))))
          (compile-cp1610-load out dep class-id slot-table const-table)
          (when tgt-list
            (format out "~&~8t;; GO DEPENDING ON (CMP/BEQ chain)")
            (loop for tgt in tgt-list for i from 1
                  do (format out "~&~8tCMPI    #~d, R0" i)
                     (format out "~&~8tBEQ     ~a" (cp1610-para-label (format nil "~a" tgt) class-id method-id)))))
        (format out "~&~8tB       ~a"
                (cp1610-para-label (format nil "~a" (or target (first targets))) class-id method-id)))))

(defun compile-cp1610-string-blt (out stmt class-id slot-table const-table)
  "Emit CP1610 block copy loop. Uses R2=src, R3=dest (R5 is return-addr for JSR)."
  (let ((source (getf (rest stmt) :source))
        (dest (getf (rest stmt) :dest))
        (length (getf (rest stmt) :length)))
    (let ((len (or (and (listp source) (getf source :length))
                   (and (listp dest) (getf dest :length))
                   length 64))
          (src-addr (cp1610-string-operand-address source))
          (dst-addr (cp1610-string-operand-address dest)))
      (format out "~&~8tMVII    #~a, R2" src-addr)
      (format out "~&~8tMVII    #~a, R3" dst-addr)
      (let ((lbl (cp1610-label "blt")))
        (format out "~&~8tMVII    #~d, R1" len)
        (format out "~&~a:" lbl)
        (format out "~&~8tMVI@    R2, R0")
        (format out "~&~8tMVO@    R0, R3")
        (format out "~&~8tDECR    R1")
        (format out "~&~8tBNEQ    ~a" lbl)))))
