;; src/backend-6502.lisp -- 6502 / 64tass code generation backend
;;
;; Implements COMPILE-TO-ASSEMBLY for the :6502 CPU keyword. Targets the
;; MOS  6502   instruction  set,   emitting  64tass   assembler  syntax.
;; Output conforms  to OOPS (Object-Oriented Programming  System) naming
;; conventions defined in Phantasia/SkylineTool.
;;
;; CPU-specific  instruction   sets  (64tass  format):  6502:   JMP  for
;; branches;  SED/CLD for  BCD;  undocumented opcodes  (lax, dcp)  where
;; helpful 65c02:  BRA, STZ, TRB,  TSB; no undocumented  opcodes 65c816:
;; Like 65c02 (emulation mode); 64tass  syntax HuC6280: Like 65c02; bank
;; switching via macros  RP2A03: 6502 subset; no SED  (no decimal mode);
;; software BCD
;;
;; Key  conventions:  Method  labels: MethodCharacterThink:  .block  ...
;; .bend GOBACK/EXIT: rts INVOKE Self "M": jsr Invoke{Class}M INVOKE Var
;; "M":  .CallMethod  Call{Type}M,  {Type}Class, Var  Slot  access:  ldy
;; #{OriginClass}{Slot} /  lda (Self), y  Array access:  ldx index  / lda
;; base, x  (X  for  subscript;  Y   for  slot)  Constants  (78/77):  lda
;; #ConstName    (immediate   addressing)    Variables:   lda    VarName
;; (direct/absolute addressing) Fault:  .LogFault "code" (4-char string;
;; assembler does minifont)
;;
;; Register  usage: A=accumulator,  X=subscript  index  or temp,  Y=slot
;; offset.   Array   fetches   use    X   (or   Y   for   slot-of-self).
;; Complex expressions may have multiple subscripts at different stages.
;; When using X  for temp (e.g. 16-bit add low-byte),  prefer PHA/PLA if
;; operands contain subscripts to avoid conflict.

(in-package :eightbol)

;;; CPU variant selection (bound during compilation)

(defvar *6502-family-cpu* :6502
  "CPU keyword for 6502-family backends. One of :6502 :65c02 :65c816 :huc6280 :rp2a03.
Controls opcode choice: bra vs jmp, stz vs lda/sta, undocumented opcodes.")

(defun 6502-branch-always-mnemonic ()
  "Return \"jmp\" for 6502/RP2A03 (no BRA), \"bra\" for 65c02/65c816/HuC6280."
  (if (member *6502-family-cpu* '(:65c02 :65c816 :huc6280))
      "bra"
      "jmp"))

(defun 6502-has-stz-p ()
  "True if CPU has STZ (65c02 and derivatives)."
  (member *6502-family-cpu* '(:65c02 :65c816 :huc6280)))

(defun 6502-use-undocumented-p ()
  "True if CPU allows undocumented 6502 opcodes (lax, dcp, etc.). Only :6502."
  (eq *6502-family-cpu* :6502))

(defun emit-6502-store-zero (out addr)
  "Emit code to store zero to memory at ADDR. Uses stz for 65c02+, lda # 0 + sta for 6502/RP2A03."
  (if (6502-has-stz-p)
      (format out "~&~10Tstz ~a" addr)
      (progn
        (format out "~&~10Tlda # 0")
        (format out "~&~10Tsta ~a" addr))))

;;; Top-level entry point

(defun method-blank-p (method)
  "True if METHOD has no statements (blank method). Blank methods delegate to a single shared implementation."
  (null (ensure-list (getf (rest method) :statements))))

(defun compile-6502-family (ast output-stream cpu)
  "Shared code generation for 6502-family CPUs (6502, 65c02, 65c816, HuC6280).
CPU is the keyword (:6502 :65c02 :65c816 :huc6280). Binds *6502-family-cpu* for opcode selection.
Blank methods (no statements) delegate to a single Method{Class}Blank."
  (let ((*6502-family-cpu* cpu)
        (cpu-label (cpu-display-name cpu)))
    (unless (and (listp ast) (eq (first ast) :program))
      (error "EIGHTBOL/~a: expected :program AST node, got ~s" cpu-label (first ast)))
    (let* ((class-id (getf (rest ast) :class-id))
           (methods (getf (rest ast) :methods))
           (has-blank (some (lambda (m)
                              (and (listp m) (eq (first m) :method)
                                   (method-blank-p m)))
                            (ensure-list methods))))
      (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table pic-size-table pic-width-table)
          (load-copybook-tables class-id)
        (let ((*output-stream* output-stream)
              (*class-id* class-id)
              (*slot-table* slot-table)
              (*type-table* type-table)
              (*const-table* const-table)
              (*service-bank-table* service-bank-table)
              (*usage-table* usage-table)
              (*sign-table* sign-table)
              (*pic-size-table* pic-size-table)
              (*pic-width-table* pic-width-table))
          (format output-stream
                  ";;; ~a -- generated by EIGHTBOL for ~a~%;;; DO NOT EDIT -- regenerate from ~a.cob~2%"
                  class-id cpu-label class-id)
          (dolist (method (ensure-list methods))
            (when (and (listp method) (eq (first method) :method))
              (if (method-blank-p method)
                  (format output-stream "~&Method~a~a: ~a Method~aBlank"
                          class-id (getf (rest method) :method-id)
                          (6502-branch-always-mnemonic) class-id)
                  (compile-6502-method method class-id cpu))))
          (when has-blank
            (format output-stream "~&Method~aBlank: .block~%        rts~&~10T.bend" class-id)))))))

(defmethod compile-to-assembly (ast (cpu (eql :6502)) output-stream)
  (compile-6502-family ast output-stream :6502))

;;; Method compilation

(defun compile-6502-method (method class-id cpu)
  (let* ((*method-id* (getf (rest method) :method-id))
         (statements (getf (rest method) :statements)))
    (format *output-stream* "~&Method~a~a: .block" class-id *method-id*)
    (dolist (stmt (ensure-list statements))
      (when (and stmt (first stmt))
        (compile-statement cpu (first stmt) (rest stmt))))
    (format *output-stream* "~&~10T.bend")))

;;; Statement dispatch via generic functions (compile-statement-* methods below)

;;; Parser format  normalization Parser  produces ("HP" "OF"  "Self") or
;;; ("HP" OF "Self"); backend expects (:of slot obj).

(defun normalize-slot-of (expr)
  "Convert parser format (slot \"OF\" obj) to (:of slot obj). Return NIL if not slot-of form."
  (when (and (listp expr) (= (length expr) 3))
    (let ((slot (first expr))
          (of (second expr))
          (obj (third expr)))
      (when (or (equal of "OF") (eq of 'eightbol::of))
        (list :of slot obj)))))

(defun slot-of-self-p (expr)
  "True if EXPR is slot OF Self in either (:of slot :self) or (slot OF Self) format."
  (let ((norm (or (and (listp expr) (eq (first expr) :of) expr)
                  (normalize-slot-of expr))))
    (when norm
      (member (third norm) '(:self "Self" self) :test #'equal))))

(defun slot-of-expr (expr)
  "Return (:of slot obj) form for EXPR, or NIL."
  (cond
    ((and (listp expr) (eq (first expr) :of)) expr)
    (t (normalize-slot-of expr))))

;;; Expression emission

(defun emit-6502-value (expr)
  "Return a 64tass expression string for EXPR.
All string identifiers are converted to PascalCase assembly symbols."
  (cond
    ((numberp expr) (format nil "~d" expr))
    ((and (listp expr) (eq (first expr) :literal))
     (format nil "~d" (second expr)))
    ((stringp expr) (to-pascal-case expr))
    ((eq expr :self) "Self")
    ((eq expr :null) "0")
    ((slot-of-expr expr)
     ;; slot OF obj -- used as rvalue address; prefer slot-symbol for Self case
     (let ((n (slot-of-expr expr)))
       (format nil "(~a)" (second n))))
    ((and (listp expr) (eq (first expr) :subscript))
     ;; (:subscript base-name index) -- indexed table access, e.g. DecalXH, x
     (format nil "~a, x"
             (to-pascal-case (format nil "~a" (second expr)))))
    (t (format nil "~a" expr))))

(defun expr-is-literal-zero-p (expr)
  (or (eql expr 0)
      (equal expr "0")
      (and (listp expr) (eq (first expr) :literal) (eql (second expr) 0))))

(defun emit-6502-immediate (value)
  "Return assembly string for immediate operand: #value. Numbers use hex (#$xx)."
  (concatenate 'string (string #\#)
               (cond ((and (integerp value) (<= 0 value) (<= value 255))
                      (format nil "$~2,'0x" value))
                     ((integerp value)
                      (format nil "$~x" value))
                     (t
                      (princ-to-string value)))))

(defun expr-is-constant-p (expr)
  "True if EXPR is a numeric literal or a named constant from CONST-TBL."
  (or (numberp expr)
      (and (listp expr) (eq (first expr) :literal))
      (and (stringp expr) (constant-p expr))))

(defun expr-constant-value (expr)
  "Return numeric value of constant EXPR. EXPR must satisfy expr-is-constant-p."
  (cond
    ((numberp expr) expr)
    ((and (listp expr) (eq (first expr) :literal)) (second expr))
    ((stringp expr) (constant-value expr))
    (t (error "Not a constant: ~s" expr))))

(defun power-of-two-p (n)
  "True if N is a positive power of two (1, 2, 4, 8, ...)."
  (and (integerp n) (> n 0) (zerop (logand n (1- n)))))

(defun log2 (n)
  "Return k such that 2^k = N, or NIL if N is not a power of two."
  (when (power-of-two-p n)
    (do ((k 0 (1+ k))
         (v 1 (* v 2)))
        ((>= v n) k))))

;;; Load into A register

(defun emit-6502-load-expr (out expr class-id)
  "Emit 6502 code to load EXPR into the A register.
Constants (numeric literals and named 77/78 items) use immediate mode (#).
Variables and slots use direct/indexed mode.
Compound bit/shift expressions are computed in-line."
  (cond
    ;; Arithmetic: a + b
    ((and (listp expr) (eq (first expr) :add-expr))
     (emit-6502-load-expr out (second expr) class-id)
     (format out "~&~10Tclc")
     (let ((rhs (third expr)))
       (if (expr-is-constant-p rhs)
           (format out "~&~10Tadc #~a" (emit-6502-immediate (expr-constant-value rhs)))
           (format out "~&~10Tadc ~a" (emit-6502-value rhs)))))
    ;; Arithmetic: a - b
    ((and (listp expr) (eq (first expr) :subtract-expr))
     (emit-6502-load-expr out (second expr) class-id)
     (format out "~&~10Tsec")
     (let ((rhs (third expr)))
       (if (expr-is-constant-p rhs)
           (format out "~&~10Tsbc #~a" (emit-6502-immediate (expr-constant-value rhs)))
           (format out "~&~10Tsbc ~a" (emit-6502-value rhs)))))
    ;; Arithmetic: a * k (k must be power of 2)
    ((and (listp expr) (eq (first expr) :multiply-expr))
     (let ((e1 (second expr)) (e2 (third expr)))
       (when (expr-is-constant-p e2)
         (let ((shift (log2 (expr-constant-value e2))))
           (when shift
             (emit-6502-load-expr out e1 class-id)
             (dotimes (_ shift) (format out "~&~10Tasl a"))
             (return-from emit-6502-load-expr))))
       (error 'backend-error
              :message "6502: multiply by non-power-of-2 requires software routine"
              :cpu :6502 :detail (list :multiply-expr e1 e2))))
    ;; Arithmetic: a / k (k must be power of 2)
    ((and (listp expr) (eq (first expr) :divide-expr))
     (let ((e1 (second expr)) (e2 (third expr)))
       (when (expr-is-constant-p e2)
         (let ((shift (log2 (expr-constant-value e2))))
           (when shift
             (emit-6502-load-expr out e1 class-id)
             (dotimes (_ shift) (format out "~&~10Tlsr a"))
             (return-from emit-6502-load-expr))))
       (error 'backend-error
              :message "6502: divide by non-power-of-2 requires software routine"
              :cpu :6502 :detail (list :divide-expr e1 e2))))
    ;; Subscripted array: base(index) — load index into X, then lda base, x
    ((and (listp expr) (eq (first expr) :subscript))
     (emit-6502-load-expr out (third expr) class-id)
     (format out "~&~10Ttax")
     (format out "~&~10Tlda ~a" (emit-6502-value expr)))
    ;; Slot OF Self -- indexed indirect via Self pointer
    ((slot-of-self-p expr)
     (let ((n (slot-of-expr expr)))
       (format out "~&~10Tldy ~a" (emit-6502-immediate (slot-symbol (second n) class-id)))
       (format out "~&~10Tlda (Self), y")))
    ;; Shift left — asl A, n times
    ((and (listp expr) (eq (first expr) :shift-left))
     (let ((n (if (numberp (third expr)) (third expr) 1)))
       (emit-6502-load-expr out (second expr) class-id)
       (dotimes (_ n) (format out "~&~10Tasl a"))))
    ;; Shift right — lsr A, n times
    ((and (listp expr) (eq (first expr) :shift-right))
     (let ((n (if (numberp (third expr)) (third expr) 1)))
       (emit-6502-load-expr out (second expr) class-id)
       (dotimes (_ n) (format out "~&~10Tlsr a"))))
    ;; Bitwise AND (mask — used for bit testing too)
    ((and (listp expr) (eq (first expr) :bit-and))
     (emit-6502-load-expr out (second expr) class-id)
     (let ((rhs (third expr)))
       (if (expr-is-constant-p rhs)
           (format out "~&~10Tand #~a" (emit-6502-value rhs))
           (format out "~&~10Tand ~a" (emit-6502-value rhs)))))
    ;; Bitwise OR
    ((and (listp expr) (eq (first expr) :bit-or))
     (emit-6502-load-expr out (second expr) class-id)
     (let ((rhs (third expr)))
       (if (expr-is-constant-p rhs)
           (format out "~&~10Tora #~a" (emit-6502-value rhs))
           (format out "~&~10Tora ~a" (emit-6502-value rhs)))))
    ;; Bitwise XOR
    ((and (listp expr) (eq (first expr) :bit-xor))
     (emit-6502-load-expr out (second expr) class-id)
     (let ((rhs (third expr)))
       (if (expr-is-constant-p rhs)
           (format out "~&~10Teor #~a" (emit-6502-value rhs))
           (format out "~&~10Teor ~a" (emit-6502-value rhs)))))
    ;; Bitwise NOT (complement all bits)
    ((and (listp expr) (eq (first expr) :bit-not))
     (emit-6502-load-expr out (second expr) class-id)
     (format out "~&~10Teor #$ff"))
    ;; Numeric literal (:literal n) from VALUE clause
    ((and (listp expr) (eq (first expr) :literal))
     (format out "~&~10Tlda ~a" (emit-6502-immediate (second expr))))
    ;; Numeric literal
    ((numberp expr)
     (format out "~&~10Tlda ~a" (emit-6502-immediate expr)))
    ;; Named constant (78/77 level)
    ((and (stringp expr) (constant-p expr))
     (format out "~&~10Tlda #~a" (to-pascal-case expr)))
    ;; Global or local variable
    ((stringp expr)
     (format out "~&~10Tlda ~a" (to-pascal-case expr)))
    (t
     (format out "~&~10Tlda ~a" (emit-6502-value expr)))))

(defun emit-6502-load-hi-byte (out ptr-expr class-id)
  "Load the high byte of a 2-byte value into A. Handles literals, constants, variables.
For :subscript, loads index into X then lda base + 1, x."
  (emit-6502-load-byte-n out ptr-expr class-id 1 2))

(defun constant-byte-value (expr n)
  "Extract byte N (0-based) from constant EXPR. Little-endian."
  (let ((v (cond ((numberp expr) expr)
                 ((and (listp expr) (eq (first expr) :literal)) (second expr))
                 ((and (stringp expr) (constant-p expr)) (constant-value expr))
                 (t nil))))
    (when v (ldb (byte 8 (* n 8)) v))))

(defun emit-6502-load-byte-n (out expr class-id n w)
  "Load byte N (0-based) of W-byte EXPR into A. N must be < W.
Handles literals, constants, variables, slot OF Self, subscript."
  (when (>= n w)
    (error "emit-6502-load-byte-n: n ~d >= w ~d" n w))
  (cond
    ((expr-is-constant-p expr)
     (let ((b (constant-byte-value expr n)))
       (format out "~&~10Tlda ~a" (emit-6502-immediate (or b 0)))))
    ((and (listp expr) (eq (first expr) :subscript))
     (emit-6502-load-expr out (third expr) class-id)
     (format out "~&~10Ttax")
     (format out "~&~10Tlda ~a + ~d, x" (to-pascal-case (format nil "~a" (second expr))) n))
    ((slot-of-self-p expr)
     (let ((offset (slot-symbol (second (slot-of-expr expr)) class-id)))
       (format out "~&~10Tldy #~a" (if (zerop n) offset (format nil "(~a+~d)" offset n)))
       (format out "~&~10Tlda (Self), y")))
    ((stringp expr)
     (format out "~&~10Tlda ~a~a"
             (to-pascal-case expr)
             (if (zerop n) "" (format nil " + ~d" n))))
    (t
     (format out "~&~10Tlda ~a~a"
             (emit-6502-value expr)
             (if (zerop n) "" (format nil " + ~d" n))))))

(defun emit-6502-store-byte-n (out dest class-id n w)
  "Store A to byte N (0-based) of W-byte DEST. Handles slot OF Self, variable."
  (when (>= n w)
    (error "emit-6502-store-byte-n: n ~d >= w ~d" n w))
  (cond
    ((slot-of-self-p dest)
     (let ((offset (slot-symbol (second (slot-of-expr dest)) class-id)))
       (format out "~&~10Tldy #~a" (if (zerop n) offset (format nil "(~a+~d)" offset n)))
       (format out "~&~10Tsta (Self), y")))
    ((stringp dest)
     (format out "~&~10Tsta ~a~a"
             (to-pascal-case dest)
             (if (zerop n) "" (format nil " + ~d" n))))
    (t
     (format out "~&~10Tsta ~a~a"
             (emit-6502-value dest)
             (if (zerop n) "" (format nil " + ~d" n))))))

(defun emit-6502-move-n-bytes (out from to-dest from-w to-w class-id &key sign-extend)
  "Copy FROM (from-w bytes) to TO-DEST (to-w bytes). Sign-extends if SIGN-EXTEND and from-w < to-w."
  (dotimes (i (min from-w to-w))
    (emit-6502-load-byte-n out from class-id i from-w)
    (emit-6502-store-byte-n out to-dest class-id i to-w))
  (when (and (< from-w to-w) (>= to-w 2))
    (let ((lbl-zero (new-6502-label "MvZero"))
          (lbl-done (new-6502-label "MvDone")))
      (if sign-extend
          (progn
            (emit-6502-load-byte-n out from class-id (1- from-w) from-w)
            (format out "~&~10Tbpl ~a" lbl-zero)
            (format out "~&~10Tlda #$ff")
            (dotimes (i (- to-w from-w))
              (emit-6502-store-byte-n out to-dest class-id (+ from-w i) to-w))
            (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-done)
            (format out "~&~a:" lbl-zero)
            (format out "~&~10Tlda ~a" (emit-6502-immediate 0))
            (dotimes (i (- to-w from-w))
              (emit-6502-store-byte-n out to-dest class-id (+ from-w i) to-w))
            (format out "~&~a:" lbl-done))
          (dotimes (i (- to-w from-w))
            (format out "~&~10Tlda ~a" (emit-6502-immediate 0))
            (emit-6502-store-byte-n out to-dest class-id (+ from-w i) to-w))))))

;;; Operand width for byte/word arithmetic (PIC 99 vs PIC 9999)

(defun expr-contains-subscript-p (expr)
  "True if EXPR or any subexpression uses :subscript (array fetch).
Array fetches use X or Y; when true, avoid using X for temp storage."
  (cond
    ((and (listp expr) (eq (first expr) :subscript)) t)
    ((and (listp expr) (member (first expr) '(:add-expr :subtract-expr :multiply-expr :divide-expr
                                            :shift-left :shift-right :bit-and :bit-or :bit-xor :bit-not)))
     (or (expr-contains-subscript-p (second expr))
         (expr-contains-subscript-p (third expr))))
    ((and (listp expr) (eq (first expr) :of))
     (expr-contains-subscript-p (third expr)))
    (t nil)))

;;; MOVE statement
;;; operand-width uses *pic-width-table* (backend.lisp)

(defun compile-6502-move (out stmt class-id)
  (let* ((from (getf (rest stmt) :from))
         (to-dest (getf (rest stmt) :to))
         (to-w (operand-width to-dest))
         (from-signed (operand-signed-p from))
         (to-signed (operand-signed-p to-dest))
         (sign-extend (and from-signed to-signed)))
    (cond
      ;; Destination is subscripted: base(index) — load index into X, then store
      ((and (listp to-dest) (eq (first to-dest) :subscript))
       (emit-6502-load-expr out (third to-dest) class-id)
       (format out "~&~10Ttax")
       (emit-6502-load-expr out from class-id)
       (format out "~&~10Tsta ~a" (emit-6502-value to-dest)))
      ;; Source is subscripted: base(index) — load index into X, then load
      ((and (listp from) (eq (first from) :subscript))
       (emit-6502-load-expr out (third from) class-id)
       (format out "~&~10Ttax")
       (format out "~&~10Tlda ~a" (emit-6502-value from))
       (format out "~&~10Tsta ~a" (emit-6502-value to-dest)))
      ;; Destination is slot OF Self
      ((slot-of-self-p to-dest)
       (let ((from-w (operand-width from)))
         (emit-6502-move-n-bytes out from to-dest from-w to-w class-id :sign-extend sign-extend)))
      ;; Source is slot OF Self, destination is a variable
      ((slot-of-self-p from)
       (let ((from-w (operand-width from)))
         (emit-6502-move-n-bytes out from to-dest from-w to-w class-id :sign-extend sign-extend)))
      ;; General: variable or constant to variable
      (t
       (let ((from-w (operand-width from)))
         (emit-6502-move-n-bytes out from to-dest from-w to-w class-id :sign-extend sign-extend))))))

;;; STRING BLT (block transfer)
;;; STRING source DELIMITED BY SIZE INTO dest [LENGTH length]
;;; Source/dest may have reference modification: name(start:length)

(defun string-operand-address (operand class-id)
  "Return 64tass address expression for STRING operand (identifier or :refmod).
For :refmod, returns Base+offset for 1-based start."
  (declare (ignore class-id))
  (cond
    ((and (listp operand) (eq (first operand) :refmod))
     (let* ((base (getf (rest operand) :base))
            (start (getf (rest operand) :start))
            (base-str (to-pascal-case (format nil "~a" base))))
       (if (and (integerp start) (= start 1))
           base-str
           (format nil "~a+~d" base-str (1- start)))))
    (t
     (emit-6502-value operand))))

(defun string-operand-length-expr (operand stmt)
  "Return length expression for STRING: from :length clause or from :refmod."
  (or (getf (rest stmt) :length)
      (when (and (listp operand) (eq (first operand) :refmod))
        (getf (rest operand) :length))))

(defun resolve-length-constant (length-expr)
  "Resolve length expression to integer. Supports number, symbol (constant), or nil."
  (cond
    ((integerp length-expr) length-expr)
    ((stringp length-expr) (constant-value length-expr))
    (t (constant-value (princ-to-string length-expr)))))

(defun compile-6502-string-blt (out stmt class-id)
  "Emit 6502 block copy loop for STRING source DELIMITED BY SIZE INTO dest."
  (let* ((source (getf (rest stmt) :source))
         (dest (getf (rest stmt) :dest))
         (length-expr (string-operand-length-expr source stmt))
         (len-val (resolve-length-constant length-expr)))
    (unless length-expr
      (error "EIGHTBOL: STRING DELIMITED BY SIZE requires LENGTH clause when source/dest have no reference modification"))
    (unless (and len-val (integerp len-val) (plusp len-val))
      (error "EIGHTBOL: STRING BLT length must be a positive integer constant"))
    (let ((src-addr (string-operand-address source class-id))
          (dst-addr (string-operand-address dest class-id)))
      (format out "~&~10T;; STRING ~a DELIMITED BY SIZE INTO ~a (~d bytes)"
              (if (listp source) (getf (rest source) :base) source)
              (if (listp dest) (getf (rest dest) :base) dest)
              len-val)
      (format out "~&~10Tldy ~a" (emit-6502-immediate 0))
      (format out "~&~10T:_blt")
      (format out "~&~10Tlda ~a, y" src-addr)
      (format out "~&~10Tsta ~a, y" dst-addr)
      (format out "~&~10Tiny")
      (format out "~&~10Tcpy #~d" len-val)
      (format out "~&~10Tbne :_blt"))))

;;; GOTO and paragraph

(defun para-label (name class-id method-id)
  "Return assembly label for paragraph NAME within method."
  (to-pascal-case (format nil "~a_~a_~a" class-id method-id name)))

(defun compile-6502-paragraph (out stmt class-id method-id)
  (let ((name (or (getf (rest stmt) :paragraph) (second stmt))))
    (when name
      (format out "~&~a:" (para-label (format nil "~a" name) class-id (or method-id ""))))))

(defun compile-6502-goto (out stmt class-id method-id)
  (let ((target (getf (rest stmt) :target))
        (targets (getf (rest stmt) :targets))
        (dep (getf (rest stmt) :depending-on)))
    (if dep
        ;; GO TO ... DEPENDING ON expr — trinary search tree (cmp/beq: equal, <, >)
        (let ((tgt-list (or targets (when target (list target)))))
          (emit-6502-load-expr out dep class-id)
          (emit-6502-goto-tristree out tgt-list 1 (length tgt-list)
                                   class-id method-id))
        ;; Simple GOTO
        (format out "~&~10T~a ~a"
                (6502-branch-always-mnemonic)
                (para-label (format nil "~a" (or target (first targets))) class-id (or method-id ""))))))

(defun emit-6502-goto-tristree (out targets lo hi class-id method-id)
  "Emit trinary search: cmp #mid; beq target_mid; bcc left; bcs right.
TARGETS is list of paragraph names (1-based indices). LO, HI are 1-based inclusive."
  (when (or (null targets) (> lo hi)) (return-from emit-6502-goto-tristree))
  (let ((mid (floor (+ lo hi) 2))
        (tgt-name (nth (1- mid) targets)))
    (when (null tgt-name) (return-from emit-6502-goto-tristree))
    (let ((lbl (para-label (format nil "~a" tgt-name) class-id (or method-id ""))))
      (if (= lo hi)
          ;; Leaf: single target
          (format out "~&~10Tcmp #~d~% beq ~a" mid lbl)
          (let ((lbl-less (new-6502-label "GtLess"))
                (lbl-more (new-6502-label "GtMore")))
            (format out "~&~10Tcmp #~d" mid)
            (format out "~&~10Tbeq ~a" lbl)
            (format out "~&~10Tbcc ~a" lbl-less)
            (format out "~&~10Tbcs ~a" lbl-more)
            (format out "~&~a:" lbl-less)
            (when (<= lo (1- mid))
              (emit-6502-goto-tristree out targets lo (1- mid) class-id method-id))
            (format out "~&~a:" lbl-more)
            (when (<= (1+ mid) hi)
              (emit-6502-goto-tristree out targets (1+ mid) hi class-id method-id)))))))

;;; EVALUATE statement

(defun compile-6502-evaluate (out stmt cpu)
  (let ((subject (getf (rest stmt) :subject))
        (clauses (getf (rest stmt) :when-clauses))
        (lbl-end (new-6502-label "EvalEnd")))
    (dolist (clause (ensure-list clauses))
      (cond
        ((eq (first clause) :when-other)
         ;; WHEN OTHER — fall-through, execute stmts
         (dolist (s (ensure-list (second clause)))
           (compile-statement cpu (first s) (rest s))))
        ((eq (first clause) :when)
         (let ((phrases (second clause))
               (stmts (third clause))
               (lbl-next (new-6502-label "WhenNext")))
           ;; Compare subject to phrases; if match, execute stmts and jump to end
           (cond
             ((eq phrases 'eightbol::any)
              ;; WHEN ANY — always match
              (dolist (s (ensure-list stmts))
                (compile-statement cpu (first s) (rest s)))
              (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-end))
             ((or (eq phrases 'eightbol::true) (equal phrases "TRUE"))
              (emit-6502-load-expr out subject *class-id*)
              (format out "~&~10Tbeq ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-statement cpu (first s) (rest s)))
              (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-end)
              (format out "~&~a:" lbl-next))
             ((or (eq phrases 'eightbol::false) (equal phrases "FALSE"))
              (emit-6502-load-expr out subject *class-id*)
              (format out "~&~10Tbne ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-statement cpu (first s) (rest s)))
              (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-end)
              (format out "~&~a:" lbl-next))
             ((and (listp phrases) (eq (first phrases) :not))
              ;; WHEN NOT expr — subject must not equal expr
              (emit-6502-load-expr out subject *class-id*)
              (if (expr-is-constant-p (second phrases))
                  (format out "~&~10Tcmp #~a" (emit-6502-value (second phrases)))
                  (format out "~&~10Tcmp ~a" (emit-6502-value (second phrases))))
              (format out "~&~10Tbeq ~a" lbl-next)
              (dolist (s (ensure-list stmts))
                (compile-statement cpu (first s) (rest s)))
              (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-end)
              (format out "~&~a:" lbl-next))
             ((and (listp phrases) (member (first phrases) '(:through thru)))
              ;; WHEN expr1 THROUGH expr2 — subject in [lo, hi] inclusive
              (let ((lo (second phrases)) (hi (third phrases)))
                (emit-6502-load-expr out subject *class-id*)
                (if (expr-is-constant-p lo)
                    (format out "~&~10Tcmp #~a" (emit-6502-value lo))
                    (format out "~&~10Tcmp ~a" (emit-6502-value lo)))
                (format out "~&~10Tbcc ~a" lbl-next)
                ;; Upper bound: skip when subject > hi, i.e. subject >= hi + 1
                (if (and (expr-is-constant-p hi) (numberp hi))
                    (format out "~&~10Tcmp #~d" (1+ hi))
                    (progn
                      ;; subject - hi: if >= 1 then subject > hi, skip
                      (format out "~&~10Tsec")
                      (if (expr-is-constant-p hi)
                          (format out "~&~10Tsbc #~a" (emit-6502-value hi))
                          (format out "~&~10Tsbc ~a" (emit-6502-value hi)))
                      (format out "~&~10Tcmp ~a" (emit-6502-immediate 1))))
                (format out "~&~10Tbcs ~a" lbl-next)
                (dolist (s (ensure-list stmts))
                  (compile-statement cpu (first s) (rest s)))
                (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-end)
                (format out "~&~a:" lbl-next)))
             (t
              ;; WHEN expr — equality
              (let ((phrase-expr (if (listp phrases) (second phrases) phrases)))
                (emit-6502-load-expr out subject *class-id*)
                (if (expr-is-constant-p phrase-expr)
                    (format out "~&~10Tcmp #~a" (emit-6502-value phrase-expr))
                    (format out "~&~10Tcmp ~a" (emit-6502-value phrase-expr)))
                (format out "~&~10Tbne ~a" lbl-next))
              (dolist (s (ensure-list stmts))
                (compile-statement cpu (first s) (rest s)))
              (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-end)
              (format out "~&~a:" lbl-next)))))))
    (format out "~&~a:" lbl-end)))

;;; INSPECT statement

(defun compile-6502-inspect (out stmt class-id)
  (let ((target (getf (rest stmt) :target))
        (tally (getf (rest stmt) :tallying))
        (conv-from (getf (rest stmt) :converting))
        (conv-to (getf (rest stmt) :to))
        (repl-by (getf (rest stmt) :by)))
    (let ((tgt-sym (to-pascal-case (format nil "~a" target))))
      (cond
        (tally
         ;; INSPECT id TALLYING tally FOR CHARACTERS — add 1 to tally per character
         (let ((tally-sym (to-pascal-case (format nil "~a" tally))))
           (format out "~&~10T;; INSPECT ~a TALLYING ~a FOR CHARACTERS" target tally)
           (format out "~&~10Tldy ~a" (emit-6502-immediate 0))
           (let ((lbl (new-6502-label "TallyLoop"))
                 (lbl-done (new-6502-label "TallyDone"))
                 (lbl-skip (new-6502-label "TallySkip")))
             (format out "~&~a:" lbl)
             (format out "~&~10Tlda ~a, y" tgt-sym)
             (format out "~&~10Tbeq ~a" lbl-done)
             (format out "~&~10Tlda ~a" tally-sym)
             (format out "~&~10Tclc")
             (format out "~&~10Tadc ~a" (emit-6502-immediate 1))
             (format out "~&~10Tsta ~a" tally-sym)
             (format out "~&~10Tbcc ~a" lbl-skip)
             (format out "~&~10Tinc ~a + 1" tally-sym)
             (format out "~&~a:" lbl-skip)
             (format out "~&~10Tiny")
             (format out "~&~10Tbne ~a" lbl)
             (format out "~&~a:" lbl-done))))
        (conv-from
         ;; INSPECT id CONVERTING from TO to — replace chars in string
         (format out "~&~10T;; INSPECT ~a CONVERTING" target)
         (format out "~&~10Tldy ~a" (emit-6502-immediate 0))
         (let ((lbl (new-6502-label "InspLoop"))
               (lbl-next (new-6502-label "InspNext"))
               (lbl-done (new-6502-label "InspDone")))
           (format out "~&~a:" lbl)
           (format out "~&~10Tlda ~a, y" tgt-sym)
           (format out "~&~10Tbeq ~a" lbl-done)
           (if (expr-is-constant-p conv-from)
               (format out "~&~10Tcmp #~a" (emit-6502-value conv-from))
               (format out "~&~10Tcmp ~a" (emit-6502-value conv-from)))
           (format out "~&~10Tbne ~a" lbl-next)
           (if (expr-is-constant-p conv-to)
               (format out "~&~10Tlda #~a" (emit-6502-value conv-to))
               (format out "~&~10Tlda ~a" (emit-6502-value conv-to)))
           (format out "~&~10Tsta ~a, y" tgt-sym)
           (format out "~&~a:" lbl-next)
           (format out "~&~10Tiny")
           (format out "~&~10Tbne ~a" lbl)
           (format out "~&~a:" lbl-done)))
        (repl-by
         ;; INSPECT id REPLACING CHARACTERS BY expr — fill string with expr
         (let ((len (or (pic-size (format nil "~a" target)) 64)))
           (format out "~&~10T;; INSPECT ~a REPLACING CHARACTERS BY ~a" target repl-by)
           (emit-6502-load-expr out repl-by class-id)
           (format out "~&~10Tldy ~a" (emit-6502-immediate 0))
           (let ((lbl (new-6502-label "InspLoop")))
             (format out "~&~a:" lbl)
             (format out "~&~10Tsta ~a, y" tgt-sym)
             (format out "~&~10Tiny")
             (format out "~&~10Tcpy #~d" len)
             (format out "~&~10Tbne ~a" lbl))))))))

;;; INVOKE statement

(defun compile-6502-invoke (out stmt class-id)
  (let ((object (getf (rest stmt) :object))
        (method (getf (rest stmt) :method))
        (returning (getf (rest stmt) :returning))
        (tail-call-p (getf (rest stmt) :tail-call-p)))
    (let ((method-sym (to-pascal-case (if (stringp method) method
                                          (format nil "~a" method))))
          (jmp-p (and tail-call-p (null returning))))
      (cond
        ;; INVOKE Self "Method"
        ((member object '(:self "Self" self) :test #'equal)
         (format out "~&~10T~a Invoke~a~a" (if jmp-p "jmp" "jsr") class-id method-sym))
        ;; INVOKE ObjVar "Method" -- typed dispatch via .CallMethod
        (t
         (let* ((obj-name (to-pascal-case (format nil "~a" object)))
                (obj-class (or (var-class obj-name) "Unknown")))
           (if (string= obj-class "Unknown")
               (format out "~&~10T~a Call~aMethod" (if jmp-p "jmp" "jsr") method-sym)
               (format out "~&~10T.CallMethod Call~a~a, ~aClass, ~a"
                       obj-class method-sym obj-class obj-name))))))
    (when returning
      (format out "~&~10Tsta ~a" (to-pascal-case (format nil "~a" returning))))))

;;; CALL statement

(defun sym-string (x)
  "Return a PascalCase symbol string from a literal, identifier, or string value."
  (to-pascal-case (if (listp x) (format nil "~a" (second x)) (format nil "~a" x))))

(defun compile-6502-call (out stmt)
  (let* ((target (getf (rest stmt) :target))
         (service (getf (rest stmt) :service))
         (bank (getf (rest stmt) :bank))
         (libraryp (getf (rest stmt) :library))
         (tail-call-p (getf (rest stmt) :tail-call-p))
         (item (or service target))
         (item-sym (sym-string item))
         (resolved-bank (or bank (and item-sym
                                      (gethash item-sym *service-bank-table*))))
         (jmp-p tail-call-p))
    (cond
      ;; CALL target IN SERVICE bank. / CALL SERVICE target. — service dispatch
      (service
       (if resolved-bank
           (let ((bank-sym (sym-string resolved-bank)))
             (format out "~&~10T.FarCall ~a, ~a" item-sym bank-sym))
           (error "EIGHTBOL: CALL ~a IN SERVICE requires bank (not in service-bank table)" item-sym)))
      ;; CALL target IN LIBRARY name. — LastBank is always resident
      (libraryp
       (format out "~&~10T~a ~a" (if jmp-p "jmp" "jsr") item-sym))
      ;; CALL target IN BANK bank. — bank-switched far call
      (bank
       (let ((bank-sym (sym-string bank)))
         (format out "~&~10T.FarJSR ~a, ~a" bank-sym item-sym)))
      ;; CALL target. — local near call
      (t
       (format out "~&~10T~a ~a" (if jmp-p "jmp" "jsr") item-sym)))))

;;; IF / conditional compilation

(defvar *6502-label-counter* 0)

(defun new-6502-label (prefix)
  "Generate unique label with meaningful name (L prefix, letter-start for 64tass)."
  (format nil "L~a~d" prefix (incf *6502-label-counter*)))

(defun compile-6502-if (out stmt cpu)
  (let ((condition (getf (rest stmt) :condition))
        (then-stmts (getf (rest stmt) :then))
        (else-stmts (getf (rest stmt) :else))
        (lbl-else (new-6502-label "IfElse"))
        (lbl-end (new-6502-label "IfEnd")))
    (emit-6502-condition out condition *class-id* lbl-else)
    (dolist (s (ensure-list then-stmts))
      (compile-statement cpu (first s) (rest s)))
    (when (and else-stmts (not (null else-stmts)))
      (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-end))
    (format out "~&~a:" lbl-else)
    (when (and else-stmts (not (null else-stmts)))
      (dolist (s (ensure-list else-stmts))
        (compile-statement cpu (first s) (rest s)))
      (format out "~&~a:" lbl-end))))

(defun emit-6502-condition (out condition class-id branch-label)
  "Emit 6502 code to evaluate CONDITION and branch to BRANCH-LABEL if false."
  (when (listp condition)
    (let ((op (first condition)))
      (cond
        ;; Equality with zero (IS ZERO / IS EQUAL TO 0)
        ((and (member op '(= equal))
              (or (expr-is-literal-zero-p (second condition))
                  (expr-is-literal-zero-p (third condition))))
         (let ((slot-expr (if (expr-is-literal-zero-p (second condition))
                              (third condition)
                              (second condition))))
           (emit-6502-load-expr out slot-expr class-id)
           (format out "~&~10Tbne ~a" branch-label)))
        ;; Negated zero test (IS NOT ZERO / NOT EQUAL TO 0)
        ((and (eq op :not)
              (listp (second condition))
              (member (first (second condition)) '(= equal)))
         (let ((inner (second condition)))
           (if (or (expr-is-literal-zero-p (second inner))
                   (expr-is-literal-zero-p (third inner)))
               (let ((slot-expr (if (expr-is-literal-zero-p (second inner))
                                    (third inner)
                                    (second inner))))
                 (emit-6502-load-expr out slot-expr class-id)
                 (format out "~&~10Tbeq ~a" branch-label))
               (emit-6502-generic-condition out condition class-id branch-label))))
        ;; NULL pointer test -- null if high byte = 0
        ((and (member op '(= equal))
              (or (member (second condition) '(:null null "NULL") :test #'equal)
                  (member (third condition) '(:null null "NULL") :test #'equal)))
         (let ((ptr-expr (if (member (second condition) '(:null null "NULL") :test #'equal)
                             (third condition)
                             (second condition))))
           (emit-6502-load-hi-byte out ptr-expr class-id)
           (format out "~&~10Tbne ~a" branch-label)))
        ;; IS NOT NULL
        ((and (eq op :not)
              (listp (second condition))
              (member (first (second condition)) '(= equal))
              (or (member (second (second condition)) '(:null null "NULL") :test #'equal)
                  (member (third (second condition)) '(:null null "NULL") :test #'equal)))
         (let* ((inner (second condition))
                (ptr-expr (if (member (second inner) '(:null null "NULL") :test #'equal)
                              (third inner)
                              (second inner))))
           (emit-6502-load-hi-byte out ptr-expr class-id)
           (format out "~&~10Tbeq ~a" branch-label)))
        ;; IS ZERO
        ((eq op :is-zero)
         (emit-6502-load-expr out (second condition) class-id)
         (format out "~&~10Tbne ~a" branch-label))
        ;; IS NOT ZERO
        ((eq op :is-not-zero)
         (emit-6502-load-expr out (second condition) class-id)
         (format out "~&~10Tbeq ~a" branch-label))
        ;; BIT-AND — bit test: zero flag set if masked result is zero
        ((eq op :bit-and)
         ;; Reuse emit-6502-load-expr for the full bit-and expression
         (emit-6502-load-expr out condition class-id)
         (format out "~&~10Tbeq ~a" branch-label))
        ;; Unsigned greater-than
        ((member op '(> greater))
         (emit-6502-compare out (second condition) (third condition) class-id)
         (format out "~&~10Tbcc ~a" branch-label)
         (format out "~&~10Tbeq ~a" branch-label))
        ;; Unsigned less-than
        ((member op '(< less))
         (emit-6502-compare out (second condition) (third condition) class-id)
         (format out "~&~10Tbcs ~a" branch-label))
        ;; AND — short-circuit: if first is false, branch; else evaluate second
        ((eq op :and)
         (emit-6502-condition out (second condition) class-id branch-label)
         (emit-6502-condition out (third condition) class-id branch-label))
        ;; OR — short-circuit: if first is true, skip to success; else evaluate second
        ((eq op :or)
         (let ((lbl-cond2 (new-6502-label "OrCond2"))
               (lbl-skip (new-6502-label "OrSkip")))
           (emit-6502-condition out (second condition) class-id lbl-cond2)
           (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-skip)
           (format out "~&~a:" lbl-cond2)
           (emit-6502-condition out (third condition) class-id branch-label)
           (format out "~&~a:" lbl-skip)))
        ;; Generic fallback
        (t (emit-6502-generic-condition out condition class-id branch-label))))))

(defun emit-6502-compare (out lhs rhs class-id)
  "Emit SEC/LDA/CMP sequence for unsigned 8-bit comparison LHS vs RHS."
  (emit-6502-load-expr out lhs class-id)
  (format out "~&~10Tsec")
  (if (expr-is-constant-p rhs)
      (format out "~&~10Tsbc #~a" (emit-6502-value rhs))
      (format out "~&~10Tsbc ~a" (emit-6502-value rhs))))

(defun emit-6502-generic-condition (out condition class-id branch-label)
  "Signal error for conditions not yet implemented."
  (declare (ignore out class-id branch-label))
  (error "EIGHTBOL: condition ~s not implemented" condition))

;;; ADD / SUBTRACT / COMPUTE

(defun literal-one-p (expr)
  "True when EXPR is the integer 1 or string \"1\"."
  (or (eql expr 1) (equal expr "1")))

(defun compile-6502-add (out stmt class-id)
  (let ((from (getf (rest stmt) :from))
        (to-op (getf (rest stmt) :to))
        (giving (getf (rest stmt) :giving))
        (result (or giving to-op))
        (w (operand-width result))
        (bcd-p (when result (usage-bcd-p (expr-to-width-name result)))))
    (cond
    ;; Optimise: ADD 1 TO variable (no GIVING) → inc variable (byte only)
    ((and (literal-one-p from) (not giving) (stringp to-op) (= (operand-width to-op) 1))
     (format out "~&~10Tinc ~a" (to-pascal-case to-op)))
    ;; Multi-byte ADD (w >= 2): result = from + to, carry propagates
    ((>= w 2)
     (when (and bcd-p (> w 2))
       (error "EIGHTBOL: BCD ADD with width ~d not yet implemented" w))
     (if (> w 2)
         (progn
           (when bcd-p (format out "~&~10Tsed"))
           (format out "~&~10Tclc")
           (dotimes (i w)
             (emit-6502-load-byte-n out from class-id i w)
             (if (expr-is-constant-p to-op)
                 (format out "~&~10Tadc ~a" (emit-6502-immediate (constant-byte-value to-op i)))
                 (format out "~&~10Tadc ~a~a" (emit-6502-value to-op) (if (zerop i) "" (format nil " + ~d" i))))
             (emit-6502-store-byte-n out result class-id i w))
           (when bcd-p (format out "~&~10Tcld")))
         (let ((use-stack (expr-contains-subscript-p from)))
           (when (or use-stack (expr-contains-subscript-p to-op) (expr-contains-subscript-p result))
             (setf use-stack t))
           (when bcd-p (format out "~&~10Tsed"))
           (emit-6502-load-expr out from class-id)
           (format out "~&~10Tclc")
           (if (expr-is-constant-p to-op)
               (let ((v (expr-constant-value to-op)))
                 (format out "~&~10Tadc #<~d" v))
               (format out "~&~10Tadc ~a" (emit-6502-value to-op)))
           (if use-stack
               (format out "~&~10Tpha")
               (format out "~&~10Ttax"))
           (emit-6502-load-hi-byte out from class-id)
           (if (expr-is-constant-p to-op)
               (let ((v (expr-constant-value to-op)))
                 (format out "~&~10Tadc #>~d" v))
               (format out "~&~10Tadc ~a + 1" (emit-6502-value to-op)))
           (if (slot-of-self-p result)
               (let ((n (slot-of-expr result)))
                 (format out "~&~10Tldy #~a + 1" (slot-symbol (second n) class-id))
                 (format out "~&~10Tsta (Self), y")
                 (format out "~&~10Tdey")
                 (format out "~&~10T~a" (if use-stack "pla" "txa"))
                 (format out "~&~10Tsta (Self), y"))
               (let ((res-sym (emit-6502-value result)))
                 (format out "~&~10Tsta ~a + 1" res-sym)
                 (format out "~&~10T~a" (if use-stack "pla" "txa"))
                 (format out "~&~10Tsta ~a" res-sym)))
           (when bcd-p (format out "~&~10Tcld")))))
    ;; General 8-bit case
    (t
     (emit-6502-load-expr out from class-id)
     (when bcd-p (format out "~&~10Tsed"))
     (format out "~&~10Tclc")
     (if giving
         (progn
           (if (expr-is-constant-p to-op)
               (format out "~&~10Tadc #~a" (emit-6502-immediate (expr-constant-value to-op)))
               (format out "~&~10Tadc ~a" (emit-6502-value to-op)))
           (format out "~&~10Tsta ~a" (emit-6502-value giving)))
         (cond
           ((slot-of-self-p to-op)
            (let ((n (slot-of-expr to-op)))
              (format out "~&~10Tldy ~a" (emit-6502-immediate (slot-symbol (second n) class-id)))
              (format out "~&~10Tadc (Self), y")
              (format out "~&~10Tsta (Self), y")))
           (t
            (format out "~&~10Tadc ~a" (emit-6502-value to-op))
            (format out "~&~10Tsta ~a" (emit-6502-value to-op)))))
     (when bcd-p (format out "~&~10Tcld"))))))

(defun compile-6502-subtract (out stmt class-id)
  (let ((from (getf (rest stmt) :from))
        (from-target (getf (rest stmt) :from-target))
        (giving (getf (rest stmt) :giving))
        (result (or giving from-target))
        (w (operand-width result))
        (bcd-p (when result (usage-bcd-p (expr-to-width-name result)))))
    (cond
    ;; Optimise: SUBTRACT 1 FROM variable (no GIVING, plain variable) → dec (byte only)
    ((and (literal-one-p from) (not giving) (stringp from-target) (= w 1))
     (format out "~&~10Tdec ~a" (to-pascal-case from-target)))
    ;; Multi-byte SUBTRACT (w >= 2): result = from-target - from
    ((>= w 2)
     (when (and bcd-p (> w 2))
       (error "EIGHTBOL: BCD SUBTRACT with width ~d not yet implemented" w))
     (if (> w 2)
         (progn
           (when bcd-p (format out "~&~10Tsed"))
           (format out "~&~10Tsec")
           (dotimes (i w)
             (emit-6502-load-byte-n out from-target class-id i w)
             (if (expr-is-constant-p from)
                 (format out "~&~10Tsbc ~a" (emit-6502-immediate (constant-byte-value from i)))
                 (format out "~&~10Tsbc ~a~a" (emit-6502-value from) (if (zerop i) "" (format nil " + ~d" i))))
             (emit-6502-store-byte-n out result class-id i w))
           (when bcd-p (format out "~&~10Tcld")))
         (let ((use-stack (expr-contains-subscript-p from-target)))
       (when (or use-stack (expr-contains-subscript-p from) (expr-contains-subscript-p result))
         (setf use-stack t))
       (when bcd-p (format out "~&~10Tsed"))
       ;; Low bytes: save result_lo (tax or pha)
       (emit-6502-load-expr out from-target class-id)
       (format out "~&~10Tsec")
       (if (expr-is-constant-p from)
           (let ((v (expr-constant-value from)))
             (format out "~&~10Tsbc #<~d" v))
           (format out "~&~10Tsbc ~a" (emit-6502-value from)))
       (if use-stack
           (format out "~&~10Tpha")
           (format out "~&~10Ttax"))
       ;; High bytes: result_hi = from-target_hi - from_hi - borrow
       (emit-6502-load-hi-byte out from-target class-id)
       (if (expr-is-constant-p from)
           (let ((v (expr-constant-value from)))
             (format out "~&~10Tsbc #>~d" v))
           (format out "~&~10Tsbc ~a + 1" (emit-6502-value from)))
         (if (slot-of-self-p result)
             (let ((n (slot-of-expr result)))
               (format out "~&~10Tldy #~a + 1" (slot-symbol (second n)  class-id))
               (format out "~&~10Tsta (Self), y")
               (format out "~&~10Tdey")
               (format out "~&~10T~a" (if use-stack "pla" "txa"))
               (format out "~&~10Tsta (Self), y"))
             (let ((res-sym (emit-6502-value result)))
               (format out "~&~10Tsta ~a + 1" res-sym)
               (format out "~&~10T~a" (if use-stack "pla" "txa"))
               (format out "~&~10Tsta ~a" res-sym)))
         (when bcd-p (format out "~&~10Tcld")))))
  ((slot-of-self-p from-target)
   (let* ((n (slot-of-expr from-target))
          (slot-name (second n)))
     (format out "~&~10Tldy ~a" (emit-6502-immediate (slot-symbol slot-name class-id)))
     (format out "~&~10Tlda (Self), y")
     (format out "~&~10Tsec")
     (if (expr-is-constant-p from)
         (format out "~&~10Tsbc #~a" (emit-6502-value from))
         (format out "~&~10Tsbc ~a" (emit-6502-value from)))
     (format out "~&~10Tsta (Self), y")))
  (giving
   (emit-6502-load-expr out from-target class-id)
   (when bcd-p (format out "~&~10Tsed"))
   (format out "~&~10Tsec")
   (if (expr-is-constant-p from)
       (format out "~&~10Tsbc #~a" (emit-6502-value from))
       (format out "~&~10Tsbc ~a" (emit-6502-value from)))
   (format out "~&~10Tsta ~a" (emit-6502-value giving))
   (when bcd-p (format out "~&~10Tcld")))
  (t
   (emit-6502-load-expr out from-target class-id)
   (when bcd-p (format out "~&~10Tsed"))
   (format out "~&~10Tsec")
   (if (expr-is-constant-p from)
       (format out "~&~10Tsbc #~a" (emit-6502-value from))
       (format out "~&~10Tsbc ~a" (emit-6502-value from)))
   (format out "~&~10Tsta ~a" (emit-6502-value from-target))
   (when bcd-p (format out "~&~10Tcld"))))))

(defun compile-6502-compute (out stmt class-id)
  "COMPUTE target = expression. Supports arbitrary width 1–8 bytes.
For w=1, expr may be compound (add, subtract, etc.). For w>1, expr must be variable/constant."
  (let ((target (getf (rest stmt) :target))
        (expr (getf (rest stmt) :expression))
        (w (operand-width target)))
    (cond
      ((= w 1)
       (emit-6502-load-expr out expr class-id)
       (emit-6502-store-byte-n out target class-id 0 1))
      (t
       (dotimes (i w)
         (emit-6502-load-byte-n out expr class-id i w)
         (emit-6502-store-byte-n out target class-id i w))))))

;;; SET statement

(defun compile-6502-set (out stmt class-id)
  "SET target TO value. Supports arbitrary width 1–8 bytes."
  (let ((target (getf (rest stmt) :target))
        (value (getf (rest stmt) :value))
        (w (operand-width target)))
    (cond
      ((member value '(:null null "NULL") :test #'equal)
       (format out "~&~10Tlda ~a" (emit-6502-immediate 0))
       (dotimes (i w)
         (emit-6502-store-byte-n out target class-id i w)))
      (t
       (let ((val-w (operand-width value)))
         (dotimes (i (min val-w w))
           (emit-6502-load-byte-n out value class-id i val-w)
           (emit-6502-store-byte-n out target class-id i w))
         (when (< val-w w)
           (format out "~&~10Tlda ~a" (emit-6502-immediate 0))
           (dotimes (i (- w val-w))
             (emit-6502-store-byte-n out target class-id (+ val-w i) w))))))))

;;; PERFORM statement

(defun compile-6502-perform (out stmt class-id)
  (let ((proc (getf (rest stmt) :procedure))
        (times (getf (rest stmt) :times))
        (until (getf (rest stmt) :until)))
    (cond
      (times
       (let ((lbl-loop (new-6502-label "PerfLoop"))
             (lbl-end (new-6502-label "PerfEnd")))
         (emit-6502-load-expr out times class-id)
         (format out "~&~10Ttax")
         (format out "~&~a:" lbl-loop)
         (format out "~&~10Tjsr ~a" (to-pascal-case (format nil "~a" proc)))
         (format out "~&~10Tdex")
         (format out "~&~10Tbne ~a" lbl-loop)
         (format out "~&~a:" lbl-end)))
      (until
          (let ((lbl-loop (new-6502-label "PerfLoop"))
                (lbl-end (new-6502-label "PerfEnd")))
            (format out "~&~a:" lbl-loop)
            (emit-6502-condition out until class-id lbl-end)
            (format out "~&~10Tjsr ~a" (to-pascal-case (format nil "~a" proc)))
            (format out "~&~10T~a ~a" (6502-branch-always-mnemonic) lbl-loop)
            (format out "~&~a:" lbl-end)))
      (t
       (format out "~&~10Tjsr ~a"
               (to-pascal-case (format nil "~a" proc)))))))

;;; ---------------------------------------------------------------
;;; compile-statement methods — one per (cpu, ast-node-type)
;;; Brief methods delegating to compile-6502-* helpers.
;;; ---------------------------------------------------------------

(defmacro def-6502-statement (stmt-type (ast-node-data) &body body)
  "Define compile-statement for :6502 and :65c02/:65c816/:huc6280 (same impl). Uses *output-stream*."
  `(progn
     (defmethod compile-statement ((cpu (eql :6502)) (stmt-type (eql ,stmt-type)) ,ast-node-data)
       ,@body)
     (defmethod compile-statement ((cpu (eql :65c02)) (stmt-type (eql ,stmt-type)) ,ast-node-data)
       ,@body)
     (defmethod compile-statement ((cpu (eql :65c816)) (stmt-type (eql ,stmt-type)) ,ast-node-data)
       ,@body)
     (defmethod compile-statement ((cpu (eql :huc6280)) (stmt-type (eql ,stmt-type)) ,ast-node-data)
       ,@body)))

(defun stmt (sym data) (cons sym data))

(def-6502-statement :goback (ast-node-data)
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10Trts"))

(def-6502-statement :exit-method (ast-node-data)
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10Trts"))

(def-6502-statement :exit-program (ast-node-data)
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10Trts"))

(def-6502-statement :stop-run (ast-node-data)
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10Trts"))

(def-6502-statement :exit (ast-node-data)
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10Trts"))

(def-6502-statement :move (ast-node-data)
  (compile-6502-move *output-stream* (stmt :move ast-node-data) *class-id*))

(def-6502-statement :invoke (ast-node-data)
  (compile-6502-invoke *output-stream* (stmt :invoke ast-node-data) *class-id*))

(def-6502-statement :call (ast-node-data)
  (compile-6502-call *output-stream* (stmt :call ast-node-data)))

(def-6502-statement :if (ast-node-data)
  (compile-6502-if *output-stream* (stmt :if ast-node-data) cpu))

(def-6502-statement :add (ast-node-data)
  (compile-6502-add *output-stream* (stmt :add ast-node-data) *class-id*))

(def-6502-statement :subtract (ast-node-data)
  (compile-6502-subtract *output-stream* (stmt :subtract ast-node-data) *class-id*))

(def-6502-statement :compute (ast-node-data)
  (compile-6502-compute *output-stream* (stmt :compute ast-node-data) *class-id*))

(def-6502-statement :set (ast-node-data)
  (compile-6502-set *output-stream* (stmt :set ast-node-data) *class-id*))

(def-6502-statement :log-fault (ast-node-data)
  (let ((code (getf ast-node-data :code)))
    (format *output-stream* "~&~10T.LogFault ~a"
            (if (stringp code)
                (format nil "\"~a\"" code)
                (emit-6502-value code)))))

(def-6502-statement :debug-break (ast-node-data)
  (let ((code (getf ast-node-data :code)))
    (format *output-stream* "~&~10T.DebugBreak ~a"
            (if (stringp code)
                (format nil "\"~a\"" code)
                (emit-6502-value code)))))

(def-6502-statement :perform (ast-node-data)
  (compile-6502-perform *output-stream* (stmt :perform ast-node-data) *class-id*))

(def-6502-statement :string-blt (ast-node-data)
  (compile-6502-string-blt *output-stream* (stmt :string-blt ast-node-data) *class-id*))

(def-6502-statement :goto (ast-node-data)
  (compile-6502-goto *output-stream* (stmt :goto ast-node-data) *class-id* *method-id*))

(def-6502-statement :paragraph (ast-node-data)
  (compile-6502-paragraph *output-stream* (stmt :paragraph ast-node-data) *class-id* *method-id*))

(def-6502-statement :evaluate (ast-node-data)
  (compile-6502-evaluate *output-stream* (stmt :evaluate ast-node-data) cpu))

(def-6502-statement :inspect (ast-node-data)
  (compile-6502-inspect *output-stream* (stmt :inspect ast-node-data) *class-id*))

(def-6502-statement :copy (ast-node-data)
  (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
         (getf ast-node-data :name)))
