;; src/backend-m6800.lisp — Motorola 6800 code generation backend
;;
;; Minimal m6800 emitter intended for Vectrex-style Motorola-family workflows.
;; Uses plain 6800-like mnemonics (LDAA/STAA/CMPA/BEQ/BNE/JSR/JMP/RTS) and
;; direct symbols for generated labels.
(in-package :eightbol)

(defun m6800-symbol (name)
  "Convert EIGHTBOL identifier to m6800 assembly symbol (PascalCase)."
  (pascal-case (format nil "~a" name)))

(defmethod compile-to-assembly (ast (cpu (eql :m6800)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/m6800: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table
                                     usage-table sign-table pic-size-table pic-width-table pic-frac-bits-table
                                     pic-nybble-semantics-table)
        (load-copybook-tables class-id)
      (declare (ignore service-bank-table usage-table sign-table pic-frac-bits-table pic-nybble-semantics-table))
      (format output-stream
              "; ~a -- generated by EIGHTBOL for m6800~%; DO NOT EDIT -- regenerate from ~a.cob~2%"
              class-id class-id)
      (dolist (method (ensure-list methods))
        (when (and (listp method) (eq (first method) :method))
          (compile-m6800-method output-stream method class-id
                                slot-table type-table const-table pic-size-table pic-width-table))))))

(defun compile-m6800-method (out method class-id slot-table type-table const-table pic-size-table pic-width-table)
  (let ((*slot-table* slot-table)
        (*type-table* type-table)
        (*const-table* const-table)
        (*pic-size-table* pic-size-table)
        (*pic-width-table* pic-width-table)
        (*class-id* class-id))
    (declare (special *slot-table* *type-table* *const-table* *pic-size-table*
                      *pic-width-table* *class-id*))
    (let ((method-id (getf (rest method) :method-id))
          (stmts (ensure-list (getf (rest method) :statements))))
      (format out "~&~%Method~a~a:" (m6800-symbol class-id) (m6800-symbol (format nil "~a" method-id)))
      (dolist (stmt stmts)
        (compile-m6800-statement out stmt class-id slot-table type-table const-table pic-size-table pic-width-table))
      (format out "~&~8tRTS"))))

(defun compile-m6800-load-a (out expr class-id slot-table const-table pic-width-table)
  (declare (ignore slot-table pic-width-table))
  (cond
    ((numberp expr)
     (format out "~&~8tLDAA    #~d" expr))
    ((and (stringp expr) (constant-p expr))
     (format out "~&~8tLDAA    #~d" (constant-value expr)))
    ((stringp expr)
     (format out "~&~8tLDAA    ~a" (bare-data-assembly-symbol expr class-id)))
    ((and (listp expr) (eq (first expr) :of))
     (let ((slot (second expr)) (obj (third expr)))
       (if (member obj '(:self "Self" self) :test #'equal)
           (progn
             (format out "~&~8tLDX     Self")
             (format out "~&~8tLDAA    ~a,X" (slot-symbol slot class-id)))
           (format out "~&~8t; Unsupported OF target ~s for m6800 load" obj))))
    (t
     (format out "~&~8t; Unsupported load ~s for m6800" expr)
     (format out "~&~8tLDAA    #0"))))

(defun compile-m6800-store-a (out dest class-id)
  (cond
    ((stringp dest)
     (format out "~&~8tSTAA    ~a" (bare-data-assembly-symbol dest class-id)))
    ((and (listp dest) (eq (first dest) :of))
     (let ((slot (second dest)) (obj (third dest)))
       (if (member obj '(:self "Self" self) :test #'equal)
           (progn
             (format out "~&~8tLDX     Self")
             (format out "~&~8tSTAA    ~a,X" (slot-symbol slot class-id)))
           (format out "~&~8t; Unsupported OF target ~s for m6800 store" obj))))
    (t
     (format out "~&~8t; Unsupported store ~s for m6800" dest))))

(defvar *m6800-label-counter* 0)

(defun m6800-label (prefix)
  (format nil "L~a~d" prefix (incf *m6800-label-counter*)))

(defun compile-m6800-condition (out condition class-id slot-table type-table const-table pic-width-table false-label)
  (declare (ignore type-table))
  (cond
    ((and (listp condition) (member (first condition) '(= equal) :test #'eq))
     (compile-m6800-load-a out (second condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tTAB")
     (compile-m6800-load-a out (third condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tCBA")
     (format out "~&~8tBNE     ~a" false-label))
    ((and (listp condition) (eq (first condition) :is-zero))
     (compile-m6800-load-a out (second condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tBNE     ~a" false-label))
    ((and (listp condition) (eq (first condition) :is-not-zero))
     (compile-m6800-load-a out (second condition) class-id slot-table const-table pic-width-table)
     (format out "~&~8tBEQ     ~a" false-label))
    (t
     (format out "~&~8t; Unsupported condition ~s for m6800" condition)
     (format out "~&~8tJMP     ~a" false-label))))

(defun compile-m6800-statement (out stmt class-id slot-table type-table const-table pic-size-table pic-width-table)
  (unless (and (listp stmt) (first stmt))
    (return-from compile-m6800-statement))
  (emit-statement-source-comment out stmt)
  (ecase (first stmt)
    (:goback (format out "~&~8tRTS"))
    (:exit-method (format out "~&~8tRTS"))
    (:exit-program (format out "~&~8tRTS"))
    (:exit (format out "~&~8tRTS"))
    (:stop-run (format out "~&~8tRTS"))
    (:move
     (compile-m6800-load-a out (getf (rest stmt) :from) class-id slot-table const-table pic-width-table)
     (compile-m6800-store-a out (getf (rest stmt) :to) class-id))
    (:set
     (compile-m6800-load-a out (getf (rest stmt) :value) class-id slot-table const-table pic-width-table)
     (compile-m6800-store-a out (getf (rest stmt) :target) class-id))
    (:if
     (let ((false-label (m6800-label "IfFalse"))
           (end-label (m6800-label "IfEnd"))
           (then-stmts (ensure-list (getf (rest stmt) :then)))
           (else-stmts (ensure-list (getf (rest stmt) :else))))
       (compile-m6800-condition out (getf (rest stmt) :condition)
                                class-id slot-table type-table const-table pic-width-table false-label)
       (dolist (s then-stmts)
         (compile-m6800-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
       (when else-stmts
         (format out "~&~8tJMP     ~a" end-label))
       (format out "~&~a:" false-label)
       (dolist (s else-stmts)
         (compile-m6800-statement out s class-id slot-table type-table const-table pic-size-table pic-width-table))
       (when else-stmts
         (format out "~&~a:" end-label))))
    (:call
     (let ((target (or (getf (rest stmt) :service) (getf (rest stmt) :target) "UnknownCall")))
       (format out "~&~8tJSR     ~a" (m6800-symbol target))))
    (:invoke
     (let ((method (or (getf (rest stmt) :method) "UnknownMethod")))
       (format out "~&~8tJSR     Invoke~a~a"
               (m6800-symbol class-id)
               (m6800-symbol method))))
    (:goto
     (let ((target (or (getf (rest stmt) :target) (first (getf (rest stmt) :targets)))))
       (format out "~&~8tJMP     ~a" (m6800-symbol target))))
    (:paragraph
     (let ((name (if (eq (first stmt) :paragraph)
                     (second stmt)
                     (or (getf (rest stmt) :paragraph) (second stmt)))))
       (when name
         (format out "~&~a:" (m6800-symbol (format nil "~a" name))))))
    (:add
     (compile-m6800-load-a out (getf (rest stmt) :to) class-id slot-table const-table pic-width-table)
     (format out "~&~8tTAB")
     (compile-m6800-load-a out (getf (rest stmt) :from) class-id slot-table const-table pic-width-table)
     (format out "~&~8tABA")
     (compile-m6800-store-a out (or (getf (rest stmt) :giving) (getf (rest stmt) :to)) class-id))
    (:subtract
     (compile-m6800-load-a out (getf (rest stmt) :from-target) class-id slot-table const-table pic-width-table)
     (format out "~&~8tTAB")
     (compile-m6800-load-a out (getf (rest stmt) :from) class-id slot-table const-table pic-width-table)
     (format out "~&~8tSBA")
     (compile-m6800-store-a out (or (getf (rest stmt) :giving) (getf (rest stmt) :from-target)) class-id))
    (:compute
     (compile-m6800-load-a out (getf (rest stmt) :expression) class-id slot-table const-table pic-width-table)
     (compile-m6800-store-a out (getf (rest stmt) :target) class-id))
    (:perform (format out "~&~8t; PERFORM not yet implemented for m6800"))
    (:evaluate (format out "~&~8t; EVALUATE not yet implemented for m6800"))
    (:inspect (format out "~&~8t; INSPECT not yet implemented for m6800"))
    (:string-blt (format out "~&~8t; STRING BLT not yet implemented for m6800"))
    (:log-fault (format out "~&~8t; LOG FAULT ~s" (getf (rest stmt) :code)))
    (:debug-break (format out "~&~8t; DEBUG BREAK ~s" (getf (rest stmt) :code)))
    (:copy (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
                  (getf (rest stmt) :name)))))
