;; src/backend-RP2A03.lisp — NES RP2A03 (6502 without decimal mode) code
;; generation
;;
;; The RP2A03  is the CPU  in the  Nintendo Entertainment System.  It is
;; a 6502  variant that LACKS  decimal mode: the  D flag is  ignored and
;; ADC/SBC always perform binary arithmetic.
;;
;; For BCD  (USAGE BCD /  PACKED-DECIMAL) variables, this  backend emits
;; software  BCD   routines  instead  of  relying   on  SED/ADC/SBC/CLD.
;; The correction algorithm:  Add: binary ADC, then if low  nibble >= 10
;; add 6; if high nibble >= $A0  or carry, add $60. Sub: binary SEC/SBC,
;; then if borrow/correction needed,  subtract 6 from nibbles (DAS-style
;; adjustment).
;;
;; Output: 64tass assembler syntax, same conventions as backend-6502.
(in-package :eightbol)

;;; Top-level entry point

(defmethod compile-to-assembly (ast (cpu (eql :rp2a03)) output-stream)
  (unless (and (listp ast) (eq (first ast) :program))
    (error "EIGHTBOL/RP2A03: expected :program AST node, got ~s" (first ast)))
  (let* ((class-id (getf (rest ast) :class-id))
         (methods  (getf (rest ast) :methods)))
    (multiple-value-bind (slot-table type-table const-table service-bank-table usage-table sign-table pic-size-table pic-width-table)
        (load-copybook-tables class-id)
      (let ((*output-stream* output-stream)
            (*class-id* class-id)
            (*slot-table* slot-table)
            (*type-table* type-table)
            (*const-table* const-table)
            (*service-bank-table* service-bank-table)
            (*usage-table* usage-table)
            (*sign-table* sign-table)
            (*pic-size-table* pic-size-table)
            (*pic-width-table* pic-width-table))
        (format *output-stream*
                ";;; ~a -- generated by EIGHTBOL for RP2A03 (NES)~%;;; DO NOT EDIT -- regenerate from ~a.cob~%;;; BCD operations use software routines (no decimal mode)~2%"
                class-id class-id)
        (dolist (method (ensure-list methods))
          (when (and (listp method) (eq (first method) :method))
            (compile-rp2a03-method method class-id)))))))

;;; Method   compilation   —   CLD   at   entry,   then   delegate   via
;;; compile-statement

(defun compile-rp2a03-method (method class-id)
  (let* ((*6502-family-cpu* :rp2a03)
         (*method-id* (getf (rest method) :method-id))
         (statements (getf (rest method) :statements)))
    (format *output-stream* "~&Method~a~a: .block" class-id *method-id*)
    (format *output-stream* "~&~10tcld~40t; RP2A03: ensure binary mode (no decimal)")
    (dolist (stmt (ensure-list statements))
      (when (and stmt (first stmt))
        (compile-statement :rp2a03 (first stmt) (rest stmt))))
    (format *output-stream* "~&~10t.bend")))

;;; RP2A03 compile-statement methods — same as 6502 except add/subtract

(defmacro def-rp2a03-statement (stmt-type &body body)
  "Define compile-statement for :rp2a03. Uses *output-stream*."
  `(defmethod compile-statement ((cpu (eql :rp2a03)) (stmt-type (eql ,stmt-type)) ast-node-data)
     ,@body))

(defun rp2a03-stmt (sym data) (cons sym data))

(def-rp2a03-statement :goback
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10trts"))

(def-rp2a03-statement :exit-method
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10trts"))

(def-rp2a03-statement :exit-program
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10trts"))

(def-rp2a03-statement :stop-run
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10trts"))

(def-rp2a03-statement :exit
  (declare (ignore ast-node-data))
  (format *output-stream* "~&~10trts"))

(def-rp2a03-statement :move
  (compile-6502-move *output-stream* (rp2a03-stmt :move ast-node-data) *class-id*))

(def-rp2a03-statement :invoke
  (compile-6502-invoke *output-stream* (rp2a03-stmt :invoke ast-node-data) *class-id*))

(def-rp2a03-statement :call
  (compile-6502-call *output-stream* (rp2a03-stmt :call ast-node-data)))

(def-rp2a03-statement :if
  (compile-6502-if *output-stream* (rp2a03-stmt :if ast-node-data) :rp2a03))

(def-rp2a03-statement :add
  (compile-rp2a03-add *output-stream* (rp2a03-stmt :add ast-node-data) *class-id*))

(def-rp2a03-statement :subtract
  (compile-rp2a03-subtract *output-stream* (rp2a03-stmt :subtract ast-node-data) *class-id*))

(def-rp2a03-statement :compute
  (compile-6502-compute *output-stream* (rp2a03-stmt :compute ast-node-data) *class-id*))

(def-rp2a03-statement :set
  (compile-6502-set *output-stream* (rp2a03-stmt :set ast-node-data) *class-id*))

(def-rp2a03-statement :log-fault
  (let ((code (getf ast-node-data :code)))
    (format *output-stream* "~&~10t.LogFault ~a"
            (if (stringp code)
                (format nil "\"~a\"" code)
                (emit-6502-value code)))))

(def-rp2a03-statement :debug-break
  (let ((code (getf ast-node-data :code)))
    (format *output-stream* "~&~10t.DebugBreak ~a"
            (if (stringp code)
                (format nil "\"~a\"" code)
                (emit-6502-value code)))))

(def-rp2a03-statement :perform
  (compile-6502-perform *output-stream* (rp2a03-stmt :perform ast-node-data) *class-id*))

(def-rp2a03-statement :string-blt
  (compile-6502-string-blt *output-stream* (rp2a03-stmt :string-blt ast-node-data) *class-id*))

(def-rp2a03-statement :goto
  (compile-6502-goto *output-stream* (rp2a03-stmt :goto ast-node-data) *class-id* *method-id*))

(def-rp2a03-statement :paragraph
  (compile-6502-paragraph *output-stream* (rp2a03-stmt :paragraph ast-node-data) *class-id* *method-id*))

(def-rp2a03-statement :evaluate
  (compile-6502-evaluate *output-stream* (rp2a03-stmt :evaluate ast-node-data) :rp2a03))

(def-rp2a03-statement :inspect
  (compile-6502-inspect *output-stream* (rp2a03-stmt :inspect ast-node-data) *class-id*))

(def-rp2a03-statement :copy
  (error "EIGHTBOL: COPY ~s should have been expanded at lex time"
         (getf ast-node-data :name)))

;;; BCD detection

(defun add-sub-targets-bcd-p (stmt add-p)
  "True if any target of ADD or SUBTRACT is a BCD variable.
ADD: to, giving.  SUBTRACT: from-target, giving. Uses *USAGE-TABLE*."
  (flet ((name (x) (if (stringp x) x (and x (format nil "~a" x)))))
    (if add-p
        (or (usage-bcd-p (name (getf (rest stmt) :to)))
            (usage-bcd-p (name (getf (rest stmt) :giving))))
        (or (usage-bcd-p (name (getf (rest stmt) :from-target)))
            (usage-bcd-p (name (getf (rest stmt) :giving)))))))

;;; Software BCD add — 8-bit, no decimal mode After binary ADC, correct:
;;; low nibble >= 10 → +6; high >= $A0 or C → +$60

(defun emit-rp2a03-bcd-add-correction (out)
  "Emit 8-bit BCD correction after ADC. A has binary sum; on exit A has BCD result.
Uses only 6502 instructions (BRA is 65c02-only); RP2A03-compatible."
  (let ((lbl-low (new-6502-label "bcd_low"))
        (lbl-skip (new-6502-label "bcd_skip"))
        (lbl-done (new-6502-label "bcd_done")))
    (format out "~&~10tpha")
    (format out "~&~10tand #$0F")
    (format out "~&~10tcmp #10")
    (format out "~&~10tbcc ~a" lbl-low)
    (format out "~&~10tpla")
    (format out "~&~10tadc #6")
    (format out "~&~10tpha")
    (format out "~a:" lbl-low)
    (format out "~&~10tpla")
    (format out "~&~10ttax")
    (format out "~&~10tand #$F0")
    (format out "~&~10tcmp #$A0")
    (format out "~&~10tbcc ~a" lbl-skip)
    (format out "~&~10ttxa")
    (format out "~&~10tadc #$60")
    (format out "~&~10tjmp ~a" lbl-done)
    (format out "~a:" lbl-skip)
    (format out "~&~10ttxa")
    (format out "~a:" lbl-done)))

;;; Software BCD subtract — 8-bit, no decimal mode
;;; After binary SEC/SBC, correct: if C=0 (borrow) or nibble > 9, subtract 6

(defun emit-rp2a03-bcd-sub-correction (out)
  "Emit 8-bit BCD correction after SBC. A has binary difference; on exit A has BCD result.
If C=0 (borrow): subtract $60. If low nibble >= 10: subtract 6.
Uses only 6502 instructions (BRA is 65c02-only); RP2A03-compatible."
  (let ((lbl-borrow (new-6502-label "bcd_borrow"))
        (lbl-skip (new-6502-label "bcd_sskip"))
        (lbl-done (new-6502-label "bcd_sdone")))
    (format out "~&~10tbcs ~a" lbl-borrow)
    (format out "~&~10tsbc #$60")
    (format out "~a:" lbl-borrow)
    (format out "~&~10tpha")
    (format out "~&~10tand #$0F")
    (format out "~&~10tcmp #10")
    (format out "~&~10tbcc ~a" lbl-skip)
    (format out "~&~10tpla")
    (format out "~&~10tsbc #6")
    (format out "~&~10tjmp ~a" lbl-done)
    (format out "~a:" lbl-skip)
    (format out "~&~10tpla")
    (format out "~a:" lbl-done)))

;;; ADD — use software BCD when target is BCD

(defun compile-rp2a03-add (out stmt class-id)
  (if (add-sub-targets-bcd-p stmt t)
      (compile-rp2a03-add-bcd out stmt class-id)
      (compile-6502-add out stmt class-id)))

(defun compile-rp2a03-add-bcd (out stmt class-id)
  ;; 16-bit BCD add TODO
  (let ((from   (getf (rest stmt) :from))
        (to     (getf (rest stmt) :to))
        (giving (getf (rest stmt) :giving)))
    (emit-6502-load-expr out from class-id)
    (format out "~&~10tclc")
    (if (expr-is-constant-p to)
        (format out "~&~10tadc #~a" (emit-6502-value to))
        (cond
          ((slot-of-self-p to)
           (let ((n (slot-of-expr to)))
             (format out "~&~10tldy #~a" (slot-symbol (second n) class-id))
             (format out "~&~10tadc (Self), y")))
          (t
           (format out "~&~10tadc ~a" (emit-6502-value to)))))
    (emit-rp2a03-bcd-add-correction out)
    (if giving
        (format out "~&~10tsta ~a" (emit-6502-value giving))
        (cond
          ((slot-of-self-p to)
           (let ((n (slot-of-expr to)))
             (format out "~&~10tldy #~a" (slot-symbol (second n) class-id))
             (format out "~&~10tsta (Self),y")))
          (t
           (format out "~&~10tsta ~a" (emit-6502-value to)))))))

;;; SUBTRACT — use software BCD when target is BCD

(defun compile-rp2a03-subtract (out stmt class-id)
  (if (add-sub-targets-bcd-p stmt nil)
      (compile-rp2a03-subtract-bcd out stmt class-id)
      (compile-6502-subtract out stmt class-id)))

(defun compile-rp2a03-subtract-bcd (out stmt class-id)
  ;; 16-bit BCD subtract TODO
  (let ((from        (getf (rest stmt) :from))
        (from-target (getf (rest stmt) :from-target))
        (giving      (getf (rest stmt) :giving)))
    (cond
      ((slot-of-self-p from-target)
       (let ((n (slot-of-expr from-target)))
         (format out "~&~10tldy #~a" (slot-symbol (second n) class-id))
         (format out "~&~10tlda (Self),y")
         (format out "~&~10tsec")
         (if (expr-is-constant-p from)
             (format out "~&~10tsbc #~a" (emit-6502-value from))
             (format out "~&~10tsbc ~a" (emit-6502-value from)))
         (emit-rp2a03-bcd-sub-correction out)
         (format out "~&~10tsta (Self),y")))
      (t
       (emit-6502-load-expr out from-target class-id)
       (format out "~&~10tsec")
       (if (expr-is-constant-p from)
           (format out "~&~10tsbc #~a" (emit-6502-value from))
           (format out "~&~10tsbc ~a" (emit-6502-value from)))
       (emit-rp2a03-bcd-sub-correction out)
       (format out "~&~10tsta ~a"
               (emit-6502-value (or giving from-target)))))))
