;; src/basic-parser.lisp — Bare-bones BASIC → Eightbol AST
;;; Copyright © 2026 Interworldly Adventuring, LLC
(defun basic-label->cobol (label)
  "Convert BASIC label to COBOL format: hyphenated, case-insensitive, trailing period."
  (let* ((trim (string-trim '(#\Space #\Tab #\Newline) label))
         (clean (cl-ppcre:regex-replace-all "[^A-Za-z0-9]+" trim "--"))
         (lower (string-downcase clean)))
    (format nil "~A." lower)))

(defun basic-label->lisp (label)
  "Convert BASIC label to Lisp format: hyphenated, case-insensitive, no trailing punctuation."
  (let* ((trim (string-trim '(#\Space #\Tab #\Newline) label))
         (clean (cl-ppcre:regex-replace-all "[^A-Za-z0-9]+" trim "--"))
         (lower (string-downcase clean)))
    lower))

(defun basic-capitalize-word (word)
  "Capitalize the first character of WORD."
  (if (zerop (length word))
      word
      (concatenate 'string (string-upcase (subseq word 0 1))
                   (string-downcase (subseq word 1)))))

(defun basic-label->assembly (label)
  "Convert BASIC label to Assembly format: PascalCase, underscore for major divisions, trailing colon."
  (let* ((trim (string-trim '(#\Space #\Tab #\Newline) label))
         ;; Split on commas or spaces
         (parts (remove-if (lambda (s) (string= s "") trim))
                (cl-ppcre:split "[, ]+" trim))
         ;; Capitalize each part
         (capitalized (mapcar #'basic-capitalize-word parts))
         (joined (reduce (lambda (a b) (format nil "~A_~B" a b)) capitalized)))
    (format nil "~A:" joined)))

(defun basic-label->cobol (label)
  "Convert BASIC label to COBOL format: hyphenated, case-insensitive, trailing period."
  (let* ((trim (string-trim '(#\Space #\Tab #\Newline) label))
         (parts (remove-if (lambda (s) (string= s ""))
                           (split-sequence:split-sequence-if (lambda (c) (or (char= c #\Space) (char= c #\,))) trim)))
         (joined (mapconcat (lambda (s) (string-downcase s)) parts "--")))
    (format nil "~A." joined)))

(defparameter *basic-keywords*
   '(("LET" . :LET) ("FOR" . :FOR) ("TO" . :TO) ("STEP" . :STEP)
     ("NEXT" . :NEXT) ("IF" . :IF) ("THEN" . :THEN) ("ELSE" . :ELSE)
     ("GOTO" . :GOTO) ("GOSUB" . :GOSUB) ("RETURN" . :RETURN)
     ("LOG" . :LOG) ("FAULT" . :FAULT) ("METHOD" . :METHOD)
     ("WHILE" . :WHILE) ("UNTIL" . :UNTIL) ("LIBRARY" . :LIBRARY)))

(defun basic-token-type (lexeme)
  "Return the token type for LEXEME."
  (cond
    ((and (stringp lexeme) (digit-char-p (char lexeme 0)))
     :NUMBER)
    ((and (stringp lexeme) (char= (char lexeme 0) #\" ))
     :STRING)
    ((assoc lexeme *basic-keywords* :test #'string-equal))
     (cdr it))
    ((find (char lexeme 0) "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_$")
     :IDENT)
    ((string= lexeme "(") :LPAREN)
    ((string= lexeme ")") :RPAREN)
    ((string= lexeme "*") :TIMES)
    ((string= lexeme "+") :PLUS)
    ((string= lexeme "-") :MINUS)
    ((string= lexeme "/") :DIVIDE)
    ((string= lexeme "=") :ASSIGN)
    ((string= lexeme ",") :COMMA)
    ((string= lexeme ".") :DOT)
    ((string= lexeme ";") :SEMI)
    (t :UNKNOWN)))

(defun basic-lex-stream (text)
  "Split TEXT into token list."
  (let ((tokens '())
        (chars '()))
    (labels ((flush () (when chars (push (coerce (reverse chars) 'string) tokens))))
      (dolist (c (concatenate 'list text))
        (cond ((find c " \t\r\n" :test #'char=) (flush) (setf chars nil))
              ((find c "(,)=*+/-.;" :test #'char=)
               (flush)
               (push (string c) tokens))
              (t (push c chars))))
    (flush)
    (mapcar (lambda (tok)
              (let ((typ (basic-token-type tok)))
                (list typ (unless (eq typ :NUMBER) tok))))
            (reverse tokens))))

(defparameter *basic-tokens* nil)
(defparameter *basic-pos* 0)

(defun peek-token () (nth *basic-pos* *basic-tokens*))
(defun consume-token () (prog1 (peek-token) (incf *basic-pos*)))

(defun parse-basic (source)
  "Parse a BASIC source string into an Eightbol AST plist."
  (setf *basic-tokens* (basic-lex-stream source) *basic-pos* 0)
  (catch :eof
    (loop while (peek-token)
          collect (parse-line) into lines
          finally (return (nreverse lines)))))

(defun parse-line ()
  (let ((lineno (parse-number))
        (label nil)
        (stmt nil))
    (cond
      ;; Quoted label definition at start of line: "This is a label":
      ((and (eq (caar (peek-token)) :STRING)
            (string= (cadar (peek-token)) ":"))
       (setf label (prog1 (cadar (consume-token)) (consume-token)))
       (setf stmt (parse-statement)))
      ;; Existing numeric line format
      ((and (eq (caar (peek-token)) :IDENT) lineno)
       (setf label (cadar (peek-token))
             stmt (parse-statement))))
    (list (when lineno (list :line-number lineno))
          (when label (list :label label))
          (when stmt (list :statement stmt)))))

(defun parse-number ()
  (let ((tok (peek-token)))
    (when (eq (caar tok) :NUMBER)
      (consume-token)
      (parse-integer (cadar tok)))))

(defun parse-expression () (parse-term))

(defun parse-term ()
  (let ((lhs (parse-factor)))
    (loop while (member (caar (peek-token)) '(:TIMES :DIVIDE :PLUS :MINUS))
          do (let ((op (caar (consume-token))))
               (setf lhs (list (cond ((eq op :TIMES) :multiply)
                                     ((eq op :DIVIDE) :divide)
                                     ((eq op :PLUS) :add)
                                     ((eq op :MINUS) :subtract)
                                     (t :add))
                               lhs (parse-factor)))))
    lhs))

(defun parse-factor ()
  (let ((tok (peek-token)))
    (ecase (caar tok)
      (:NUMBER (prog1 (cadar tok) (consume-token)))
      (:STRING (prog1 (cadar tok) (consume-token)))
      (:IDENT
       (let ((name (prog1 (cadar tok) (consume-token))))
         (when (eq (caar (peek-token)) :LPAREN)
           (consume-token)
           (let ((index (parse-expression)))
             (when (eq (caar (consume-token)) :RPAREN)
               (list :subscript name index)))))
      (:LPAREN (consume-token) (let ((e (parse-expression))) (consume-token) e)))))

(defun parse-statement ()
  (let ((tok (peek-token)))
    (ecase (caar tok)
      (:LET (consume-token)
            (let ((target (prog1 (cadar (consume-token)) (consume-token)))
              (consume-token)
              (let ((source (parse-expression)))
                (list :move :to target :from source))))
      (:GOTO (consume-token)
              (let ((target (prog1 (cadar (consume-token)) (consume-token)))
                    (library nil)
                    (bank-intro nil))
                (when (and (eq (caar (peek-token)) :COMMA))
                  (consume-token)
                  (let ((next-tok (peek-token)))
                    (cond
                      ((and (eq (caar next-tok) :LIBRARY))
                       (setf library t)
                       (consume-token))
                      ((eq (caar next-tok) :IDENT)
                       (setf bank-intro (cadar (consume-token)))))))
                (list :goto :target target :library library :bank-intro bank-intro)))
      (:GOSUB (consume-token)
               (let ((target (prog1 (cadar (consume-token)) (consume-token)))
                     (library nil)
                     (bank-intro nil))
                 (when (and (eq (caar (peek-token)) :COMMA))
                   (consume-token)
                   (let ((next-tok (peek-token)))
                     (cond
                       ((and (eq (caar next-tok) :LIBRARY))
                        (setf library t)
                        (consume-token))
                       ((eq (caar next-tok) :IDENT)
                        (setf bank-intro (cadar (consume-token)))))))
                 (list :gosub :target target :library library :bank-intro bank-intro)))
      (:RETURN (consume-token) (list :return))
      (:IF (consume-token)
           (let ((cond (parse-expression))
                 (consume-token)
                 (then-stmt (parse-statement)))
             (when (eq (caar (peek-token)) :ELSE)
               (consume-token)
               (let ((else-stmt (parse-statement)))
                 (list :if :condition cond :then then-stmt :else else-stmt)))))
       (:FOR (consume-token)
             (let ((var (prog1 (cadar (consume-token)) (consume-token)))
                   (consume-token)
                   (start (parse-expression))
                   (consume-token)
                   (end (parse-expression))
                   (step (when (eq (caar (peek-token)) :STEP)
                           (consume-token)
                           (parse-expression))))
               (list :perform-varying var :from start :to end :by step)))
       (:WHILE (consume-token)
               (let ((condition (parse-expression))
                     (body (parse-statement)))
                 (when (and (eq (caar (peek-token)) :NEXT))
                   (consume-token))
                 (list :while :condition condition :body body)))
       (:UNTIL (consume-token)
                (let ((condition (parse-expression))
                      (body (parse-statement)))
                  (when (and (eq (caar (peek-token)) :NEXT))
                    (consume-token))
                  (list :until :condition condition :body body)))
      (:LOG (consume-token)
            (consume-token)
            (let ((msg (prog1 (cadar (consume-token)) (consume-token))))
              (list :log-fault :code msg)))))))

(defun basic-parse-string (text)
  "Parse BASIC TEXT and return AST plist."
  (parse-basic text))

(export 'basic-parse-string 'parse-basic 'basic-lex-stream))